Applications/Classification/TensorFlow/Training_Keras.py, Applications/Classification/TensorFlow/Training_tf.py, Applications/Classification/jni/main.cpp, Applications/KNN/jni/demo.cpp, Applications/LogisticRegression/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/ReinforcementLearning/Environment/CartPole/cartpole.cpp, Applications/ReinforcementLearning/Environment/CartPole/cartpole.h, Applications/ReinforcementLearning/Environment/CartPole/main.cpp, Applications/Training/jni/main.cpp, include/databuffer.h, include/layers.h, include/neuralnet.h, include/tensor.h, src/databuffer.cpp, src/layers.cpp, src/neuralnet.cpp, src/tensor.cpp
Change nntrainer home URL to github.com/nnstreamer/nntrainer
=> Fix nntrainer home URL @open sesame 3/25 10:06

meson.build
In case that there are no cmake files or no pkg-config files for iniparser, this patch adds fallback mechanism to find it.
Signed-off-by: Wook Song <wook16.song@samsung.com>
=> meson: Add fallback mechanism to find iniparser

nntrainer/src/databuffer.cpp
The value of an arithmetic expression (I * this->input_size + I *
this->class_num) * sizeof(float) is subject to overflow due to a
failure to cast operands to a larger data type before perfoming arithmetic
=> [SVACE] Check the index of test case if it is exceed the file size

nntrainer/include/nntrainer_log.h, nntrainer/include/nntrainer_logger.h, nntrainer/src/nntrainer_logger.cpp
In order to log, implement Logger class to use when there is no
logging system. If there is, we are going to use them. For example,
we are going to use tizen dlog for the tizen and android log system
for android with same interface such as nn_log[i,w,e,d].
=> [API] Add Logger for NNTrainer

nntrainer/src/neuralnet.cpp
There is no reason to be global because only one function use these
global variables.
=> Remove global variables to parse the configuration file

README.md
Add Coverage Test Badge for nntrainer in README.md
Resolves:
=> Add Coverage Test badge for nntrainer

.clang-format, Applications/Classification/res/Classification.ini, Applications/LogisticRegression/res/LogisticRegression.ini, Applications/ReinforcementLearning/DeepQ/jni/DeepQ.ini, Applications/Training/res/Training.ini, nntrainer/src/neuralnet.cpp, test/tizen_capi/test_conf.ini
Instead of using camel type, snakes type is used.
=> lower case for layer type.

Applications/Classification/jni/main.cpp, Applications/Classification/res/Classification.ini, nntrainer/include/databuffer.h, nntrainer/include/neuralnet.h, nntrainer/src/databuffer.cpp, nntrainer/src/neuralnet.cpp, test/tizen_capi/test_conf.ini, test/unittest/unittest_nntrainer_internal.cpp
In order to handle various input generation cases, make DataBuffer
Class is base class and inherit this, several children classes is
introduced.
. DataBufferFromDataFile
. DataBufferFromCallback : NYI
. DataBufferFromFramework : NYI
. others. : NYI
=> Introduce DataBufferFromDataFile Class

Applications/Classification/jni/main_func.cpp, Applications/Classification/jni/meson.build, Applications/Classification/res/Classification_func.ini, nntrainer/include/databuffer.h, nntrainer/include/neuralnet.h, nntrainer/src/databuffer.cpp, nntrainer/src/neuralnet.cpp, test/unittest/unittest_nntrainer_internal.cpp
With this class, it is possible to train with user specific data
generation callback function. This is the default to get training 
data unless there is [DataSet] key in configuration file.
- in Application/Classification/jni/main_func.cpp
NN.train(getMiniBatch_train, getMiniBatch_val, getMiniBatch_train)
Then, data buffer thread call these functions to get newest data with
size of mini batch.
The format this function should be :
/*
* @brief Callback function to get user specific data
* @param[in] X data  3D float vector type
* @param[in] Y label 3D float vector type
* @param[out] status status for error handle
* @retval true / false generate all data for this epoch
*/
bool  func(std::vector<std::vector<std::vector<float>>>& X,
std::vector<std::vector<std::vector<float>>>& Y, int &status) …
=> Introduce DataBufferFromCallback Class

test/unittest/meson.build
Fix issue that `ninja -C build test` is failing because there is no test data set
included.
=> Add test dataset automatically with meson build

Applications/Tizen_CAPI/Tizen_CAPI_config.ini, Applications/Tizen_CAPI/main.c, Applications/Tizen_CAPI/meson.build, Applications/meson.build, api/capi/include/nntrainer.h, meson.build
Add Tizen CAPI Example with configuration file
- Add example application for tizen capi which run neural network with
configuration file
=> [CAPI] Tizen CAPI Example @open sesame 05/04 17:34

test/meson.build, test/tizen_capi/meson.build, test/tizen_capi/unittest_tizen_capi.cpp, test/unittest/meson.build
This PR..
1. Make library for test_util so, it does not need compile over and
over again
2. Combine identical variable with diffrent name
=> Delete overlapping logic in test/meson.build

packaging/run_unittests.sh
This patch generates gtest xml files reported to DCube as unittest
results.
Signed-off-by: Dongju Chae <dongju.chae@samsung.com>
=> [UnitTest/DCube] Genereate gtest xml files to report unittest results

api/capi/src/nntrainer.cpp, nntrainer/include/databuffer.h, nntrainer/src/databuffer.cpp, nntrainer/src/neuralnet.cpp, test/unittest/unittest_databuffer_file.cpp, test/unittest/unittest_util_func.cpp
This PR
1. Solves potential memory leak detected from valgrind.
2. Correct the author of `unittest_util_func.cpp`.
=> Fix potential memory leak when finalize.

api/capi/include/nntrainer.h, api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, jni/Android.mk, nntrainer/include/layers.h, nntrainer/include/neuralnet.h, nntrainer/include/parse_util.h, nntrainer/meson.build, nntrainer/src/layers.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/parse_util.cpp, nntrainer/src/tensor.cpp, packaging/nntrainer.spec, test/tizen_capi/unittest_tizen_capi_layer.cpp
. Implement Set Property API for Neural Network Layer
- Each layer has setProperty methods with its own Property enum
class.
- Layer Class has virtual setProperty Class
- Seperate parseType and make parse_util.h & cpp to use other
files.
- Use TensorDim for Define demesion of hidden layer
- Added TOC generator for README.md
Resolves:
=> [API] Set Property API for Neural Network Layer

api/capi/include/nntrainer.h, api/capi/src/nntrainer.cpp, nntrainer/include/layers.h, nntrainer/src/layers.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp
Modify ml_nnlayer_set_property () to get multiple arguments for
property.
=> [API] Modify to get Multiple Property Arguments

api/capi/include/nntrainer.h, api/capi/src/nntrainer.cpp, nntrainer/include/optimizer.h, nntrainer/include/parse_util.h, nntrainer/src/optimizer.cpp, nntrainer/src/parse_util.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp
. ml_nnoptimizer_set_perperty(ml_nnopt_h opt, ...)
: variable parameter MUST be end with NULL.
. Properties:
enum class PropertyType {
learning_rate = 0,
decay_rate = 1,
decay_steps = 2,
beta1 = 3,
beta2 = 4,
epsilon = 5,
};
=> [API] set Optimizer Property 

nntrainer/include/layers.h, nntrainer/src/layers.cpp
This patch newly adds updateLoss method into FullyConnectedLayer class
to remove redundant code.
=> [API] Add updateLoss method

api/capi/include/nntrainer.h, api/capi/src/nntrainer.cpp, nntrainer/include/layers.h, nntrainer/include/parse_util.h, nntrainer/src/layers.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/parse_util.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp
Instead of using multiple string to describe key-value, it would be
more intuitive to be combine with "=".
for example,
ml_*_set_property (handle, "beta1=0.332", "beta2=0.001", NULL)
=> [API] change key, value format for the property

nntrainer/include/layers.h, nntrainer/include/parse_util.h, nntrainer/src/layers.cpp, nntrainer/src/parse_util.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp
Instead of using input_shape to get the fc layer dimenson, it is
simple to get the ouptut dimesion using unit keyword.
=> [ API ] using "unit" key to get the dimension for fc layer

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/main.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/res/edje/main.edc, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
Add main.edc to separate UI design/interactions
- Add main.edc
- Add view.[ch]
- Add data.h
- Change main initiation to use view function
- Move data definitions to data.h
=> [After #102] [Example] Add edc layout to the scaffolding @open sesame 05/18 16:27

nntrainer/include/bn_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, test/unittest/unittest_nntrainer_internal.cpp
Even though the layer instance is created, its type of property is not set properly so it is LAYER_UNKNOWN as default. Because of this reason, checkValidation() method is not working properly. 
Detailed patches of this PR are as below.
* Set layer type in constructor
* Add checkValidation() test case of each Layer class
=> [Bugfix] Set layer type in constructor

nntrainer/src/databuffer.cpp
There is an occasional error from `unittest_tizen_capi` 
This PR is a possible fix for the problem.
unittests runs more than 200 times without error with this patch.
```bash
[ RUN      ] nntrainer_capi_nnmodel.train_with_file_01_p
training
data_buffer made
data_buffer made done
size: 2
data_buffer clear
data_buffer end
double free or corruption (out)
Aborted (core dumped)
```
join data buffer threads first before clearing vectors that are
used in the target function to (possibly) prevent double free
=> Fix possible error that cause double free on destruction @open sesame 05/20 21:09

nntrainer/include/neuralnet.h, nntrainer/src/databuffer.cpp, nntrainer/src/neuralnet.cpp
There is memory leak at the last iteration of epoch. It run data
buffer again and exit without free the memory.
In this PR, this issue is fixed.
=> [ Fix ] Fix potential memory leak

Applications/Tizen_native/CustomShortcut/.gitignore, Applications/Tizen_native/CustomShortcut/res/edje/main.edc, Applications/Tizen_native/CustomShortcut/src/view.c
**Changes proposed in this PR**
- Add scaffolding layouts to be used to construct multiple pages
- Change group name "main" -> "home"
- Update .gitignore to ignore tizen studio generated files
=> [Example] Add basic layout in edc file @05/27 20:54

README.md
Recently we move ci server and there are some cases didn't apply the
change.
In this PR, change it in the README.md file
=> [ CI ] Fix wrong ci url

nntrainer/include/layer.h, nntrainer/src/fc_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/neuralnet.cpp
Cannot use weight initiatlization method for other layer.
In this PR, Move it into Layer class to use for other layer.
=> [ Refactor ] Layer Method for weight initialization

Applications/Tizen_native/CustomShortcut/.cproject, Applications/Tizen_native/CustomShortcut/.gitignore, Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
- Add and use _on_back_pressed_cb when back button is pressed
- Change `view_routes_to` signature to return naviframe item.
- Delete unused functions
- Bump tizen studio version to 3.7 and rebuild `.cproject` 
=> [Example] Add exit when naviframe is empty

nntrainer/src/bn_layer.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/tensor.cpp
- Reduce `average()` call in `Optimizer::calculate
- Delete setZero call after construction `Tensor`
- Reduce indexing and multiplication in few loops
This PR results in better performance including roughly 60% decrease
in time spent in `Tensor::average()` in Classification example(checked in vtune).
=> Reduce duplicated function call

nntrainer/include/conv2d_layer.h, nntrainer/include/parse_util.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/parse_util.cpp, test/unittest/unittest_nntrainer_layers.cpp
. parse and set Convolution 2D Property
0. input shape : string
1. bias zero : bool
4. activation : string (type)
6. weight_decay : string (type)
7. weight_decay_lambda : float
9. filter : int
10. kernel_size : ( n , m )
11. stride : ( n, m )
12, padding : valid | same
=> [ Layer ] Set Property for Conv2D Layer

Applications/LogisticRegression/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/databuffer.h, nntrainer/include/fc_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/optimizer.h, nntrainer/include/tensor.h, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/databuffer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/tensor.cpp, nntrainer/src/util_func.cpp, test/include/nntrainer_test_util.h, test/tizen_capi/unittest_tizen_capi.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_tensor.cpp, test/unittest/unittest_util_func.cpp
Until now, nntrainer cannot handle 3D Tensor including channel. Only
supported 2D Tensor which is batch, height, width.
From this PR, nntrainer can handle 3D Tensor include channel. But more
optimization is required.
=> [ Refactor ] Modify to deal with 3D Tensor @open sesame 06/08 18:08

nntrainer/include/tensor.h, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
- add_i(Tensor T) operator for memcopyless operation
=> [Tensor] Add `add_i(Tensor T)` operator @open sesame 06/09 14:35

nntrainer/include/lazy_tensor.h, nntrainer/include/tensor.h, nntrainer/meson.build, nntrainer/src/lazy_tensor.cpp, nntrainer/src/tensor.cpp, packaging/nntrainer.spec, test/unittest/meson.build, test/unittest/unittest_nntrainer_lazy_tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
This PR propose 2 concepts.
1. Propose `*_i` type of operation to `Tensor`. Which mutates target
tensor instead of memcopying the tensor.(511c74d)
2. Add chaining for lazy & memcopyless operation.
For example Tensor could do the operation in such manner:
```cpp
Tensor t;
t.chain() /* Initial memcpy happens to guarantee immutability */
.add_i(x)
.multiply_i(y) /* NYI */
.divide_i(y) /* NYI */
.run()
```
operations are delayed until `.run()` is called. This is done by
monadic object named `DefferedTensor`.
=> Add lazy evaluation feature to Tensor @open sesame 06/09 16:16

nntrainer/include/tensor.h, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
- Add subtract_i(Tensor) operator for a memcpyless operation
- Lint unformated lines
=>  [Tensor] Add `subtract_i(Tensor)` operator @open sesame 06/09 19:12 (AFTER #131)

nntrainer/include/lazy_tensor.h, nntrainer/include/tensor.h, nntrainer/src/lazy_tensor.cpp, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp
- Register tensor ops to `LazyTensor`
- Add test fixture to `LazyTensor`
- Add tests to `LazyTensor`
- Change `Tensor::apply` signature to permit closures
=> Register Tensor ops to lazy tensor @open sesame 06/11 17:01

debian/control, debian/rules, nntrainer/include/conv2d_layer.h, nntrainer/include/tensor.h, nntrainer/include/tensor_dim.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/tensor.cpp, nntrainer/src/tensor_dim.cpp, packaging/nntrainer.spec, test/unittest/unittest_nntrainer_layers.cpp
This PR provides forwarding calculation of conv2d layer
=> [ Conv2D ] forwarding calculation

jni/Android.mk, nntrainer/include/fc_layer.h, nntrainer/src/fc_layer.cpp
This patch proposes concept of using memcopyless operation on Tensor.
- `i_operation` are used to calculate without memcopy in fc_layer.
=> [Proposal] Optimizing concept for Tensor operation

jni/Android.mk, meson.build, nntrainer/meson.build, nntrainer/src/tensor.cpp
- Fix:`meson -Denable-blas=false` has no dep found error
- Fix:sum() function bug when `USE_BLAS` is not defined
- Add openmp dependency
- Apply openmp to l2norm function
=> Add openmp parellelism to l2norm()

nntrainer/include/lazy_tensor.h, nntrainer/include/tensor.h, nntrainer/include/tensor_dim.h, nntrainer/src/fc_layer.cpp, nntrainer/src/lazy_tensor.cpp, nntrainer/src/tensor.cpp, nntrainer/src/tensor_dim.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
Current implementation of average() is confusing when compared with sum().
Both sum() and average() do not take axis, and perform similar operations.
However, the semantics of their output is different -
- sum() acts over the dimensions other than batch size
- average() acts over the batch size
To avoid this confusion, average is provided with axis argument with 0 as default.
This is now analogous to sum(axis) than sum()
Further, sum() is renamed to sum_by_batch() as thats what it does and is different from sum(axis)
Minor updates to TensorDim are also made
Resolves #99 
=> [tensor] Added axis dimension to average

nntrainer/src/lazy_tensor.cpp
Fix unintential memcopy occurring in capture clause in lambda
With this PR combined with #115, there is significant performance boost.
=> [LazyTensor] Fix memcopy happening on lambda func

nntrainer/include/tensor.h, nntrainer/src/tensor.cpp
- Add `static constexpr min / max` to Tensor
- Change normalization to use predefined method for acceleration
Resolves #141
=> Fix numeric limits in `Tensor`

nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/neuralnet.cpp
Errors in forward and backward propagation were ignored.
Added error handling for them.
Further, model was being saved after validation.
Errors in validation would result in no model.
Changed to saving of model after training than after validation.
=> [layers] Ignoring error in training/validation

Applications/ReinforcementLearning/DeepQ/jni/main.cpp, nntrainer/include/tensor.h, nntrainer/src/tensor.cpp
This method is initially proposed to flatten and clone mat to vector.
However, `Tensor::getData()` can cover most of it's purpose, it seems
no longer in need.
- Delete `Tensor::mat2vec()`.
See also:
https://github.com/nnstreamer/nntrainer/pull/149#discussion_r439172191
=> Refactor: delete Tensor::mat2vec()

nntrainer/include/lazy_tensor.h, nntrainer/include/tensor.h, nntrainer/src/lazy_tensor.cpp, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
- `Add_i(Tensor &T, float alpha)` for coefficient multiplication
- Change test accordingly
- Optimize `blas` implementation for `multiply_i`
- run clang format to auto lint
See also: #166
=> [Tensor] Change Add_i to have alpha signature

nntrainer/src/neuralnet.cpp
Input Layer does not have activation property
=> [ Bug ] setActivation for input layer

nntrainer/include/lazy_tensor.h, nntrainer/src/lazy_tensor.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp
This PR propose `LazyTensor::applyIf` for more control flow.
Because of the problem proposed in http://wg21.link/P0834R0, 
function wrapping macro is used as a workaround.
- add `LazyTensor::applyIf` semantics
- add `LazyTensor::applyIf` tests
=> Add `LazyTensor::applyIf`

jni/Android.mk, nntrainer/include/lazy_tensor.h, nntrainer/src/lazy_tensor.cpp, nntrainer/src/optimizer.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp
This PR is just for proposed purpose and should not be merged(yet).
Later this PR would contain improvement on `optimizer::calculate`
`X = X + Y` can be viewed as special case of `X = X + 1 * Y`. If you 
look at that way, adding alpha to make `X = X + alpha * Y` is natural.
With this change
`weight.add_i(weight.multiply(1 - beta))` can be substituted to
`weight.add_i(weight, 1 - beta)`.
This kind of operation happens a lot in NN Training.
still alpha = 1 will be set. So user thinks it does not use alpha value
for normal adding case.
This is initial proposal to add control flow to LazyTensor method.
applyIf can run the operation only when `pred` is `true`.
It is skipped if not.
for example this can be used like below to integrate operation using potential optimization(done by `LazyTensor`) …
=> [Refactor] optimizer::calculate (After #175)

nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp
learning rate is decayed using the iteration
however current implementation was using epoch count
Note: iteration is saved so that it can be saved with optimizer to continue training if needed.
=> [neuralnet] Iteration bug fix in learning rate

nntrainer/include/pooling2d_layer.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/pooling2d_layer.cpp
This PR fixs the copy member function of covn2d and pooling layer.
. include copy of layer varaibles for conv2d
. implemnet copy of pooling2d layer
=> [ Layer copy ] copy function for conv2d & pooling

Applications/Tizen_CAPI/main.c, api/capi/include/nntrainer.h, api/capi/src/nntrainer.cpp, test/tizen_capi/unittest_tizen_capi.cpp
Exposed function "model_construct_with_conf" with config input makes "compile_with_conf" looks strange without any config
Rather, just keep one common "model_construct"  for construction of the model and "compile_with_conf" can take the config file
=> [API] simplify API

nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/neuralnet.h, nntrainer/include/optimizer.h, nntrainer/include/pooling2d_layer.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/parse_util.cpp
Properties exposed to the users and internal are different (losslayer, etc)
Hence using `*_string.size() - 1` for unknown cases will cause bugs in parse_util
Replaced with its own individual unknown value
V2:
Combined all individual layer properties into common properties in layer.h
=> [parse] Parse unknown properties

nntrainer/src/tensor.cpp
`memset` can't be used to initialize a float array as explained [here](https://stackoverflow.com/questions/1040070/initializing-a-float-array-with-memset)
- change `memset` to `std::fill`
=> Fix bug in `Tensor::setValue`

jni/Android.mk, nntrainer/include/activation_layer.h, nntrainer/include/layer.h, nntrainer/meson.build, nntrainer/src/activation_layer.cpp, packaging/nntrainer.spec
- add activation_layer.[h|cpp] (~Partly~ implemented)
- add test to activation_layer(#190)
- add activation_layer when ini find activation property(~planned to~ moved to another PR)
- change cost calculation to be independent from actiType(maybe in another PR, TBD)
- add `COST_ENTROPY_SIGMOID` to `CostType`
- add `COST_ENTROPY_SOFTMAX`
- move `activation_type` to activation_layer (NYI, maybe in another PR)
- remove `activation`, `activation_prime` from Layer(NYI, maybe in another PR)
see also #153, #152 
=> Separate activation to layer @open sesame 06/18 15:46

.clang-format, nntrainer/include/databuffer.h, nntrainer/include/layer.h, nntrainer/include/lazy_tensor.h
preivious initialization list was hard to read when it gets too long.
eg) layers initialization list
before:
```cpp
Layer()
: last_layer(false), init_zero(false), type(LAYER_UNKNOWN),
activation(NULL), activation_prime(NULL), activation_type(ACT_UNKNOWN),
bn_follow(false), weight_decay(), weight_ini_type(WEIGHT_UNKNOWN) {}
```
after:
```cpp
Layer()
: last_layer(false),
init_zero(false),
type(LAYER_UNKNOWN),
activation(NULL),
activation_prime(NULL),
activation_type(ACT_UNKNOWN),
bn_follow(false),
weight_decay(),
weight_ini_type(WEIGHT_UNKNOWN) {}
```
1. Build test: [ ]Passed [ ]Failed [x]Skipped
2. Run test: [ ]Passed [ ]Failed [x]Skipped
=> [Proposal] clang format for initializer list

.clang-format, nntrainer/include/activation_layer.h, nntrainer/include/databuffer.h, nntrainer/include/layer.h, nntrainer/include/lazy_tensor.h, nntrainer/include/loss_layer.h, nntrainer/include/neuralnet.h, nntrainer/include/optimizer.h, nntrainer/include/pooling2d_layer.h, nntrainer/src/fc_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/parse_util.cpp, nntrainer/src/pooling2d_layer.cpp, nntrainer/src/tensor.cpp, nntrainer/src/util_func.cpp
Clang-format 6 is widely used. However,
`AllowAllConstructorInitializersOnNextLine` added from #203 is supported
from clang-format 9.
This Pr reverts use of `AllowAllConstructorInitializersOnNextLine`
while having similar linting style.
=> Make .clang-format competible with version 6

Applications/Classification/jni/Android.mk, Applications/KNN/jni/Android.mk, Applications/Training/jni/Android.mk, Applications/prepare_tflite.sh
There seems a problem with building tensorflow. This PR propose to use
prebuilt tensorflow-lite instead of building one.
- Change `Applications/android.mk` to use prebuilt library (thanks to @jaeyun-jung )
- Change `prepare_tflite.sh`
- Bump tflite to 1.13.1 as suggested in #20
Resolves #207
=> [Fix/jni] Change tflite-dependency

nntrainer/include/layer.h, nntrainer/include/optimizer.h, nntrainer/src/fc_layer.cpp, nntrainer/src/optimizer.cpp
- remove weight_decay from `Optimizer::calculate` signature
- fix bugs that weight_decay was applying twice
- apply weight decay to `fc_layer`
please note that `conv2d_layer::backwarding` also need to handle weight
decay after this PR is merged.
Resolves #213
=> Move weight_decay handling from opt to layer

nntrainer/include/optimizer.h, nntrainer/src/optimizer.cpp
Bias updatation fixed for sgd where it only happened when bias was initialized with 0
For adam, bias updatation was happening twice
cc. @jijoongmoon Did I misinterpret a feature as a bug?
=> [bias] Bias updation missing for sgd

nntrainer/src/fc_layer.cpp
optimizer signature now does not have `init_zero`
This quick fix deletes init_zero from `fc_layer::backward`
=> Fix optimizer signature

nntrainer/src/activation_layer.cpp
The derivative of softmax has been handcrafted to be different from others
Refer to https://github.com/nnstreamer/nntrainer/blob/2a650512813db6ce3bba828b5790066fbc655f14/nntrainer/src/fc_layer.cpp#L264-L267 for the original implementation
Softmax requires softmax(x) as input for derivative while other activations require x as input for derivative
=> [activation] Derivative for activation

test/unittest/unittest_nntrainer_tensor.cpp
This Pr adds tensor save / read test.
Not directly related to the PR though, save & read better
need error handling
=> Add tensor save / read test

nntrainer/src/optimizer.cpp
Tensor copy constructor and copy assigment operator creates a copy of the vector
This led to bug in optimizer which updated the copy of the weight than the weight itself
Fixed by refernce of weight in optimizer
Resolves #241
=> [optimizer] Bug fix

nntrainer/include/layer.h, nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp
Add missing initialization and setting input/output dimension for activation layer
Also updated setting previous dimension to be from the last computation layer
=> [activation] Add missing config for activation layer

api/capi/src/nntrainer.cpp, nntrainer/include/tensor_dim.h, nntrainer/src/activation_layer.cpp, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/databuffer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/pooling2d_layer.cpp, nntrainer/src/tensor_dim.cpp, test/unittest/unittest_databuffer_file.cpp, test/unittest/unittest_nntrainer_internal.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_tensor.cpp
**Prerequisite**
- Add capi exception wrapper (~later pr~ #237)
- Add `std::invalid_argument` to `TensorDim::setTensorDim`
- Fix `fc_layer` positive test does not have unit declared.
- Fix tests accordingly.
**Todo**
- ~Add TensorDim test (positive && negative)~
See also: #233
2. Run test: [X]Passed [ ]Failed [ ]Skipped ~(CAPI needs error handler)~
=> [WAIT FOR #237] Add exception to TensorDim::setTensorDim @open sesame 07/03 11:18

nntrainer/include/lazy_tensor.h, nntrainer/include/tensor.h, nntrainer/src/tensor.cpp
This PR restructures Tensor to enable sharing between Tensor. as well as refactoring the inner data structure to not use vector also providing significant speed increases(20s -> 10s in example application)
- Change inner data structure
- Refactor Tensor ctors
- Add copy/move ctors & assignment operators
=> Restructure inner data structure inside Tensor

nntrainer/include/layer.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp
Since layers only store weights reference, store them once than doing it in every iteration
=> [weight/gradients] Initialize Weights once only

nntrainer/src/pooling2d_layer.cpp
When pooling2d_layer is initialized once as a default.
and initialized again as a `global_max` | `global_pooling`
`output.width`, `output.height` is set to 2.
Although following scenario is highly unlikely, initializing layer
should be done deterministically.
=> Fix potential bug in pooling 2D layer

api/capi/src/nntrainer.cpp, nntrainer/include/layer.h, nntrainer/src/activation_layer.cpp, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/layer.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp
Many layers has common properties which are defined in layer.h
As they are in layer.h and are expected to be used in most layers, lets set their properties in layer.h itself
This reduces a lot of redundancies
If some property is not required to be handled by a specific layer in rare case, handle it as an error in that layer itself
Related Issue #260
=> [property] Set common properties in layer.h

packaging/nntrainer.spec
This patch fixes the wrong Requires for libopenblas.
=> [Spec] Fix the wrong Requires section

nntrainer/include/tensor.h, nntrainer/src/conv2d_layer.cpp, nntrainer/src/pooling2d_layer.cpp, nntrainer/src/tensor.cpp, nntrainer/src/util_func.cpp, test/unittest/unittest_nntrainer_tensor.cpp
Tensor constructors should not zero to the memory by default
This hides many bugs in the code and also leads to big overheads
Removed setting zero in constructor and corresponding many bug fixes
=> [bug fixes] [tensor] Tensor constructor should not set zero

Applications/Tizen_CAPI/capi_file.c, Applications/Tizen_CAPI/capi_func.c, api/capi/include/nntrainer.h, api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, test/tizen_capi/unittest_tizen_capi.cpp
Update C-API semantics about layer and optimizer
While the layer and optimizer are in use, do allow deletion of layer and optimizer
Further, once the layer and optimizer are set/added to a model, their ownership is transferred to the model
So, no need to delete them separately. Deleting the model will directly delete them as well.
=> [API] Update C-API semantics

nntrainer/include/activation_layer.h, nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/loss_layer.h, nntrainer/include/parse_util.h, nntrainer/include/pooling2d_layer.h, nntrainer/src/activation_layer.cpp, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/pooling2d_layer.cpp, test/unittest/unittest_nntrainer_layers.cpp
Since Layer::setProperty is iterating through vectors, only part that
needs overriding is setting each particular property.
This PR add setProperty by type to relieve the issue.
w.r.t #270, this patch enables layers to check if given property type
is valid.
=> Add setProperty for each property type

test/unittestcoverage.py
This patch fixes the coverage generator to use python3.
It seems that Python2 package was removed in nntrainer.spec.
Signed-off-by: Dongju Chae <dongju.chae@samsung.com>
=> [Urgent][Fix/Coverage] Fix the coverage generator to use python3

nntrainer/include/layer.h, nntrainer/include/parse_util.h, nntrainer/src/layer.cpp, nntrainer/src/parse_util.cpp, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_tensor.cpp
Hook points and print options are added to customize print options.
- Add print option to layer
- Add `Layer::print` function
- Add hook point to print function for derived layer.
- Add `ostream &operater<<` for Layer type
Level of verbosity can be defined as a combination of `PrintOptions` with this PR.
For example, print with options
```cpp
unsigned int option = nntrainer::LayerPrintOption::PRINT_INST_INFO |
nntrainer::LayerPrintOption::PRINT_SHAPE_INFO |
nntrainer::LayerPrintOption::PRINT_PROP |
nntrainer::LayerPrintOption::PRINT_PROP_META |
nntrainer::LayerPrintOption::PRINT_WEIGHTS |
nntrainer::LayerPrintOption::PRINT_METRIC;
```
in `conv2d layer` would result:
```
======instance info: 
<N9nntrainer11Conv2DLayerE at 0x5589a5e55fc0>
Layer Type: 3 …
```
=> Add layer print

nntrainer/src/neuralnet.cpp
Delete layer in finalize had wrong index. This PR fix this issue
=> Fix NeuralNetwork::finalize

nntrainer/include/databuffer.h, nntrainer/include/databuffer_file.h, nntrainer/include/databuffer_func.h, nntrainer/src/databuffer.cpp, nntrainer/src/databuffer_file.cpp, nntrainer/src/databuffer_func.cpp
data buffer updateData() passes the reference of a on-stack variable
which is deleted after the function call exits. However the callee function
remains on a new thread causing problems.
Added bug fix for this.
=> [data buffer] Bug fix for data buffer

Applications/Tizen_CAPI/capi_file.c, Applications/Tizen_CAPI/capi_func.c, Applications/Tizen_CAPI/main.c, api/capi/include/nntrainer.h, api/capi/include/nntrainer_internal.h, api/capi/meson.build, api/capi/src/nntrainer.cpp, api/capi/src/nntrainer_util.cpp, nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp
Setting optimizer now uses enum than string
The name space of the layers has been updated
Below is the summary the updates:
ml_nnmodel_* -> ml_train_model_*
ml_nnlayer_* -> ml_train_layer_*
ml_nnopt_* -> ml_train_optimizer_*
*_delete() -> *_destroy()
ml_nnmodel_train_with_file() and ml_nnmodel_train_with_generator() have been kept back
These will be updated in the upcoming PR where dataset interface for API is updated
=> [API] Update API namespace and use enum for opitmizer

api/capi/include/nntrainer_internal.h
Remove duplicate declaration of ml_train_model_run_async
cc. @jijoonmoon
=> [api] remove duplicate declaration

nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/optimizer.cpp
Gradient dimension should match weight dimension
Currently optimizer applies averaging of gradients, which is not correct
Apply averaging of gradients before calling applyGradients
Further, Gradients of the layer should perform sum over batch than average
This is consistent with tensorflow's implementation
Resolves #280
=> [optimzer/layers] Gradient dimension should match weight dim and sum

test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/meson.build, test/unittest/unittest_nntrainer_modelfile.cpp
Add automated test scaffolding to test modelfile configuration &
NN initiation.
- Add `IniSection `class to control ini (for testing)
- Add Ini test fixture for paremeterized ini testing
- Add `unittest_nntrainer_modelfile.cpp`
=> Add test for modelfiles

Applications/KNN/jni/Android.mk, Applications/LogisticRegression/jni/Android.mk, Applications/ReinforcementLearning/DeepQ/jni/Android.mk, Applications/Training/jni/Android.mk, api/capi/include/nntrainer.h, api/capi/src/nntrainer.cpp, api/nntrainer-api-common.h, nntrainer/include/layer.h, nntrainer/include/neuralnet.h, nntrainer/src/layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/neuralnet.cpp, test/tizen_capi/unittest_tizen_capi.cpp
This PR mainly add `NeuralNetwork::print`. Note that it should be highly
refactored for proper functionality. Confer `@todo`'s in this patch.
- add `NeuralNetwork::print`
- implement `model_get_summary`
- Add capi test for `model_get_summary`
- move `ml_train_summary_type_e` to `api-common`
- minor bug fix
=> [CAPI] Implement summary api

nntrainer/src/neuralnet.cpp
Fix flag to be parsed properly by verbosity
cc. @jijoongmoon
=> Fix summary logic error

nntrainer/src/neuralnet.cpp
Add bug fix for setTrainConfig
Break in switch in default case was hiding the error
=> [neuralnet] Bug fix for setTrainConfig

nntrainer/src/neuralnet.cpp, test/tizen_capi/unittest_tizen_capi.cpp
Batch size property should be set before compiling for now
Initializing of layers allocates memory for the layers
Setting batch size property with training call requires layers to be re-initialized
which isnt supported yet
resolves #278
=> [neuralNet] Moving batch size property to compile time

packaging/nntrainer.spec
This patch fix rpm spec file dependency for `capi-nntrainer`
Resolves #357
=> Fix rpm spec file dependency

Applications/Tizen_native/CustomShortcut/.cproject, Applications/Tizen_native/CustomShortcut/.project, Applications/Tizen_native/CustomShortcut/.tproject, Applications/Tizen_native/CustomShortcut/README.md, Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/tizen-manifest.xml
- Bump project version to 6.0 in order to use nntrainer
- Add sanity test for nntrainer (will be removed in the future)
=> [example] Bump to tizen 6.0 && add nntrainer capi

Applications/Classification/jni/main.cpp, Applications/Classification/jni/meson.build, Applications/Classification/res/Classification_func.ini, Applications/KNN/jni/meson.build, Applications/LogisticRegression/jni/meson.build, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/meson.build, Applications/Tizen_CAPI/meson.build, Applications/Training/jni/meson.build, Applications/mnist/jni/meson.build
This patch currently check if example apps are running fine.
To make this better, we should add parameterized app test with golden
result plus some negative cases rather than running 1 test per 1 app,
it is not done because it is not the highest priority.
This patch only ensures that it is running fine for current setup(ini
and other stuff)
So this tests does not guarantee that app is running fine for every
cases.
resolves #375
see also #374
=> [ Meson ] Add app sanity test

Applications/Classification/jni/main.cpp, Applications/Classification/jni/main_func.cpp, Applications/Classification/jni/meson.build, Applications/Classification/res/Classification_func.ini, Applications/KNN/jni/meson.build, Applications/LogisticRegression/jni/meson.build, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/meson.build, Applications/Tizen_CAPI/meson.build, Applications/Training/jni/main.cpp, Applications/Training/jni/meson.build, Applications/mnist/jni/main.cpp, Applications/mnist/jni/meson.build, api/capi/src/nntrainer.cpp, nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp, test/unittest/unittest_nntrainer_internal.cpp
Change `Neuralnet::setConfig` to throw instead of return status
**This PR also patches:**
- Minor typos
- Delete unused function
- Fix neuralnet ctor delegation order
=> [Wait 4 #378] Change neuralnet setConfig to throw

nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/optimizer.h, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/optimizer.cpp
Many layer has setOptimizer implemented while layer can hadle all.
- Delete unnecessary setOptimizer
- Unify optimizer::initialize signature
=> Unify optimizer initialize

nntrainer/src/nntrainer_logger.cpp
This patch fix bugs that logging happen twice in non tizen environment
=> Fix bug that logging happen twice

nntrainer/include/bn_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/pooling2d_layer.h, nntrainer/src/flatten_layer.cpp, nntrainer/src/pooling2d_layer.cpp
Remove extra forwarding declaration and definition from layers
forwarding (in, out, status) is only to be supported by loss
it is not needed by other layers and should not be supported
=> [layers] Remove extra forwarding definition from layers

test/tizen_capi/unittest_tizen_capi.cpp
Train with generator positive unittest bugs are fixed
Now, it is also training
=> [unittest] Tizen C-API unittest bug fix

Applications/Tizen_CAPI/capi_file.c
issue #377 has occurred since #403.
Found that current classification assumes to have trainingSet as a
validationSet.
Fixed accordingly, which resolves #377
I think it is hard to say as a bug though, this patch enables training.
=> Tizen C-API application bug fix

Applications/ReinforcementLearning/DeepQ/jni/main.cpp, nntrainer/include/activation_layer.h, nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/lazy_tensor.h, nntrainer/include/loss_layer.h, nntrainer/include/neuralnet.h, nntrainer/include/optimizer.h, nntrainer/include/pooling2d_layer.h, nntrainer/include/tensor.h, nntrainer/src/activation_layer.cpp, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/pooling2d_layer.cpp, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_tensor.cpp
This patch enables default copy constructor to fix #281 and resolves #409 
=> [Tensor] Enable default copy constructor @open sesame 08/10 14:32

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/res/edje/main.edc, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/view.c
In this patch, user draws smile face and sad face respectively for 5
times.
It is splited half to trainset/validationSet and used for training.
Thus deleting inference part and instead train result (accuracy, train result, validation result will be shown)
=> [Example] Change user scenario

nntrainer/include/tensor_dim.h, nntrainer/src/tensor.cpp, nntrainer/src/tensor_dim.cpp, test/unittest/unittest_nntrainer_layers.cpp
Default tensor dim constructor sets up tensorDim of all 0 which are invalid to use by nature
Setting any dimension resets all the 0 dimensions to 1
This removes allocation of memory by tensor on default constructor yet allows using default constructor of tensor
Resolves #359
=> [TensorDim] Change behaviour of default tensorDim constructor

api/capi/src/nntrainer.cpp, nntrainer/include/neuralnet.h, nntrainer/include/tensor_dim.h, nntrainer/src/neuralnet.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
- Add term `realization`. This term denotes that enum type is turned
into an instance
- Change `initActivationLayer` -> `realizeActivationType`
- Change `initFlattenLayer` -> `relizeFlattenType`
- Delete `_make_act_layer`
- Add `TensorDim::isEmpty()`
- Clarify `checkValidation` -> `isInitializable` and move beforehand
validation logics
- Fix logic that prevents double activation
- Move layer name validaton phase `addLayer` -> `isInitializable`
- Prevent realization of `ACT_NONE`
- Sort unittest_modelfile order and update comments
- Enable few test cases
Resolves #390
See also #388
=> Additional validation and fixes for network::init

Applications/Classification/jni/main.cpp
Previously model path is fixed as "../../res/mobilenetv2.tflite"
In this PR, data_path is used for define path.
=> [ Application ] fix model file path of classification example

nntrainer/src/conv2d_layer.cpp, nntrainer/src/neuralnet.cpp
In this PR, calculation of training loss is fixed.
Previously, network loss is calculated using last mini_batch size data set.
This should be summarized through out whole data set and averaged.
=> [ Bug ] Fix calculating training loss

nntrainer/src/bn_layer.cpp
Remove ununsed gradients for mu and variance for the batch normalization layers to remove unnecessary memory usage.
=> [bn_layer] Remove unused gradients

nntrainer/src/neuralnet.cpp
Multiple nested loop with same variable names are being used. Fix that.
Also, reporting for train epoch should start from 1 and not from 0.
=> [neuralnet] Train loop index variable reuse remove

Applications/ReinforcementLearning/DeepQ/jni/main.cpp, nntrainer/include/tensor.h, nntrainer/src/activation_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
Tensor setDim() is renamed to reshape() as tensor should only be allowed to reshape
Resizing it invalidates the invariant for the other holders of the same data of tensor (see also #412)
This patch renames setDim() to reshape() which throws if there is an attempt to change size
Further getDim() now returns a copy of the dimension to disallow changing dimension of a tensor directly
Also some aliases in Tensor (like getWidth()) have been removed. Rather, width() like functions are kept
to maintain coherency with TensorDim() interface.
Resolves #412
=> [tensor] restricted setDim is now reshape

test/unittest/unittest_nntrainer_layers.cpp
This patch fixes no test that has no assertion
=> [TCM] Fix no assertion test

packaging/nntrainer.spec
- Fix typo capi-nntrainer that are causing unexpected exit
=> Fix typo in capi-nntrainer spec

nntrainer/include/databuffer.h, nntrainer/src/databuffer.cpp, nntrainer/src/databuffer_file.cpp, nntrainer/src/databuffer_func.cpp, nntrainer/src/model_loader.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
This patch changes the initialization of buffer size.
The buffer size is now initialized with value 1 if user does not set it.
Then the proper checks on buffer size are performed at init
and buffer size is appropriately resized then.
=> [dataset] check bufsize at init

api/capi/src/nntrainer.cpp, nntrainer/include/layer.h
- Change logic to feature check first for `ml_train_construct_with_conf`
- Add exception boundary to all make_shared
- Add noexcpt to `layer::getName` since errors are not handled in capi
=> [CAPI] Fix potential issue in capi

nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp, test/include/nntrainer_test_util.h, test/tizen_capi/unittest_tizen_capi.cpp
This patch add verification of accuracy for training metrics like loss and accuracy
in capi test cases
=> [unittest] Add verification of accuracy for training metrics

nntrainer/src/databuffer.cpp, nntrainer/src/databuffer_file.cpp
When the buffer thread broadcasts "DATA_END" while main thread get the
data from buffer, the main thread return even if there are data in
data buffer.
This PR includes fix this situation.
releated issues #427
=> [ DataBuffer ] Fix for conner cases.

nntrainer/include/tensor.h, nntrainer/include/tensor_dim.h, nntrainer/src/tensor.cpp, nntrainer/src/tensor_dim.cpp, test/unittest/unittest_nntrainer_tensor.cpp
This patch adds multiple axes support for sum and average.
which is esentially needed to build bn_layer
=> [Tensor] Add multiple axes support

api/capi/src/nntrainer.cpp, nntrainer/include/databuffer.h, nntrainer/src/databuffer.cpp, nntrainer/src/databuffer_func.cpp, test/tizen_capi/unittest_tizen_capi_dataset.cpp
Support setting user_data for the dataset using generators
For now, there is only 1 user_data for all 3 train/valid/test dataset
The format for setting user_data is
"ml_train_dataset_set_property(dataset, "user_data", (void *) data, NULL)"
It is to be passed two consecutive arguments, and with list being terminated by NULL
=> [dataset] Support setting user_data for generator dataset

nntrainer/include/optimizer.h, nntrainer/include/tensor.h, nntrainer/src/bn_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/tensor.cpp
The default constructor does no heap memory allocation (size is 0)
However it can still throw which isn't right
This patch updates the tensor default constructor to not throw because of heap allocation
to create less issues with static checkers which requires to add try catch around tensor declarations
=> [wait for #529] [tensor] Update default constructor of tensor to not throw

nntrainer/include/optimizer.h, nntrainer/src/bn_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/optimizer.cpp
This patch provides bugfix for setting the optiimzer for bn layer
although the weight updates are called only for the trainable params,
the optimizer is initialized with all the weights which are not trainable
and have no gradients
This results in un-necessary memory allocation for them as well as
creates issues for #517
This patch adds a count for trainable_param_size and a getTrainableParams() for the layer
and instead of all params, only trainable params of the layer are passed to the optimizer
An alternate was for the optimizer to check gradient size and ignore the ones with 0 size
but thats over-engineering at this point.
Resolves #528  …
=> [bn] bug fix for setting optimizer for bn layer

test/tizen_capi/meson.build, test/unittest/meson.build
Install missing unittest dependent files when installing the unittest
=> [unittest] install unittest dependent files

.gitignore
- Add python generated extensions to gitignore
1. Build test: [ ]Passed [ ]Failed [x]Skipped
2. Run test: [ ]Passed [ ]Failed [x]Skipped
=> Add gitignore for python generated files

Applications/TransferLearning/Draw_Classification/jni/meson.build, nnstreamer/tensor_filter/meson.build
Move dependencies of glib and gstreamer to nnstreamer plugin from applications
=> [meson] Move dependencies to correct location

nntrainer/include/nntrainer_error.h
NNTrainer is not LGPL. It is Apache2.0 and fix accordingly.
Signed-off-by: HyesuAhn <linim@naver.com>
=> [ LICENSE ] Fix license header

nntrainer/include/bn_layer.h, nntrainer/include/layer.h, nntrainer/src/bn_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/parse_util.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
This patch add properties for bn layer
- momentum
- moving_mean_initializer
- moving_variance_initializer
- gamma_initializer
- beta_initializer
=> Add bn layer properties

nntrainer/src/databuffer.cpp
Add check and return INVALID_PARAM when the validation bit is false.
If it returns INVALID_PARAM, then train_run return INVALID_PARAM as
well.
related issues : #425 
=> [ DataBuffer ] Fix Undeterministic Behavior when validation is false

nntrainer/src/tensor.cpp, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/unittest_nntrainer_tensor.cpp
Fix bug that strides and buffer axis are miscalculated
- Clarified consecutive-one strategy and same-stride(dimension matching) strategy
- Change the last stride to 0 only if it is using a consecutive-one strategy
- Add regression test
Resolves: #559
Cc: Jijoong Moon <jijoong.moon@samsung.com>
=> [Tensor] Fix bug in the broadcast support @open sesame 09/18 11:48

Applications/TransferLearning/Draw_Classification/jni/bitmap_helpers.cpp, Applications/TransferLearning/Draw_Classification/jni/bitmap_helpers.h, Applications/TransferLearning/Draw_Classification/jni/main.cpp, Applications/TransferLearning/Draw_Classification/jni/meson.build, Applications/TransferLearning/Draw_Classification/res/Training.ini, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, packaging/nntrainer.spec
Update transfer learning application to use just C-API
This divides the application into 3 parts -
1. Running the fixed part of the model - done using nnstreamer-single C-API
2. Training the trianable part of the model - done with nntrainer C-API
3. Running the testing of the trainable part of the model - done with nnstreamer-pipeline C-API with nntrainer tensor filter extension
The outputs of section 1 is kept loaded in the memory than saving to disk and loading back
Commit - 2
Added callback for testing the model
The callback prints the top-1 predicted output for a given image file
Increased number of epochs back to 1000 to acheive better accuracy
Resolves #451 
Signed-off-by: …
=> [application] Transfer learning using just C-API

nntrainer/include/addition_layer.h, nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/optimizer.h, nntrainer/include/pooling2d_layer.h
Make all move constructors to be noexcept
Without noexcept, compiler many times does not use move constructor but rather uses copy constructor
=> [layers] Move constructors must be noexcept

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/src/loss_layer.cpp, nntrainer/src/neuralnet.cpp
Added inference bug fix to run the last activation layer when it has been merged in the loss layer This is done by supporting forwarding(in) method for loss which was earlier not supported We just have to be careful for this not be called in any other case other than inference
Later this will be changed to handled with train/eval mode (which I think @zhoonit will add for bn layer)
Resolves #587
=> [inference] Inference bug fix @open sesame 09/23 15:03

packaging/nntrainer.spec
NNtrainer tensor filter was packaged with nntrainer which isnt right
Now nntrainer tensor filter is packaged separately and depends on nnstreamer and nntrainer both
=> [dist/tizen] Package tensor filter properly

debian/changelog, packaging/nntrainer.spec
=> [ Release ] NNTrainer 0.1.1 Release

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/main.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/res/edje/main.edc, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
- Change home to accomodate inference
- Route draw inference
- Add `draw_target` to use appdata to address label
resolves #571 
=> [CS] Add inference page @open sesame 09/24 19:32

Applications/TransferLearning/Draw_Classification/jni/main.cpp
Update transfer learning application to use softmax prediction value
to give prediction only if softmax is beyond certain threshold
=> [transfer learning] Update to use softmax prediction

Applications/LogisticRegression/jni/main.cpp, Applications/MNIST/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp, api/capi/src/nntrainer.cpp, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp
Merge model finalize to destructor itself
User need not call finalize explicitly
Other minor updates:
- Merge all train methods into 1
- isInitializable() is made private. Removed some of the name checking from this function
to when the layer itself was created.
=> [model] Merge model finalize to destructor

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/main.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
This patch layouts Customshortcut refactor. It is being migrated
Model-View-Presenter pattern for clarity.
- Add `presenter_*` to main presenter function
- Add `util_*` to data for utility function
- Some static function residing in `view.c` has exposed
- Strict segregation between view and data change
Resolves #577
=> [CS/Refactor] restructure code to MVP pattern @open sesame 09/24 19:32 

Applications/Tizen_native/CustomShortcut/inc/main.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
- Disable backkey press while training
- Move back_key callback to `presenter`
- Prune unnecessary argument for view/create_layout
Resolves #573
=> [CS] Prevent HW backkey press while training  @open sesame 09/24 19:32 

jni/Android.mk, nntrainer/include/layer.h, nntrainer/include/neuralnet.h, nntrainer/include/optimizer.h, nntrainer/include/tensor.h, nntrainer/include/tensor_dim.h, nntrainer/include/weight.h, nntrainer/meson.build, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/optimizer.cpp, nntrainer/src/tensor.cpp, nntrainer/src/tensor_dim.cpp, nntrainer/src/weight.cpp, packaging/nntrainer.spec, test/unittest/unittest_nntrainer_layers.cpp
Added a weight class to simplify headers All weight-related enums and properties go to the weight header rather being dumped in layer or optimizer.
=> [weight] weight class to simplify headers and enums

Applications/MNIST/jni/main.cpp, nntrainer/include/neuralnet.h
getLoss used to get the current loss of the model which was based
on the previous batch of data which the network ran on.
This does not allow getting training/validation loss.
Added getTrainingLoss and getValidationLoss for this purpose.
And update getLoss description to include this information.
As MNIST application was using getLoss() which returns the
loss of the last ran element, this value was changed with #600
as with #600 last element is a batch of data than just 1 data element.
The application is updated to now compare all three loss with
updated values.
So, this patch fixes that bug in main branch as well.
Resolves #617 …
=> [neuralnet] Add alternatives to getLoss

nnstreamer/tensor_filter/meson.build
- Add gmodule_dep to build nnstreamer_filter_nntrainer
- `nnstreamer_subpluin.c` includes `gmodule.h`
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
The following compile error log was fixed:
```
...
[103/109] Linking target nnstreamer/tensor_filter/libnnstreamer_filter_nntrainer.so.                                                                                                                               
FAILED: nnstreamer/tensor_filter/libnnstreamer_filter_nntrainer.so                                                                                                                                                 
c++  -o nnstreamer/tensor_filter/libnnstreamer_filter_nntrainer.so 'nnstreamer/tensor_filter/27bbb30@@nnstreamer_filter_nntrainer@sha/tensor_filter_nntrainer.cc.o' …
```
=> [build/meson] Add gmodule_dep for nnstreamer subplugin

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/include/neuralnet.h, nntrainer/src/model_loader.cpp
Currently, with is_train, user has to decide at model construction if the model is to be used for inference or train but we still allow changing it. We dont need that difference, rather using inference/train should be allowed at anytime by just changing the batch-size (this has been allowed with the previous commit)
Now, once the train is done, with model loaded in memory, inference can be called directly. Inference can be run by creating and loading the model from disk.
=> [inference] Remove deciding for inference at model construction

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/res/edje/main.edc, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
Commit #1
change ad->draw_target to draw->label and draw->mode to
incorporate with inference and training at the same time
Commit #2
This patch shows inference to the page after evaluation.
=> [CS] Show inference

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/src/data.c
Currently, pngdec gstelement is not supported in the wearable by
default. Change save data format to jpeg in order to use jpegdec.
See also #553
=> [CS] Change png -> jpeg

nntrainer/include/activation_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer.h, nntrainer/include/loss_layer.h, nntrainer/include/neuralnet.h, nntrainer/include/pooling2d_layer.h, nntrainer/include/tensor.h, nntrainer/src/activation_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/parse_util.cpp, nntrainer/src/tensor.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/unittest/unittest_nntrainer_layers.cpp
Update the interface for layer This changes the public and private exposed member functions Corresponding unittests are updated
Major changes are for Flatten and Loss layers - they both now support setting basic layer properties such are input_shape etc.
Commit - 2:
Minor changes to tensor and model
Move BroadcastInfo to private
Move printMetrics to private
See also #199
=> [layer] Update layer interface

Applications/Tizen_native/CustomShortcut/inc/data.h, Applications/Tizen_native/CustomShortcut/inc/view.h, Applications/Tizen_native/CustomShortcut/res/model.ini, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/Tizen_native/CustomShortcut/src/main.c, Applications/Tizen_native/CustomShortcut/src/view.c
commit 1 minor retouch:.
- Ecore Pipe is no longer used to update UI
- Broaden the canvas to make it easier to draw
- s/tries/epoch for training progress
- Minor bug fix that was generating warnings
commit 2. Add cutoff logic
- Add more epochs
- Add cutoff logic to check if the guess is confident
=> [CS] Add cutoff logic through accuracy

nntrainer/include/databuffer.h, nntrainer/include/tensor.h, nntrainer/src/databuffer.cpp, nntrainer/src/neuralnet.cpp
This patch rearranges getDataFromBuffer to not rely on nested buffers to
avoid unnecessary allocation & deallocation.
This patch provides notable speedup for some cases.
resolves #611 
=> Refactor getDataFromBuffer

nntrainer/include/layer.h, nntrainer/include/pooling2d_layer.h, nntrainer/src/layer.cpp, nntrainer/src/pooling2d_layer.cpp
This PR includs:
- make Layer::setBatch virtual function to set batch size
- max_id for max poooling should be created at initialization time
but the batch size is not set properly at this time. So when the
setBatch is called for each layer, it is set properly.
TODO: depnding on inference and training, max_id should be handled
properly. It is not needed for inference.
=> [ Max Pooling ] Fix bug when max_id created

.github/CODEOWNERS
This commit is to fix an incorrect "@org/team-name" (e.g., @NNStreamer/nntrainer)
since there is no the team name that is called "@NNStreamer/nntrainer". So, we need
to replace @NNStreamer/nntrainer with @nnstreamer/nnstreamer.
For more details, please refer to the below webpage.
* NNStreamer's Teams - https://github.com/orgs/nnstreamer/teams
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
=> [GitHub] Replaced @NNStreamer/nntrainer with @nnstreamer/nnstreamer

README.md
As docker GIAG build support is no longer maintained, this patch removes
the guide to docker GIAG build.
=> [Docs] Remove docker GIAG from readme.md

nntrainer/src/neuralnet.cpp
setBatchSize is not called at init which cause a problem when calling
layers from outside.
This fixes the issue
=> [NN] call setBatchSize at init

nntrainer/include/layer.h, nntrainer/src/activation_layer.cpp, nntrainer/src/layer.cpp
`Act::setActivation` should be called for activationLayer.
However, because `virtual Layer::setActivation` had diffrent signature
`Act::setActivation`, There was no way this function can be called.
This patch fixes the issue.
=> [Bug/Act] Fix setActivation call properly

nntrainer/include/weight.h, nntrainer/src/weight.cpp
Weight did not have copy/move ctor which they should have.
This patch adds them.
Resolves #652 
=> [Weight] Add ctors

test/unittest/meson.build, test/unittest/unittest_nntrainer_models.cpp
This patch generates `NodeWatcher` and `GraphWatcher` to make a test for
unittest_nntrainer_model test.
- Add multi iteration test
- Add gtest scafolding
**Additional Patch will be followed**
- Handle loss + activation merge scenario
- Add param test
- Add mnist as a test
- Add final inference result
=> [Test] Add unittest_nntrainer_models 

nntrainer/src/layer.cpp
Print layer name if available
if layer name is not avaiable, then print layer object name and its address
Resolved #666 
=> [layer] Print layer name over layer address

Applications/LogisticRegression/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main.cpp, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/include/activation_layer.h, nntrainer/include/addition_layer.h, nntrainer/include/bn_layer.h, nntrainer/include/conv2d_layer.h, nntrainer/include/fc_layer.h, nntrainer/include/flatten_layer.h, nntrainer/include/input_layer.h, nntrainer/include/layer_internal.h, nntrainer/include/loss_layer.h, nntrainer/include/neuralnet.h, nntrainer/include/pooling2d_layer.h, nntrainer/include/tensor.h, nntrainer/src/activation_layer.cpp, nntrainer/src/addition_layer.cpp, nntrainer/src/bn_layer.cpp, nntrainer/src/conv2d_layer.cpp, nntrainer/src/fc_layer.cpp, nntrainer/src/flatten_layer.cpp, nntrainer/src/input_layer.cpp, nntrainer/src/loss_layer.cpp, nntrainer/src/neuralnet.cpp, nntrainer/src/pooling2d_layer.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_models.cpp
Currently we only take and push one tensor per layer. For the skip
connection or other layer which takes and make multiple tensors, we
need to handle tensors as an input and output of layer.
In this PR, tensor input chaneged to tensor vector.
=> [ TENSOR ] Change to get Tensor Vector

README.md
This patch adds hall-of-fame section to README.md
It looks like below
[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/images/0)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/links/0)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/images/1)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/links/1)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/images/2)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/links/2)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/images/3)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/links/3)[![](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/images/4)](https://sourcerer.io/fame/dongju-chae/nnstreamer/nntrainer/links/4)[![](https://sourcer …
=> [README.md] Add hall-of-fame section to README.md

nntrainer/include/layer_internal.h, test/unittest/unittest_nntrainer_layers.cpp
There was a bug that `std::cout << layer` is calling undefined function.
This patche fixes the issue and add some regression test.
=> [Layer] Fix 'stream << ' delegation

nntrainer/include/model_loader.h, nntrainer/include/neuralnet.h, nntrainer/src/model_loader.cpp, nntrainer/src/neuralnet.cpp, test/include/nntrainer_test_util.h, test/unittest/unittest_nntrainer_modelfile.cpp
This patch adds support of ini based backbone to the model neural network
From the point of view of ini file, backbone is treated as a layer itself.
This allows a graph of layers to be represented as a layer itself in the
ini file.
With this design, backbone must be specified as a layer with property backbone
as shown below with a sample pseudo-ini:
```ini
[Model]
...
[Block1]
backbone: base_block.ini
[PoolLayer]
type: pooling2d
[Block2]
backbone: base_block.ini
```
ModelLoader loads the layer configuration from the backbone independently
and then extends the existing graph in the main model with this newly created
graph from the backbone ini.
The names of all layers which are inserted from the backbone to a model are
prefixed with the name of the backbone for easier management and for …
=> [model] Add support of ini based backbone to the model

nntrainer/include/layer_internal.h, nntrainer/include/model_loader.h, nntrainer/src/model_loader.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
This patch adds supporting training feature to backbone
Corresponding unittests are also added
=> [backbone] Add trainable feature to backbone

nntrainer/include/optimizer_internal.h, nntrainer/src/optimizer.cpp
There was a bug that decay_rate were always applied when it is set to
default value. Becuase `decay_steps != -1` was evaluated to true.
This patch fixes the issue.
=> [Fix/Optimizer] Fix decay_rate application

nntrainer/src/bn_layer.cpp
Fix batchnormalizationLayer that epsilon is included toward saving
moving variacne that could lead to long term inaccuracy
=> [Fix/bn] Fix batchnormalize layer @open sesame 10/29 10:43

nntrainer/include/neuralnet.h, nntrainer/src/neuralnet.cpp, test/unittest/unittest_nntrainer_models.cpp
~From the paper, adam's time t start from 1. So other framework do like
`iteration + 1` because they start iteration from 0. However, nntrainer
start iteration from 1 so, iteration + 1 is not correct.~
~Also, there was a bug that iteration is not counted correctly for the
train data, this patch fixes the issue~
- Fix bug that epoch_idx is not saved for continue_train
- Fix iteration to start from 0 in model test
=> Fix adam iteration start to 1 at model_test

Applications/Tizen_native/CustomShortcut/res/model.ini, Applications/Tizen_native/CustomShortcut/src/data.c, Applications/TransferLearning/Draw_Classification/jni/main.cpp, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, test/nnstreamer_filter_nntrainer/runTest.sh
nntrainer takes data of NCHW
however, nnstreamer's tensor_converter produces data of format NHWC.
Existing implementation transposed the dimensions to match to NCHW format
However, the data was not transposed.
The unittest passed because the channel was just 1 which does not require
transpose on data side.
This patch removes the transpose of dimension from the nntrainer tensor_filter
and the transpose is done properly in the pipeline with nnstreamer's tensor_transform
Resolves #695
=> [tensorfilter] Bug fix of tranpose

nntrainer/include/tensor_dim.h, nntrainer/src/concat_layer.cpp, nntrainer/src/tensor_dim.cpp
Move the dimension checks for validity of the various inputs
for concat layer are moved to initialize().
They are kept back in forwarding() under DEBUG conditional.
=> [concat] Move validity checks to init

api/ccapi/include/layer.h, nntrainer/include/parse_util.h, nntrainer/src/layer.cpp, nntrainer/src/parse_util.cpp, test/unittest/meson.build, test/unittest/unittest_nntrainer_graph.cpp
This PR includes enabling 'input_layers' keyword.
With this keyword, we could specify layer's input tensor.
. Added skip in parse_util to remove space and '[',']' in string and
split with ',' delimiter.
=> [ Layer ] Add input_layers keyword

api/ccapi/include/layer.h, jni/Android.mk, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/output_layer.cpp, nntrainer/layers/output_layer.h, nntrainer/utils/parse_util.cpp
Currently there is no way to support multiple output.
However it is not neccessary to be explicit support.
Instead if user use "output_layers = layername0, layername1", then nntrainer
automatically add output layer. ( comparing ouput dimension and input
layer's dimension, we could decide it is addition or split operation. )
Also, if certain layer is specify as an input layer from mutiple
layers, then it should be added implicitly.
TODO: support split operation
=> [ Layer ] Add Output Layer to support multiple output

nntrainer/layers/pooling2d_layer.cpp
For the global pooling, we need to set the output dimension on last
dimension, width.
=> [ POOLING ] Fix global pooling dimensions

docs/configuration-ini.md, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/conv2d_layer.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/layer_internal.h, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/unittest_nntrainer_modelfile.cpp
Added ini backbone properties :
- scaleSize - scale the size of the model
- preload - load the weights of this backbone model before adding to the model
preload has issues which requires the format of the model file to update
wait for #361 
Commit2:
Added support for subgraph of a given ini backbone
Added corresponding unittests as well
=> [backbone] Add ini backbone properties

nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/meson.build, packaging/nntrainer.spec, test/unittest/meson.build, test/unittest/unittest_nntrainer_appcontext.cpp
This patch add basic app context with setting current working directory
Implemented without `std::experimental::filesystem`
~Current implementation (as of `f0d969f`) uses std::experimental::filesystem.~
~**ndk does not support std::filesystem until r22**~
~So either 1. we have to support from r22 or 2. reimplement related method in this patch.~
~IMO, I think we should stick to r21 since other people might not be using r22. and reimplement `app_context.cpp`~
=> [AppContext] Add AppContext

api/ccapi/src/factory.cpp, nntrainer/optimizers/optimizer_factory.cpp, nntrainer/optimizers/optimizer_factory.h
- ~**#720** [Fix] Throw when read/save fails~
- ~**#721** [Optimizer] Change enum type to string~
- [Optimizer] Add enum type factory
```
This patch adds integer factory to align with capi
```
=> [Optimizer] Add enum type factory

nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.cpp, nntrainer/optimizers/adam.cpp, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/utils/util_func.cpp, nntrainer/utils/util_func.h, test/unittest/unittest_nntrainer_activations.cpp
**Commit1:**
Update tensor op signature for dot
Further, fc layer has been updated based on this signature
**Commit2:**
This patch updates tensor signature to include output for apply
Correspondingly, activation layer and loss layer have been updated.
More changes in the patch
- Convolution layer has been updated to reuse its output derivative.
- added a getBatchSlice() which provides a slice of the original tensor by batch
and avoids creating a copy everytime
Note : Using a class like Weight for inputs/outputs has been inteniontionally skipped to limit the size of this patch. Further, the `ret_derivative` is not created as a vector, will be done when extended to a new class. 
See also #670 #732
2. Run test: [x]Passed [ …
=> [tensor] Tensor operations change style

api/ccapi/include/layer.h, api/ccapi/include/optimizer.h, api/ccapi/src/factory.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/layer_factory.cpp, nntrainer/layers/layer_factory.h, nntrainer/layers/loss_layer.h, nntrainer/layers/meson.build, nntrainer/layers/output_layer.cpp, nntrainer/layers/output_layer.h, test/ccapi/unittest_ccapi.cpp
Added syntactic sugar constructors for optimizers
which allow making optimizer closer to existing API
and more readable.
Resolves #734
=> [ccapi] Syntactic sugar constructors

nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/input_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/optimizers/adam.cpp, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/unittest_nntrainer_layers.cpp
Reduce overall tensor memory overhead
- standardization and normalization now take in-place
- input and label tensor in train are now allocated only once externally and reused for each epoch
that being used in each epoch
- add_i does not allocate new memory now
- removed support for normalization and standardization for conv layer
See also #670 #732
=> [tensor] Reduce overall memory overhead

nntrainer/layers/conv2d_layer.cpp, test/unittest/unittest_nntrainer_layers.cpp
Remove support for standardization and normalization from convolution operations
These operations do not support backwarding for now, and cannot be forwarded with conv2d layer for this reason
For now, this is only supported with input layer which is never backwarded
=> [conv] Remove standardization and normalization

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/app_context.cpp, nntrainer/app_context.h, test/unittest/unittest_nntrainer_appcontext.cpp
- ~#728 [AppContext] Add AppContext~
- ~#720 [Fix] Throw when read/save fails~
- ~#721  [Optimizer] Change enum type to string~
- [AppContext] Add register, invoke factory
```
[AppContext] Add registerer,invoke factory methods
- Add factory registerer
- Add factory invoker
- Register built-in objects to each layers(postponed)
- Add tests
```
=> [AppContext] Add register, invoke factory @open sesame 11/26 18:15

nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/layers/addition_layer.cpp, nntrainer/layers/addition_layer.h, nntrainer/layers/bn_layer.cpp, nntrainer/layers/bn_layer.h, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/conv2d_layer.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/flatten_layer.cpp, nntrainer/layers/flatten_layer.h, nntrainer/layers/input_layer.cpp, nntrainer/layers/input_layer.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.cpp, nntrainer/layers/loss_layer.h, nntrainer/layers/nnstreamer_layer.cpp, nntrainer/layers/nnstreamer_layer.h, nntrainer/layers/output_layer.cpp, nntrainer/layers/output_layer.h, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/pooling2d_layer.h, nntrainer/layers/tflite_layer.cpp, nntrainer/layers/tflite_layer.h, test/unittest/unittest_nntrainer_models.cpp
Split layer backwarding into smaller functions for optimization purposes
- calcDerivative() - calculate the derivative to be passed to previous layers
this function must be implemented by all derived layers
- calcGradient() - calculate the gradient for the weights of the layer
- applyGradient() - apply the gradients to the weights of the layer
Also, now input->backwarding() throws than just silently not doing anything.
=> [layers] Split backwarding into smaller functions

Applications/KNN/jni/Android.mk, Applications/LogisticRegression/jni/Android.mk, Applications/MNIST/jni/Android.mk, Applications/ReinforcementLearning/DeepQ/jni/Android.mk, Applications/TransferLearning/CIFAR_Classification/jni/Android.mk, Applications/TransferLearning/Draw_Classification/jni/Android.mk, Applications/VGG/jni/Android.mk, Applications/utils/jni/Android.mk, jni/Android.mk, meson.build, nntrainer/meson.build
Openmp is no longer used. It is deleted to reduce memory consumption
resolves #758
=> [Deps] Remove openmp dependency

api/ccapi/include/optimizer.h, api/ccapi/src/factory.cpp, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/optimizers/adam.h, nntrainer/optimizers/sgd.h
- ~**#728** [AppContext] Add AppContext~
- ~**#745** [AppContext] Add registerer,invoke factory methods~
- [AppContext] Register Default ops at the begining
```
- Register default optimizer at the beginning of the load
```
=> [AppContext][Optimizer] Register Default ops at the beginning @open sesame 11/27 15:35

nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/conv2d_layer.h, nntrainer/layers/fc_layer.cpp, nntrainer/tensor/tensor.h, test/unittest/unittest_nntrainer_layers.cpp
**Commit 1: **
Conv2d layer has some issues #761
This patch addresses some of them:
- Weight is now independent of the filter size. Different filter
weights have now been combined. This has resulted in easier addressing of weights
- Above combining of weights also reduced many mem-copies of weights to bring it in a particular shape
- Moved to use getSlice() to get access to some data than creating copies
Now, all layers have fixed number of weights.
**Commit 2:**
Regularization loss for conv2d layer took average over output filters
than adding it up. This patch fixes it.
**Commit 3:**
This patch provides more optimizations for conv2d
by avoiding more memcopies and operations along with modification
to internal interface of conv2d_gemm operation
Resolves #761
1. Build …
=> [conv2d] Refactor conv2d layer

api/ccapi/include/layer.h, api/ccapi/src/factory.cpp, nntrainer/app_context.cpp, nntrainer/app_context.h, test/ccapi/unittest_ccapi.cpp, test/unittest/unittest_nntrainer_appcontext.cpp
- ~**#745** [AppContext] Add registerer,invoke factory methods~
- ~**#746** [AppContext] Register Default ops at the begining~
- [AppContext] Fix key is case sensitive
```
In current semantics, type key should be case insensitive however case
was sensitive, this patch fixes the issue.
```
- [Layer] Add built-in ops to the context
```
- Add default layers to the global context
```
=> [Layer] Add built-in ops to the context @open sesame 11/30 11:08

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_internal.h, nntrainer/models/neuralnet.cpp
This patch skips the backwarding for the non-trainable layers.
Further, the last trainable layer skips calcDerivative as well.
This results in much fewer calculations as well as more importantly, reduced memory.
See also #732
=> [graph] Skip backwarding for non-trainable layers

nntrainer/layers/activation_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/bn_layer.h, nntrainer/layers/layer.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/pooling2d_layer.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/tensor_dim.cpp, nntrainer/utils/parse_util.cpp, nntrainer/utils/parse_util.h, test/nntrainer_test_util.cpp
Commit 1: [regex] Make regex static const
Although it is using static string, that memory is always being allocated inside regex
Making is static const only makes it once for the function lifetime
Commit 2: [activaiton] Reduce temporary memory alloc
Reduce temporary memory allocations by activation layer
by using the hidden and ret_derivative class variables
This temporarily increases peak memory but alloc-dealloc is removed
from every iteration
Commit 3: [pooling] Reduce temporary mem allocations
Reduce temporary memory allocations for pooling
Remove unnecessary temporary memory allocations which can be
replaced with a slice view
Also removed unnecessary setting memory to zero
Commit 4: [tensor] Support multiply/divide with given output
Support multiply/divide with given output tensor …
=> [memory] Memory based optimizations and fixes

nntrainer/layers/layer.cpp, nntrainer/models/model_loader.cpp, nntrainer/models/model_loader.h, nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_internal.cpp
- ~**#746** [AppContext] Register Default ops at the begining~
- ~**#753** [AppContext] Fix key is case sensitive~
- ~**#753** [Layer] Add built-in ops to the context~
- [ModelLoader] Use vector<string> when creating layer
```
When creating a layer from an ini, enum based properties were used.
This prevents adding a new properties without changing the api header.
This patch moves to setting layer properties to vector<string>
to enable setting properties without changing the api header, eventually
enabling custom properties in custom layer.
**Semantics Change propesed in this PR**
Ini won't ignore the properties that is not supported since model_loader
would not know if it is supported or not
See also #716
2. Run test: …
```
=> [ModelLoader] Use vector when creating layer

nntrainer/graph/network_graph.cpp, nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/layers/addition_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/flatten_layer.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.cpp, nntrainer/layers/output_layer.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_layers.cpp
This PR includes,
. remove grad memory buffer in n_buffes for graph. We do not need
this because we could use var memory buffer of n_buffers to
backwarding.
. For MNIST, memory consumption is reduced 3.5 to 2.6
=> [ Graph ] remove grad mem buffer for backwarding

nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h
Update tensor operation signature to return Tensor reference as a retval
than a tensor itself. This avoid creating dummy tensors as a return (which might have been
optimized by the compiler but lets do manually as the input is also a reference).
This patch also update `Tensor::copy/clone` to not allocate new tensor memory 
if already allocated and same size which did happen in many cases.
Resolves #670
@zhoonit thanks for this suggestion.
Note that this is the last patch for the tensor signature. Please suggest any more signature changes, if any. After this patch, signature is finalized and more functions will be updated later as per needed. Important core functions have already been updated.
2. Run test: [x]Passed [ …
=> [tensor] Update tensor operation signature

Applications/VGG/PyTorch/main.py, Applications/VGG/Tensorflow/vgg_keras.py, Applications/VGG/res/vgg.ini
Added pytorch model for vgg16
This is to benchmark against tf and nntrainer
Update the nntrainer and tensorflow to use official VGG16 model architecture
The FC layers setup is different as the cifar100 dataset has just 100 output classes
than 1000 classes of the imagenet.
Further, the number of epochs are reduced to 1.
When training, this can be increased appropriately.
=> [vgg] Added pytorch model for vgg16

nntrainer/tensor/blas_interface.cpp, nntrainer/tensor/blas_interface.h, nntrainer/tensor/tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
- ~**#797** [Profiler] Separate Profiler for wider use~
- ~**#797** [Test] Add profiler test~
- ~**#797** [Profiler] Add basic profilerlistener~
- [Fix] fix lda, ldb param
```
- lda, ldb, ldc is for layout so it should be set in terms of memory
layout, this patch fixes the issue while adding a corresponding test
```
resolves #801
- [Optim] Add shortcut to dot product
```
When dimension is 1, it is vector by matrix or vector by vector
multiplication. This patch adds a shortcut in that situation
2. Run test: [X]Passed [ ]Failed [ …
```
=> [Optim] Add shortcut to dot product @open sesame 12/14 22:55

api/capi/doc/nntrainer_doc.h
This patch removes the unnecessary HTML link for feature/privilege.
1. Build test: [X]Passed [ ]Failed []Skipped
2. Run test: []Passed [ ]Failed [X]Skipped
* https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=197150692
=> [Docs] Remove unnecessary HTML link for feature/privilege.

Applications/Custom/LayerClient/jni/main.cpp, Applications/MNIST/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp, Applications/TransferLearning/Draw_Classification/jni/main.cpp, Applications/VGG/jni/main.cpp, nntrainer/layers/nnstreamer_layer.h, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp
- [svace] assure file to be closed before remove
```
```
- [svace] Error handling for applications/test
```
1. Fix inconsistent alloc/dealloc(new/free)
2. Add try catch to some statements
3. Fix memory leak from `asprintf`
```
- [svace] Assure unintialized members
```
nnstreamer_layer had two unintialized members.
This patch initializes those two …
```
=> Fix various svace issues

test/ccapi/unittest_ccapi.cpp
When backbone is not enabled, test fails because backbone is not enabled
This patch adds a define in the test so that test can pass when backbone
is not enabled
resolves #803
=> [Test] Add macro to check if backbone is enabled @open sesame 12/16 14:30

nntrainer/tensor/tensor.cpp
Need to fix to calcuate argmax in tensor
=> [ ARGMAX ] Fix bug about argmax

nntrainer/layers/conv2d_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/unittest_nntrainer_models.cpp
Support in-place batch normalization where the batch normalization
input/output is not stored and is over-written by the next layer.
This patch removes the input/output memory requirement when using
batch normalization layer.
=> [layer] Support in-place batch normalization

nntrainer/tensor/tensor.cpp
Apply memory allocation bugfix to argmax
where a empty vector is being addressed
=> [tensor] argmax bugfix

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/models/neuralnet.cpp, nntrainer/utils/profiler.cpp, nntrainer/utils/profiler.h, test/unittest/unittest_nntrainer_profiler.cpp
- [Profiler] Add event registerator
```
Profiler can now dynamically register event and send it to
profileListenr as of this patch with fixing few bugs
resolves #814
```
- [Profiler] Apply ops level profiler
```
This patch attaches ops level profiler
```
Resolves #814
=> [Profiler] Add event registerator

nntrainer/utils/profiler.cpp, nntrainer/utils/profiler.h, test/unittest/unittest_nntrainer_profiler.cpp
- ~**#815** [Profiler] Add event registerator~
- ~**#815** [Profiler] Apply ops level profiler~
- [Profiler] Change profiler specs
```
- Profiler time unit is changed: milli -> microsecond
- Now report is ordered by key
```
=> [Profiler] Change profiler specs

Applications/Custom/LayerClient/jni/pow.cpp, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/activation_layer.cpp, nntrainer/layers/addition_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/flatten_layer.cpp, nntrainer/layers/input_layer.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.cpp, nntrainer/layers/nnstreamer_layer.cpp, nntrainer/layers/output_layer.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/tflite_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/var_grad.h, test/unittest/unittest_nntrainer_layers.cpp
Move layer inputs/outputs memory management to the manager.
This is accomplished by replacing the use of NetBuffers instead of Var_Grad.
Now, all the memory of weights, gradients, inputs, outputs and derivatives
are managed by the manager, and allows more optimizations to be done with
inputs/outputs.
=> [layer] Move layer input/output management to manager

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/layers/addition_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/flatten_layer.cpp, nntrainer/layers/input_layer.cpp, nntrainer/layers/input_layer.h, nntrainer/layers/layer.cpp, nntrainer/layers/loss_layer.cpp, nntrainer/layers/output_layer.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, test/unittest/unittest_nntrainer_activations.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_models.cpp
Commit 1: [inputlayer] Input layer must be non-trainable 
Input layer must always be non-trainable as it does not support backwarding operation
Commit 2: [manager] Manager tracks input/output memory
Manager tracks input/output memory and allocates it
based on if the execution is training or inference
Commit 3: [layer] Use gradient instead of variable for derivative
Use gradient instead of variable for derivative
Manager internally sets gradient memory same as variable for the optimization
but hides this kind of optimizations from the layer
Commit 4: [activation] Making activation in-place
Added activation layer to be in-place.
Each layer now allocates memory for its output than for its input.
For activation layer, if its memory is optimized, then the memory
for the layer behind activation …
=> [optimization] In-place memory optimization for activation layer

nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h
This patch initialize max_dervative_size to avoid unexpected termination
resolves #834
=> [Fix] Assign default value for max_deriv size @open sesame 12/29 15:57

nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/conv2d_layer.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/unittest_nntrainer_tensor.cpp
- ~**#818** [Profiler] Change profiler specs~
- ~**#834** [Fix] Assign default value for max_deriv size~
- [Tensor] Optimize accessor
```
This patch...
- inlines some accessor with noexcept specifier to boost up
- Add getValuePadded to reduce memory copy to make a padded tensor
see also #825
Cc: Parichay Kapoor <pk.kappor@samsung.com>
```
- [Conv] Optimize im2col
```
This patch optimize im2col by...
- Add padding as a argument instead of passing pad value
- Skip creating padded tensor and assignment for padded index
- Refactor variable names for clarity
See also #824
1. Build test: [X]Passed [ ]Failed [ …
```
=> [Conv] Improve im2col performance @open sesame 12/29 15:57

packaging/nntrainer.spec
Enable nntrainer unittests for tizen build
Not sure why or when this got commented
but lets enable it
=> [dist/tizen] Enable base unittests for tizen build @open sesame 12/29 15:57

nntrainer/graph/network_graph.cpp, nntrainer/layers/addition_layer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/loss_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_models.cpp
Optimize input/output memory for inference by using a shared buffer
where the max([sum(input_l, output_l)) for l from all layers]) memory
is allocated for inference.
Baseline working unittest added with models unittest which ensures
that inference works with and without optimizations without any
failures. Value verification tests is done by nnstreamer subplugin of
nntrainer.
Resolves #790
=> [manager] Optimize input/output memory for inference

test/input_gen/transLayer.py
For batchnormalization in tf 2.3 it is not detected in transLayer, so
added new type to detect batch normalization layer
=> [Tools] Fix bug that translayer cannot detect bn

api/ccapi/include/layer.h, nntrainer/layers/activation_layer.h, nntrainer/layers/flatten_layer.h, nntrainer/layers/layer.cpp, nntrainer/utils/parse_util.cpp
- **#844** commit 1
- commit 2 
Enable trainable property to layer 
Set trainable value to false in constructor in activation layer, flatten_layer
=>  [ini] add trainable property for layer

nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h
Add outplace ops with already allocated tensor.
See also #856
=> [Tensor] Add outplace method for arithmetic ops

nntrainer/graph/network_graph.cpp, test/unittest/unittest_nntrainer_models.cpp
Inplace layer optimization is performed for multiple layers - activation and batch normalization layers
and this list will increase with data augmentation etc.
However, the in-place layers cannot work correctly consecutively if these layers are trainable.
They can work perfectly is they dont need to pass the derivative back.
For now, this patch limits two consecutive layers to be in-place.
This will be made generic later dependent on the trainable and inPlace property of the layer.
See also #871
=> [optimization] Bug fix for in-place layer optimization

README.md
Add nntrainer coverity badge to README.
I activated the coverity scan in the pre-build module of the taos-ci.
Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>
=> [README] Add coverity badge

nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/pooling2d_layer.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h, test/unittest/unittest_nntrainer_layers.cpp
Commit 1 : [manager] Donot allocate adam for inference 
Donot allocate adam and gradient memory for weights
when the model is being executed for inference
Commit 2 : [neuralnet] Donot set batchsize in initialize 
Donot set batch size in initialize as that allocates memory for pooling
layer. batch size is not directly set in inference/training itself.
=> [mem-opt] Inference memory optimizations

nntrainer/layers/loss_layer.cpp, nntrainer/layers/tflite_layer.cpp
Now, memory alllocation is handled outside of each layer.
Accordingly, allocating out tensor shouldn't be done inside a layer.
For the same reason, loss layer backwarding needs some fix, for now
it is just commented and will be handled soon
This patch handles the issue for tflite layer
See also #856
=> [Fix/TFlite] Fix tflite allocation

api/capi/include/platform/ml-api-common.h, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/delegate.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h, test/nnstreamer_filter_nntrainer/checkLabel.py, test/nnstreamer_filter_nntrainer/gen24bBMP.py, test/nnstreamer_filter_nntrainer/runTest.sh
1. Do not use "Apache-2.0-only". It's "Apache-2.0".
2. Relicense files to Apache-2.0. (The author permits; I'm the author.)
CC: @helloahn : You need to explicitly permit this as well.
=> License Fix / Relicense to Apache-2.0

nntrainer/layers/preprocess_flip_layer.cpp, nntrainer/layers/preprocess_flip_layer.h, nntrainer/layers/preprocess_translate_layer.cpp, nntrainer/layers/preprocess_translate_layer.h, test/unittest/unittest_nntrainer_layers.cpp
From merging some big prs there happend some inconsistency which casued
a build break. This patch solves the issue
- Use manager.initializeTensor() in the unittest
- Add training signature to forwarding
=> [Fix] Reflect changes to upstream/main

api/capi/capi-nntrainer.pc.in, api/capi/meson.build, api/ccapi/ccapi-nntrainer.pc.in, api/ccapi/meson.build, meson.build, nntrainer/meson.build, packaging/nntrainer.spec
- [meson] Clean up ml-api-common dependency
```
This patch cleans up the ml-api-common dependency.
If it is seems to be stable with multiple platform, we can remove
`api/capi/include/platform/ml-api-common.h`. let's keep it for now
```
- [spec] add backward competibility under tizen 6
```
Since `ml-error-common` redclares error enum inside nnstreamer in tizen
5.5. This patch workarounds the issue by making a fake ml-api-error.h
```
=> [spec] add backward competibility under tizen 6

Applications/KNN/README.md, Applications/README.md, docs/coding-convention.md, docs/configuration-ini.md, docs/contributing.md, docs/getting-started.md, docs/hotdoc/gen-hotdoc.sh, docs/hotdoc/index.md, docs/hotdoc/sitemap.txt, docs/hotdoc/theme/extra/css/extra_frontend.css, docs/hotdoc/theme/extra/templates/navbar_links.html, docs/how-to-run-examples.md, docs/how-to-use-testcases.md, index.md
Generate nntrainer docs.
See: https://nntrainer.github.io/
The modifications can be reflected in this repository: https://github.com/nntrainer/nntrainer.github.io
- Sub-documents such as Application/* need to be added
- The table and others need to be modified according to the hotdoc rule.
Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>
=> [Docs] Generate nntrainer docs

nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/unittest_nntrainer_tensor.cpp
Commit 1: [manager] Disable user_shared_memory 
Disable user_shared_memory to as NNAPI is not required to be supported.
It is further needed to decouple tensor structure allocation and its
internal memory allocation.
Commit 2: [manager] bug fix for Tensor::map
This patch exposes a bug from Tensor::Map
where the offset is not checked when assigning the data.
Commit 3: [tensor] Update interface for tensor::map …
Update interface for tensor::map to include the size of the original
buffer to ensure that the buffer contains enough memory required
by the tensor shape wrapping around the memory.
Added another negative unittest for it.
Resolves #892
This is because of the bug in manager for batch normalization layer.
=> [manager] Bug fix using tensor map

nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/unittest_nntrainer_tensor.cpp
- ~**#857** [Tensor] Add outplace method for arithmetic ops~
- [Tensor/Clean] Relocate tensor methods
```
This patch rearranges arithmetic methods while adding some missing
outplace operation signature.
Order is
1. inplace -> outplace -> outplace (with allocated memory)
2. multiply -> divide -> add -> subtract
3. scalar -> tensor
```
- [Tensor] Rearrange methods 
```
- Add missing out param methods
- Change way it is delegated for some methods
- Rename s/operator_/apply_broadcast
- Assure dimension checks
- remove `operator_i` and `operator_i_util`
2. Run test: …
```
=> [Tensor] rearrange methods

nntrainer/tensor/tensor.cpp, test/unittest/unittest_nntrainer_layers.cpp
When copying uninitialized tensor to another unintialized tensor,
tensor::copy tried to reshape uninitialized dimension.
This patch fixes the issue.
=> [Tensor] Handle copy edge case

nntrainer/optimizers/adam.cpp, test/unittest/unittest_nntrainer_layers.cpp
Reduce temporary memory allocation for adam
This is done by reusing gradient memory to calculate the final
update which is to be applied for the weight.
This reduces temporary memory allocations, which were being every epoch
for each weight, but also reduces peak memory usage.
Resolves #917
This has a side effect that the after `applyGradient()`, `getGradient()` will return
the `update` to be applied to the weight than the gradient itself.
=> [adam] Reduce temporary memory allocation

debian/control
remove capi-nnstreamer dependency
=> [ MESON ] fix capi-nnstreamer dependency

nntrainer/app_context.cpp
This solves the build issue for gcc5 when using std::call_once
Original code calls bind with copy of the argument to the function
and fails are reference is expected with gcc5
This patch adds a std::ref explicitly to make this work with gcc5
Resolves #932
=> [app_context] Resolve build issue with gcc5

debian/control
Set higher gcc version to build debian
=> [ DEBIAN ] Fix gcc version for debian build

nntrainer/graph/network_graph.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h, test/nnstreamer_filter_nntrainer/runTest.sh, test/test_models/models/mnist_inf.ini, test/unittest/unittest_nntrainer_layers.cpp
**Commit 1**: [tensor] Support late memory allocation for tensors
Support late memory allocation for tensors.
This helps create tensor wrapper elements and allocate memory
later when needed.
This allows finalizing the graph, creating all the tensors and graph
connections for all the layers which can be stored in offline setup
and then loaded directly from file.
This decoupling allows reusing tensors with every call to train
where we can allocate and deallocate memory without having to create
and do tensor management again and again.
In short term, this is necessary for in-place layer optimization.
See Also #879
The implementation requires caching the source tensor when creating
shared tensors as shared tensors cannot be created unless the source
tensor memory has been allocated.
**Commit …
=> [tensor/manager] Fix in-place layer optimization bug

nntrainer/tensor/manager.cpp, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h
Cleanup train argument for initialize gradient
This argument was needed when weights and gradient were initialized together
But now, the caller must call initializeGradient only when its trainable
=> [Weight] Cleanup train argument for initialize gradient

nntrainer/tensor/tensor.cpp
This patch fixes lazy alloc ctor to lazy allocate which were delegated
to eager ctor thus causing allocating tensor twice for the lazy
allocated tensor
=> [Fix] Update lazy alloc ctor to lazy alloc

api/nntrainer-api-common.h
From tizen convention since should be Since, this patch resolves the
issue
=> [Chore] s/since/Since/

meson.build, nntrainer/nntrainer_error.h, test/include/nntrainer_test_util.h, test/meson.build, test/nntrainer_test_util.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_dataset.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp, test/unittest/unittest_databuffer_file.cpp, test/unittest/unittest_nntrainer_activations.cpp, test/unittest/unittest_nntrainer_internal.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_lazy_tensor.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_tensor.cpp, test/unittest/unittest_util_func.cpp
- **#896**  [Util] Add gtest style throw macro
- [Build] Decouple gtest from nntrainer_test_util
```
As nntrainer_test_util had gtest, it was preventing from compiler checks
some trivial bugs (like sign compare) and had some weird bug.
This patch decouples gtest from nntrainer_test_util while changing gtest
to static build.
Resolves #910
```
=> [Build] Decouple gtest from nntrainer_test_util @open sesame 02/15 17:40

Applications/Custom/LayerClient/jni/main.cpp
Add try catch to the top level app to ensure exception does not
propagates to the very top level
=> [Fix/Svace] Add try catch to the top level app

README.md
This is a trivial commit that fixes typos in README.md
Signed-off-by: Juyeong Lee <2jy22@naver.com>
=> [Docs] Fix typos in README.md

nntrainer/layers/activation_layer.h, nntrainer/layers/addition_layer.h, nntrainer/layers/bn_layer.h, nntrainer/layers/concat_layer.h, nntrainer/layers/conv2d_layer.h, nntrainer/layers/fc_layer.h, nntrainer/layers/flatten_layer.h, nntrainer/layers/input_layer.h, nntrainer/layers/loss_layer.h, nntrainer/layers/output_layer.h, nntrainer/layers/pooling2d_layer.h, nntrainer/layers/preprocess_flip_layer.h, nntrainer/layers/preprocess_translate_layer.h, nntrainer/layers/tflite_layer.h
Add override specifier to fix some Android build warnings. (Related to #924)
* Warnings about override specifiers are resolved, but there are still some remaining warnings:
```
warning: explicitly defaulted copy constructor is implicitly deleted [-Wdefaulted-function-deleted]
warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
```
<details>
<summary> full log </summary>
```
Android.mk:19: INIPARSER_ROOT is not defined!
Android.mk:20: INIPARSER SRC is going to be downloaded!
Cloning into 'iniparser'...
~/development/nntrainer/jni ~/development/nntrainer/jni PREPARING ini parser at ./ ~/development/nntrainer/jni
Android.mk:35: BUILDING TFLITE BACKBONE !
Android.mk:40: TENSORFLOW_ROOT is not defined!
Android.mk:41: TENSORFLOW SRC is …
```
=> [Fix warning] Add override specifier

nntrainer/layers/loss_layer.cpp, test/unittest/unittest_nntrainer_models.cpp
- [Tensor/Clean] Relocate tensor methods
- [Tensor] rearrange methods
- [Loss] Fix loss layer were allocating a new mem
```
As allocation is managed in `manager`, layer shouldn't be allocate a new
memory that are managed by memory.
However, loss layer was allocating a new memory. This patch fixes the issue.
Cc: Parichay Kapoor <pk.kapoor@samsung.com>
```
=> [Loss] Fix loss layer were allocating a new mem @open sesame 02/19 18:25

meson.build
Setting -O optimization manually gives meson warnings.
```
meson.build:59: WARNING: Consider using the built-in optimization level instead of using "-O2".
```
Instead update meson buildtype to release
This sets debug to 0 and optimization to level 3.
Note that this patch increases the optimization level of the library from 2 to 3.
=> [meson] Set meson buildtype to release

nntrainer/nntrainer_error.h
This patch removes internal namespace from nntrainer::exception
=> [Util] Delete internal namespace @open sesame 02/19 17:28

Applications/SimpleShot/layers/centroid_knn.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/models/neuralnet.cpp, nntrainer/optimizers/adam.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/optimizer.cpp, nntrainer/optimizers/optimizer_internal.h, nntrainer/optimizers/sgd.cpp, nntrainer/optimizers/sgd.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h, nntrainer/utils/parse_util.cpp
**Commit 1**: [weight/layer] Move weight regularization out of layers
Move weight regularization out of layers to weights
and remove same code from the all the layers.
Loss and grads from weight regularization is done by the
weight itself.
**Commit 2**: [weight] Move apply gradient to weight
Move apply gradient which will just add the gradient
to the variable multiplied with the gradient.
**Commit 3**: [optimizer] Update to camelcase
Update apply_gradient(s) to applyGradient(s)
Resolves #762 #774
=> Move weight regularization @open sesame 02/02 20:01

.gitignore, docs/configuration-ini.md, nntrainer/graph/network_graph.cpp, nntrainer/layers/loss_layer.cpp, nntrainer/layers/loss_layer.h, nntrainer/models/model_loader.cpp, nntrainer/models/model_loader.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/utils/parse_util.cpp, test/test_models/models/mnist_inf.ini, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Allow setting no loss in the model
This allows inferencing a model, and creating submodels
with backbones to infer some particular output features
Updated existing unittest with no loss to succeed
and added more unittests to validate that models run successfully
without loss
See Also #927
=> [loss] Allow no loss in the model @open sesame 02/19 17:43

nnstreamer/tensor_filter/meson.build, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nnstreamer/tensor_filter/tensor_filter_nntrainer.hh
This patch extracts inference wrapper header for testability and better
maintainability.
=> [filter] Extract inference wrapper header @open sesame 02/19 17:42

nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h, test/ccapi/unittest_ccapi.cpp, test/nnstreamer_filter_nntrainer/runTest.sh
Commit 1: [tensor] Allow updating batch size after allocation 
Allow updating batch size after memory allocation for tensor.
If previously allocated memory is first set to null and then allocated again
with the new batch size. As tensors share memory, the previously allocated
might not be freed when set to null and can lead to high peak memory usage.
It is recommended to free the memory for all tensors whose batch size is changing
first, update batch size and then allocate again to keep the peak memory requirement
at check.
As the memory is allowed to be re-allocated, the src_tensor for a tensor is not
reset anymore after memory allocation. When reallocating, the src_tensor is used
again in order to maintain the memory management done once duing initialization.
This patch also sets …
=> [model] Allow update batch size

Applications/Custom/LayerClient/jni/main.cpp
The two functions of the following code may throw
exceptions. Handle them.
```
if (arg == "model") {
return api_model_run();
} else {
return ini_model_run(arg);
}
```
This fixes SVACE 457479.
=> [Fix/Svace] Add try catch to model-run

test/tizen_capi/unittest_tizen_capi_dataset.cpp
The unittest gives segmentation fault when trying to close a dataset
object which has not been opened successfully.
Initializing the object to false solves the issue.
This unittest before the patch fails for debug mode in meson.
=> [dataset/unittest] Bug fix for segmentation fault

Applications/Custom/LayerClient/jni/meson.build, Applications/Custom/LayerPlugin/layer_plugin_test.cpp, Applications/Custom/LayerPlugin/meson.build, debian/nntrainer.install, meson.build, nntrainer.ini.in, nntrainer/app_context.cpp, nntrainer/app_context.h, packaging/nntrainer.spec
This patch mainly adds the functionality to add `.so` from a directory (by api, environment variable, and configuration ini)
- ~**#894** [Fix] Resolve static init order fiasco~
- ~**#896** [Util] Add gtest style throw macro~
- ~**#908** [API] Add layer pluggable definition~
- ~**#908** [Pluggable] Add layer wrapper for plugged layer~
- ~**#908** [AppContext] Add register plugin function~
- ~**#908** [Test] Add test to create layer from an example~
- [AppContext] Default Path loader
```
Add appcontext default path loader.
- add `AppContext::registerLayerFromDirectory`
- call `add_extension_object` routine for `AppContext::Global()`. The
routine searches the directory of `NNTRAINER_PATH` and from
`nntrainer.ini`(installing ini in upcoming PR)
**Self …
```
=> Load layer plugin from directories @open sesame 03/02 16:11

meson.build, meson_options.txt, packaging/nntrainer.spec
This patch resolves dependency name by given distro version.
Tested building on 6.5 and 6.0 latest snapshot.
Cc: Sangjung Woo <sangjung.woo@samsung.com>
resolves #973
=> [rpm/tizen] Support 6.0 build

nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h, test/ccapi/unittest_ccapi.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_models.cpp
**Commit 1**: [manager] Add check in manager for multiple init and allocate 
Add a check in the manager to avoid multiple initializations of the same
variables and their allocations. This happens when inference/train is called
multiple times on the same model.
This patch adds a check inside the manager which does not re-init or allocate
if it is already initialized/allocated.
**Commit 2:** [manager] Support deallocation of memory
Create a proper support for deallocation of memory by the manager which
for now will be done with destruction of manager or the model itself.
This frees all the memory involved in the model for inference or training.
**Commit 3:** [manager] Check on re-initialize
Add a check on re-initialize for the ccapi unittest
As re-initialize is removed, the memory …
=> [manager] Manage memory allocation and de-allocation

api/capi/src/nntrainer_util.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp
This patch adds mapping to newly added enum and corresponding test
Please note that tct will be added based on this PR.
=> [CAPI] Add mapping to newly added enum

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/unittest_nntrainer_graph.cpp, test/unittest/unittest_nntrainer_models.cpp
**Commit 1:** [neuralnet] Support deallocate of tensors 
Support deallocate and allocation of tensors from the neuralnet.
Also perform the deallocation of tensors after each train run.
Once a training is performed, the memory associated for that training
except the weights variables will be freed.
The memory associated with inference will not be freed until freed manually.
This will require calling deallocate() with the model object.
Note that calling a train() after inference() will free the inference memory
and the train will allocate its own memory which will be freed at the end
of the training.
**Commit 2:** [model] Free memory for inference 
Support freeing memory for inference with free_mem argument in inference
This defaults to true.
See Also #965  #974
1. …
=> [model] Support freeing memory with train and inference

nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h
Remove the allocation of input of the first layer and label of the last
layer during inference. This is because those tensors are overridden at
the call to inference by the tensors provided externally by the user.
Note that the output of the last layer will still be allocated by the manager.
Also refactor initializeTensors() in manager into two functions
separated for inference and training, along with a couple of bug fixes inside them.
See Also #974 #888
cc. @zhoonit Please check if this resolves the second issue in #888.
=> [Manager] Remove alloc for first/last layer during inference

Applications/TransferLearning/Draw_Classification/jni/meson.build
Set environment variable in meson to run the application test
This patch solves the failing app_draw_classification in ninja test
See also #995
cc. @zhoonit thanks for the help.
=> [app] Set env to run the app test

nntrainer/models/neuralnet.cpp
Update batch size check to exactly match with the model
This is because batch size is used by certain layers for calculation and
running an input with wrong batch (with correct memory allocations) can result
in wrong output.
This is independent of the running a batch size 16 with memory allocated for
bigger batch size. That will still work with this patch as long as batch size
is set correctly for the model, and memory allocated is at least big enough
to handle this batch size.
See also #888
cc. @zhoonit thanks for making #888 clearer in person.
=> [model] Update batch size check

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/addition_layer.cpp, nntrainer/layers/addition_layer.h, nntrainer/layers/bn_layer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/embedding.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/flatten_layer.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/output_layer.cpp, nntrainer/layers/output_layer.h, nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_layers.cpp
Refactor layer to properly handle the number of inputs
and outputs, which is maintained across the in/out dimensions,
in/out data.
This is not maintained for in/out layers as these properties will move
out of layers in the next commit.
Also added bugfix in output_layer which used to clear the output dimension
rendering the num outputs 0 for sometime.
NetworkGraph setNumNetBufferSize is also removed as the above
refactoring handles it at the layer level.
See Also #986
=> [layer] refactor inputs/outputs for layer

nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_models.cpp
Add a check in model to read and save after init only
Added a corresponding unittest for the negative case
=> [model] Read and save after init

nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/models/model_loader.cpp, nntrainer/models/model_loader.h, test/test_models/models/mnist.ini, test/test_models/models/mnist_inf.ini, test/unittest/unittest_nntrainer_modelfile.cpp
Ini description is expected to be somewhat determinisitic.
But paths inside ini is not deterministic. For example, if you have
save_path=model.bin,
if A application trains it and B application try to use it, reading the
same ini does not gaurantee B to read to the weights from A.
It is because A and B can have diffrent working path.
To make it consistent, this patch changes semantics of paths' in ini.
1. if model.appcontext.hasWorkingDirectory(), path inside ini are interpreted from
the workingDirectory
2. else, it is interpreted **relative to where ini is located at.**
=> [loader] Change semantics of path in ini

Applications/MNIST/jni/meson.build, nntrainer/app_context.cpp
There was a throw in a regular call path. This patch removes the error
by changing semantics.
@kparichay thank you for the report.
resolves #1012
=> [AppContext] Remove throw regular path

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h
Move layers from model to graph.
This places all the graph related elements in the graph
and easy to extend and reason about model.
This shows the redundancy in the graph which shall be handled in
upcoming PRs.
Remove friendship between classes as it makes extending the interface
difficult. Some friendships exist which will be removed in upcoming
PRs.
See Also #986
=> [model] Move layers out of model

nntrainer/layers/bn_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h, test/unittest/unittest_nntrainer_layers.cpp
Commit 1: [layers] Weight creation bug fix
The name of the weight being passed as string was being interpreted as a string
for the variable alloc_now. This patch fixes it by passing the arguments
appropriately.
Commit 2: [Weights] Split weight variable init and allocSplit the initialization and memory allocation for weights
3 exposed bugs with this has been resolved:
- manager does not allow tracking var_grads once initialized
- resetGradient confirms the allocation is done before accessing the memory
- allocateVariable() calls the correct initializer now
Further, the logic of reinitialize in unittest for layers has been
split into two parts - initialize and reinitialize where
reinitialize will reset layer and manager and then call initialize.
Resolves #974 …
=> [weights] Bug fix + lazy allocation

Applications/Custom/LayerPlugin/layer_plugin_test.cpp, Applications/MNIST/res/mnist.ini, Applications/ReinforcementLearning/DeepQ/jni/meson.build, Applications/TransferLearning/CIFAR_Classification/README.md, Applications/TransferLearning/CIFAR_Classification/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp, Applications/TransferLearning/CIFAR_Classification/res/Classification.ini, Applications/TransferLearning/CIFAR_Classification/res/Classification_func.ini, Applications/TransferLearning/Draw_Classification/jni/main.cpp, docs/configuration-ini.md, nntrainer/models/neuralnet.cpp, packaging/nntrainer.spec
- [Bug] s/weight_decay/weight_regularizer
```
weight_decay is a old property which made some app test to fail. This
patch resolves the issue
revealed from #1008
resolves #1018
```
- [Package] Use meson test
```
As meson already provides test suite, this patch substitue old test to
meson test. This is to provide coherency between build test and simple
test conducted on a local machine.
resolves #998
```
- [Test] Add pluggable layer test
```
Add some missing test for …
```
=> [Package] Use meson test and include app test

nntrainer/tensor/var_grad.h, test/unittest/unittest_nntrainer_layers.cpp
This patch adds bug fix for layers unittest
resetLayer() used to first free the layer and then call reset on the manager.
Freeing the layer used to free the memory of the weights, which left
the reference_wrapper for the weights in the manager in an undefined state.
This patch changes the order. Further, this patch removes some unsafe
practices from the var_grad.
This is a hotfix. The inability to check the validity of the weights in the manager
will be handled separately.
Resolves #1027
=> [test/bug] Bug fix for layers unittest

test/unittest/unittest_nntrainer_models.cpp
Valgrind gives the error of uninitialized memory usage for this
unittest which is fixed with this patch.
=> [models/test] Valgrind models test fix

Applications/SimpleShot/test/meson.build, Applications/TransferLearning/Draw_Classification/jni/meson.build, test/ccapi/meson.build, test/tizen_capi/meson.build, test/unittest/meson.build
As xml output is needed for the testhub, this patch add generation for
the meson test
=> [TestHub] Produce xml output for gtest

jni/Android.mk, nntrainer/layers/acti_func.cpp, nntrainer/layers/acti_func.h, nntrainer/layers/activation_layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.cpp, nntrainer/layers/meson.build, test/unittest/unittest_nntrainer_activations.cpp, test/unittest/unittest_nntrainer_layers.cpp
In order to use Activation function method in other Layer, it is
better to make sepearte the activation function definition and Layer.
In this PR, new ActiFunc Class is introduced and midified the
activation layer to use it.
RNN Layer also use this as an private variable.
=> [ ActFunc ] Separate Activation Function from Activation Layer

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, test/unittest/unittest_nntrainer_models.cpp
This patch adds support for default input_layers
If no input_layers is specified, the layer above
the current layer in the ini file or the previously
adding layer in the model becomes the input layer for the current layer.
However, this connection is only made if the current layer
has no input layers.
Resolves #1046
=> [graph/ini] Support for default input_layers

nntrainer/graph/network_graph.cpp, nntrainer/layers/loss_layer.h
Added bug fix for handling the scenario when there is no loss
specified. The issue was the difference in ordering of the loss
types in the parser and loss type enums.
This patch fixes it. Further, graph now simply returns if no loss found.
Resolves #1055
=> [graph] Bug fix for no loss

packaging/nntrainer.spec
This patch resolves nnstreamer dependency problem. Thus making rpm to
enable plugin related test.
This patch is wating for nnstreamer/nnstreamer#3147
resolves #997
=> [rpm] Fix nnstreamer dependency @opensesame 03/30 01:49

packaging/run_unittests.sh
'return' in script is not available, call 'exit' instead.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
resolves #1052
=> [Test/Util] use exit in script @open sesame 04/01 11:12

Applications/Custom/LayerClient/res/custom_layer_client.ini, Applications/LogisticRegression/res/LogisticRegression.ini, Applications/MNIST/res/mnist.ini, Applications/MNIST/res/mnist_valid.ini, Applications/ReinforcementLearning/DeepQ/jni/DeepQ.ini, Applications/ResNet/res/resnet18.ini, Applications/TransferLearning/CIFAR_Classification/res/Classification.ini, Applications/TransferLearning/CIFAR_Classification/res/Classification_func.ini, Applications/TransferLearning/CIFAR_Classification/res/Classification_new.ini, Applications/TransferLearning/Draw_Classification/res/Training.ini, Applications/VGG/res/vgg.ini, Applications/VGG/res/vgg_small.ini, docs/configuration-ini.md, nntrainer/models/model_loader.cpp, nntrainer/models/model_loader.h, nntrainer/models/neuralnet.cpp, test/ccapi/unittest_ccapi.cpp, test/test_models/models/mnist.ini, test/tizen_capi/unittest_tizen_capi.cpp, test/unittest/unittest_nntrainer_graph.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Add a new optimizer section to INI
This is essential to allow custom optimizers as the
properties of optimizers needs to be iterables.
Currently, optimizer needs to specified in the model, which
along being not the best design, limits the properties to
be set for the optimizer as the model loader has to know
which properties are for optimizer and which for model.
This patch separates the optimizer as a new section and updates
the unittests.
V2:
Added backward compatibility for optimizers.
Update ini loader for model to support more properties
than the ones which are hardcoded.
See also #986
=> [optimizer] Add optimizer section to INI @open sesame 04/01 17:19

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h
**Commit 1:** [graph] Update setting output layers in graph + bug fix 
Update setting output layers in graph to a unified location.
The graph is first made with just input layers.
Output layers are set at the end for the completeness at
one go than adding at each realization to avoid more errors.
Also, added a bug fix where the last layer in  the model
is not the last layer in the ini file. Now the last layer
is not the last layer in the adj but the layer without any
output_layers.
**Commit 2**: [graph] Remove graph edges after compile
This patch removes edges from the graph after compiling to
save the memory. This graph can be reconstructed by adding those edges
again from the information in the layers themselves.
See also #986
1. Build test: [x]Passed [ ]Failed [ …
=> [graph] More refactors for graph + bug fix @open sesame 04/01 11:12

debian/control, meson.build, packaging/nntrainer.spec
From SRI-D it was reported that iniparser 3.x is not compatible.
This patch adds a version check for the iniparser
resolves #1047
=> [Deps] Add iniparser dependency version @open sesame 04/01 11:12

nntrainer/graph/graph_node.h, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.h
**Commit 1** :  [Graph] Add interface for graph node
Add interface for the graph node.
Graph will use this interface.
**Commit 2:** [graph] Add node the graph of layers
Create class for the graph of layers which will represent nodes
This class also represents the object which will be created with APIs from now.
The actual class object resides inside this layer node object.
Properties for this layer node will be intercepted by the layer node object,
and properties of the graph node will be set in the layer node.
Others will be passed down to the layer node.
See Aso #986
=> [API/Graph] Update graph node and layer objects

jni/Android.mk, nntrainer/utils/ini_wrapper.cpp, nntrainer/utils/ini_wrapper.h, nntrainer/utils/meson.build
- [Ini] Propose ini wrapper
This patch adds `IniSection` which was often used inside unittest. 
```
Most codes are taken from the test directly.
```
=> [Ini] Propose ini wrapper

nntrainer/tensor/manager.h
Enable inference_inout_memory_opt in inference could make a problem
Cause: If the networks are not flatten which means have a cycle, some of output of layer should be preserved.
For example, in resnet there is a residual output and if the opt is enabled this data could be corrupted.
See Also #1094
=> [manager] disable inference_memory_opt

nntrainer/layers/output_layer.cpp
- [Fix] Multiout layer calcDerivative initialize 
```
This patch fixes multiout layer to initialize for calcDerivative
```
=> [Fix] Multiout layer calcDerivative initialize

nntrainer/compiler/ini_interpreter.cpp, nntrainer/utils/ini_wrapper.cpp, nntrainer/utils/ini_wrapper.h, test/unittest/compiler/unittest_interpreter.cpp
- [Ini/Serialize] Implement logic to serialize 
```
This patch implements general concept of serializing a node.
Below is the plan to implement this logic
0. Implement logic to serialize [*]
1. Add export api
2. Add exporter
3. Add export test
4. Implement properties
5. combine with export
6. Add extra test
```
=> [Ini/Serialize] Implement logic to serialize

Applications/Custom/LayerClient/jni/Android.mk, Applications/Embedding/jni/Android.mk, Applications/LogisticRegression/jni/Android.mk, Applications/ReinforcementLearning/DeepQ/jni/Android.mk, Applications/TransferLearning/CIFAR_Classification/jni/Android.mk, Applications/TransferLearning/Draw_Classification/jni/Android.mk, Applications/VGG/jni/Android.mk, jni/Android.mk, nntrainer/layers/layer_internal.h, nntrainer/utils/node_exporter.h
This patch adds exporter to export node. This exploits visitor pattern
because, exporting need templated function to be executed, but virtual
functions does not allow templated function.
=> [Serializer] Add exporter to export node

nntrainer/utils/base_properties.h, test/unittest/meson.build, test/unittest/unittest_properties.cpp
- [Test/Props] Add basic property tests 
```
This patch adds basic property test to demonstrate specification and
cover some test cases
```
- [Props] Add base properties 
```
Add base properties to be used for the property implementation
```
=> [Props] Add base properties test

jni/Android.mk, nntrainer/utils/meson.build, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h, test/unittest/unittest_properties.cpp
- [Exporter] Add exporter test to prop test 
```
This patch adds exporter test to prop test to ensure that it is working
fine.
```
- [Exporter] Add string vector exporter 
```
This patch adds string vector exporter implementation
Exporter will iterate through props (`iterate_props`) and will pass a
generic lambda to be called.
Later, We can retrieve the result by `get_result` if needed.
```
=> [Exporter] Add exporter test to prop test

test/ccapi/unittest_ccapi.cpp
- [Competibility] Change test reference value 
```
This patch change tolerance for the `model->getValidationLoss` which
affects in i586
resolves #1125
```
=> [Competibility] Change test reference tolerance @open sesame 04/22 18:25

nntrainer/layers/layer_node.h
- [Fix] Reorder error in layernode 
```
This patch fixes trivial build warning which is treated as error.
```
resolves #1147
=> [Fix] Reorder error in layernode

nntrainer/layers/common_properties.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/layer_internal.h, nntrainer/utils/base_properties.h, test/unittest/unittest_properties.cpp
- [FC/props] Wrap properties with properties 
```
- Add base_properties for common use
- Change fc unit to property
- Add export test
- Add `uint_prop_tag` and it's handler
```
=> [FC/props] Wrap properties with properties

Applications/SimpleShot/meson.build, Applications/SimpleShot/task_runner.cpp, nntrainer/graph/network_graph.cpp, nntrainer/models/neuralnet.cpp
- [Fix] handle edge case for countNonTrainable 
```
- Handle edge case when every layer is non trainable
for `countNonTrainableLayersAtBegin`
- Trivial code cleans on simpleshot task_runner / neuralnetwork
```
resolves #1135
=> [Fix] handle edge case for countNonTrainable

nntrainer/layers/common_properties.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/utils/base_properties.h, nntrainer/utils/node_exporter.h, test/unittest/unittest_properties.cpp
- [Layer/props] Convert name to props. 
```
- Convert name to props
- Add std::string specialization for property
```
=> [Layer/props] Convert name to props

nntrainer/compiler/ini_interpreter.cpp, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/utils/ini_wrapper.cpp, nntrainer/utils/ini_wrapper.h, test/unittest/compiler/unittest_interpreter.cpp
- [IniSerializer] Add `serialize` to ini 
```
- implements ini interpreter::serialize
- add corresponding test (reference shoud be equal to
serialize->deserialized graph)
- Fix some const correctness
```
=> [IniSerializer] Add `serialize` to ini

jni/Android.mk, nntrainer/utils/base_properties.cpp, nntrainer/utils/base_properties.h, nntrainer/utils/meson.build
- [Props] Separate base_propeties to a source
```
This patch separate base_properties into some specialization to source
file
The purpose is to save compile time and redundant doxygen, and clean up
length header.
```
=> [Props] Separate base_propeties to a source

nntrainer/utils/base_properties.h, test/unittest/unittest_properties.cpp
- [Props] Add cast operator
```
- Add cast operator to property base for easier use
- Add corresponding test
```
=> [Props] Add cast operator

nntrainer/compiler/tflite_interpreter.cpp, test/unittest/compiler/unittest_interpreter.cpp
- [Tf/Skeleton] Add basic meta data 
```
This patch adds basic meta data to tflite file for startup
```
=> [Tf/Skeleton] Add basic meta data @open sesame 05/10 13:16

Applications/Custom/LayerClient/jni/main.cpp, Applications/Custom/LayerPlugin/layer_plugin_test.cpp, Applications/Custom/pow.cpp, Applications/Embedding/jni/main.cpp, Applications/ReinforcementLearning/DeepQ/jni/main.cpp, Applications/SimpleShot/task_runner.cpp, Applications/SimpleShot/test/simpleshot_centering_test.cpp, Applications/SimpleShot/test/simpleshot_centroid_knn.cpp, Applications/SimpleShot/test/simpleshot_l2norm_test.cpp, api/ccapi/src/factory.cpp, jni/Android.mk, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/compiler/ini_interpreter.cpp, nntrainer/dataset/databuffer_func.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/meson.build, nntrainer/layers/plugged_layer.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Update API to create LayerNode instead of Layer
Internally updated implementation to use this as LayerNode
and extract layer from inside it when needed.
=> [model] Update Layer with LayerNode

nntrainer/compiler/tflite_interpreter.cpp, nntrainer/layers/layer_internal.h, test/unittest/compiler/unittest_interpreter.cpp
- [Tflite] Implement TfOpNode 
```
This patch implements TfOpNode which will be used to deserialize layer
node to a mere chunk of informations. Please note that those methods are
tentative and subject to change wile implementing other methods
```
=> [Tflite] Implement TfOpNode

nntrainer/graph/network_graph.cpp
- [Svace] Fix dangling reference issue
```
This patch fixes dangling reference caused from Sorted.pop_back();
tracking id: 1229992
```
=> [Svace] Fix dangling reference issue

nntrainer/utils/base_properties.cpp, nntrainer/utils/base_properties.h, nntrainer/utils/node_exporter.h, test/unittest/unittest_properties.cpp
- [Props] Add vector/array handler
```
This patch add vector property handler.
vectored property have sementics that number of size is not defined
arrayed property have sementics that number of size must match
```
=> [Props] Add vector/array handler

nntrainer/graph/graph_core.cpp, nntrainer/graph/graph_core.h, nntrainer/graph/graph_node.h, nntrainer/graph/meson.build, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.h
Add graph core class
This is mainly separating the existing implementation of core part
of the graph from NetworkGraph.
This patch does not contain new implementation but mostly contain
borrowed implementation from existing graph.
See Also #1176
=> [graph] Add graph core class 

nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_models.cpp
Model inference should not catch throw, and must throw errors
so that the callers can catch it and detect errors.
This has also revealed bug in time distribution layer test case which was hidden till now.
Resolves #1191.
=> [model] Model inference should not catch throw

nntrainer/layers/time_dist.h
Added setProperty for time distribution layer, which passes
the properties to its underlying layer.
Resolves #1189
=> [time_dist] setProperty for time distribution layer

nntrainer/layers/fc_layer.cpp, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/utils/base_properties.cpp
Update tensor sum to support in-place sum when done over
multiple dimensions.
Also update arguments order to have output tensor as a latter
argument.
Make bias derivative in-place for fc layer
resolves #1202
=> [fc/tensor] Update fc layer bias derivative to in-place

jni/Android.mk, nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/meson.build, test/unittest/meson.build, test/unittest/unittest_base_properties.cpp, test/unittest/unittest_common_properties.cpp
- [Props] Add Name validator and unittest
```
- Add name validator
- Add source file for `common_properties`
- Change name of `unittest_properties.cpp` ->
`unittest_base_properties.cpp`
- Add `unittest_common_properties.cpp`
```
=> [Props] Add Name validator and unittest

nntrainer/nntrainer_logger.cpp
- [Fix] Add missing header
```
This patch adds missing header for logger when `enable_logging=false`
```
=> [Fix] Add missing header

nntrainer/compiler/tflite_interpreter.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/tensor/tensor_dim.cpp, nntrainer/tensor/tensor_dim.h, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_tensor.cpp
```
This patch fixes tf shape building, by adding `eff_dim_flag` and
`dyn_dim_flag`.
`eff_dim_flag` checks which dimension are actually used so that to be
squeezed.
`dyn_dim_flag` checks which dimension should be set to -1 (meaning it is
not fixed)
With those flag set, our tensor dim is able to convert to the dimension
representation that supports `-1` and not fixed size
Those fixes are apply to fc layer for now
```
- ~**[Pending MERGES - #1155]** Merge branch '"'"'@dox/tensordim'"'"' into @1067/tf_interpreter/10_base~
=> [Tflite] Fix tf shape building @open sesame 05/24 16:44

jni/Android.mk, nntrainer/compiler/ini_interpreter.cpp, nntrainer/compiler/tflite_interpreter.cpp, nntrainer/graph/graph_core.cpp, nntrainer/graph/graph_core.h, nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Migrate neural network independent and generic sections of the graph
to graph core. This is not yet complete and will be done over a few commits.
This will cleanup NetworkGraph class and will allow optimizations to
be done on the GraphCore/NetworkGraph class easily, and simplify
the classes as well.
Now, graph related structures can move out from layer to layer node.
Cleanup graph usage
Graph remove support for getNodes() but rather
use iterators to iterator over the graph.
Add non-const iterators for the graph.
Most of the locations use const-iterators.
This will be updated when layer_node is updated to use its
properties than layer. …
=> [Graph] Update network graph to use graph core

nntrainer/graph/graph_core.cpp
- [Fix/graph] fix index after removing node
```
- After removing last node, adj node after the target node becomes not
correct, this patch fixes the issue
```
=> [Fix/graph] fix index after removing node

nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h
- [VarGrad] Add clone Transpose
```
This patch adds clone transpose to `var_grad`, this function clones the
current `var_grad` but transpose and save
```
=> [VarGrad] Add clone Transpose

api/ccapi/include/layer.h, jni/Android.mk, nntrainer/app_context.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/layer_factory.cpp, nntrainer/layers/split_layer.cpp, nntrainer/layers/split_layer.h, test/unittest/unittest_nntrainer_layers.cpp
Added unittests for split layer covering initialization,
forwarding and backwarding. Corresponding bug fixes are
also added.
This has revealed an issue with concat layer #1226
which will be resolved soon.
Resolves #1208
=> [wait for #1210] [split/test] Added unittests for split layer 

nntrainer/graph/network_graph.cpp, test/unittest/unittest_nntrainer_layers.cpp
- [Fix] Prevent creating multiout for split
```
This patch make an exception for split layer to not create multiout
layer. While fixing trivial build error of sign compare
```
=> [Fix] Prevent creating multiout for split

Applications/Embedding/README.md, Applications/Embedding/jni/main.cpp, Applications/Embedding/jni/meson.build, Applications/Embedding/res/Embedding_split.ini
- [Example] Concat example
```
This patch adds concat example with embedding
The structure is
(input)
/       \
(embed1)   (embed2)
\         /
(concat)
|
(flatten)
|
(fc)
```
=> [Example] Concat example

Applications/ProductRatings/jni/main.cpp
- [Product Ratings] Fix inconsistent batch
```
This patch fixes inconcistent batch size between source file and model
configuration.
Also found a bug #1238, which will be dealt seperately.
```
=> [Product Ratings] Fix inconsistent batch

debian/changelog, packaging/nntrainer.spec
=> [ Release ] NNTrainer 0.2.0 Release

debian/control, meson.build, packaging/nntrainer.spec
Update dependency from tensorflow-lite to tensorflow2-lite.
This is done for Tizen and Debian build. It has already been done for Android.
Tensorflow2-lite header is dependent on flatbuffer, so flatbuffers-devel
is additionally added as a build-dependency.
Resolves #1244
cc. @myungjoo
=> [tflite] Update dependency from tflite to tf2lite 

debian/rules, meson.build, meson_options.txt, packaging/nntrainer.spec, test/include/nntrainer_test_util.h
Reduce error tolerance for release builds to succeed build on launchpad and tizen builds.
The default error tolerance is only reduced for all release builds for all tests that use defined tolerance.
However, the CI will run at original tolerance for all the builds and will ensure that
values are matched with original precision.
The tolerance has to be reduced because different os
have different versions and implementations of the blas
which results in minor difference in the results of the float
operations. However, when the difference is accumulated over
a range of operations, the unittests fail to match the
exact values.
See Also #1251 …
=> [pkg] Reduce error tolerance for all builds @open sesame 06/08 10:52

jni/Android.mk, nntrainer/compiler/ini_interpreter.cpp, nntrainer/compiler/tflite_interpreter.cpp, nntrainer/compiler/tflite_opnode.cpp, nntrainer/compiler/tflite_opnode.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/unittest_base_properties.cpp
- [Android] Add tflite interpreter option
```
This patch add tflite interpreter option to ndk build
```
- [Refactor] Delegate tfNode creation to exporter
```
This patch enables delegating exporting logic to exporter.
Note that this is supposed to be 1:1 mapping, if it has to be m:n
mapping, it should be directly handled by the interpreter, which
actually can see the node.
Also s/`save_result`/`saveResult` and `get_result`/`getResult`
```
=> [Android] Add tflite interpreter option

debian/control, meson.build, meson_options.txt, nntrainer/compiler/meson.build, packaging/nntrainer.spec
Enable tflite-interpreter by default as tflite layer is
already enabled.
Also move flatc dependency out to the main meson.build
=> [meson] Enable tflite-interpreter by default

nntrainer/compiler/ini_interpreter.cpp, nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/time_dist.h, test/unittest/unittest_nntrainer_layers.cpp
move distribute to LayerNode from layer
Further, the distribute layer is now supposed to be used
as a wrapper of a layer maintained by the LayerNode,
and must not be maintained externally.
Rather, use getDistribute() to check if the node is distributed
and treat the layer as a regular layer.
=> [layer] Move distribute to LayerNode

nntrainer/layers/permute_layer.cpp, nntrainer/layers/permute_layer.h, nntrainer/utils/node_exporter.h
- [Permute] Implement peripheral functions
```
This patch implements initialize, export and setProperty of permute
layer
```
=> [Permute] Implement peripheral functions

test/input_gen/genModelTests.py, test/input_gen/recorder.py, test/input_gen/transLayer.py
- [Recorder] Add multiout equivalent in transLayer
```
When getting gradient from `gradientTape` it adds all derivatives of the
dependent layer. While this behavior is true, we need to measure to what
extent each layer contributed to the layer.
This patch adds a multiout layer which consists of some stublayer that
seperates derivatives one by one.
```
=> [Recorder] Add multiout equivalent in transLayer @open sesame 06/09 15:12

nntrainer/layers/permute_layer.cpp, nntrainer/layers/permute_layer.h, test/unittest/unittest_nntrainer_layers.cpp
- [Permute] Add permute layer forward/backward
```
This patch implements forward/backward with a following test
```
=> [Permute] Add permute layer forward/backward

Applications/SimpleShot/layers/centroid_knn.h, nntrainer/layers/layer_internal.h, nntrainer/layers/loss_layer.h
- [Layer] Add requireLabel() function
```
Add a simple function `Layer::requireLayer()`.
This function is used to detect if a certain layer requires a layer.
```
=> [Layer] Add requireLabel() function

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/acti_func.cpp, nntrainer/layers/acti_func.h, nntrainer/layers/activation_layer.h, nntrainer/layers/bn_layer.h, nntrainer/layers/layer_internal.h, test/unittest/unittest_nntrainer_models.cpp
Support inPlace() as an interface for the layer.
If returns true, manager can set its inputs/outputs to be
the same memory location, but not necessarily.
Corresponding graph code is also updated.
Resolves #867
=> [layer] add supportInPlace() as an interface for the layer

nntrainer/layers/lstm.cpp
- [Trivial] Fix NDK warning -Wbraced-scalar-init
```
This patch fixes trivial NDK warning below
```
././../nntrainer/layers/lstm.cpp:315:25: warning: braces around scalar initializer [-Wbraced-scalar-init]
Tensor dh_nx = Tensor({derivative_.width()});
^~~~~~~~~~~~~~~~~~~~~
././../nntrainer/layers/lstm.cpp:316:25: warning: braces around scalar initializer [-Wbraced-scalar-init]
Tensor dc_nx = Tensor({derivative_.width()});
^~~~~~~~~~~~~~~~~~~~~
././../nntrainer/layers/lstm.cpp:352:26: warning: braces around scalar initializer [-Wbraced-scalar-init]
hs_prev = Tensor({hs_t.width()});
^~~~~~~~~~~~~~
././../nntrainer/layers/lstm.cpp:354:26: warning: braces around scalar initializer [-Wbraced-scalar-init]
cs_prev = Tensor({cs_t.width()});
```
1. Build test: [X]Passed [ …
```
=> [Trivial] Fix NDK warning -Wbraced-scalar-init

nntrainer/compiler/ini_interpreter.cpp, nntrainer/compiler/tflite_interpreter.cpp, nntrainer/compiler/tflite_opnode.cpp, nntrainer/compiler/tflite_opnode.h, nntrainer/graph/network_graph.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h
This patch moves input/output layers to LayerNode.
Also, create an interface for accessing/setting input/output layers
from in the LayerNode.
Refactor get/set number of inputs/outputs.
This is now handled by layer_node.
Updating the input/output layers updates the count.
=> [layer/node] Move input/output layers to LayerNode 

Applications/SimpleShot/layers/centering.h, Applications/SimpleShot/layers/centroid_knn.h, Applications/SimpleShot/layers/l2norm.h, nntrainer/app_context.h, nntrainer/compiler/ini_interpreter.cpp, nntrainer/compiler/tflite_opnode.h, nntrainer/graph/graph_node.h, nntrainer/layers/common_properties.h, nntrainer/layers/layer_internal.h, nntrainer/tensor/tensor_dim.h, nntrainer/tensor/var_grad.h, nntrainer/utils/base_properties.h, nntrainer/utils/ini_wrapper.h, nntrainer/utils/parse_util.h, nntrainer/utils/util_func.h, test/unittest/compiler/unittest_interpreter.cpp
- [Trivial] Change return -> retval
```
When stating value in doxygen it is recommended to use @retval, this
patch reflects the issue
```
=> [Trivial] Change return -> retval

debian/rules, test/ccapi/meson.build, test/tizen_capi/meson.build
Inverse the check for lower error tolerance for debian build
Also increase timeouts for nntrainer capi/ccapi unittests
as they timeout for armhf architecture on launchpad.
See also #1251
=> [deb/pkg] Update lower tolerance bug + increase timeouts

test/tizen_capi/meson.build
Increase c-api unittest timeout even further to
pass armhf build on launchpad.
=> [deb/pkg] Increase c-api unittest timeout

nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, test/unittest/unittest_common_properties.cpp
- [Props] Implement input_layers as a property
```
This patch implements input_layers as a property with following changes
below
- Add ConnectionSpec object for generic purpose
- Add InputSepc as a property
- Add following tests
```
=> [Props] Implement input_layers as a property @open sesame 06/09 15:12

nntrainer/layers/layer_context.h, nntrainer/layers/layer_devel.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h
This patch proposes layer context and layer_devel.
The layer context provides basic necessities for each layer
like inputs, outputs, weights, tensors. Weights are the trainable tensors
required by the layers which can be requested with the context interfaces.
Correspondingly, any other tensor requirements by the layer can also be
requested with the context.
There are two types of context :
1. InitContext - provides context for initialization with input_dimensions
filled. This contains specifications for all the inputs/outputs/weights/tensors
which will be made available during executiong.
2. RunContext - provides allocated weights/inputs/outputs/tensors along with
some of the basic properties of the layer like trainable, etc.
This design allows layer devel to be stateless (derived layer …
=> [layer context] Propose layer context and layer_devel

nntrainer/layers/split_layer.h
Split layer has class member leading_helper_dim
which remains uninitialized and results in bugs
when setBatchSize() is called before initialization of the layer.
This patch fixes the bug.
Resolves #1279
cc. @zhoonit
=> [split layer] Initialize class member bugfix

Applications/Custom/LayerPlugin/layer_plugin_test.cpp, Applications/SimpleShot/test/simpleshot_centering_test.cpp, Applications/SimpleShot/test/simpleshot_centroid_knn.cpp, Applications/SimpleShot/test/simpleshot_l2norm_test.cpp, nntrainer/graph/network_graph.cpp, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/plugged_layer.h, nntrainer/layers/time_dist.cpp, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/meson.build, test/unittest/unittest_base_properties.cpp, test/unittest/unittest_nntrainer_appcontext.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Move layer identifier name to LayerNode.
Now each node in the graph has name as its direct identifier.
This patch also disable unittest_nntrianer_layers for some while
till layer refactoring is taking place. However, other unittests
and apptests must remain enabled to ensure that everything else is
working.
=> [layer] Move name to LayerNode

nntrainer/graph/network_graph.cpp, nntrainer/layers/loss_layer.cpp, nntrainer/layers/time_dist.h, nntrainer/models/neuralnet.cpp
- [Loss] Apply requireLabel to feed label
```
Currently, loss layer is the only one that can accept label which was
prohibiting building a custom loss layer.
**Major Changes**
- Apply requireLabel to feed label
- Last layer is not assumed loss layer when feeding label(still it is in
other places, need to be dealt)
**Minor Changes**
- Feeding multiple label is now possible (spliting label is future work)
- [Fix] Count Trainable includes loss layer
- [Fix] Handle cases When all layer is not trainable for
neuralnet::backwarding
```
=> [Loss] Apply requireLabel to feed label

nntrainer/models/neuralnet.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
1. [unittests] Update unittests for new gtest version …
Remove gtest version check comments and update unittests for the new
gtest versions.
2. [neuralnet] Neural network bugfix 
Two PRs merged have caused main branch to fail.
This patch provides temporary fix.
Proper fix  will be done with layer_v2.
=> Gtest update

nntrainer/layers/addition_layer.cpp, nntrainer/layers/concat_layer.cpp
Bug fix for addition layer calcDerivative().
addition layer assign the same tensor derivative memory back to its
other layers. If the other layers connecting with addition layers are
inplace, then this can lead to wrong results.
cc. @zhoonit
=> [addition] Bug fix addition layer calcDerivative

docs/getting-started.md
Updated docs with tensorflow-lite version to be 2.3.0 or higher
and added missing dependencies for local meson build as well.
=> [docs] Update docs for tflite version

nntrainer/graph/graph_core.cpp, nntrainer/graph/graph_core.h, nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.h
1. [graph] Make adjacency list lazily
Update graph to make adjacenct list lazily when required
during the topological sort.
Until then, keep the node_list which contains simply all the nodes.
2. [graph] Update node_names to unordered_set
Update node_names storing all the names of the nodes
in the graph for uniqueness to use unordered_set.
3. [graph] Graph iterator for sorted and unsorted 
Updated graph iteartor to run over unsorted list of nodes
if the graph is not yet sorted. If the graph is sorted,
the iterator iterates over sorted nodes.
4. [graph] Remove getNodes for the graph
Remove getNodes() which provided direct access to the data structure
holding the graph. Now, all access is done using the iterators.
5. [graph] Remove non-const iterators
Remove non-const iterators for the …
=> [graph] Graph core cleanup

api/ccapi/include/layer.h, nntrainer/graph/graph_node.h, nntrainer/layers/layer_node.h
- [Layer] Add const to the layer::getName()
```
getName() is independent of const, so this patch adds const to
layer::getName();
```
=> [Layer] Add const to the layer::getName()

nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/layer_node.h, nntrainer/utils/base_properties.h, nntrainer/utils/node_exporter.h, test/unittest/unittest_base_properties.cpp
- [Props] Add concept of empty to property
This patch adds empty concept to property instead of having insensible
value inside a property as a default
before this patch,
```cpp
auto a = Property<int>();
EXPECT_EQ(a.get(), -1); // let's assume -1 is default value which might not be sensible.
```
after this patch
```cpp
auto a = Property<int>();
EXPECT_THROW(a.get(), std::invalid_argument);
EXPECT_TRUE(a.empty());
```
so underlying value remains always null or valid.
Now, it became natural to distinguish mandatory props and non-mandatory
props
=> [Props] Add concept of empty to property

nntrainer/layers/common_properties.h, nntrainer/layers/layer_context.h, nntrainer/layers/layer_impl.cpp, nntrainer/layers/layer_impl.h, test/unittest/layers/layers_common_tests.cpp, test/unittest/layers/layers_common_tests.h, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_fully_connected.cpp, test/unittest/layers/unittest_layers_impl.cpp
- [Test/Prepare] Add layer semantics test
```
For layer_v2, there will be more structured way to access tests.
This patch adds a skeleton for layer semantics test.
```
- [Layer] Add trainable prop
```
This patch add trainable property to layer
```
- [Properties] Add float and boolean cases
```
Add float and boolean case to be used later.
Signed-off-by: …
```
=> [Test/Prepare] Add layer semantics test

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_context.h, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.h
Network graph updated to work with LayerV2
This involves settings input dimension in InitContext, and setting
up RunContext for each layer before their execution.
Further, some helper functions are also added in LayerNode.
=> [networkgraph] Network graph updated for Layer V2

nntrainer/layers/layer_context.h
Minor bugfix for layer context
Removes the extra trainable parameter from layer context
=> [layercontext] Minor bugfix for layer context

nntrainer/graph/network_graph.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
Remove the check for double activation, it is now allowed to have
two activation operations one after the other.
=> [network] Remove check for double activation

Applications/Custom/LayerPlugin/layer_plugin_test.cpp, Applications/Custom/pow.cpp, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_internal.h, nntrainer/layers/plugged_layer.h, test/unittest/layers/layers_common_tests.cpp, test/unittest/layers/layers_common_tests.h
- [AppContext] Integrate layer-devel
```
This patch integrates layer devel to appcontext and plugin features.
From this patch, having it is able to include LayerV1 and Layer at the
same time.
Also adding a test
```
=> [AppContext] Integrate layer-devel @open sesame 06/22 16:38

nntrainer/layers/layer_devel.h, nntrainer/layers/layer_impl.cpp, nntrainer/layers/layer_impl.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, test/unittest/layers/unittest_layers_impl.cpp
Add support of Layer (layer devel) interfaces in LayerNode.
LayerNode interfaces are without arguments, and LayerNode will fill in
the corresponding context needed by the Layer.
=> [layernode] Layer interfaces support in LayerNode

nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h
Add interfaces to layer context required by layer developer
when they override setBatch()
=> [layer context] Add interfaces for setBatch 

nntrainer/layers/layer_impl.cpp, nntrainer/layers/layer_impl.h, nntrainer/layers/layer_node.h
1. Add input_dim property to layer node
2. Add weights/bias related properties such as initializer, regularizer,
etc to LayerImpl. This creates a differentiating factor of LayerImpl
from LayerDevel as LayerImpl provides a base class for layers with
weights/bias properties loaded.
=> [layernode/impl] Add properties to Layer Node and Impl 

Applications/Custom/mae_loss.cpp, Applications/Custom/mae_loss.h
- [CustomLoss] Implement mae loss layer
```
This patch implements mae loss layer forward and backward, also moves
other functions to the sourcefile instead of inlinining it.
```
=> [CustomLoss] Implement mae loss layer

Applications/Custom/LayerClient/jni/main.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/layer_internal.h, nntrainer/utils/ini_wrapper.cpp, nntrainer/utils/ini_wrapper.h, nntrainer/utils/node_exporter.cpp, test/unittest/layers/layers_common_tests.cpp
Coverity
1. Deleted noexception keyword where throw exception can occured.
2. Initialze member variable in constructor
3. Correct bitwise operation
resolves: 1238192, 1238193, 1238195, 1238196, 1238298
Svace
1. Catch unhandled throw
resolve: 464062
=> [Fix] coverity, svace issues

nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h
Update throw to retval in setProperty when the property
is not set by LayerNode. Illegal properties vs non-captured properties
were being mixed in this case.
Now it has been separated by return false. If setProperty() throws, it
must propagate upwards as that error shows the error in the property
given.
=> [layernode] Update throw to retval in setProperty 

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp, Applications/Custom/LayerPlugin/layer_plugin_test.cpp, docs/configuration-ini.md, nntrainer/compiler/ini_interpreter.cpp, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/conv2d_layer.h, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/layer.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_devel.h, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/plugged_layer.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/optimizers/adam.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/optimizer_devel.cpp, nntrainer/optimizers/optimizer_devel.h, nntrainer/optimizers/optimizer_impl.h, nntrainer/optimizers/plugged_optimizer.h, nntrainer/optimizers/sgd.cpp, nntrainer/optimizers/sgd.h, test/tizen_capi/unittest_tizen_capi.cpp, test/unittest/unittest_nntrainer_appcontext.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
Reduce dependence on LayerNode()->getObject() which returns LayerV1
object.
Reduce the usage of getObject() for optimizer.
This patch changes optimizer interface to work on each weight
individually and adds a getWeightObject() for the LayerContext.
This allows removal of getObject() from the neural network class for
backwarding.
This patch also disable dynamic_training_optimization.
=> [layer/model] Reduce dependence on LayerV1

api/ccapi/include/layer.h, nntrainer/layers/gru.cpp, nntrainer/layers/gru.h, nntrainer/layers/layer_internal.h, nntrainer/layers/lstm.cpp, nntrainer/layers/lstm.h, nntrainer/layers/rnn.cpp, nntrainer/layers/rnn.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/utils/parse_util.cpp
In this commit, drop out for recurrent network is intrduced.
dropout property is introduced and if the element value of random
tensor is smaller than dropout rate, then it will be set zero.
The element which is not set zero, then it will scale with
1.0/(1.0-dropout).
=> [ Recurrent ] Implement Dropout for Recurrent Net

nntrainer/app_context.cpp, nntrainer/compiler/ini_interpreter.cpp, nntrainer/compiler/ini_interpreter.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/loss/cross_entropy_loss_layer.h, nntrainer/layers/loss/cross_entropy_sigmoid_loss_layer.h, nntrainer/layers/loss/cross_entropy_softmax_loss_layer.h, nntrainer/layers/loss/mse_loss_layer.h, nntrainer/tensor/manager.h, test/unittest/meson.build, test/unittest/unittest_nntrainer_modelfile.cpp
Enable model file unit tests with newly update LayerV2 to test
building and initialization of the models.
=> [tests/modelfile] Enable modelfile unittest @open sesame 06/30 17:00

nntrainer/graph/network_graph.cpp, nntrainer/layers/activation_layer.cpp, nntrainer/layers/activation_layer.h, nntrainer/layers/input_layer.cpp, nntrainer/layers/input_layer.h, test/unittest/unittest_nntrainer_modelfile.cpp
Update activation layer implementation with layerV2 design.
Also add minor updates to input layer.
Enable more unittests for modelfile which depended on activation layers.
Also updated some of the unittests with the change in behavior of the
network graphs.
=> [layer] Update Activation layer to LayerV2 

nntrainer/layers/common_properties.h
- [Padding] Add padding2d prop header
```
This patch adds padding2d property header.
Padding2D prop will be saved as a string and compute the integer when it
is needed
```
=> [Padding] Add padding2d prop header @open sesame 07/05 16:40

nntrainer/compiler/tflite_opnode.cpp, nntrainer/graph/graph_core.cpp, nntrainer/graph/network_graph.cpp, nntrainer/layers/activation_layer.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h, test/unittest/meson.build, test/unittest/unittest_nntrainer_models.cpp
Support input/output tensor allocation for layerv2 design
Enable models unittest for layerv2
Corresponding bugfixes are also added
Separate getNumInputs/Outputs semantics for inputs/outputs
and for connections as a node. Number of inputs/outputs will always be
more than 1, but number of input/output connections can be 0 for
input/output nodes of the graph.
This patch separates the two concepts, and its usage.
=> [unittest] Enable models unittests @open sesame 07/05 19:36

nntrainer/layers/common_properties.cpp, test/unittest/unittest_common_properties.cpp
- [Padding] Add padding verification
```
This patch implements `Padding2D::isValid` and tests respectively.
Padding2D property is valid when
1. string is "valid" or "same"
2. comma seperated, non-integer value of size 1, 2, 4
```
=> [Padding] Add padding verification

nntrainer/layers/common_properties.cpp, test/unittest/unittest_common_properties.cpp
- [Padding] Add padding compute function
```
This patch implements padding2d::compute with a test
```
=> [Padding] Add padding compute function

nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/input_layer.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/pooling2d_layer.h, nntrainer/models/neuralnet.cpp, nntrainer/tensor/tensor.h, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_pooling2d.cpp, test/unittest/unittest_nntrainer_models.cpp
**Commit 1:**
Update pooling layer to Layerv2 design.
Corresponding unittests for common and models are added and enabled
respectively.
setBatch() for layer node has been updated.
Further, some minor updates have been added to layer context to check if
they are ready to use.
**Commit 2:**
Update pooling layer to use helper tensors.
Instead of using vector memory, pooling layer will now use tensors
managed with the nntrainer.
As the memory is supposed to be integer, this patch currently interprets
float memory as integer memory. Note that no tensor operation is
performed on this memory as it would corrupt the data. Manual reading
and writing of data is done as was done with vector, but memory
management is moved out of the pooling layer with this patch.
This can be done formally when other …
=> [pooling] Update to LayerV2 

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/utils/ini_wrapper.h, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Support for loss as a layer with the API has been done.
However, the verification of this feature was missing.
This patch ensures that the added loss layer is verified and its
required conditions checked before finalizing the graph.
Add loss layer unittests for various loss configurations to be
supported. These tests do not ensure correct graph formation.
This will be done soon with models unittest.
Add golden tests for loss layer added as a layer.
This patch modified the existing models test architecture to be
described where layer is added externally.
More will be added ones more models tests are enabled.
cc. @zhoonit
=> [loss/unittest] Proper support for loss as layer

packaging/nntrainer.spec
Some of the packages state the `requires` as wrong names (missing
package name as prefix). This does not show in build and unit/app tests
but fails when using these packages externally as those dependent
`requires` packaging dont exist.
For example, `nntrainer-devel-static` package depends on `devel`
package, and not on `nntrainer-devel`. This patch provides the
corresponding fix.
BEFORE:
```bash
1:57:04 [:~/GBS-ROOT-SNAPSHOT/local/BUILD-ROOTS/scratch.x86_64.0/home/abuild/rpmbuild/RPMS/x86_64] $ rpm -qp nntrainer-devel-static-0.2.0-0.x86_64.rpm --requires
devel = 0.2.0-0   <-------------------------------------------------------
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
11:59:25 …
```
=> [spec/pkg] Bugfix for dependency

api/ccapi/include/layer.h, nntrainer/layers/activation_layer.h, nntrainer/layers/addition_layer.cpp, nntrainer/layers/addition_layer.h, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/layer_context.h, nntrainer/layers/layer_internal.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/output_layer.cpp, nntrainer/layers/output_layer.h, nntrainer/utils/parse_util.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/unittest/layers/layers_dependent_common_tests.cpp, test/unittest/layers/layers_standalone_common_tests.cpp, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_addition.cpp, test/unittest/layers/unittest_layers_multiout.cpp, test/unittest/meson.build, test/unittest/unittest_nntrainer_graph.cpp, test/unittest/unittest_nntrainer_layers.cpp, test/unittest/unittest_nntrainer_models.cpp
Update addition and multioutput layer for V2 design.
Add corresponding unittests.
Enable graph unittests which creates resnet like model for testing.
Enable correspoding resnet like add in models unittest.
=> [layer] Enable addition and multiout layer for V2 design

api/capi/include/nntrainer-tizen-internal.h, api/capi/meson.build, api/ccapi/include/model.h, api/nntrainer-api-common.h, packaging/nntrainer.spec
- [CAPI] Propose save/load api
```
**Motivations**
1. Fine grained api required to save and load
- Add function to model.h  / `save`, `load`
- Mark `readModel()` deprecated (later remove...)
- Mark `saveModel()` to change `exportTo`
- Add `ModelSaveLoadFormat`
- Create capi-machine-learning-training-tizen-internal for internal api
support
```
=> [CAPI] Propose save/load api @open sesame 07/05 16:40

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nntrainer/compiler/meson.build, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/rnn.cpp, nntrainer/layers/rnn.h, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_rnn.cpp, test/unittest/unittest_nntrainer_models.cpp
Update RNN to layerv2 design.
Corresponding unittests have been added and enabled.
Cleanup RNN implementation.
Reduce usage of temporary allocated memory and reuse existing memory as much as possible.
Further, request hidden state memory from context than creating by self.
=> [layer] Update RNN to layerv2

Applications/SimpleShot/task_runner.cpp, Applications/SimpleShot/tasks/labels.dat, api/ccapi/include/dataset.h, nntrainer/dataset/databuffer.cpp, nntrainer/dataset/databuffer.h, nntrainer/dataset/databuffer_file.cpp, nntrainer/models/model_loader.cpp, nntrainer/utils/parse_util.cpp, test/ccapi/unittest_ccapi.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_dataset.cpp, test/unittest/unittest_databuffer_file.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
- [dataset] Remove label data
```
Before this patch, label.dat was only used to get number of classes,
unfortunately, it was clashing with how databuffer_generator is getting
the number of classes and creating some inconsistency. This patch fixes
the issue by deprecating label data.
* Checked TCT and there is no critical issue that makes tests fail with
this PR.
```
=> [dataset] Remove label data

Applications/LogisticRegression/jni/main.cpp, Applications/VGG/jni/main.cpp, api/ccapi/include/dataset.h, nntrainer/dataset/databuffer.cpp, nntrainer/dataset/databuffer.h, nntrainer/dataset/databuffer_factory.cpp, nntrainer/dataset/databuffer_factory.h, nntrainer/dataset/databuffer_file.cpp, nntrainer/dataset/databuffer_file.h, nntrainer/dataset/databuffer_func.cpp, nntrainer/dataset/databuffer_func.h, nntrainer/dataset/databuffer_util.h, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, test/unittest/unittest_databuffer_file.cpp
~**[Pending commit: #1372]**~
- [dataset] Clean up dataset enums
```
`nntrainer::DataType` and `nntrainer::BufferType` is duplicated from
ccapi which was adding complication. This patch simply alternate those
types ccapi `DatasetType` / `DatasetDataUsageType`
```
=> [dataset] Clean up dataset enums

Applications/Custom/LayerClient/jni/main.cpp, Applications/LogisticRegression/jni/main.cpp, Applications/MNIST/jni/main.cpp, Applications/ProductRatings/jni/main.cpp, Applications/Resnet/jni/main.cpp, Applications/SimpleShot/task_runner.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp, Applications/TransferLearning/Draw_Classification/jni/main.cpp, Applications/VGG/jni/main.cpp, api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, api/ccapi/include/dataset.h, api/ccapi/include/model.h, api/ccapi/src/factory.cpp, nntrainer/dataset/databuffer.cpp, nntrainer/dataset/databuffer.h, nntrainer/dataset/databuffer_factory.cpp, nntrainer/dataset/databuffer_factory.h, nntrainer/dataset/databuffer_func.cpp, nntrainer/dataset/databuffer_func.h, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/utils/parse_util.cpp, test/ccapi/unittest_ccapi.cpp, test/tizen_capi/unittest_tizen_capi.cpp
- [dataset] Clean up dataset enums
```
`nntrainer::DataType` and `nntrainer::BufferType` is duplicated from
ccapi which was adding complication. This patch simply alternate those
types ccapi `DatasetType` / `DatasetDataUsageType`
```
- [dataset] split train / val / test databuffer
```
This patch splits train / val / test dataset.
It is also possible to set dataset separately from the model.
**Major Changes**
1. `auto dataset = createDataset(train_cb, val_cb, test_cb)` -> `auto
dataset_train = createDataset(train_cb)`
1. `NN.setDataset(dataset);` -> `NN.setDataset(DATA_TRAIN,
dataset_train)`
1. Build test: …
```
=> [dataset] split train / val / test databuffer @open sesame 07/15 15:00

Applications/ProductRatings/res/product_ratings_model.ini, Applications/TransferLearning/CIFAR_Classification/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/res/Classification.ini, Applications/TransferLearning/CIFAR_Classification/res/Classification_new.ini, Applications/meson.build, api/ccapi/include/layer.h, meson_options.txt, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, nntrainer/layers/embedding.cpp, nntrainer/layers/embedding.h, nntrainer/layers/layer_internal.h, nntrainer/layers/split_layer.cpp, nntrainer/layers/split_layer.h, nntrainer/utils/parse_util.cpp, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_concat.cpp, test/unittest/layers/unittest_layers_embedding.cpp, test/unittest/layers/unittest_layers_split.cpp, test/unittest/unittest_nntrainer_layers.cpp
Enable working applications with v2. This is done by also enabling split, concat and embedding layer for the V2 design.
Adding some minor updates to the applications to match with the v2 implementation.
An extra property from embedding layer was also removed to work with the new LayerV2 semantics.
resolves #1229
=> [applications] Enable working applications with v2

Applications/SimpleShot/layers/centering.cpp, Applications/SimpleShot/layers/centering.h, Applications/SimpleShot/layers/centroid_knn.cpp, Applications/SimpleShot/layers/centroid_knn.h, Applications/SimpleShot/layers/l2norm.cpp, Applications/SimpleShot/layers/l2norm.h, Applications/SimpleShot/meson.build, Applications/SimpleShot/task_runner.cpp, Applications/SimpleShot/test/meson.build, Applications/SimpleShot/test/simpleshot_centering_test.cpp, Applications/SimpleShot/test/simpleshot_centroid_knn.cpp, Applications/SimpleShot/test/simpleshot_l2norm_test.cpp, Applications/SimpleShot/test/simpleshot_layer_common_tests.cpp, Applications/meson.build
SimpleShot application update for layer V2 design.
This includes updating the three implemented layers - centering, l2norm, and centroid_knn.
Further, task_runner has been updated to use only 1 loss kind of layer.
Unittests of layers have not been enabled, they will be enabled with unittest_layers.
=> [application] SimpleShot application update for V2

Applications/MNIST/jni/main.cpp
MNIST unittest was not running as patch c87963c5433514bccdf0d13f733dd15de4356105
added some filecheck but returned 0 upon failure.
This patch removes returning on failure with just a warning.
=> [application] Disable MNIST unittest

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_context.h, nntrainer/layers/layer_impl.cpp, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/time_dist.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/weight.h, nntrainer/utils/node_exporter.cpp
Remove LayerNode dependence on LayerV1.
Further, NetworkGraph dependence on LayerV1 is also removed.
Some More bugfixes in the patch:
- Add initialization for the missing variables for LayerImpl class
- Add missing initialization in constructor for the weight class
=> [layer] LayerV1 cleanup from LayerNode

nntrainer/graph/network_graph.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/time_dist.cpp, nntrainer/layers/time_dist.h, nntrainer/tensor/tensor_dim.h, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_models.cpp
Enable time dist layer for LayerV2 design.
This patch tries to simulate the InitContext and the RunContext inside
the time dist layer so that proper shapes of variables can be passed to
the internal layer. Further, context changing function calls are
replicated on the actual InitContext/RunContext by detecting changes and
making those function calls again.
LayerNode was updated to ensure that a layer is not getting distributed
again and again.
Some more getter APIs were added for TensorDim and LayerContext.
Unittests related to distribute have also been enabled with this patch.
=> [layer] Enable time dist layer for V2

Applications/MNIST/jni/main.cpp, nntrainer/layers/acti_func.cpp, nntrainer/layers/acti_func.h, nntrainer/layers/gru.h, nntrainer/layers/lstm.h, nntrainer/layers/rnn.h, nntrainer/tensor/manager.h
Update implementation to handle in-place and non-inplace scenarios.
With new memory scheme coming in, in-place activation optimization and
derivative optimization is disabled. This patch updates the activation
function implementations to work for in-place and non-in-place
scenarios.
RNN, LSTM and GRU use activation functions internally with always
in-place settings. So, both the modes are supported.
This patch specifically convers the activation function scenario.
The generic support of in-place will be done when manager is updated.
This resolves the MNIST training bug.
Update MNIST application benchmark values based on the updated weight
initialization.
Resolves #1422
=> [activation] Update implementation for in-place 

Applications/Custom/LayerPlugin/layer_plugin_rnnt_loss_test.cpp, Applications/Custom/LayerPlugin/meson.build, Applications/Custom/meson.build, Applications/Custom/rnnt_loss.cpp, Applications/Custom/rnnt_loss.h
This commit includes:
. Sekeleton Code for RNNT Loss as an Custom Loss Layer
. Sementic Unit Test
=> [ RNNT LOSS ] Add skeleton code for rnnt loss @open sesame 07/26 15:25

test/unittest/datasets/data_producer_common_tests.cpp, test/unittest/datasets/data_producer_common_tests.h, test/unittest/datasets/meson.build, test/unittest/datasets/unittest_random_data_producers.cpp, test/unittest/meson.build
- [Dataset] Add test for the random dataproducer
```
- Add random data producer tests
- Add abstract test for more data producers
```
=> [Dataset] Add test for the random dataproducer

api/capi/include/nntrainer.h, meson.build
- [CAPI] Deprecate old dataset apis
```
This patch updates to deprecate old dataset apis
```
=> [CAPI] Deprecate old dataset apis

api/capi/include/nntrainer-tizen-internal.h
- [CAPI] Add ml_train_model_get_layer to internal
```
This patch adds ml_train_model_get_layer to internal api
```
=> [CAPI] Add ml_train_model_get_layer to internal

api/capi/include/nntrainer.h
- [CAPI] Change tensor dim -> information
```
This patch updates description of the tensors_info, while explicitly
stating that the information object is newly created
Cc: Hyeonseok Lee<hs89.lee@samsung.com>
Cc: Parichay Kapoor<pk.kapoor@samsung.com>
```
=> [CAPI] Change tensor dim -> information

api/ccapi/include/model.h, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nnstreamer/tensor_filter/tensor_filter_nntrainer.hh, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h
1. Add model inference to the c++ API using the vector of float ptrs as
inputs and outputs.
2. This patch adds bugfix for the nnstreamer's tensorfilter of nntrainer.
- include proper headers required by the tensor filter header
- use the correct offset for the multi-input scenario
3. Remove tensor filter implementations dependency on nntrianer::Tensor.
Resolves #1442
=> [ccapi] Add ccapi for model inference

api/capi/include/nntrainer-tizen-internal.h, api/capi/include/nntrainer.h
- [CAPI] Move save/load api to public
```
This patch moves save/load api to public
```
=> [CAPI] Move save/load api to public

test/tizen_capi/unittest_tizen_capi.cpp
C-API unittest was checking for throw but instead should be checking for
return value. This patch fixes the test.
Further, the unittests tries to free unallocated tensordim in error
cases. This patch resolves it too.
=> [test] capi unittest fix

jni/Android.mk, nntrainer/dataset/batch_queue.cpp, nntrainer/dataset/batch_queue.h, nntrainer/dataset/meson.build, test/unittest/datasets/meson.build, test/unittest/datasets/unittest_batch_queue.cpp
- [Dataset] Add thread safe queue for the buffer
```
Currently, databuffer is not queuing any iteration but requesting buffer
on-demand basis.
This patch adds thread safe queue for the buffer to queue multiple
buffers
```
=> [Dataset] Add thread safe queue for the buffer

nnstreamer/tensor_filter/meson.build, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nnstreamer/tensor_filter/tensor_filter_nntrainer.hh
Update nntrainer's tensor filter for nnstreamer to depend only on ccapi
and nntrainer directly and internal headers.
See Also #986
Resolves #696
=> [tensorfilter] Update tensor filter to use ccapi

nntrainer/dataset/data_producers.h, nntrainer/dataset/databuffer.cpp, nntrainer/dataset/databuffer.h, nntrainer/dataset/random_data_producers.cpp, nntrainer/dataset/random_data_producers.h, nntrainer/dataset/raw_file_data_producer.cpp, nntrainer/dataset/raw_file_data_producer.h, test/unittest/datasets/meson.build, test/unittest/datasets/unittest_databuffer.cpp, test/unittest/datasets/unittest_random_data_producers.cpp
- [Dataset] Implement data getter
```
This patch implements data getter.
There are two types of data getter.
1. queue multiple iterations and get one by one
(`DataBuffer::startFetchWorker()`, `DataBuffer::fetch()`)
2. generate one iteration on the fly (`DataBuffer::batcher()`)
```
=> [Dataset] Implement data getter

api/capi/src/nntrainer.cpp, api/ccapi/include/layer.h, api/ccapi/include/optimizer.h, jni/Android.mk, nntrainer/graph/graph_node.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/dynamic_training_optimization.cpp, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/optimizers/adam.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/meson.build, nntrainer/optimizers/optimizer_context.cpp, nntrainer/optimizers/optimizer_context.h, nntrainer/optimizers/optimizer_devel.cpp, nntrainer/optimizers/optimizer_devel.h, nntrainer/optimizers/optimizer_impl.cpp, nntrainer/optimizers/optimizer_impl.h, nntrainer/optimizers/plugged_optimizer.h, nntrainer/optimizers/sgd.cpp, nntrainer/optimizers/sgd.h, test/unittest/unittest_nntrainer_appcontext.cpp
Cleanup optimizer interface where some extra interfaces have been
removed, and arguments interface has been updated.
Further, the dependency on weight header has been removed, and added an
optimizer context interface which provides an interface to weight
related tensors required by the optimizer.
Update the interface for the layer.h setProperty.
=> [optimizer] Make optimizer independent of weight

debian/rules
Remove unsupported meson build option from debian script.
=> Debian: you don't have debian-build meson option.

nntrainer/dataset/raw_file_data_producer.cpp, test/unittest/datasets/unittest_databuffer.cpp, test/unittest/unittest_nntrainer_models.cpp
- Using ValuesIn function instead of Values cause the arguments are more than 50
- Comment unused variable
=> [unittest] enable commented unittest

nntrainer/layers/nnstreamer_layer.cpp, nntrainer/layers/nnstreamer_layer.h, test/tizen_capi/unittest_tizen_capi.cpp
This patch adds bug fixes after adding fixes related to address
sanitzer:
- NNStreamerLayer wasnt freeing resources upon destruction
- accessing released model handle in capi unittest
- not releasing model handle before end of unittest
See Also #1480
=> [fixes] Add bug fixes found with address sanitizer

nntrainer/graph/graph_core.cpp, nntrainer/graph/graph_core.h, nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h
This patch provides graph cleanup and preparation for memory optimizations:
- Remove layerv2 initialize code for network graph.
- Currently each graph node has two identifiers - name and idx - where
both were unique. This patch removes the idx as the indentifier.
The corresponding functions are also removed.
In order to support fast fetching of nodes, graphcore has a map nodes.
- This change revealed a bug with the names in the code. As ini does not
allow case sensitive names, the names from the ini are changed to lower
case. However, input_layers property names were allowed to be
case-sensitive. Further names set by the API were also case sensitive.
This patch forces all such names to be case-insensitive to lowercase.
- Update the check for checking if a given node is input node.
The …
=> [graph] Graph cleanup and prepare for memory optimization

api/capi/include/nntrainer.h
- [CAPI] Reflect privilege reviews
```
This patch update document to add privilege to `ml_train_model_save()`
and `ml_train_model_load()`
```
=> [CAPI] Reflect privilege reviews

nntrainer/dataset/data_producers.h
- [Dataset] Add interface for samplewise producer
```
This patch adds interface to migrate batchwise producer to samplewise
producer
```
=> [Dataset] Add interface for samplewise producer

Applications/SimpleShot/layers/centroid_knn.cpp, nntrainer/graph/graph_core.cpp, nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/bn_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/dropout.cpp, nntrainer/layers/embedding.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/gru.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/lstm.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/rnn.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor_wrap_specs.h, nntrainer/tensor/weight.h, test/unittest/layers/layers_standalone_common_tests.cpp
This patch creates a var_grad/weight to usage index mapping for both forwarding and backwarding.
These indexes will be used by the manager and the memory allocator for understanding the overlapping use of tensors.
The changes to achieve are (summarized per commit):
- Move manager from NeuralNetwork class to NetworkGraph class.
Some corresponding minor adjustments are also added.
- Update the layers to make the requested weights and tensors names to be
unique. This done using the layer name with the postfix of the
weights/tensors name making the combination unqiue as layer name is
unique.
InitLayerContext is updated to provide access to the layer name while
finalizing the layer.
- Set default usage time index for all the tensors based on when the layer
is to be run in the sorted list.
The …
=> [layers/manager] Set tensor to usage mapping

Applications/Custom/LayerClient/jni/meson.build
- [Trivial] layer client test was not running
```
This patch changes test variable argument in order for layer client
tests to run
```
=> [Trivial] layer client test was not running

nntrainer/dataset/random_data_producers.cpp, nntrainer/dataset/random_data_producers.h, test/unittest/datasets/data_producer_common_tests.cpp, test/unittest/datasets/data_producer_common_tests.h, test/unittest/datasets/unittest_random_data_producers.cpp
- [Dataset] Implement samplewise producer for random
```
This patch implements samplewise producer for random and its
corresponding test abstraction
```
=> [Dataset] Implement samplewise producer for random

Applications/SimpleShot/task_runner.cpp, api/ccapi/include/layer.h, nntrainer/compiler/ini_interpreter.cpp, nntrainer/layers/nnstreamer_layer.cpp, nntrainer/layers/nnstreamer_layer.h, nntrainer/layers/tflite_layer.cpp, nntrainer/layers/tflite_layer.h
- [Backbone/CAPI] Implement backbone layer creation
```
- Connect enum to nnstreamer backbone
- Change `model_file` property to `model_path` for generality
- Add handling for when model_file property is loaded from interpretation
Resolves #1072
Cc: Inki Dae <inki.dae@samsung.com>
```
=> [Backbone/CAPI] Implement backbone layer creation

api/capi/include/nntrainer.h
- [CAPI] Reflect feature review
```
This patch reflects feature review.
**Changes Proposed**
- Adding Not Supported enum
```
=> [CAPI] Reflect feature review

nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_planner.h, nntrainer/tensor/memory_pool.h
- Simplify weight and gradient allocation out to the most basic strategy
so that the memory optimization can be applied on it.
With this patch, the memory for gradient is not shared anymore till the
memory optimization is implemented.
- This patch introduces memory planner interface which will provide a
layout plan given the various memories required by the model.
Different memory allocations plans/strategies will be implemented by
extending this class with the given interface.
- This patch introduces memory pool for tensors. All the tensors requiring
memory can ask memory pool for their memory. The memory pool collects
all the requirements, uses the provided memory planner to plan a memory
layout, allocates the required memory, and then finally returns the
allocated memory to the …
=> [memory] Introduce memory pool and planner

test/unittest/layers/unittest_layers_nnstreamer.cpp, test/unittest/layers/unittest_layers_tflite.cpp
Update backbone property name for the layers unittests.
This patch fixes failing unittests for main.
=> [unittest] backbone property name update

nntrainer/dataset/data_producers.h, nntrainer/dataset/func_data_producer.cpp, nntrainer/dataset/func_data_producer.h, nntrainer/dataset/random_data_producers.cpp, nntrainer/dataset/random_data_producers.h, nntrainer/dataset/raw_file_data_producer.cpp, nntrainer/dataset/raw_file_data_producer.h
- [Dataset] Change finalize signature
```
This patch changes finalize signature to contain user_data,
user_data will be needed to replicate the current worker(with diffrent
arguments) in case of
MT_safty is not provided by the producer. Please note that this does not
change any current behavior but the preparation for the future
enhancements.
```
=> [Dataset] Change finalize signature

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
- [Trivial] delete no meaningful save/load test
```
This patch delete no menaingful save/load test which was drawing
attention of static anaysis tool
```
=> [Trivial] delete no meaningful save/load test

nntrainer/tensor/basic_planner.cpp, nntrainer/tensor/basic_planner.h, nntrainer/tensor/memory_planner.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/meson.build, test/unittest/layers/unittest_layers_activation.cpp, test/unittest/memory/memory_planner_validate.cpp, test/unittest/memory/memory_planner_validate.h, test/unittest/memory/meson.build, test/unittest/memory/unittest_memory_planner.cpp, test/unittest/meson.build
Add support for a basic memory planner along with its unittests:
- This patch adds support for the basic memory planner.
The basic memory planner does not provide any memory sharing, and
results in all tensors being allocated in separate memories.
This forms the baseline for memory allocation.
Other memory planners will be enhancement over this.
- This patch adds unittests for the memory planner.
The unittests covers some of the extreme scenarios for memory planning
and ensures that the constraints are satisfied.
Note that these tests do not test the efficient of the planning but the
validity of the planned layout.
Corresponding bug fixes are also added.
See Also #1127
=> [MemoryPlanner] Basic memory planner with unittests

api/capi/include/nntrainer.h, api/ccapi/include/model.h, jni/Android.mk, nnstreamer/tensor_filter/tensor_filter_nntrainer.cc, nnstreamer/tensor_filter/tensor_filter_nntrainer.hh, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/input_layer.cpp, nntrainer/layers/layer_impl.cpp, nntrainer/models/meson.build, nntrainer/models/model_common_properties.cpp, nntrainer/models/model_common_properties.h, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/utils/base_properties.cpp, nntrainer/utils/base_properties.h, nntrainer/utils/ini_wrapper.cpp, nntrainer/utils/ini_wrapper.h, nntrainer/utils/parse_util.cpp, nntrainer/utils/parse_util.h, nntrainer/utils/util_func.h, test/ccapi/unittest_ccapi.cpp, test/unittest/memory/memory_planner_validate.cpp
- [ini] Implement model save
```
This patch implements model section save in ini format
**Side Changes proposed in this PR:**
- Move `THROW_STATUS` and `RETURN_STATUS` to util_func.h
```
- [ini] Migrate to properties for model
```
This patch migrate to properties for neuralnet
**Semantic Changes**
- NeuralNetwork::batch_size does not change when actual batchsize change
from neuralnetwork instead, model graph keeps batch size separately.
- Move members to props in model
- Move inline declaration to declaration for some functions
- Remove unused member/functions from parse_util / neuralnet
**Self …
```
=> [ini] Implement model save

nntrainer/compiler/ini_interpreter.cpp, nntrainer/models/model_loader.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/optimizers/adam.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/optimizer_devel.h, nntrainer/optimizers/optimizer_impl.cpp, nntrainer/optimizers/optimizer_impl.h, nntrainer/optimizers/sgd.cpp, nntrainer/optimizers/sgd.h, nntrainer/utils/base_properties.cpp, nntrainer/utils/base_properties.h, nntrainer/utils/ini_wrapper.h, nntrainer/utils/parse_util.cpp, nntrainer/utils/parse_util.h
- [ini/save] Save Optimizer Section
```
This patch saves optimizer section to ini.
```
- [Optimizer] Refactor to use props
```
This patch refactors optimizer families to use properties while removing
some unused functions and constructors
```
- [IniWrapper] Add factory method
```
This patch adds a function to create ini section directly from
exportable which implements .exportTo to reduce overlapping codes
1. Build test: [X]Passed [ ]Failed [ …
```
=> [ini/save] Save Optimizer Section

nntrainer/graph/graph_node.h, nntrainer/graph/network_graph.cpp, nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, test/unittest/unittest_common_properties.cpp
- [ini] Implement input layers property
```
This patch implements input layers property while decoupling input
dimensions from input layers as much as possible
to make the property dumb.
```
=> [ini] Implement input layers property @open sesame 09/08 14:17

nntrainer/models/model_common_properties.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h
- [model] implement save best acc logic
```
This patch implements saving best accuracy when training
```
=> [model] implement save best acc logic

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/time_dist.cpp, nntrainer/utils/base_properties.h, test/unittest/layers/layers_dependent_common_tests.cpp, test/unittest/unittest_base_properties.cpp
- [props] Support enum properties
```
This patch aims to support enum based properties, please refer to the
test to see how it works.
```
- [Ini Save] input shape property
```
This patch includes input shape property generation
```
- [LayerNode] Change context to be RAII
```
This patch refactors context to be RAII to make layer node properties
dumb.
**Changes**
- init context is removed
- layer node instead created and returned from layerNode::finalize(input_dims)
- remove dependency to input dimension before initialize
- layerNode now has input_shapes instead of setting …
```
=> [props] Support enum properties

packaging/nntrainer.spec, test/unittest/datasets/unittest_databuffer.cpp
- [Spec] Exclude generated coverage items
```
This patch excludes generated coverage items from daily coverage report
```
=> [Spec] Exclude generated coverage items

nntrainer/utils/node_exporter.h, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp, test/unittest/unittest_base_properties.cpp
- Enable Saving props by delimiter '|'
```
This patch enables saving properties by delimiter '|'
Cc: Inki Dae <inki.dae@samsung.com>
```
=> Enable Saving props by delimiter '|'

test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_preprocess_flip.cpp, test/unittest/layers/unittest_layers_preprocess_translate.cpp
- [Fix] upstream build fail
```
This patch fixes upstream build fail from overlapping test suite name
```
=> [Fix] upstream build fail

nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/pooling2d_layer.cpp, test/unittest/unittest_common_properties.cpp
- [Conv2d] Conv2d Padding Fix
```
This patch resolves conv2d calculation is crooked in some cases
- Conv2d Fix
- Padding::Compute Fix
Co-authored-by: Parichay Kapoor <pk.kapoor@samsung.com>
```
=> [Conv2d] Conv2d Padding Fix

Applications/Resnet/jni/main.cpp, Applications/Resnet/jni/meson.build, Applications/Resnet/tensorflow/resnet18.py, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h
- Add resnet18 tensorflow version to match against nntrainer.
- Update resnet application to match tensorflow implementation.
- This patch reduces the number of operations required for tensor sum by
accumulating the consecutive axes in order to increase the precision of
the operation.
- This patch adds test check on the training of the resnet application.
This test can be enabled with enable-long-test and enable-test.
Note: reduction of operations for sum was intended to reduce the number of operations to result in higher precision but can very well result in speedup as well.
resolves #904
Resolves #1533
=> [application] Add resnet18 tensorflow + update application @open sesame 09/23 13:59

test/input_gen/genModelTests.py, test/input_gen/recorder.py, test/unittest/unittest_nntrainer_models.cpp
- This patch adds resnet18 unittest model generation with genModelTests.
Further, the input data range is changed from 0 to x from -x to x as
relu based models work better with 0 to x data range to prevent loss of
information.
- This patch adds resnet models unittest for resnet18.
The verification has been done offline for 2 iterations for the output
of all layers with precision of 1.1e-4.
Derivaitves and gradients have higher error because of relu: when some
value is close to 0, it can be positive or negative with some error (of
the order of e-7). Although this error is way within the error limit.
however, this exacerbates the error in backwarding where derivatives (which
are significant in values) can flow if the relu value was over 0, and
not flow if under zero. This is manageable in …
=> [resnet/unittest] Add unittest for resnet @open sesame 09/23 13:59

nntrainer/tensor/basic_planner.cpp, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/meson.build, test/unittest/memory/memory_planner_validate.cpp, test/unittest/memory/memory_planner_validate.h, test/unittest/memory/meson.build, test/unittest/memory/unittest_memory_planner.cpp, test/unittest/memory/unittest_memory_pool.cpp
This patch adds memory pool implementation with its unittests which uses the basic planner as the planner
- This patch provides implementation for memory pool which uses a memory
planner to plan the layout of the memory and provides efficiency of the
given planner.
- This patch adds unittests for memory pool for its public APIs.
Further, memory validation is added for the requested memories and
those tests will be added for each planner. This ensures that the
memories returned by each planner do not overlap, and remain valid while
usage.
Fixes corresponding to the unittests are also added.
See ALso #1127
=> [MemoryPool] Add memory pool implementation with unittests

nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp
Note: number of commits for this PR = 3
This patch provides cleanup for VarGrad and Manager, and add name to Tensor:
1. Flatten the tensors (weights/inputs/outputs/tensors) list stored in the
manager. It was of the form vector<vector<>> to club the tensors
requested from a layer together. However, this is neither required now
nor is it sufficient. If required later, a mapping from node will be
created.
2. Move name as an identifier to the tensor.
This name has been mvoed from the Var_Grad object.
Var_Grad now does not contain name itself.
The semantics of name for Tensor currently follows from var-grad:
- empty name is allowed
- repititive names are allowed
Restrictions can and will be added over time.
3. This patch cleansup VarGrad implementation, and ends up removing all its
members …
=> [vargrad/tensor] Tensor names + cleanup 

nntrainer/graph/network_graph.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/dropout.cpp, nntrainer/layers/gru.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/lstm.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/rnn.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor_wrap_specs.h, nntrainer/tensor/var_grad.h, nntrainer/utils/util_func.h
Note: number of commits for this PR = 2
This patch adds the execution order and lifespan of all the requested tensors in the manager.
- Create a lifetime and usage list for all the tensors which have been
requested by the manager in the form of weights/inputs/outputs/trainable
tensors.
A tensor name based map is used as each tensor has the name identifier.
Further, the restriction of the name to be unique is added for the
tensors which are requested by the manager.
TensorLifespan enum values are updated to be of the form of bit wise
enabling. This allows checking and upgrading lifespan of an existing
tensor.
- Add the constraint of the output tensors of a node with the input
tensors of the next nodes. This allows memory pool to understand the
manager that these two inputs/outputs must use …
=> [manager] Add execution-order and lifespan of tensors

jni/Android.mk, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/meson.build, nntrainer/tensor/tensor.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, test/unittest/meson.build, test/unittest/unittest_nntrainer_tensor_pool.cpp
- This patch introduces TensorPool which manages the list of all the
tensors with their execution orders and lifespan.
The conversion of lifespan and execution orders to the validity will be
done by the TensorPool.
TensorPool forms the middle ground between memory pool and manager for
easier maintainance.
- Added tensor pool implementation with unittests.
Tensorpool provides the interface where all the requested tensors are
managed at one places ensuring the uniqueness of name with their
lifespan and execution orders.
Corresponding unittests checking the working is added.
This patch aims to reduce the work and data structures from the manager and shift the workload to TensorPool.
Merged already approved #1492 in this PR.
See Also #1127 …
=> [TensorPool] Added TensorPool as a pool of tensors

Applications/VGG/res/vgg_small.ini, jni/Android.mk, nntrainer/graph/network_graph.cpp, nntrainer/layers/acti_func.cpp, nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.h, nntrainer/layers/loss/cross_entropy_sigmoid_loss_layer.cpp, nntrainer/layers/loss/cross_entropy_softmax_loss_layer.cpp, nntrainer/layers/loss/mse_loss_layer.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/tensor.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h
- This patch adds bugfixes for layers:
1. acti_func in-place support bug
2. batch normalization layer weight name bug
3. loss layers not using tensor reference bug
- This patch updates manager to use TensorPool for its weights and
corresponding weights. Corresponding changes to Var_Grad/Weights and
Tensors are also added.
- setBatchSize() now takes dimensions from user, and then updates the
provides these updates dimensions to the manager. We can possibly remove
setBatch(RunLayerContext), which will be finalized in the next commit.
- Use TensorPool for gradients of the weights.
- This patch makes tensor list in tensorpool ordered.
This ensures that the requested tensors are initialized in the order of
the their requests which is by the order of the sorted graph.
- This patch adds fix when …
=> [Manager] Manager use TensorPool for Weights

test/unittest/unittest_nntrainer_tensor_pool.cpp
<details><summary>[Fix] gcc-7 has compile error</summary><br />
This patch fixes gcc compile error (-wsign-compare,
-wmaybe-uninitialized)
</details>
=> [Fix] gcc-7 has compile error

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.cpp, nntrainer/tensor/weight.h, test/unittest/unittest_nntrainer_models.cpp
This patch updates manager to use TensorPool for all of its requests.
Other changes are as listed below:
- NetworkGraph now caches the inputs and labels Var_Grads which can
directly by the model before execution.
- setLabels and setInputs in the model have been updated. Further,
manual setting of inputs and labels has been removed.
- Introduce clear in memory pool to clear any allocations and requests
- TensorPool clears any requests made before making more requests in
finalize
- models unittest updated to not pass label when loss is not given in
the model. Passing label without loss in the model now results in error
- Manager updated to use tensor pool for all the memory requests. The
allocation, initialization and deallocation has been correspondingly simplified
Much needed cleanup will …
=> [Manager] Manager to use TensorPool for all requests

nntrainer/graph/graph_core.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_context.cpp, nntrainer/models/execution_mode.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/tensor.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, nntrainer/tensor/weight.h, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/datasets/data_producer_common_tests.cpp, test/unittest/unittest_nntrainer_models.cpp
Number of commits to review in this PR : 2
This patch provides cleanup for manager and related classes:
- cleanup for Manager
- cleanup for Var_Grad and Weights
Fixes:
- Graphcore,NetworkGraph,NeuralNet destructor fixed to not clear their
lists until they are destructed, as this caused bug in copy constructor
- initialize and allocation for tensors are merged for model, graph and
manager interface. This removes unnecessary confusion and possible bugs
from these classes
- Pass appropriate start and end execution orders to manager for
allocation
- Support setInputs to set multiple inputs
- clean inputs/labels which are allocated by the dataset, other manager
tries to clear them. This is temporary till dataset is not using the
manager
- memory pool to start giving tokens from 1 instead of 0. …
=> [cleanup/fix] Cleanup + bugfix

nntrainer/layers/bn_layer.cpp, nntrainer/layers/bn_layer.h, nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/time_dist.cpp, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/layers/layers_golden_tests.cpp
- This patch optimizes batch normalization implementation.
Reduces the temporary memory allocation and provide speedup for the
layer execution. With this patch, resnet18 runtime improves by approx
5%.
- update the tensor usage method to give the output tensor. Although the methods where already allocated output can be passed were available, they were not being used. This patch adds the corresponding support.
- This patch optimizes batch norm layer and tries to share the
calculations performed in calcGradient and calcDerivative.
- reuse dbeta and dgamma calculations
- reduce number of required temporary variables
- create all the required tensor variables with context
- add support for checking if the layer is trainable or not via run
context
- support average operation with the output …
=> [batchnorm] Optimize batch norm for memory and speed @open sesame 09/28 18:42

Applications/Resnet/jni/meson.build, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/tensor/basic_planner.cpp, nntrainer/tensor/memory_pool.h, nntrainer/tensor/meson.build, nntrainer/tensor/optimized_v1_planner.cpp, nntrainer/tensor/optimized_v1_planner.h, test/unittest/memory/memory_planner_validate.cpp, test/unittest/memory/unittest_memory_planner.cpp, test/unittest/memory/unittest_memory_pool.cpp
- This patch adds an optimized v1 planner for memory sharing.
- This planner assigns memory in the order of start of the validity,
and then by decreasing the order of the end of the validity. This matches
the memory use pattern while training the model.
This planner is supposed to work better for training than for inference.
- Also added unit tests for the optimized v1 planner.
Merged changes from #1539 (as it became a trivial PR after rebase):
- This patch enables resnet application with some fixes. tensor allocation for ENABLE_TEST mode updated.
See Also #1127
Resolves #1533
=> [planner] Add optimized v1 planner 

jni/Android.mk, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/flatten_layer.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/optimized_v1_planner.cpp, nntrainer/tensor/tensor_pool.cpp, test/unittest/memory/memory_planner_validate.cpp, test/unittest/unittest_nntrainer_models.cpp
- Flatten layer in-place implementation manipulates the tensor stored in
its input and output. This violates the execution order usage of the
tensors and does not work with the memory planning setup.
This patch makes flatten layer to work out-of-place with a copy.
There will soon be a patch to make flatten work in-place with proper
method.
- Added bug fix in the execution order calculation where some of the
execution values were being missed in the previous implementation.
- Optimized v1 planner is updated to reuse expired allocations which are
not at the top the sorted list. This is a heuristic which works well for
training memory usage scenario.
The unittest is also updated to be more generic when checking the
interval overlap with the allocations.
-This patch adds the corresponding bug …
=> [graph/manager] bug fix + Enable memory v1 optimizations 

nntrainer/layers/bn_layer.cpp, nntrainer/layers/bn_layer.h
- Reduce the memory comsumption of batch norm for forwarding by re-using
the output tensor as temporary memory than requesting new memory.
- Remove the extra full size extra memory requirement as the cost of the
reduced memory. The difference in memory requirmement can be
significant. Earlier memory requirement was b*c*h*w vs now it is just c
where the assumption is that batch norm if is normalizing along
axis=channel.
This is achieved by reordering of the operations.
Note: this change has no performance impact.
Resolves #1591
=> [batch norm] reduce batch norm memory utilization further

nntrainer/layers/attention_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/centroid_knn.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/dropout.cpp, nntrainer/layers/embedding.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/gru.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/lstm.cpp, nntrainer/layers/lstmcell.cpp, nntrainer/layers/pooling2d_layer.cpp, nntrainer/layers/rnn.cpp, nntrainer/layers/time_dist.cpp
- All layers were required to make unique name for their requests.
This is now rather done by layer context by appending layer name as a
prefix to the requested name.
- This patch allows support for prefix for sharing weight names across
layers, so that layers which should share their weights can do so by
using the same prefix.
=> [layer] Simplify naming scheme for requested tensors 

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/lstmcell.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/tensor.cpp, test/unittest/models/models_test_utils.cpp, test/unittest/models/models_test_utils.h
Current implementation assumes that the graph is always linear and skips
the backwarding for contiguous set of layers at the start of the model
which should not do the backwarding.
This patch makes a fix to this issue but allowing layers in the middle
of the sorted graph to skip backwarding.
Resolves #1686
Resolves #1664
Note: this will provide minor speedup for complex models where some more layers backwarding can be skipped.
=> [graph] Skip backwarding bug fix + memory optimize

nntrainer/graph/network_graph.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, nntrainer/tensor/tensor_wrap_specs.h, test/unittest/unittest_nntrainer_tensor_pool.cpp
<details><summary>[TPool] Add interface to enable extensive sharing</summary><br />
This patch add interface to enable extensive sharing, including
reassigning or tensor pointer sharing (previously discussed as s3
sharing)
</details>
<details><summary>[TPool] implement create/placeholder</summary><br />
This patch implements create/view and its corresponding test.
</details>
<details><summary>[tpool] Implement view()</summary><br />
- …
=> Policy based tensor request for tensor pool.

nntrainer/layers/centroid_knn.cpp, nntrainer/layers/centroid_knn.h, nntrainer/layers/layer_context.cpp
<details><summary>[KNN] Implement knn saving</summary><br />
As knn was not saving it's props, this patch implements saving property
</details>
<details><summary>[KNN] Fix querying label when not training</summary><br />
This patch fix querying label when not training, which is not feasible
</details>
=> [KNN] Fix querying label when not training

nntrainer/graph/network_graph.cpp, nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/var_grad.cpp, nntrainer/tensor/var_grad.h, test/unittest/models/models_test_utils.cpp, test/unittest/models/unittest_models_recurrent.cpp
<details><summary>[QuickFix] Add not dependent weight sharing</summary><br />
This patch allows weight sharing regardless of allocation order of
weight sharing
</details>
<details><summary>[Weights] Add last access concept</summary><br />
As all weights are shared now, we need last accesss to be deteremined
This patch implements such behavior with a test
</details>
<details><summary>[QuickFix] Check weight access for the last</summary><br />
This patch sets …
=> [QuickFix] Check weight access for the last @open sesame 11/19 10:09

api/capi/src/nntrainer-capi-tizen-feature-check.cpp, meson.build, meson_options.txt, packaging/nntrainer.spec
<details><summary>[Feature check] Add tizen 6.5 compatibility</summary><br />
As prefix has been added to the `ml_tizen_set_feature_state` for tizen
7.0 this patch makes backward compatible to the old tizen version
</details>
=> [Feature check] Add tizen 6.5 compatibility

nntrainer/compiler/slice_realizer.cpp, nntrainer/layers/concat_layer.cpp, nntrainer/layers/concat_layer.h, test/unittest/compiler/unittest_realizer.cpp, test/unittest/unittest_nntrainer_models.cpp
- Concat layer has properties which were not being saved. This patch adds
the corresponding support.
- Below bugs have been fixed for the slice realizer:
- end layers were being added using children which were not set yet
- the dfs_stack never ignored nodes which had already been visited which
was leading to infinite loop
- an invalid graph given with loops would be stuck in infinite loop in
the DFS
- Slice realizer was storing the path for each node from the start nodes
to themselves. This can be big, and also comes with a overhead of
storing and copying these paths for each node.
This patch updates the implementation of the dfs to a recursive approach
which maintains the stack of the nodes in the memory which represents
the path till now. …
=> [fixes] Fixes to layer and graph @open sesame 11/19 10:10

api/ccapi/include/model.h, jni/Android.mk, nntrainer/compiler/flatten_realizer.cpp, nntrainer/compiler/meson.build, nntrainer/compiler/previous_input_realizer.cpp, nntrainer/compiler/previous_input_realizer.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/models/neuralnet.cpp, test/unittest/compiler/unittest_interpreter.cpp, test/unittest/compiler/unittest_realizer.cpp
<details><summary>[Scaffolding] previous input realizer</summary><br />
This patch implements previous input realizer.
</details>
<details><summary>[Realizer] Implement previous input realizer test</summary><br />
This patch implement previous input realizer test to demonstrate
specification of previout input realizer
</details>
<details><summary>[Realizer] Implement previous input realizer</summary><br />
This patch implement previous input realizer.
**Self …
=> [nn] Apply previous input realizer

api/ccapi/include/layer.h, nntrainer/layers/permute_layer.cpp, nntrainer/layers/reshape_layer.cpp
- Add shape mismatch check in reshape layer.
- Permute layer backward bug in the calculation of the reverse
direction of the permute is fixed.
- Add missing layer constructor for permute.
=> [fixes] Few minor fixes

nntrainer/layers/grucell.cpp, nntrainer/layers/layer_context.h, nntrainer/models/neuralnet.cpp, nntrainer/tensor/tensor.cpp
[QuickFix] Disable contiguous check on add_i
- For now disable contiguous check of tensor on add_i
since the add_strided does not support broadcast.
=> [QuickFix] Disable contiguous check on add_i

nntrainer/graph/graph_node.h, nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/input_layer.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h, test/unittest/unittest_common_properties.cpp
<details><summary>[Connection] Add indexing to connection</summary><br />
This patch revisition connection spec to contain identifier and index to
make use of it.
</details>
<details><summary>[Node] Replace input layers -> input connection</summary><br />
This patch replace input layers to input connection.
</details>
<details><summary>[Node] replace output layer string -> connection</summary><br />
This patch replaces output layer from string to connection
**Self …
=> [Node] Add get/set method to manipulate connection

Applications/ProductRatings/jni/main.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/embedding.cpp, nntrainer/layers/embedding.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h
- Embedding layer should assume that the input data is written in int
format than in float data. Reading data as float can lead to wrong
values when typecasting to int if std::lround() is not properly used.
Further, as other frameworks require using integer data for embedding,
its best if follow the same input formats.
- Embedding layer support zero mask index which if set will pass zero
values for that particular index in the forward propagation and will not
be updated with gradient.
Further minor updates to tensor related to getting tensor values.
resolves #1729
=> [layer] Embedding layer new property + bug fix @open sesame 11/29 16:00

Applications/ProductRatings/res/product_ratings_model.ini, jni/Android.mk, nntrainer/compiler/activation_realizer.cpp, nntrainer/compiler/activation_realizer.h, nntrainer/compiler/flatten_realizer.cpp, nntrainer/compiler/meson.build, nntrainer/compiler/multiout_realizer.cpp, nntrainer/compiler/multiout_realizer.h, nntrainer/compiler/remap_realizer.cpp, nntrainer/compiler/remap_realizer.h, nntrainer/graph/graph_core.h, nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/unittest/compiler/unittest_realizer.cpp
- **[Pending commit: #1733]**
<details><summary>[Realizer] Implement activation realizer</summary><br />
This patch implement activation realizer
</details>
<details><summary>[Test] Activation realizer test</summary><br />
This patch implement activation realizer
</details>
<details><summary>[nn] Attach activation realizer</summary><br />
This patch attach activation realizer
2. Run test: [X]Passed [ …
=> [Wait for #1733] [nn] Attach activation realizer

api/ccapi/include/layer.h, jni/Android.mk, nntrainer/app_context.cpp, nntrainer/layers/acti_func.cpp, nntrainer/layers/attention_layer.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/meson.build, nntrainer/layers/mol_attention_layer.cpp, nntrainer/layers/mol_attention_layer.h, nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/unittest/layers/meson.build, test/unittest/layers/unittest_layers_mol_attention.cpp, test/unittest/models/models_test_utils.cpp, test/unittest/unittest_nntrainer_models.cpp
- This patch prepares scaffolding for MoL Attention Layer.
Attention layer has also been updated for MoLAttentionLayer to extend
AttentionLayer.
- This patch provides support for all the properties required for MoL
attention layer.
- This patch provides the forwarding implementation for the mol attention
layer. New underlying requirements have been added with this which
requires more tensor operations to support strided operations like
softmax which will be supported soon.
- add basic validation unittests + forwarding fix for mol
attention layer.
Further a validation test for mol layer is also added for larger size,
and nntrainer model is fixed to support multiple inputs.
- Add support for batched dot operaiton. Provide cleanup for both the
attention layers.\
Signed-off-by: Parichay …
=> [layer] Support MoL attention layer forwarding

debian/nntrainer-dev.install, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/meson.build, packaging/nntrainer.spec
<details><summary>[Dev] Expose app context header</summary><br />
This patch exposes app context header to make custom layer deployable.
Please note that this is a temporary measure and we might want to use
diffrent abstraction for this.
</details>
<details><summary>[Header] Remove nntrainer_log.h from app_context.h</summary><br />
This patch removes nntrainer_log.h from app_context.h and implement
additional safecheck
</details>
=> [Dev] Expose app context header

Applications/Resnet/jni/cifar_dataloader.cpp, nntrainer/tensor/manager.cpp, nntrainer/tensor/tensor_pool.cpp, test/unittest/unittest_nntrainer_tensor_pool.cpp
There were bugs releate with,
. Tensor_pool try to allocate even if there is no need
. Resnet in RandomData generate batch size data
=> [ Fix ] bug fixes in tensor_pool and resnet

nntrainer/layers/grucell.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/lstm.cpp, nntrainer/layers/lstmcell.cpp, nntrainer/layers/rnncell.cpp
<details><summary>[Tensor Sharing] Make tensor sharing private by default</summary><br />
Add a boolean to tell sharing should be enabled or not for a certian
`requestTensor()`. If this value is off, it means make tensor should be
only used inside the certain tensor (like a local variable) and not
shared.
</details>
=> [Tensor Sharing] Make tensor sharing private by default

nntrainer/graph/network_graph.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/grucell.cpp, nntrainer/layers/layer_node.cpp, nntrainer/layers/lstmcell.cpp, nntrainer/layers/rnncell.cpp, nntrainer/models/neuralnet.cpp
<details><summary>[Fix] Setting batch after finalize/initialize</summary><br />
This patch delays setting batch after finalize/initialize.
Setting batch must be done after runcontext has made, the reason is that
we have semantics that finalize should be independent of batch size, but
if batch size is set before output_dims batch must be set according to
input_dims batch, which is not desirable.
</details>
=> [Fix] Setting batch after finalize/initialize

nntrainer/layers/mol_attention_layer.cpp
<details><summary>[Fix] Add dstate to mol attention batch</summary><br />
This patch fixes that dstate does not have the batch size updated
</details>
=> [Fix] Add dstate to mol attention batch

nntrainer/compiler/recurrent_realizer.cpp, nntrainer/compiler/recurrent_realizer.h, nntrainer/layers/common_properties.h, test/unittest/compiler/unittest_realizer.cpp, test/unittest/models/unittest_models_recurrent.cpp, test/unittest/unittest_nntrainer_models.cpp
<details><summary>[Clean] Prepare remap realizer for further changes</summary><br />
This patch add comments and terms(idx -> time_idx) inside remap realizer
to prepare further changes
</details>
<details><summary>[Test] Update multiout support specification</summary><br />
This patch updates multiout support specification.
Patch planned: 1. support return sequence with layer name
2. support multiple input, output layers
3. support multiple input, output connections …
=> [Recurrent] Support connection for recurrents

test/unittest/models/unittest_models_recurrent.cpp
- Fix broken zoneout lstmcell unittest
=> [hotfix] Enable zoneout lstmcell unittest

.gitignore, nntrainer/compiler/activation_realizer.cpp, nntrainer/compiler/recurrent_realizer.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/embedding.cpp, nntrainer/layers/embedding.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/mol_attention_layer.cpp, nntrainer/layers/mol_attention_layer.h, nntrainer/layers/zoneout_lstmcell.cpp, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/tensor.cpp, test/input_gen/recorder_v2.py, test/input_gen/transLayer_v2.py, test/unittest/compiler/unittest_realizer.cpp, test/unittest/models/unittest_models_recurrent.cpp
- concat to not loop over all inputs multiple times.
- gradient accumulation
- support only 1 output in case state update is not used
- bug fix in backwarding
- activation to work out of place
- Bug fix for activaiton realizer to find the realizer where the layer is
looping to itself with name change.
TODO: also do for flatten and other realizers which modified the graph
in similar fashion.
- zoneout lstm bug fix for handling the scenario where mask rate is set to
zero for either hidden or cell.
- Undo earlier changes due to bug in them.
The changes will be proposed again with more unittests.
The changes have been commented for now.
- Add clip gradient norm property for the the model as a simple interface
to set for all the layers.
- support recorder to read data from file than always …
=> [all] Mixed commits for fixes

nntrainer/layers/common_properties.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/layer_impl.cpp, nntrainer/layers/layer_impl.h, nntrainer/utils/node_exporter.cpp, nntrainer/utils/node_exporter.h
- Add disable bias property for the layer impl class.
- This patch enables disable bias for fully connected and convolution layer.
Support for disable bias in other classes extending layer impl class will be done later.
See Also #1769
=> [layer] Support disable bias for fc and conv

nntrainer/tensor/manager.cpp, test/unittest/models/models_test_utils.cpp, test/unittest/models/models_test_utils.h, test/unittest/unittest_nntrainer_models.cpp
This patch removes activation input exec order from backwarding as input
of the activation layer is not used in the backwarding.
This leads to change in the unittests as we cannot check all the
outputs, especially close to the end of the model. So, with optimization
enabled, only the output layer's forwarding is checked.
Resolves #1725
=> [manager] Remove activation input exec order from backwarding

nntrainer/layers/attention_layer.cpp, nntrainer/layers/bn_layer.cpp, nntrainer/layers/centroid_knn.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/conv1d_layer.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/layers/embedding.cpp, nntrainer/layers/fc_layer.cpp, nntrainer/layers/fc_layer.h, nntrainer/layers/gru.cpp, nntrainer/layers/grucell.cpp, nntrainer/layers/lstm.cpp, nntrainer/layers/lstmcell.cpp, nntrainer/layers/lstmcell_core.cpp, nntrainer/layers/mol_attention_layer.cpp, nntrainer/layers/rnn.cpp, nntrainer/layers/rnncell.cpp, nntrainer/layers/zoneout_lstmcell.cpp
Bug fix for array initializer storing the indices of the requested
weight so that accessing weights not requested always causes error.
resolves #1773
=> [layer] bug fix for array initializer

nntrainer/layers/loss/mse_loss_layer.cpp
- reduce memory usage for mse forwarding.
- optimize mse backwarding calculation by merging multiple and divide into
a single call.
- optimize mse layer to use scaled l2norm instead of manually calculating
the l2norm.
=> [layer] mse layer optimize for memory and compute

nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, nntrainer/utils/util_func.cpp, nntrainer/utils/util_func.h, test/unittest/unittest_util_func.cpp
<details><summary>[Trivial] Tensor save changes /ofstream/ostream</summary><br />
There is no reason to limit saving to ofstream. Thus it is changed to
ostream
</details>
=> [Trivial] Tensor save changes /ofstream/ostream

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h
optimizer is requesting variables for non-trainable weights, but it
should not.
This patch provides the corresponding fix.
Resolves #1806
=> [optimizer] no request vars for non-trainable weights

nntrainer/graph/network_graph.cpp
<details><summary>[Graph] set trainable only if trainable</summary><br />
This patch fixes bug that needsCalcGradient is set true when it
shouldn't be
</details>
=> [Graph] set trainable only if trainable

debian/nnstreamer-nntrainer.install, meson_options.txt, nnstreamer/tensor_filter/meson.build, packaging/nntrainer.spec
<details><summary>[Spec] Change nntrainer install dir</summary><br />
This patch change nntrainer install dir to /usr/prefix/*,
see also https://github.com/nnstreamer/nnstreamer/issues/3560
</details>
=> [Spec] Change nntrainer install dir

nntrainer/layers/concat_layer.cpp, nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_context.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/layers/mol_attention_layer.cpp, nntrainer/layers/multiout_layer.cpp, nntrainer/layers/split_layer.cpp, nntrainer/layers/time_dist.cpp, test/unittest/layers/layers_dependent_common_tests.cpp, test/unittest/layers/layers_standalone_common_tests.cpp
<details><summary>[Semantics] InitContext NumOutput is hint</summary><br />
This patch changes init context num output to be a hint how many outputs
has to be allocated. Layers may or may not depend on this information.
What Layer must gaurantee is that number of acutal outputs must be
bigger than the init context num output requested, this fixes dangling,
unused variable issue
</details>
resolves #1797
=> [Semantics] InitContext NumOutput is hint

nntrainer/compiler/input_realizer.cpp, nntrainer/compiler/input_realizer.h, nntrainer/compiler/recurrent_realizer.cpp, nntrainer/compiler/recurrent_realizer.h, nntrainer/compiler/slice_realizer.cpp, nntrainer/compiler/slice_realizer.h, nntrainer/graph/connection.h, nntrainer/layers/common_properties.h, nntrainer/models/neuralnet.cpp, test/unittest/compiler/unittest_realizer.cpp
<details><summary>[Realizer] Change slice realizer to get connection</summary><br />
This patch change slice realizer to get connection
</details>
<details><summary>[Realizer] Change input connection semantics</summary><br />
Input connection semantic changed to be more intuitive by mapping
connection one to one
</details>
<details><summary>[RecurrentRealizer] Modify to have connection</summary><br />
This patch modifies recurrent realizer to have connetion
**Self …
=> [RecurrentRealizer] Modify to have connection

nntrainer/compiler/recurrent_realizer.cpp, nntrainer/compiler/recurrent_realizer.h, test/unittest/compiler/unittest_realizer.cpp, test/unittest/unittest_nntrainer_models.cpp
<details><summary>[Recurrent] Support connection for as_sequence</summary><br />
This patch enables recurrent realizer to consume support connection
residing in as_sequence parameter
</details>
=> [Recurrent] Support connection for as_sequence

nntrainer/compiler/recurrent_realizer.cpp, nntrainer/compiler/recurrent_realizer.h, nntrainer/graph/network_graph.cpp, nntrainer/layers/common_properties.h, test/unittest/compiler/unittest_realizer.cpp
<details><summary>[Recurrent] Add input seqeuncing mechanism</summary><br />
As some kind of recurrent model requires input layer it self to be
changed along the sequence, this patch proposes a simple mechanism to
add time stamp suffix for the input layers as well
</details>
=> [Recurrent] Add input seqeuncing mechanism

Applications/utils/mem_usage.sh, nntrainer/layers/layer_context.cpp
When we turn on the inPlaceOptimization, it will fail if we have
mulitiple inputs: input layer ( can be inplace operatation ), normal
layers. Then, we are not allocate the grad between input layer and
this layer and it cause the error during calcDeriviate which requires
the grad tensor of input layer.
This patch fix this temporally by creating tensor buffer it reqruies.
and it includes modification of mem_check script to generate proper
output.
=> [ Network Graph ] Temporal Fix in getInputGrad

jni/Android.mk.in, jni/meson.build
<details><summary>[Android] Delegate option control to android.mk</summary><br />
This patch delegates option control in android mk to meson for debug and
optimized build
</details>
=> [Android] Delegate option control to android.mk

Applications/KNN/jni/main_sample.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main.cpp, nntrainer/layers/layer_context.cpp, nntrainer/layers/tflite_layer.h, test/unittest/compiler/unittest_interpreter.cpp
<details><summary>[manager] Separate backwarding -> grad, deriv</summary><br />
This patch separate backwaring to grad and deriv for the requestTensors
</details>
<details><summary>[compat] remove contrib from tf headers</summary><br />
This patch remove contrib path from tflite headers as contrib headers is
being removed.
</details>
=> [compat] remove contrib from tf headers @open sesame 01/18 18:09

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/tensor/manager.cpp, nntrainer/tensor/manager.h, nntrainer/tensor/tensor_pool.cpp, nntrainer/tensor/tensor_pool.h, nntrainer/tensor/tensor_wrap_specs.h
<details><summary>[Network Graph] Split max_exec_order</summary><br />
This patch split max_exec_order to three part.
1. graph_exec_end: graph execution end
2. backward_iter_end: end node of backward operation
3. forward_iter_end: end node of the forward operation
</details>
<details><summary>[ExecOrder] Add exec order control and fix inference</summary><br />
This patch add exec order control and reduce memory overhead of saving
inference result
exec order cotrol has two part
1. Additional exec order. This enable graph to add some exec order.
2. Expose bit. This enables request to be visible after the end of the
execution. …
=> [Tensor Pool] Add expose/persist concept

nntrainer/compiler/flatten_realizer.cpp, test/unittest/compiler/unittest_realizer.cpp
<details><summary>[Fix] Flatten realizer to maintain original name</summary><br />
This patch changes flatten realizer to maintain original node name.
Please see the included test patch to get the concept.
</details>
=> [Fix] Flatten realizer to maintain original name

nntrainer/layers/bn_layer.cpp, nntrainer/layers/bn_layer.h
Enable weight decay for batch normalization.
=> [weight-decay] Enable for batch normalization

nntrainer/layers/common_properties.h, nntrainer/optimizers/lr_scheduler.h, nntrainer/optimizers/lr_scheduler_constant.cpp, nntrainer/optimizers/lr_scheduler_constant.h, nntrainer/optimizers/lr_scheduler_exponential.cpp, nntrainer/optimizers/lr_scheduler_exponential.h, nntrainer/optimizers/meson.build, nntrainer/optimizers/optimizer_impl.cpp, nntrainer/optimizers/optimizer_impl.h
- Move declaration and definition of learning rate related properties out
to common properties from optimizer_impl class.
- Add interface for the learning rate scheduler which all learning rate
schedulers must abide by.
- Support constant learning rate scheduler.
- Support exponential decay learning rate scheduler with decay rate and
decay steps are the controllable properties.
See Also #1776
=> [learning-rate-scheduler] New interface for learning rate scheduler 

nntrainer/layers/layer_node.cpp, nntrainer/models/neuralnet.cpp
In this PR, Load and save is updated for the adam optimizer variables.
In order to do it, optimizer load twice, one for the weight, and one
for the optimizer variables.
- Added TOC generator for README.md
Resolves:
=> [Load/Save] Update to load and save the adam momentum variables

nntrainer/models/neuralnet.cpp, nntrainer/tensor/weight.h
- weight decay should be applied before calling the optimizer
this was not detected earlier as it was tested with sgd
- Enable weighte regularization and decay with weiht clipping.
=> Weight decay fix

jni/Android.mk, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/optimizers/lr_scheduler.h, nntrainer/optimizers/lr_scheduler_constant.h, test/unittest/meson.build, test/unittest/unittest_nntrainer_lr_scheduler.cpp
- register learning rate scheduler with the app context and regiter its
type factories.
- Add unittests for the constant and exponential learning rate schedulers.
See Also #1776
=> Register learning rate schedulers with app_context and unittests

test/tizen_capi/unittest_tizen_capi.cpp
Update capi test to include an example where batchsize is set at the
training time and not at compile time.
=> [capi/test] Example of batchsize set at train

debian/nntrainer-dev.install, nntrainer/optimizers/meson.build, packaging/nntrainer.spec
For the dependency of apt_context.h, we need to install lr_scheduler.h
in install include directory.
=> [ BUILD ] add lr_scheduler.h in include dir

nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/neuralnet.cpp, nntrainer/optimizers/adam.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/optimizer_devel.cpp, nntrainer/optimizers/optimizer_devel.h
In this PR,
1. new property of adam optimizer, "laod_var" is added to set loading
momentum variables
2. update the read and save binary file
using  ml::train::OptimizerType
3. update read in layer_node to skip the optimizer variables if
load_var is set as "false"
4. is_laod_var() is added in optimizer_devel
=> Load Optimizer Variables @open sesame 3/8 11:35

nntrainer/layers/layer_context.cpp, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, nntrainer/tensor/manager.cpp
<details><summary>Change loading meta information behavior</summary><br />
**Before this PR**
optimizer variable loaded from load_path every time.
Calling model->train(); in a row became unintuitive
1. model->train() load from original load path
thus iteration number roll back to the first one.
2. Same happens for the adam weight
3. model->load(); after model->initialize(); is noop
because loadedWeight becomes true
**After this PR**
1. model load from load_path only at initialize time
2. model->load is not implicitly overriden
**Additional Changes**
1. optimizer weight became part of weights. Now available after initialize()
2. Save format became coherent with load format
3. Some unused variables deleted
2. Run test: …
=> Change loading meta information behavior @open sesame 03/14 11:08

meson.build, nntrainer/tensor/memory_pool.cpp, nntrainer/tensor/tensor.h, test/unittest/layers/meson.build, test/unittest/memory/meson.build, test/unittest/memory/unittest_memory_pool.cpp
This is a series of fixes for portability with gcc-7.5 and gcc-11 in Ubuntu.
Fixes #1857
---
commit 7114500876d436ce7a5f45ad509270500b9f5350 (HEAD -> fix/1857, origin/fix/1857)
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Wed Mar 16 16:56:56 2022 +0900
Portability: unittest uninit vars.
1. gtest code has maybe-uninitialized warnings. Suppress it.
2. maybe-unitialized warning from unittest code fixed.
commit 8c2c4a831f58a672f3afa30b292dac355dca2e8d
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Wed Mar 16 16:39:44 2022 +0900
Portability: g++-11 has different std policy.
It requires stdexcept and limits for std::invalid_arguments and std::numeric_limits.
Fixes #1857
Signed-off-by: MyungJoo Ham …
=> Fix/1857: Fix portability issues.

Applications/MNIST/jni/main.cpp, Applications/ProductRatings/jni/main.cpp, Applications/Resnet/jni/main.cpp, Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp, Applications/meson.build, api/capi/include/nntrainer.h, api/capi/meson.build, api/ccapi/include/layer.h, api/ccapi/include/optimizer.h, api/meson.build, debian/rules, jni/Android.mk, jni/Android.mk.in, meson.build, meson_options.txt, nntrainer/models/neuralnet.h, nntrainer/nntrainer_error.h, packaging/nntrainer.spec, test/ccapi/meson.build, test/ccapi/unittest_ccapi.cpp, test/meson.build, test/unittest/meson.build, test/unittest/models/meson.build, test/unittest/unittest_nntrainer_modelfile.cpp
Users should be able to build nntrainer in a system without
ML-API and nnstreamer by default.
ML-API and nnstreamer dependency should only be mandated
in related systems (a few embedded systems).
Let's keep it "auto" so that most external users can forget
about nnstreamer and ML-API.
Addresses #1853
=> meson: dependency on ml-api should be optional @open sesame 03/31 17:58

api/capi/include/nntrainer-tizen-internal.h, api/capi/include/nntrainer.h, api/capi/include/nntrainer_internal.h, nntrainer/tensor/manager.cpp
This patch moves the get_layer api to public
=> [CAPI] Move getlayer api to public

api/ccapi/include/layer.h, api/nntrainer-api-common.h
- Classified enumeration as neural network, simple transformation and loass layer
- To perform TCT added newly, match position of enumeration between nntrainer-api-common.h and layer.h
1. Build test:  [X]Passed [ ]Failed [ ]Skipped
2. Run test:    [X]Passed [ ]Failed [ ]Skipped
=> [CCAPI] Rearrange enumeration of layer type

test/meson.build
This patch cp the golden data for enable-tflite-interpreter when do
meson test.
=> [ MESON ] fix bug when meson test

nntrainer/compiler/tflite_interpreter.cpp, nntrainer/compiler/tflite_opnode.cpp, nntrainer/compiler/tflite_opnode.h
This patch add getter of Flatbuffer builtin options in TfOpNodes.
More case will be added to get the builtin options.
Resolves:
=> [Exporter] move builtin options for tflite into tflite_opnode

Applications/TransferLearning/Draw_Classification/jni/meson.build
This patch disable the test when the nnstreamer is
disabled. Prerequisite of this test is nnstreamer is enabled.
=> [ TEST ] disable app draw classification if nnstreamer is disabled

nntrainer/layers/layer_node.cpp, nntrainer/models/neuralnet.cpp, test/tizen_capi/unittest_tizen_capi.cpp
Commit 1:     [neuralnet] enhance print function to print graph info
- Enhance print function in neuralnet to print layer connection
printing input tensor info is omitted.
- Enhance print function in layer_node to print layer properties
Commit 2:     [capi] added unittest for get layer
- Added 4 unittest for capi ml_train_model_get_layer
- get layer api is validate using get summary function
but this should be replace by layer getProperty(#1875)
=> [capi] added unittest for get layer

README.md, jni/prepare_ml-api.sh
Change nnstreamer CI server domain name.
nnstreamer.mooo.com -> ci.nnstreamer.ai
Signed-off-by: gichan <gichan2.jang@samsung.com>
=> [Doc] Change nnstreamer CI server domain name. @open sesame 04/20 11:04

nntrainer/compiler/bn_realizer.cpp, nntrainer/compiler/bn_realizer.h, nntrainer/compiler/meson.build
This patch includes skeleton code for bn realizer which removes the
batch normalization layer for inference
=> [ Compiler ] add batch norm layer realizer

api/capi/src/nntrainer.cpp
- Check if model is null or not before checking in ml_train_model_get_summary_util()
=> [CAPI] Add check if model is null to ml_train_model_get_summary()

nntrainer/compiler/bn_realizer.cpp, nntrainer/layers/layer_node.cpp, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/compiler/unittest_realizer.cpp
This patch completes the bn realizer for the inference.
This path is only for the inference and therefore it is supposed to 1 to
1 connection ( one input and one output for the bn layer ) in the
model graph. That means if there are multiple connections, then
multi-out layer is followed, and make sure the bn layer has 1 to 1
in/output during compilation.
=> [Wait for #1881] [ Compiler ] Implement bn realizer with test 

jni/Android.mk, nntrainer/compiler/bn_realizer.cpp, nntrainer/compiler/tflite_interpreter.cpp, nntrainer/layers/layer_node.cpp, nntrainer/optimizers/adam.h, nntrainer/optimizers/sgd.h, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/compiler/unittest_realizer.cpp
This patch removes the batch normalization layers with bn_realizer in
the GraphRepresentation for TfliteInterperter which is for the
inference.
=> [Wait for #1882] [ Interpreter ] add batch normalziation realizer @open sesame 04/26 10:37

nntrainer/compiler/bn_realizer.cpp, nntrainer/compiler/bn_realizer.h, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/compiler/unittest_realizer.cpp
This patch adds the test case for batch normalization realizer with
kind of resnet basic block which includes the multiout layer.
=> [Wait for #1883] [ TEST ] add more test cases for batch normalization realizer

test/nntrainer_test_util.cpp
This patch remove the mse loss layer in makeCompiledGraph
=> [ Unit Test ] remove mse loss layer  in makeCompiledGraph @open sesame 05/04 10:00

Applications/TransferLearning/Draw_Classification/jni/main.cpp, api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer-capi-tizen-feature-check.cpp, test/nnstreamer/test_nnstreamer_single.cpp, test/tizen_capi/unittest_tizen_capi.cpp, test/tizen_capi/unittest_tizen_capi_dataset.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp, test/unittest/unittest_nntrainer_modelfile.cpp
This patch make the set_featture_state variable compatible with tizen
ml api. It requires ml feature parameter to set and get, it fixs
accordingly.
=> [ CAPI ] change set_feature_state to compatible with tizen api

api/ccapi/include/model.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h
Commit 1: [model] support stop training
- During the training the function will check every epoch to decide stop
the training or not.
Commit 2: [model] added getter for current epoch_idx
- Through this function user can get epoch_idx
Commit 3:  [neuralnet] set epoch_idx to zero only if train from scratch
- Until now, the epoch property had a meaning of how many epoch to run,
but from now it will have a meaning of final epochs to run
=> [model] add callback in train @open sesame 05/06 15:07

api/ccapi/include/layer.h, api/ccapi/include/model.h, api/ccapi/src/factory.cpp, nntrainer/graph/graph_core.h, nntrainer/layers/layer_node.cpp, nntrainer/layers/layer_node.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h, test/ccapi/unittest_ccapi.cpp, test/tizen_capi/unittest_tizen_capi.cpp
This patch enables the API for the copy model configuration and
get/set Weight Tensor data with vector of float pointer.
sementics of this APIs are:
. copyConfigurarion(ml::train::Model &from)
. std::vector<float*> getWeights()
. void setWeights(const std::vector<float*>)
This is only copy the model configuration, it reauires the compile and
initialization before train.
=> [ CCAPI ] add copy model configuration & get/set Weight of layer @open sesame 05/06 15:07

nntrainer/compiler/loss_realizer.cpp, nntrainer/compiler/loss_realizer.h, nntrainer/compiler/meson.build, test/include/nntrainer_test_util.h, test/nntrainer_test_util.cpp, test/unittest/compiler/unittest_realizer.cpp
This patch includes loss realizer implementation and tests which removes the loss layer for exports.
Related: #1879 
Signed-off-by: seongwoo <mhs4670go@naver.com>
=> [ Compiler ] add loss layer realizer

nntrainer/layers/flatten_layer.cpp, nntrainer/layers/reshape_layer.cpp, nntrainer/layers/reshape_layer.h
This patch makes a flatten layer consider target_shape and use it during exporting.
FYI, flatten layer exports to `Reshape` operator in tflite. That is why the flatten layer needs to know about target shape.
Related: #1879 
Signed-off-by: seongwoo <mhs4670go@naver.com>
=> [layers] flatten layer consider target_shape

api/ccapi/meson.build, debian/ccapi-ml-training-dev.install, packaging/nntrainer.spec
- Newly created common header file was missing in meson build
=> [ccapi] include common header in meson

api/ccapi/include/model.h, nntrainer/models/neuralnet.h
<details>
<summary> [ccapi/nntrainer] Add getters for compiled, initialized and loadedFromConfig </summary>
1. Added getter for a `nntrainer::NeuralNetwork::compiled` variable.
2. Added getter for a `nntrainer::NeuralNetwork::initialized` variable.
3. Added getter for a `nntrainer::NeuralNetwork::loadedFromConfig` variable.
</details>
=> [ccapi/nntrainer] Add getters for `ml::train::Model` states

Applications/MNIST/jni/main.cpp, meson.build, nntrainer/graph/network_graph.cpp, nntrainer/layers/layer_node.cpp, nntrainer/models/neuralnet.cpp, nntrainer/tensor/memory_pool.cpp, nntrainer/utils/profiler.cpp, nntrainer/utils/profiler.h, test/meson.build, test/unittest/unittest_nntrainer_profiler.cpp
This patch implement memory profiling feature.
Profile is refactored to handle memory statics information.
Unnecessary dependency from ProfileListener to Profile
class is removed, and inner information is redesigned to handle
both time and memory profiling.
For the memory profile, below infomation is managed:
event: ALLOC | DEALLOC
current size: total allocated memory size
info: user friendly tag for the analysis
duration: time interval between alloc and dealloc
=> [Utils] Add Memory profile feature to Profiler

api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, nntrainer/utils/node_exporter.h, nntrainer/utils/util_func.cpp, test/tizen_capi/unittest_tizen_capi.cpp
[CAPI] Add internal API for C# DllImport
- ml_train_model_compile() and  ml_train_model_run() has a va_list and this is a problem with DllImport in C#, va_list must be passed dynamically for each architect, this is not guaranteed to work for some architects. so C# will pass the model compile params as a single string
=> [CAPI] Add ml_train_model_compile_with_params() internally for C# DllImport

nntrainer/tensor/tensor.cpp, test/unittest/unittest_nntrainer_tensor.cpp
This patch removes the limitaion of rank 2 for dot op.
It expectes to compute with 4D tensor as 2D with [BxCxH, W]
dimension.
=> [ Tensor ] remove rank 2 limitation for dot op

packaging/nntrainer.spec
The compiler module always uses flatc command but 'flatbuffers-devel'
dependency is added in case of the Tizen version is lower than 6.5.
Because of this reason, the buildbreak issue occurs when building for
Tizen 7.0. This patch fixes this bug.
=> [Spec] Add flatbuffers-devel BuildRequires as default

api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, test/tizen_capi/unittest_tizen_capi_layer.cpp
* N/A
<details><summary>[CAPI]Modify model_compile_with_single_param() and ml_train_model_run_with_single_param() </summary></br>
Modified the internal APIs created as a C# va_list issue since capi can receive
single string in the form "key=value | key=value" and all objects have loadProperties
in setProperty which can split it with '|'.
so, the original code was reverted and added new code related call capi directly.
</details>
<details><summary>[CAPI] Add ml_train_layer_set_property_with_single_param() internally for C# DllImport </summary></br>
ml_train_layer_set_property() has a va_list and this is a problem with …
=> [CAPI] Add ml_train_layer_set_property_with_single_param() internally

api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, test/tizen_capi/unittest_tizen_capi_optimizer.cpp
*N/A
<details><summary> [CAPI] Add set property with single param for optimizer</summary><br/>
Add ml_train_optimizer_set_property_with_single_param().
ml_train_optimizer_set_property() has a va_list and this is a problem with DllImport in C#.
va_list must be passed dynamically for each architect, this is not guaranteed to
work for some architects. This api receive param as a single string from C# DllImport.
</details>
<details><summary>[TEST] Add unittest related to setProperty for optimizer</summary><br/>
- Add unittest for ml_train_optimizer_set_property_with_single_param()
1. Build test:   [X]Passed …
=> [CAPI] Add set property with single param for optimizer

jni/meson.build, meson.build
This patch fix the wrong size of nntrainer library, libnntrainer.so,
when using the android build script.
- change the ndk-build options with NDK_LIBS_OUT
=> [ BUILD ] fix binary size of libnntrainer with android build script @open sesame 06/22 21:21

api/capi/include/nntrainer_internal.h, api/capi/src/nntrainer.cpp, test/tizen_capi/unittest_tizen_capi_dataset.cpp
*N/A
<details><summary>[CAPI] Add set property with single param for dataset</summary></br>
Add ml_train_dataset_set_property_for_mode_with_single_param().
ml_train_dataset_set_property_for_mode() has a va_list and this is a problem with DllImport in C#.
va_list must be passed dynamically for each architect, this is not guaranteed to
work for some architects. This api receive param as a single string from C# DllImport.
</details>
<details><summary>[TEST] Add unittest related to setProperty for dataset</summary></br>
Add unittest for ml_train_dataset_set_property_for_mode_with_single_param()
1. Build …
=> [CAPI] Add set property with single param for dataset

meson.build, test/unittest/meson.build
google mock API is changed from 1.10.0,
and it does not support MOCK_METHOD under 1.10.0 version.
'profiler' test is only enabled for proper gmock.
=> [BUILD] fix supported gmock version

debian/nntrainer-dev.install, jni/Android.mk, meson.build, meson_options.txt, nntrainer/dataset/func_data_producer.cpp, nntrainer/dataset/func_data_producer.h, nntrainer/layers/common_properties.cpp, nntrainer/layers/common_properties.h, nntrainer/layers/conv2d_layer.cpp, nntrainer/utils/meson.build, nntrainer/utils/nntr_threads.cpp, nntrainer/utils/nntr_threads.h, packaging/nntrainer.spec
```.This patch demostrate the batch direction parallelization with conv2d
calcDerivatives.
. add the meson option with 'nntr-num-threads' key and int value.
. add extra compile option, NNTR_NUM_THREADS ( default value is 1 )
```
```
.This patch includes the NNTrThreads Features. This will be used for the
Multi-Thread Feature of nntrainer, such as Thread Pool, for loop
multi-threading along batch direction.
```
=> [ Layer ] Parallelization along batch direction @open sesame 07/12 13:23

nntrainer/layers/acti_func.cpp, nntrainer/layers/conv2d_layer.cpp, nntrainer/utils/nntr_threads.cpp, nntrainer/utils/nntr_threads.h
```
. This patch includes multi-threading for gradient computation of conv2d
layer.
```
```
This patch improves the computation of tanh.
Rather than calling tanh fuction, it is faster when
sigmoid is used.
tanh(x) = 2.0*sigmoid(2.0*x) -1.0;
```
=> [Wait for #1954][ Layer ] Conv2d Gradient Computation with Multi-Threads @open sesame 08/01 07:49

Applications/Resnet/res/resnet18.ini
SPDX-License_Identifier --> SPDX-License-Identifier
Added one more # to the first line for doxygen.
=> Fix inappropriate SPDX license tag

nntrainer/models/neuralnet.cpp
- Assume that stop_cb immediately called so reduce current epoch_idx by 1
=> [neuralnet] adjust epoch_idx when stop_cb is called

Applications/utils/mem_usage.sh
Sometimes, cpu frequency check is required.
This patch includes the cpu frequency logging in mem_usage.sh
=> [ UTIL ] add frequency data in mem_usage.sh

nntrainer/layers/common_properties.cpp
[Property] Remove if-else statement in DroupOutRate::isValid()
- Remove if-else statement
Signed-off-by: hyunil park <hyunil46.park@samsung.com>
=> [Property] Remove if-else statement in DroupOutRate::isValid()

test/unittest/datasets/data_producer_common_tests.cpp, test/unittest/datasets/unittest_databuffer.cpp, test/unittest/layers/unittest_layer_node.cpp, test/unittest/memory/unittest_memory_pool.cpp, test/unittest/unittest_nntrainer_modelfile.cpp, test/unittest/unittest_nntrainer_tensor_pool.cpp
Commit 1:     [unittest] rename negative testcase name to _n place at the end
- Since the indicator _p/_n is at the middle of testcase name all of test cases
are regarded as positive testcases(default). So place indicator at the end.
- Added '_' right before 'n' to indicate negative testcase.
Commit 2:     [unittest] added negative testcase
- Added negative testcase
=> [unittest] add negative unittest

debian/changelog, meson.build, packaging/nntrainer.spec
=> [Release] NNTrainer 0.4.0 Release

nntrainer/tensor/tensor.cpp, nntrainer/tensor/tensor.h, test/ccapi/unittest_ccapi.cpp, test/unittest/unittest_util_func.cpp
- Remove noexcept in copy function cause it throws when data is non contiguous
- Initialize char array
- Delete array not element("[]" was missing)
=> [trivial] fix ahub issues

debian/rules
Sometimes, debuild has errors with dh_clean:
```
dh_clean: error: find .  \( \( \
\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
\( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
-o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
-o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
-o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
\) -exec rm -f {} + \) -o \
\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \) returned exit code 1
make: *** [debian/rules:28: clean] Error 25
```
Override dh_clean to avoid this.
=> debian: fix occasional debuild error

nntrainer/graph/network_graph.cpp, nntrainer/graph/network_graph.h, nntrainer/models/neuralnet.cpp, nntrainer/models/neuralnet.h
- Check stop_cb before doing forwarding/calcGrading/calcDerivative by every layer to stop training more quickly.
=> [neuralnet] check stop_cb by every layer

README.md
Fixed the typo error in the title of the paper bellow.
- NNTrainer: Light-Weight On-Device Training Framework, arXiv, 2022
Signed-off-by: seungbaek <sb92.hong@samsung.com>
=> [README] Fix typo error in README

docs/getting-started.md
Fix the typo error in getting-started.md file.
Signed-off-by: Seungbaek Hong <sb92.hong@samsung.net>
=> Fix typo error

meson.build, meson_options.txt, nntrainer.ini.in, nntrainer/app_context.cpp, nntrainer/app_context.h, nntrainer/models/model_loader.cpp, nntrainer/models/model_loader.h, nntrainer/models/neuralnet.cpp
This patch is for app properties propergation.
App properties is described in global configuration file (ini),
and the properties are under section, which only have a meaning for
human readability. It means section deos not have any real role for
behavior. Propergated properties can be used in anywhere in the network.
In this patch include 'memmory_swap' and 'memory_swap_path' which is
used for Model flex properties.
=> [Context] Propergate properties to model @open sesame 10/25 13:37

nntrainer/tensor/tensor.cpp
- Omit of default delete of shared_ptr<MemoryData> causes memory leak.
=> [tensor] Add default delete on tensor map

nntrainer/compiler/tflite_interpreter.cpp, nntrainer/compiler/tflite_opnode.cpp, nntrainer/utils/node_exporter.cpp
- Add `is_virtual` to default constructor of `TfOpNode` in tflite_opnode.cpp
- Add `fbb` to default constructor of `Exporter` in node_exporter.cpp
- Add a conditional statement to work only if the `result of find_if()` is not the end of the iterator
to solve the `INVALIDATE_ITERATOR` issue in tflite_interpreter.cpp
=> [Trivial] Fix svace and coverity issue

nntrainer/nntrainer_logger.cpp
[Logger] Modify initialization error message of logger instance
- Runtime error occurs when an app is executed in a place other
than the home directory excepted Android and Tizen
- Currently, Android and Tizen don't make logger
- If an user runs an app using nntrainer in a place where
the logger cannot be initialized, the path is shown for help
- In case of Ubunut, logger unable to initialize on '/usr/bin/',
/usr/lib/' and etc
Signed-off-by: hyunil park <hyunil46.park@samsung.com>
=> [Logger] Modify initialization error message of logger instance
