Applications/meson.build
nntrainer/graph/network_graph.cpp
nntrainer/layers/tflite_layer.cpp
nntrainer/layers/tflite_layer.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_split.cpp
test/unittest/layers/unittest_layers_tflite.cpp

Enable draw classification application.
Corresponding bug fixes are also added.
Enabled tflite backbone layer required for this application.

[application] Enable draw classification app 

---

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_mae_loss_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_test.cpp
Applications/Custom/LayerPlugin/meson.build
Applications/Custom/mae_loss.cpp
Applications/Custom/mae_loss.h
Applications/Custom/meson.build
Applications/Custom/pow.cpp
Applications/Custom/pow.h
Applications/meson.build
nntrainer/app_context.cpp
nntrainer/app_context.h
nntrainer/layers/plugged_layer.h
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/layers/meson.build

Update plugged layer for V2 design.
The corresponding updates in app_context have also been made.
Enable custom application for v2 layer design.
This also includes updating the power layer and mae loss layer implementation
with layerv2 and updating their corresponding unittests.

[application] Enable custom application

---

debian/nntrainer-dev.install
nntrainer/layers/meson.build
packaging/nntrainer.spec

- [devel] Add layer_devel to devel
```
Add layer_devel to devel, without this, build fails with upstream/main
build
```

[devel] Add layer_devel/context to devel

---

nntrainer/layers/layer_node.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

[unittest] Enable backbone unittests 

---

nntrainer/layers/nnstreamer_layer.cpp
nntrainer/layers/nnstreamer_layer.h
nntrainer/layers/permute_layer.cpp
nntrainer/layers/permute_layer.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_nnstreamer.cpp
test/unittest/layers/unittest_layers_permute.cpp

Update Permute and NNStreamer Layers to LayerV2.

[layers] Update permute + nnstreamer layer to V2

---

api/capi/src/nntrainer.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp

- [Dataset/CAPI] implement dataset ctor
```
- Implement `ml_train_dataset_create()`
- Implement `ml_train_add_generator()`
- Implement `ml_train_add_file()`
- Add test as per the implementation.
```

[Dataset/CAPI] implement dataset ctor

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/dropout.cpp
nntrainer/layers/dropout.h
nntrainer/layers/meson.build

In this commit,
. implementation of DropOutLayer
Resolves:

[ Layer ] implementation of DropOut Layer

---

api/capi/src/nntrainer.cpp
nntrainer/dataset/databuffer.cpp

- Fix logical expression
- Initialize member variable

[Fix] Logical expression

---

api/capi/src/nntrainer.cpp
nntrainer/dataset/data_producers.h
test/tizen_capi/unittest_tizen_capi_dataset.cpp

**[Pending commit: #1381]**
- [Dataset] Introduce data producer
```
This patch introduces data producer which abstracts a single iteration
creator.
```

[Wait for #1381] [Dataset] Introduce data producer

---

nntrainer/dataset/data_producers.h
nntrainer/dataset/meson.build
nntrainer/dataset/random_data_producers.cpp
nntrainer/dataset/random_data_producers.h

- [Dataset] Add random producer
```
Add onehot random producer which generatese a fake data
```

[Dataset] Add random producer

---

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
nntrainer/dataset/random_data_producers.cpp
test/unittest/layers/layers_dependent_common_tests.cpp
test/unittest/layers/layers_standalone_common_tests.cpp
test/unittest/unittest_nntrainer_models.cpp

. compilation error fix : unused + wrong type comparison

[ TEST ] fix compilation error

---

jni/Android.mk
jni/prepare_openblas.sh

. Fix android build issues
: openblas link and download

[ Fix ] Fix android build error with meson @open sesame 07/26 12:11

---

Applications/TransferLearning/Draw_Classification/jni/Android.mk

- [Android] Add missing dependency
```
This patch adds mssing dependency to the android application build
```

[Android] Add missing dependency

---

nntrainer/layers/dropout.cpp
nntrainer/layers/dropout.h
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h

This commit includes :
. implementation of mask for dropout

[ RNN ] Add mask for dropout 

---

nntrainer/layers/dropout.cpp
nntrainer/layers/dropout.h
nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h

In this commit,
. drop out mask is added.
. calculation of drop out is implemented.

[Wait for #1427] [ LSTM ] Add drop out mask

---

.gitignore
Applications/TransferLearning/Draw_Classification/jni/Android.mk
jni/prepare_ml-api.sh

- [Android] Fix undefined definition
```
This patch defines ML_API_COMMON_ROOT previously undefined
```

[Android] Fix undefined definition @open sesame 07/27 13:50

---

nntrainer/layers/gru.cpp
nntrainer/layers/gru.h
nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h

This commit includes:
. Implementation of drop out mask
Resolves:

[ Wait for #1428 ] [ GRU ] Add drop out mask 

---

jni/Android.mk
nntrainer/dataset/func_data_producer.cpp
nntrainer/dataset/func_data_producer.h
nntrainer/dataset/meson.build
nntrainer/dataset/random_data_producers.cpp
test/unittest/datasets/data_producer_common_tests.cpp
test/unittest/datasets/data_producer_common_tests.h
test/unittest/datasets/meson.build
test/unittest/datasets/unittest_func_data_producers.cpp
test/unittest/datasets/unittest_random_data_producers.cpp

- [Dataset] Add callback generator
```
This patch add callback producer to abstract generator
```

[Dataset] Add callback generator

---

api/nntrainer-api-common.h

- [CAPI] Expose layer enums
```
This patch contains layer enums to be exposed
```

[CAPI] Expose layer enums

---

Applications/Custom/LayerPlugin/layer_plugin_test.cpp
Applications/Resnet/jni/cifar_dataloader.h
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
api/ccapi/include/model.h
api/ccapi/include/tensor_dim.h
api/ccapi/meson.build
debian/ccapi-ml-training-dev.install
debian/nntrainer-dev.install
nntrainer/dataset/databuffer.h
nntrainer/dataset/random_data_producers.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/layer_context.h
nntrainer/layers/nnstreamer_layer.cpp
nntrainer/layers/split_layer.cpp
nntrainer/layers/tflite_layer.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
nntrainer/utils/base_properties.cpp
nntrainer/utils/base_properties.h
packaging/nntrainer.spec
test/tizen_capi/unittest_tizen_capi.cpp

Commit 1: 
[tensor_dim] package tensor_dim.h with ccapi
- Package tensor_dim with ccapi
- MAXDIM belongs to tensorDim class
Commit 2:
[CAPI] Implement ml_train_model_get_input|output_dims
- Implement ml_train_model_get_input_dimensions
- Implement ml_train_model_get_output_dimensions
- Make a unittest for implemented apis

[CAPI] Implement ml_train_model_get_input|output_dims

---

jni/Android.mk
nntrainer/dataset/data_producers.h
nntrainer/dataset/databuffer.h
nntrainer/dataset/func_data_producer.cpp
nntrainer/dataset/func_data_producer.h
nntrainer/dataset/meson.build
nntrainer/dataset/random_data_producers.cpp
nntrainer/dataset/random_data_producers.h
nntrainer/dataset/raw_file_data_producer.cpp
nntrainer/dataset/raw_file_data_producer.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
test/unittest/datasets/data_producer_common_tests.cpp
test/unittest/datasets/meson.build
test/unittest/datasets/unittest_func_data_producer.cpp
test/unittest/datasets/unittest_raw_file_data_producer.cpp

- [dataset] Add file producer
```
This patch adds file producer which abstracts reading a raw file. Also,
this component makes sure that the file accepts various kind of input
shapes.
```

[dataset] Add file producer

---

nntrainer/app_context.h
nntrainer/layers/common_properties.h
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
test/ccapi/unittest_ccapi.cpp
test/meson.build
test/tizen_capi/meson.build
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_nntrainer_appcontext.cpp

This patch enables c/cc disabled tests.
Corresponding required updates in the tests are also added.
Resolves #1453

[test] Enable c/cc disabled tests @open sesame 08/02 16:31

---

api/ccapi/include/dataset.h
api/ccapi/src/factory.cpp
jni/Android.mk
nntrainer/dataset/batch_queue.cpp
nntrainer/dataset/batch_queue.h
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/databuffer.h
nntrainer/dataset/meson.build
nntrainer/models/model_loader.cpp
test/ccapi/unittest_ccapi.cpp
test/unittest/datasets/meson.build
test/unittest/datasets/unittest_batch_queue.cpp

**[Pending commit: #1405]**
- [DataSet] Refactor to use properties
```
This patch enables properties in dataset while changing signature of
dataset
```

[Wait for #1405] [DataSet] Refactor to use properties

---

Applications/VGG/jni/meson.build
api/capi/meson.build
meson.build
meson_options.txt
nntrainer/meson.build
packaging/nntrainer.spec

- Make yocto build option
- Check sysroot

[mesonbuild] update meson build

---

api/capi/include/nntrainer_internal.h
api/ccapi/include/tensor_dim.h
jni/Android.mk
nntrainer/tensor/tensor_dim.cpp

[tensordim] move implementation to source file
- header file remains without implementaion

[wait for #1430] Move implementation to source tensordim

---

debian/nntrainer-dev.install
nntrainer/graph/meson.build
nntrainer/layers/meson.build
nntrainer/meson.build
nntrainer/models/meson.build
nntrainer/optimizers/meson.build
nntrainer/tensor/meson.build
nntrainer/tensor/tensor_wrap_specs.h
nntrainer/utils/meson.build
packaging/nntrainer.spec

Update the devel packaging to remove unnecessary headers.. Below is the list of packaging update:
- weight/var_grad headers are removed
- app_context and other graph, network related headers are removed. They
can be added once network/neural network headers are refactored for
custom models.
- manager and dynamic_training_optimization header is removed
- databuffer headers are commented. They will be updated once dataset
refactoring is done.
Resolves #986

[devel/pkg] Update the devel packaging 

---

api/ccapi/include/dataset.h
api/ccapi/src/factory.cpp
nntrainer/dataset/databuffer_factory.cpp
nntrainer/dataset/databuffer_file.h
nntrainer/dataset/databuffer_func.h
nntrainer/models/model_loader.cpp
test/ccapi/unittest_ccapi.cpp

- [Dataset] Change factory signature
```
Add properties to factory, given contructor argument, it is delegated to
the constructor
Cc: Parichay Kapoor<pk.kapoor@samsung.com>
```

[Dataset] Change factory signature

---

Applications/ProductRatings/jni/main.cpp
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/databuffer_factory.cpp
nntrainer/dataset/raw_file_data_producer.cpp
nntrainer/dataset/raw_file_data_producer.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/utils/base_properties.h
test/ccapi/unittest_ccapi.cpp
test/tizen_capi/unittest_tizen_capi.cpp

- [Dataset] Adopt new datagetter to databuffer
```
**Changes Propsed in this PR**
1. Adopt new data getter to neuralnet / factory
2. Fix: bugs found in raw_file_data_producer
3. Fix: databuffer not feeding last iteration when error
```

[Dataset] Adopt new datagetter to databuffer

---

Applications/TransferLearning/Draw_Classification/jni/main.cpp
meson.build
nntrainer/app_context.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp

- [fixes] Add bug fixes from asan
```
- Fix issues from address sanitizer
- Enable deprecated-declaration warning but disable for some files
```

[fixes] Add bug fixes from asan

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h

Move manager from NeuralNetwork class to NetworkGraph class.
Some corresponding minor adjustments are also added.
See Also #1127

[graph/neuralnet] Move manager from neuralnet to netgraph 

---

Applications/VGG/jni/main.cpp
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/raw_file_data_producer.cpp
nntrainer/layers/layer_node.cpp
nntrainer/tensor/tensor.cpp

- Added try catch statement
- Check value to avoid divide by zero
- Added const keyword to match override function
- Initialize member variable in constructor

[fix] ahub issues

---

api/capi/src/nntrainer.cpp
api/ccapi/include/dataset.h
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/databuffer.h
nntrainer/dataset/func_data_producer.cpp
nntrainer/dataset/func_data_producer.h
nntrainer/utils/base_properties.h
test/unittest/unittest_base_properties.cpp

- [Dataset] Add user_data set Property handler
```
- PtrType properties
- Add user_data set property handler for backward competibility
```

[Dataset] Add user_data set Property handler

---

api/nntrainer-api-common.h

- [CAPI] Update description of ml_train_datagen_cb
```
This patch updates ml_train_datagen_cb with newly added api sets and
clarify the parameter @a last means.
```

[CAPI] Update description of ml_train_datagen_cb

---

nntrainer/dataset/random_data_producers.cpp
nntrainer/dataset/raw_file_data_producer.cpp
nntrainer/dataset/raw_file_data_producer.h
test/unittest/datasets/unittest_raw_file_data_producer.cpp

- [Dataset] Implement samplewise for file
```
- implements samplewise size(), finalize() for file
- add corresponding test
```

[Dataset] Implement samplewise for file

---

Applications/SimpleShot/meson.build
Applications/SimpleShot/task_runner.cpp
Applications/SimpleShot/test/simpleshot_layer_common_tests.cpp
api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/centroid_knn.cpp
nntrainer/layers/centroid_knn.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/meson.build

- [CAPI] Open centroid KNN
```
- Move centroid KNN to layer, delete centroid knn from the Application
Cc: Inki Dae <inki.dae@samsung.com>
```

[CAPI] Open centroid KNN

---

nntrainer/dataset/func_data_producer.cpp
nntrainer/dataset/func_data_producer.h
nntrainer/layers/split_layer.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/datasets/data_producer_common_tests.cpp
test/unittest/datasets/unittest_func_data_producer.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- [Dataset] Rework func dataset to samplewise
```
- Fix bugs in Tensor::Map
- Add shortcut for the Tensor::updateBatch
- Add func_data_producer with sample
```

[Dataset] Rework func dataset to samplewise

---

nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

- [NeuralNet] Fix testset run
```
This patch fixes testset running while cleaning up the code to reuse
repeating logics with callback
```

[NeuralNet] Fix testset run

---

Applications/Resnet/jni/cifar_dataloader.cpp
nntrainer/layers/bn_layer.cpp
nntrainer/models/neuralnet.cpp

- Bug fix for requested variable for batch norm layer.
- This patch fixes the data loader for resnet application after the
dataset loader has been changed to load data element by element than the
whole batch.
- Fix validation values reporting.
See Also #1533 #904

[resnet] Fix data loader for resnet application 

---

nntrainer/layers/bn_layer.h

This patch provides bug fix to the initialization of the batch norm
values.

[bnlayer] Batch norm layer bug fix

---

nntrainer/layers/layer_node.cpp

- [Bug] Fix support inplace for distribute Layer
```
This patch fixes support inplace for distirbute layer
Cc: Parichay Kapoor <pk.kapoor@samsung.com>
```

[Bug] Fix support inplace for distribute Layer

---

nntrainer/dataset/data_producer.h
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/databuffer.h
nntrainer/dataset/func_data_producer.cpp
nntrainer/dataset/func_data_producer.h
nntrainer/dataset/raw_file_data_producer.cpp
nntrainer/dataset/raw_file_data_producer.h
nntrainer/graph/network_graph.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/activation_layer.cpp
nntrainer/layers/activation_layer.h
nntrainer/layers/centroid_knn.h
nntrainer/layers/common_properties.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/model_loader.cpp
nntrainer/models/neuralnet.cpp
nntrainer/utils/base_properties.h
test/ccapi/unittest_ccapi.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp

**[Pending commit: #1549]**
- [Test] Add save load test
```
Add save load test while adding options to model test
```

[with #1549] [Test] Add save load test

---

Applications/Custom/LayerPlugin/meson.build
Applications/SimpleShot/test/meson.build
debian/control
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/preprocess_flip_layer.cpp
nntrainer/layers/preprocess_translate_layer.cpp
packaging/nntrainer.spec
test/meson.build
test/unittest/layers/layers_common_tests.h
test/unittest/layers/layers_standalone_common_tests.cpp
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_preprocess_flip.cpp
test/unittest/layers/unittest_layers_preprocess_translate.cpp
test/unittest/layers/unittest_layers_split.cpp
test/unittest/memory/meson.build

- [Fix] Fix semantic tests were not running
```
This patch fixes semantic tests were not running
```

[Fix] Fix semantic tests were not running

---

Applications/Custom/LayerPlugin/layer_plugin_common_test.h
nntrainer/compiler/ini_interpreter.cpp
nntrainer/compiler/ini_interpreter.h
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp
nntrainer/compiler/tflite_opnode.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/pooling2d_layer.cpp
nntrainer/models/model_loader.cpp
nntrainer/models/neuralnet.cpp
nntrainer/utils/ini_wrapper.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
test/tizen_capi/unittest_tizen_capi_layer.cpp
test/unittest/compiler/meson.build
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/layers/layers_standalone_common_tests.cpp
test/unittest/unittest_base_properties.cpp

- [Interpreter] Enable tests
```
Interpreter test was not running, this patch enables interpreter tests
```

[Interpreter] Enable tests

---

nntrainer/layers/bn_layer.h
nntrainer/layers/flatten_layer.h
nntrainer/layers/pooling2d_layer.cpp

This patch adds bug fixes for layers:
- bn layer support in-place is corrected.
- flatten layer support in-place is corrected.
- pooling layer padding related corrections.

[layer] Bug fixes for layers

---

test/unittest/unittest_nntrainer_models.cpp

This patch fixes the matching for the last layer of each model for the
unittest of the models.
See also #1562

[unittest/models] Fix matching for models unittest

---

.gitignore

Update gitignore to ignore the following files:
- data files for applications
- log files

[gitignore] Update gitignore

---

debian/changelog
meson.build
packaging/nntrainer.spec

[ Release ] NNTrainer 0.3.0 Release

---

Applications/MNIST/jni/main.cpp
nntrainer/graph/network_graph.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h

- [Profiler] Enable profiler with fine grained profile
```
This patch enables profiler with layer profiling.
```
resolves #1573

[Profiler] Enable profiler with fine grained profile

---

test/unittest/layers/layers_common_tests.h
test/unittest/layers/layers_golden_tests.cpp
test/unittest/layers/unittest_layers_batch_normalization.cpp
test/unittest/layers/unittest_layers_fully_connected.cpp

<details><summary>[Test] Add bn layer inference test</summary><br />
- bn layer inference mode test
- add option to skip backwarding golden test
</details>

[Test] Add bn layer inference test

---

test/unittest/datasets/data_producer_common_tests.cpp

<details><summary>[Dataset/test] Update batch before creating tensor</summary><br />
Dataset sample creating now creates a tensor after updating batch to one
resolves #1604
</details>

[Dataset/test] Update batch before creating tensor

---

README.md

This patch includes readme update.

[ README ] update readme

---

jni/meson.build
meson.build

<details><summary>[meson] Add android tflite disable option</summary><br />
This patch add android tflite disable option
</details>

[meson] Add android tflite disable option

---

README.md

fix typo & add link for cc APIs

[ README ] fix typo & add link for cc APIs

---

nntrainer/tensor/tensor_pool.cpp

<details><summary>[tp] Implement reidentifySource()</summary><br />
This patch implements reidentifySource(). Test will be followed
</details>

[tp] Implement reidentifySource()

---

test/meson.build
test/nnstreamer/meson.build
test/nnstreamer/test_nnstreamer_single.cpp

<details><summary>[Test] Add ml singleshot example</summary><br />
This patch adds integrated test to show and test ml singleshot.
</details>

[Test] Add ml singleshot example

---

nntrainer/tensor/manager.cpp
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h
test/unittest/unittest_nntrainer_tensor_pool.cpp

<details><summary>[Tp] rename externallyAllocated -> placeholder</summary><br />
This patch renames externallyAllocated -> placeholder
</details>
<details><summary>[Tp] requestPreallocated -> view</summary><br />
This patch rename requestPreallocated to view
</details>
<details><summary>[Tp] Rename requestTensor -> request</summary><br />
This patch renames requestTensor to request
2. Run test: …

[Tp] Rename requestTensor -> request

---

api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer-capi-tizen-feature-check.cpp
test/nnstreamer/meson.build
test/nnstreamer/test_nnstreamer_single.cpp

<details><summary>[Fix] api feature check problem</summary><br />
This is an emergency measure for feature check is failing inside
unittest of gbs build.
Also enabled ml_inference test
</details>

[Fix] api feature check problem

---

nntrainer/compiler/meson.build

<details><summary>[Build] Fix fbs causing rebuilding</summary><br />
This patch fixes flatbuffer cause rebuilding.
</details>

[Build] Fix fbs causing rebuilding

---

README.md

Add SSDC2021 Presentation in README

[ README ] Add SSDC2021 presentation

---

nntrainer/tensor/tensor.cpp

This patch adds checks for contiguous tensors ensuring that operations
which don't support non-contiguous tensors throw on receiving the
non-contiguous tensors.
This is in preparation for making the concat and split layer inplace.

[tensor] Add checks for non-contiguous tensor before operations @open sesame 11/19 23:17

---

nntrainer/tensor/manager.h
nntrainer/tensor/tensor_pool.h
nntrainer/tensor/tensor_wrap_specs.h

<details><summary>[Tp] Propose new tensor spec</summary><br />
This patch proposes new tensor specification
</details>

[Tp] Propose new tensor spec

---

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
nntrainer/models/neuralnet.cpp
test/nnstreamer/test_nnstreamer_single.cpp

<details><summary>[Filter] Add dimension inference mechanism</summary><br />
This patch add dimension inference mechanism as requested.
Please refer to nnstreamer/api#105 for details
</details>
<details><summary>[Test] Add singleshot case test</summary><br />
Add singleshot test case when ml_inference get null input information
</details>

[Test] Add singleshot case test

---

nntrainer/layers/acti_func.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/unittest_nntrainer_models.cpp

<details><summary>[Add] add leaky relu to actifun</summary><br />
This patch add leaky relu to actifun, for now there is no need to add
slope parameter, this is more like a quick fix
</details>

[Add] add leaky relu to actifun

---

nntrainer/layers/layer_node.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layer_node.cpp

[test] Enable layer node test @open sesame 11/19 10:09

---

jni/Android.mk.in

This is the fix for "cannot find libomp.so"

[ Android ] add static option for openmp

---

jni/Android.mk
nntrainer/layers/loss/kld_loss_layer.cpp
nntrainer/layers/loss/kld_loss_layer.h
nntrainer/layers/loss/meson.build

<details><summary>[KLD loss] kld loss scaffolding</summary><br />
This patch add kld loss scaffolding
</details>

[KLD loss] kld loss scaffolding

---

nntrainer/compiler/multiout_realizer.cpp

<details><summary>[trivial] Add note on the freq</summary><br />
This patch add note on the frequency map
</details>

[trivial] Add note on the freq

---

test/unittest/models/meson.build
test/unittest/models/models_golden_test.cpp
test/unittest/models/models_golden_test.h
test/unittest/models/unittest_models_multiout.cpp

<details><summary>[Test] Add simple multiple inout case</summary><br />
This patch add simple multiple inout case
**Additional changes**
- model test now have options for v2
- fix bugs that save_load test was not actually loading graph
from the saved ini
</details>

[Test] Add simple multiple inout case

---

test/unittest/models/unittest_models_recurrent.cpp

[test] enable zoneout lstm test

---

api/ccapi/include/model.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

<details><summary>[API] Add layer visitor for the model</summary><br />
This patch add visitor for the model api
</details>

[API] Add layer visitor for the model

---

nntrainer/tensor/tensor_pool.cpp

If the max execution order for the tensor pool was less than the
largest execution order for a tensor in the tensor pool, then the max
execution order was being included in the execution order of that
tensor.
This patch resolves this issue for end order, as well as for the start
order.
resolves #1807

[tensor] Tensor pool request bug fix

---

Applications/Custom/mae_loss.cpp

MAE layer bug fix:
- forwarding fixed to propagate input unchanged
- backwarding updated to scale with size of the tensor

[layer] MAE layer bug fix

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/identity_layer.cpp
nntrainer/layers/identity_layer.h
nntrainer/layers/meson.build
nntrainer/layers/reduce_mean_layer.cpp
nntrainer/layers/reduce_mean_layer.h
test/unittest/models/models_test_utils.cpp
test/unittest/unittest_nntrainer_models.cpp

<details><summary>[Identity] Add identity header</summary><br />
This patch add identity layer header.
</details>
<details><summary>[Identity] Implement and connect identity layer</summary><br />
THis patch implement and connect identity layer
</details>
<details><summary>[Identity] Add identity layer test</summary><br />
This patch add identity layer test …

[Identity] Add identity layer test

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/bn_layer.cpp
nntrainer/layers/layer_context.cpp
nntrainer/layers/lstmcell.cpp
nntrainer/layers/zoneout_lstmcell.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/optimized_v1_planner.cpp

<details><summary>[Fix] Non-const reference</summary><br />
This patch fixes returning reference of local variable.
</details>
<details><summary>[Fix] BN life span</summary><br />
t_reduced is used in forward, but lifespan was in backwarding. This
patch fixes the issue
</details>
<details><summary>[Fix] change max order to point last</summary><br />
This patch fixes bug that gradient clipping was not applied correctly
when optimization is on.
1. …

[Fix] lifespans and gradient clippings

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/weight.h

Enable save / load optimizer variables such as M and V for adam
optimizer

[ SAVE/LOAD ] save / load optimizer variables

---

nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
test/input_gen/genModelsRecurrent_v2.py
test/input_gen/transLayer_v2.py
test/unittest/models/unittest_models_recurrent.cpp

[lstm] implement bidirectional lstm forward
- For now only support forward bidirectional lstm

[Wait for #1829] [lstm] implement bidirectional lstm forward

---

api/ccapi/include/model.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

Update model inference to accept inputs and labels which are const
vectors.

[api] Update model inference API

---

nntrainer/optimizers/adam.cpp
nntrainer/optimizers/adam.h

Add pytorch reference mode for adam which references adam implementation
of pytorch.

[optim] Add pytorch reference for adam @open sesame 12/22 19:01

---

packaging/nntrainer.spec

- Added gcov package for automatic line coverage

[spec] Add gcov package

---

nntrainer/layers/lstm.h

this patch adds LSTM weight array size fix.

[layer] LSTM weight array size fix

---

nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/optimizers/adam.cpp
nntrainer/optimizers/adam.h
nntrainer/optimizers/optimizer_devel.cpp
nntrainer/optimizers/optimizer_devel.h

<details><summary>Revert "Load Optimizer Variables"</summary><br />
This reverts commit c669732b1f52f4aad3114839fe1ebba0f5d95f27.
As this commit contains some compatibility breaking changes, this commit
should be merged with where nntrainer is being used.
</details>

Revert "Load Optimizer Variables"

---

Applications/TransferLearning/Draw_Classification/jni/main.cpp

- Added missing statement to check called function works properly

[fix] check return value

---

nntrainer/tensor/manager.cpp

This patch remove unreachable code

[COVERITY] remove unreachec code

---

README.md

This patch update reviewers in README

[README] update reviewers

---

jni/meson.build

This patch fix ci fail when we build android using
tools/package_andorid.sh script

[CI] fix android build

---

jni/prepare_openblas.sh
meson.build
meson_options.txt
nntrainer/tensor/blas_interface.cpp
tools/package_android.sh

This patch use openblas_set_num_thread() to set the number of thread
for BLAS computation, instread of set environment variables

[ BLAS ] use openblas function to set num threads

---

nntrainer/layers/grucell.cpp
nntrainer/layers/zoneout_lstmcell.cpp

Commit 1:     [zoneout lstmcell] enable zoneout only when used
- Check zoneout rate before apply zoneout
- Makes zoneout_mask tensors to be shared when it is unrolled
Commit 2:     [grucell] remove temporary tensor
- Reduce temporary tensor

Enable zoneout only when used

---

nntrainer/optimizers/adam.h
nntrainer/optimizers/sgd.h

This patch fixs the warnning message for the android

[ Android ] fix the warning message

---

Applications/Resnet/jni/main.cpp
api/ccapi/include/tensor_dim.h

- fix typo
- Use const for catched exception
- use EXIT_SUCCESS macro
- use error code

[Fix] Clean code for resnet application @open sesame 04/26 10:15

---

test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp
test/unittest/unittest_nntrainer_internal.cpp
test/unittest/unittest_nntrainer_lr_scheduler.cpp
test/unittest/unittest_nntrainer_tensor_pool.cpp
test/unittest/unittest_util_func.cpp

There are some case where there is a positive test but no negative test

[test] Add some negative tests to tizen_capi

---

docs/how-to-run-example-android.md

Updated documentation to include some additional things needed and added some troubleshooting cases.
Signed-off-by: Udit <udit.jain@samsung.com>

[Documentation update] Update how-to-run-example-android.md @open sesame 05/16 20:21

---

Applications/LogisticRegression/jni/Android.mk
Applications/LogisticRegression/jni/main.cpp
Applications/LogisticRegression/res/LogisticRegression.ini
jni/Android.mk

This patch includes
. Update Logistic Regression to use CCAPIs
. Update Inference process
. static link about openmp

[ Application ] Update Logistic Regression to use CCAPI @open sesame 05/16 22:20

---

nntrainer/layers/zoneout_lstmcell.cpp

- This patch enable zoneout even though the zoneout rate is smaller than epsilon

[bug_fix] bug fix zoneout lstmcell layer

---

packaging/nntrainer.spec
test/meson.build

This patch includes fixes to support Tizne 6.0 build
. Fix .spec & meson.build

[ Packaging ] Packaging for Tizen 6.0

---

docs/configuration-ini.md

- Remove learning_rate from oprimizer section
- Add learning rate scheduler section
- Remove dataset section
- Add train set, validation set and test set section
- Add many types to layer section
- Add table about type, key, value, default value and description for each layers
- Update configuration file example

[docs] Update configuration-ini.md file

---

README.md

Add new doc which explains NNTrainer internal

[ Doc ] Update Readme.md

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/optimizers/lr_scheduler_step.cpp
nntrainer/optimizers/optimizer_wrapped.cpp
nntrainer/optimizers/optimizer_wrapped.h
nntrainer/tensor/memory_pool.h
test/unittest/memory/memory_planner_validate.cpp

- Fix typo
- Delete duplicated code

[trivial] fix typo @open sesame 06/09 22:09

---

nntrainer/tensor/tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- Test the zoneout mask is generated according to the zoneout rate

[unittest] added zoneout mask unittest

---

Applications/MNIST/README.md
Applications/MNIST/Tensorflow/Training_Keras.py

- Fix typo
- Fix ist --> i <sup>th</sup> for readability

[trivial] fix typo -> nntrainer/Applications/MNIST

---

Applications/MNIST/jni/main.cpp

- Added how to use step learning rate scheduler in mnist application

[Application] add step learning rate scheduler example

---

Applications/LogisticRegression/jni/main.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp

- Delete duplicated unittest
- Added try catch statement to catch exception

[fix] fix svace issue

---

nntrainer/utils/profiler.cpp

- After print profile information restore precision

[profiler] restore precision

---

nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/utils/profiler.cpp

- Added ifdef statement to check tflite interpreter is enabled
- Added override specifier in get/setWeights

[neuralnet] check tflite interpreter is enabled when export

---

Applications/VGG/jni/Android.mk
Applications/VGG/jni/cifar_dataloader.cpp
Applications/VGG/jni/cifar_dataloader.h
Applications/VGG/jni/main.cpp
Applications/VGG/jni/meson.build

This patch includes the fixes of VGG Application.
- Remove the training data generation with batch size.
: Recently we update the data generation callback to fill one data
set a time
- Remove include the nntrainer interanls : neuralnet.h
: Update to use CCAPI
- Reuse the data generation with ciar_dataloader.h in Resnet

[ Application ] Fix VGG using CCAPI

---

Applications/VGG/jni/main.cpp
nntrainer/layers/common_properties.cpp
test/unittest/layers/unittest_layers_zoneout_lstmcell.cpp

- Added try catch statement
- Delete structually dead code

[trivial] fix ahub issue @open sesame 07/19 16:19

---

nntrainer/layers/conv2d_layer.cpp
nntrainer/utils/nntr_threads.cpp
nntrainer/utils/nntr_threads.h

This patch includes the batch direction parallelization of forwarding
in Conv2D layer.

[ Wait for #1952 ][ Layers ] paralleize Forwarding of conv2d  @open sesame 07/19 16:13

---

Applications/MNIST/README.md
Applications/MNIST/res/mnist.ini

- Update README res/mnist.ini part (Split Optimizer, LearningRateScheduler)
- Update align code comment
Signed-off-by : DongHak Park <donghak.park@samsung.com>

[Application] Update README.md File @open sesame 07/20 10:38

---

Applications/README.md
README.md

This is Proposal PR with issue #1974
- Remove Exmaple contents in nntrainer/README.md
- Add Example contents in nntrainer/Application/README.md
- Close #1974

[trivial] Reorganize README.md files @open sesame 08/08 10:48

---

Applications/VGG/jni/main.cpp
nntrainer/utils/profiler.h

This patch adds the profile in VGG Application

[Application] Add profile for VGG

---

nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/lstm.cpp
nntrainer/layers/pooling2d_layer.cpp
nntrainer/utils/nntr_threads.cpp
nntrainer/utils/nntr_threads.h

This patch includes more parallelization along batch direction. 
- Forward function of Pooling Layer
- calGradient function of LSTM Layer

[ Layer ] More Parallelization along batch direction

---

api/ccapi/include/layer.h
nntrainer/app_context.cpp
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/meson.build
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h

- Added calcCommonDerivative
- Added finalizeCommon
- Replace torch_ref property to reference_framework

[multi head attention] Added multi head attention scaffold @open sesame 8/22 13:32

---

Applications/VGG/jni/main.cpp
nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/lstm.cpp
nntrainer/layers/lstmcell_core.cpp
nntrainer/layers/pooling2d_layer.cpp
nntrainer/utils/nntr_threads.cpp
nntrainer/utils/nntr_threads.h

Gradient computaion of LSTM takes over 60% of computation. This patch
includes the optimization using the tensor dimenson which only has
width.

[ LSTM ] Optimize LSTM Gradient calculation

---

Applications/KNN/jni/main.cpp
Applications/LogisticRegression/README.md
nntrainer/compiler/bn_realizer.h
nntrainer/compiler/compiler.h
nntrainer/compiler/interpreter.h
nntrainer/compiler/loss_realizer.h
nntrainer/compiler/recurrent_realizer.cpp
nntrainer/compiler/remap_realizer.h

Fix Typo in nntrainer/compiler/*

[Trivial] Fix Typo  @open sesame 08/30 14:58

---

api/nntrainer-api-common.h

- Added newly implemented layer enum to nntrainer-api-common.h

[api] added newly implemented layer enum

---

api/ccapi/include/layer.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h

- implement multi head attention finalizeCommon, finalize

[multi head attention] implement finalize @open sesame 8/22 14:00

---

nntrainer/layers/multi_head_attention_layer.cpp

- implement multi head attention forwarding

[multi head attention] implement forwarding

---

nntrainer/layers/multi_head_attention_layer.cpp

- implement multi head attention calcCommonDerivative

[multi head attention] implement calcCommonDerivative

---

nntrainer/layers/multi_head_attention_layer.cpp

- Implement multi head attention calcDerivative, calcGradient
- Needs to support attention mask

[multi_head_attention] implement calcDerivative, calcGradient

---

nntrainer/layers/bn_layer.cpp
nntrainer/layers/concat_layer.cpp
nntrainer/layers/conv1d_layer.cpp
nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/embedding.cpp
nntrainer/layers/fc_layer.cpp
nntrainer/layers/gru.cpp
nntrainer/layers/grucell.cpp
nntrainer/layers/lstmcell.cpp
nntrainer/layers/mol_attention_layer.cpp
nntrainer/layers/pooling2d_layer.cpp
nntrainer/layers/preprocess_l2norm_layer.cpp
nntrainer/layers/preprocess_translate_layer.cpp
nntrainer/layers/reduce_mean_layer.cpp
nntrainer/layers/reshape_layer.cpp
nntrainer/layers/rnn.cpp
nntrainer/layers/rnncell.cpp
nntrainer/layers/split_layer.cpp
nntrainer/layers/tflite_layer.cpp
nntrainer/layers/time_dist.cpp
nntrainer/layers/zoneout_lstmcell.cpp

- Instead of directly using throw convert it to use NNTR_THROW_IF in layer finalize

[layer] [trivial] convert throw to nntr_throw in layer finalize

---

README.md

Add new features:
. positional encoding layer
. Multi-head attention layer
. layer normalization layer
. kld loss
. learning rate schedule

[ README ] add new features in README

---

test/unittest/layers/unittest_layer_node.cpp

[bugfix] initialize local variable

---

nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
nntrainer/layers/lstmcell.cpp
nntrainer/layers/lstmcell.h
nntrainer/layers/lstmcell_core.cpp
nntrainer/layers/lstmcell_core.h
nntrainer/layers/zoneout_lstmcell.cpp
nntrainer/layers/zoneout_lstmcell.h

- Make lstm_core as class so let lstm/lstm_cell/zoneout_lstmcell inherit this.
close #1997

[lstm] make lstm_core as class

---

nntrainer/utils/profiler.cpp
nntrainer/utils/profiler.h
test/unittest/unittest_nntrainer_profiler.cpp

It add two functions:
- provide PROFILE_MEM_ANNOTATE macro
- print average and maximum usage of memory.

[Profile] Add memory statiscs & annotation

---

nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

- Added log when start/finish training
- Added log when get current epoch is called

[neuralnet] add log about training

---

nntrainer/layers/common_properties.h
test/unittest/layers/unittest_layers_convolution1d.cpp

- Change Padding1D key to padding to use same key with Padding2D.

[hotfix] [padding1d] change padding1d key to padding

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h
nntrainer/tensor/meson.build
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h
test/unittest/memory/unittest_memory_pool.cpp

Initial implementaion of cache pool.
It inherites from memory pool to utilize optimized memory information.
And, swap device class is introduce. It operates with cache memory and keeps data permantly in the device.
The storage size is fixed when the device opens, sparse file is created with garbage data. And, it's removed when the device close, 
Issue: #1966

Add memory swap @open sesame 10/13 14:17

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

- Currently cache related codes(flushCache/flushCacheExcept) are not included in lts branch so remove the codes.

[neuralnet] remove cache related code

---

debian/nntrainer-dev.install
nntrainer/tensor/memory_data.h
nntrainer/tensor/memory_pool.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor.h
packaging/nntrainer.spec

- Extract MemoryData class from memory_pool.h and make memory_data.h file
- Add doxygen

[memory] extract MemoryData class from memory_pool to another file

---

nntrainer/graph/network_graph.h
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h

MemorySwapPath property is added to define path for swap files.
If it's not defined, it creates files in crurent directory.

[Model] Add memory swap path property @open sesame 10/17 16:08

---

Applications/Resnet/jni/main.cpp
Applications/VGG/jni/meson.build
nntrainer/optimizers/lr_scheduler.h
nntrainer/optimizers/optimizer_devel.h
nntrainer/optimizers/optimizer_wrapped.h
nntrainer/optimizers/plugged_optimizer.h

Fix the typo errors in bellow dir
- Applications/
- nntrainer/optimizers/

[typo] Fix typo error @open sesame 10/21 11:43

---

nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/swap_device.cpp

- Add try, catch statement to catch exception
- Add NNTR_THROW_IF to check return

[fix] fix coverity_tizen issue @open sesame 10/24 14:10

---

Applications/MNIST/jni/main.cpp
api/ccapi/include/common.h
api/ccapi/include/model.h
nntrainer/app_context.h
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/manager.h

Fix the typo error through spell checker
- Application/
- api/ccapi/
- nntrainer/

[typo] Fix typo error

---

README.md

fix the typo error in README.md file

[typo] Fix typo

---

nntrainer/graph/network_graph.cpp
nntrainer/models/neuralnet.cpp

It adds several annotations for memory profiling.
Each of them can help to teach profile steps.
It depends on #1965

[Profile] Add annotate for memory profiling @open sesame 10/20 07:09

---

Applications/TransferLearning/Draw_Classification/jni/meson.build
debian/rules
packaging/nntrainer.spec
test/nnstreamer/meson.build
test/unittest/layers/unittest_layers_nnstreamer.cpp

Temporarily, we have to turn off the nnstreamer backbone until some issue is fixed.

[ CI ] Temporal Fix for the CI about NNStreamer Backone

---

Applications/TransferLearning/Draw_Classification/jni/meson.build
debian/rules
packaging/nntrainer.spec
test/nnstreamer/meson.build
test/unittest/layers/unittest_layers_nnstreamer.cpp

Rerun nnstreamer test.
Signed-off-by: gichan <gichan2.jang@samsung.com>

Rerun nnstreamer test @open sesame 11/25 15:52

---

nntrainer/tensor/meson.build
nntrainer/tensor/task.h
nntrainer/tensor/task_executor.cpp
nntrainer/tensor/task_executor.h
test/unittest/meson.build
test/unittest/unittest_nntrainer_task.cpp

Task has several properties for its state and working information.
There are two types for Task, Synchronous and Asynchronous. and, their
behaviors will be differ when they are executed by TaskExecutor.
TaskExecutor class manages task's execution by their type.
Synchoronous tasks are exeucuted immediately, while asynchoronous tasks
are executed in thread manner.
For testing above two classes, unittest codes are also included.
The mock class for TaskExecutor is introduced to check work thread is
correctly working, and completion check is also working correctly.
Many tests are added to check asynchronous tasks' correctness.
Issue (#2034)

Add Task and TaskExecutor @open sesame 11/11 10:50

---

Applications/Resnet/jni/main.cpp
Applications/utils/datagen/cifar/cifar_dataloader.cpp

This fix data loader bug, which is related to iteration number.

[Resnet] Fix FakeDataLoader bug

---

Applications/MNIST/Tensorflow/Training_Keras.py

Modified for tensorflow 2.10.0.

[Application] mnist: Fix tf example

---

Applications/utils/mem_usage.sh

It uses /proc/$PID/smaps information to check current memory usage.
Please refer doc:
https://man7.org/linux/man-pages/man5/proc.5.html

[Utils] Modify memory usage script

---

nntrainer/utils/profiler.cpp
nntrainer/utils/profiler.h

This patch adds swap status and policies.
Deallocation memory size is added, and swap IN/OUT status and cache policy columns are added.
---
Example output:
```
event                size               total                                                        info       dur              policy      swap                                                                                                                                                                         
========================================================================================================================================================================================================================== …
```

[Profile] Modify for swap status

---

Applications/LSTM/README.md
Applications/LSTM/pytorch/torch_lstm.py
Applications/LSTM/tensorflow/tensor_lstm.py
Applications/README.md

Add LSTM examples using pytorch and tensorflow.
- LSTM example using NNTrainer needs to be added.
- We conduct memory benchmark test based on these codes.

[Application] Add LSTM examples using pytorch and tensorflow

---

Applications/Layers/PyTorch/Conv.py
Applications/Layers/PyTorch/Linear.py
Applications/Layers/PyTorch/Model_A_Conv.py
Applications/Layers/PyTorch/Model_A_Linear.py
Applications/Layers/PyTorch/Model_C_Conv.py
Applications/Layers/PyTorch/Model_C_Linear.py

Add Simple Pytorch examples with Dummy Data
- Linear
- Conv
- LSTM (Will merge with exist file)
- Model_A_Linear
- Model_A_Conv
- Model_C_Linear
- Model_C_COnv
It has same Layer with NNtrainer example that has same name

[Wait for #2102] [Application] Add Simple Layers Pytorch examples

---

Applications/Layers/README.md
Applications/Layers/jni/Android.mk
Applications/Layers/jni/Application.mk
Applications/Layers/jni/main.cpp
Applications/Layers/jni/meson.build
Applications/Layers/res/Conv.ini
Applications/Layers/res/LSTM.ini
Applications/Layers/res/Linear.ini
Applications/Layers/res/Model_A_Conv.ini
Applications/Layers/res/Model_A_Linear.ini
Applications/Layers/res/Model_C_Conv.ini
Applications/Layers/res/Model_C_Linear.ini
Applications/README.md
Applications/meson.build

Add Simple Layers NNtrainer example(FC, LSTM, Conv)  with Dummy Data
- Linear(Fully-Connected)
- Conv
- LSTM
We conduct Memory & Latency Benchmark test based on these code It's Loss possibly show inf cause It's DataSet is Dummy If you want to get actual Loss set your own Dataset
- It support only training if user want they can set dataset, validation loss, test loss... etc

[Application] Add Simple Layers NNtrainer example(FC, LSTM, Conv)

---

nntrainer.ini.in
nntrainer/graph/network_graph.h
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h

It implement lookahead(preloading) behavior.
Preloading is working with cache flush synchroneously, due to
cache flush is done when each execution order finishes.

(Wait for #2041) [SWAP] Implement lookahead(preloading) behavior

---

nntrainer.ini.in
nntrainer/graph/graph_node.h
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_node.cpp
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h
nntrainer/tensor/tensor_wrap_specs.h

After derivative calculation, gradient needs to be applied. But, the
order for it was merged with derv calculation.
This patch divide apply graident order, and modify related lifespans.

(Wait for #2071, #2075) [Memory] Add apply gradient step @open sesame 02/23 09:27

---

nntrainer/tensor/cache_loader.cpp
nntrainer/utils/node_exporter.cpp

This patch fixes for tflite interpreter option.

Fix: fixes for options

---

api/ccapi/include/common.h
api/ccapi/include/model.h
api/nntrainer-api-common.h
nntrainer/compiler/flatbuffer_interpreter.cpp
nntrainer/compiler/flatbuffer_interpreter.h
nntrainer/models/neuralnet.cpp

<details><summary> 1. Create Flatbuffer_interpreter.h </summary><br/> 
add Flatbuffer Type into apis
for support Flatbuffer, write interpreter from GraphInterpreter, tflite_interpreter
</details>

[FlatBuffer] Support FlatBuffer import &export @open sesame 02/21 14:01

---

.github/workflows/Upload.yml
.github/workflows/labeler.yml

There was Permission Error on Auto Labeler
- Chagne Permission for pull request, issue

[GitAction] Fix Auto Labeler

---

.github/workflows/Upload.yml
.github/workflows/labeler.yml

- Request for removal when there is no label or request for addition when there is a label
- Add is_Contain Variable to upload & in labeler they check it already contain label or not
- In gitaction document their api use name : "Need Review" not labels : ["Need Review"]
- Remove unused Debug line
- Reorder step

[GitAction] Fix Gitaction Auto Labeler

---

docs/getting-started.md

Update getting-started.md file
- Corrected the ambiguous content to make it easier for users to understand

[Trivial] Update getting-started.md @open sesame 03/07 13:50

---

Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/utils/datagen/cifar/cifar_dataloader.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/models/model_loader.cpp
nntrainer/tensor/swap_device.cpp
nntrainer/utils/ini_wrapper.cpp
nntrainer/utils/util_func.h

- Replace strerror with strerror_r to make thread safe.

replace strerror with strerror_r

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/models/neuralnet.cpp
nntrainer/tensor/tensor.cpp
nntrainer/utils/util_func.cpp

- cast unsigned value to signed value and check its value it overrides sign-bit.

[ahub] fix ahub issue

---

Applications/YOLO/PyTorch/dataset.py
Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo.py
Applications/YOLO/PyTorch/yolo_loss.py
Applications/YOLO/jni/Android.mk
Applications/YOLO/jni/Application.mk
Applications/YOLO/jni/main.cpp
Applications/YOLO/jni/meson.build
Applications/meson.build

define YOLO v2 model structure corresponding to pytorch example.
now, it is implemented by fake data, and there is no loss function for this model.

[Application] define YOLO v2 model class

---

nntrainer/compiler/ini_interpreter.cpp
nntrainer/compiler/input_realizer.cpp
nntrainer/compiler/input_realizer.h
nntrainer/layers/pooling2d_layer.cpp
nntrainer/utils/node_exporter.h

Fix Typo Error
- Correct typos found during development in compiler dir

[Trivial] Typo Error

---

api/capi/src/nntrainer.cpp
api/ccapi/include/model.h
api/ccapi/include/tensor_dim.h
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/tflite_layer.cpp
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
nntrainer/utils/base_properties.cpp
nntrainer/utils/base_properties.h

Previously, the dimension type of tensor dim is unsigned int and it cause the error for bigger problems. This pr change the demeion type to size_t.
Also, This pr fix the user_data for stop callback to use user_data.
Resolves:
Signed-off-by: Jijoong Moon <jijoong.moon@samsung.com>

[ Tensor ] fix the dim type

---

nntrainer/layers/conv2d_layer.cpp

It was used for better latency but it consumes more memory than we expected when there are many conv layers.
In this pr, this inter_result is removed.
Signed-off-by: Jijoong Moon <jijoong.moon@samsung.com>

[Conv2d] Remove inter_result in conv2d layer

---

nntrainer/layers/tflite_layer.cpp

add more error infor when tflite and input dim mismatch.

[ Trivial ] add more error infor

---

Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo.py

Add yolo example moving weight from pytorch to nntrainer.
Signed-off-by: Seungbaek Hong [sb92.hong@samsung.com](mailto:sb92.hong@samsung.com)

[Application] yolo example moving weight from torch to nntrainer

---

nntrainer/graph/graph_node.h
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_context.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/basic_planner.cpp
nntrainer/tensor/basic_planner.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/memory_planner.h
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h
nntrainer/tensor/meson.build
nntrainer/tensor/optimized_v1_planner.cpp
nntrainer/tensor/optimized_v1_planner.h
nntrainer/tensor/optimized_v2_planner.cpp
nntrainer/tensor/optimized_v2_planner.h
nntrainer/tensor/optimized_v3_planner.cpp
nntrainer/tensor/optimized_v3_planner.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h
test/unittest/memory/unittest_memory_planner.cpp

This PR includes,
1. assigning right execution order depending on layer type.
: We do need to move those fixes in to each layer
2. Update memory Planner to use the memory with smaller size

[Memory Planner] Update the Memory Planner 

---

Applications/Custom/LayerPlugin/layer_plugin_common_test.h
Applications/Custom/OptimizerPlugin/meson.build
Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.cpp
Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.h
Applications/Custom/OptimizerPlugin/optimizer_plugin_momentum_test.cpp
Applications/Custom/meson.build
Applications/Custom/momentum.cpp
Applications/Custom/momentum.h
debian/nntrainer-dev.install
nntrainer/meson.build
packaging/nntrainer.spec

This PR includes the custom optimizer 'momentum' example in Applicaiton/Custom
It adds the testcase and demo implementaiton

[ Custom ] Add custom optimizer example in Application

---

Applications/YOLO/PyTorch/yolo_loss.py

For tracking the gradients of Loss class,
I removed in-place operation in the Loss class.
And, I added hook_variable function for tracking specific tensors.
We can register specific variable with name using hook_variable
function, then we can check the gradient values using
print_hook_variable function after backwarding.

[Application] Update yolo example of torch for tracking gradients

---

Applications/YOLO/PyTorch/main.py

Add validation process of yolo example using validation dataset on
pytorch.

[Application] add validation process of yolo example on pytorch

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
test/input_gen/genModelExeOrder.cpp

Fixed some svace issues on svace-tizen_7.5.
Add exception handling to
- tensor_trainer_nntrainer.cc
- genModelExeOrder.cpp

[Ahub] Fix svace issue @open sesame 04/06 09:40

---

Applications/TransferLearning/Draw_Classification/jni/main.cpp
debian/rules
meson.build
nnstreamer/meson.build
nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
nntrainer/layers/nnstreamer_layer.cpp

This pr fixes the limit of rank whic greater than 4.

[NNStreamer] fix input dimension with MAX RANK with 8 

---

Applications/Resnet/jni/main.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/models/neuralnet.cpp
nntrainer/tensor/lazy_tensor.cpp
nntrainer/utils/profiler.cpp

Fix AHub Defect
- make some exception statement
- change auto element -> auto &element

[AHub] Fix AHub Defect @open sesame 04/10 09:22

---

nntrainer/compiler/tflite_opnode.cpp
nntrainer/compiler/tflite_opnode.h

Update tflite_opnode
- Add is_trainable for make fused op, by checking is trainable we can make fused of for inference
- Add MUL Op for BatchNormalization Fused Op

[TF Export] Update tflite_opnode @open sesame 04/07 20:08

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h

- Added identity layer enum to capi

[capi] add identity layer to capi

---

Applications/Android/kotlin/app/build.gradle

There is CVE issues befor gson 2.8.9.

[Application] Fix CVE issues in kotlin gson

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

- Change from int64_t to unsigned int
- bug-fix: when getting values from nnstreamer in an arm 32bit environment, invalid values are passed

[NNstreamer] Change variable type of sub-plugin

---

api/capi/src/nntrainer.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/utils/profiler.cpp
test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp

[tct] fix coverity issues

---

test/unittest/layers/layers_standalone_common_tests.cpp
test/unittest/memory/unittest_cache_loader.cpp
test/unittest/unittest_base_properties.cpp

- Remove meaningless unittest
- Unify unittest

[unittest] remove meaningless unittest

---

api/ccapi/include/layer.h
nntrainer/layers/acti_func.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/layers/unittest_layers_activation.cpp
test/unittest/unittest_nntrainer_activations.cpp

Added GELU activation function for supporting gpt.
I created unittest for this using pytorch.

[activation] add gelu function

---

Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo.py
Applications/YOLO/jni/main.cpp

Yolo v2 model was updated similar to original yolo v2 model.
This model was intended to be implemented in accordance with
the original paper of Yolo v2 as much as possible,
but now average pooling is temporarily used instead of the
re-organization module.
If only the average pooling is replaced with the re-organization
module in the future, the rest is the same as the original paper
in Yolo v2.
Both the PyTorch version and the NNTrainer version updated the model
structure and verified that the same results could be obtained
by loading trained weights from PyTorch.

[Application] Update yolo v2 model similar to original paper @open sesame 04/20 15:09

---

nntrainer/layers/layer_context.cpp

fix typo error (requesing -> requesting).

[Trivial] Fix typo error

---

api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp
test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp
test/unittest/unittest_nntrainer_lr_scheduler.cpp

Fix Typo
- nntrainer_internal.h
- nntrainer.cpp
- unittest_tizen_capi_lr_scheduler.cpp
- unittest_tizen_capi_optimizer.cpp
- unittest_nntrainer_lr_scheduler.cpp

[Trivial] Fix Typo

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

- epoch_complete_cb is called When one epoch ends in nntrainer and
RunStats information is retrieved from the model.
- Send event to NNStreamer, NNStreamer waits to receive results every epoch.
- Use getStatus and nnstreamer_trainer_notify_event()

[Wait for nnstreamer #4080][nnstreamer][trainer] Add getting model stats information @open sesame 06/08 11:20

---

Applications/Resnet/jni/main.cpp

Fix it because the results of the computation of pytorch and nntrainer are different.
padding was written as same when stride was 2 in NNtrainer Resnet code. In pytorch, this is set to error. 
In addition, padding was not applied normally in nntrainer, so the results were different. 
To solve this problem, the parameters of a1 layer (conv layer) have been modified.
Additionally, momentum and epsilon were added to batch_norm layer.

[Application] Fix Resnet18 @open sesame 06/13 10:05

---

Applications/Resnet/jni/main.cpp

I added transfer learning option to resnet-18 example.
If this option is enabled, then load pre-trained weights and freeze the weights of backbone(feature extractor). (It just a simple transfer learning, and default option is "false").
You can make pre-trained weights using save_bin function from our pytorch resnet-18 example.

[Application] Transfer learning example on Resnet-18

---

Applications/YOLO/jni/main.cpp
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nntrainer/compiler/tflite_opnode.cpp
nntrainer/dataset/dir_data_producers.cpp

- Fixed the NNTrainerTrain constructor so that the member variable notiofier is initialized.
- Fixed nntrainer_model_start_training to stop when nntrainer and notifier are null.
- Fixed AUTO_CAUSES_COPY issue.

[fix_ahub] Fix AHub Defect

---

meson.build
nnstreamer/tensor_filter/tensor_filter_nntrainer.hh
nntrainer/graph/graph_node.h
nntrainer/layers/attention_layer.h

This patch includes gcc-13 compatible fixes.

[Toolchain] Enable gcc-13 support

---

meson.build
nntrainer/dataset/dir_data_producers.cpp
nntrainer/graph/network_graph.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/rnncell.cpp
nntrainer/nntrainer_logger.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor_pool.cpp
test/unittest/compiler/compiler_test_util.cpp
test/unittest/compiler/unittest_realizer.cpp
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_nntrainer_activations.cpp

- Remove inheriting the stl iterator as this is deprecated.
- Added warning flags. These flags should be removed

enable compile with gcc-13

---

nntrainer/compiler/tflite_opnode.cpp
nntrainer/compiler/tflite_opnode.h

for Export Tflite format with Fused Op add some Variable and Function
1. Add getter, setter, replace to weights, inputs, outputs
- for Fused Op we need to adjust Variables after made Opnode
2. Add isToBeRemove variable
- After made Opnode, check condition and mark as to be remove
3. Add additional_props
- for BatchNormalization Fused Op we need additional props from nntrainer
- made vector<float> variable for save additional data

[TFLite Export] Add variabel, functions TfOpNodes for Fused OP export

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp

**For Fused OP Made Realized Path**
1. Check Trainable 
- check node is trainable or not for Fusing
2. Conv + ReLU Fusing
- For Trainable (Conv) with Batch Normalization it can Fused 
**- Fused weight(conv) = weight(conv) * (weight(bn) / sqrt(var(bn) + eps))**
**- Fused Bias(cov) = (bias(conv) - mean) * (weight(bn) / sqrt(var(bn) + eps)) + bias(bn)**
3. Batch Normalization Fusing
- If non-trainable with batchnorm, it will split in to MUL + ADD nodes with below 
**- y = x  * (gamma / sqrt(variance + epsilon)) + (beta - mean * gamma / sqrt(variance + epsilon) )**

[Wait For #2184][TFLite Export] Add Realized Path for Fused Op

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

For adjust exist node, we need some information from old node, and in Flatbuffer it is hard to bring. so made some variables for saving information
Add Epsilon Props to additional_props for fusing
- For Fusing we need Epsilon for batch norm
Add padding, stride props to props_vector
- For Conv Fusing we need to made new BuiltinOption and for building new BuiltinOption with FUSED activation we need padding,stride
**Related PR**
#2184 #2185 #2204

[Wait for #2185][TFLite Export] Update node_exporter @open sesame 05/10 11:14

---

meson.build

- Added Wno-maybe-uninitialized flag

[bugfix] added warning flag to compile with gcc 13

---

nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h

This path checks requested memory is weight gradient which information will be used for planning.

[FIX] modified for checking weight grad

---

meson.build
meson_options.txt
test/unittest/compiler/meson.build
test/unittest/datasets/meson.build
test/unittest/layers/meson.build
test/unittest/memory/meson.build
test/unittest/meson.build
test/unittest/models/meson.build

It adds timeout option to adjust meson test timeout.

[TEST] Add timeout option

---

README.md

- add new reviewers : sungsik Kong, donghyeon Jeong

[trivial] Add reviewers

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

[sub-plugin] Add function to stop model training
nnstreamer tensor_trainer call this function to stop model training

[sub-plugin] Add function to stop model training

---

nntrainer/tensor/blas_neon.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

- Optimized fp16 implementation of SGEMV using NEON to run on Android(ARM). Optimized both scenarios: transpose, non transpose.
- Added unit test for SGEMV operations.
Signed-off-by:s-debadri <s.debadri@samsung.com>

[blas/neon] Optimization on SGEMV fp16 implementation

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

<details><summary>   NEON fp16 implementation of SGEMM    </summary><br />
Enable neon sgemm function for Android (ARM) fp16 computation.
</details>
<details><summary>   Add unit test for SGEMM NEON fp16 function  </summary><br />
Add unit test for fp16 sgemm function in Android(ARM).
</details>
Signed-off-by:s-debadri <s.debadri@samsung.com>

[blas/neon] SGEMM fp16 implementation using NEON

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp

Used padded calculations for SGEMM using NEON for any value of M. Where M is the number of rows in output matrix.
Signed-off-by:s-debadri <s.debadri@samsung.com>

[blas/neon] SGEMM Neon execution for any M value

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

Modify synchronization mechanism between push_data and getSample
- Remove some member variable
- Add member function to check queue

   [sub-plugin] Modify synchronization mechanism between push_data and getSample

---

api/ccapi/include/tensor_dim.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
nntrainer/utils/base_properties.h
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp
test/unittest/unittest_nntrainer_tensor_pool.cpp

- Quantized Tensor is now present with Int 8 with scale.
- Dequantization is performed by multiplying values by a scaling factor for channels.
- Only read, write, and dequantization operations are allowed.

[Tensor] Quantized Tensor (Int 8) with Scale

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/models/model_common_properties.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/utils/base_properties.h
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp
test/unittest/unittest_nntrainer_tensor_pool.cpp

- Quantized tensor values are unsigned with zero points
- Layer context dequantize quantized tensor when request weight
- Template dequantize function

[Tensor] Unsigned Quantized Tensor

---

Applications/YOLO/PyTorch/dataset.py
Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo_loss.py
Applications/YOLO/jni/Android.mk
Applications/YOLO/jni/main.cpp
Applications/YOLO/jni/meson.build
Applications/YOLO/jni/yolo_v2_loss.cpp
Applications/YOLO/jni/yolo_v2_loss.h
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

I've rebased #2177(loss for yolo) and #2213(custom layer for yolo).
(Because the author of PR #2177 is absent for now.)
If someone needs to use yolo v2, then use this pr.
I'll update document for this later.

[Wait for #2177,#2213][Application] rebase for yolo v2 @open sesame 06/13 14:42

---

Applications/YOLO/jni/meson.build
Applications/YOLO/jni/yolo_v2_loss.cpp
debian/nntrainer-applications.install
packaging/nntrainer.spec

Setup meson file for making libyolov2_loss_layer.so in yolo v2 application.

[Application] Setup meson file for libyolov2_loss_layer.so @open sesame 09/13 18:48

---

debian/changelog
meson.build
packaging/nntrainer.spec

This reverts commit 258967dcad51caffde61a06f46bde7f6329622d9.
We cancel to release.
Signed-off-by: Jijoong Moon <jijoong.moon@samsung.com>

Revert "[Release] NNTrainer v0.5.1 release"

---

Applications/YOLO/jni/main.cpp
Applications/YOLO/jni/reorg_layer.h

[Application] bugfix for YOLO version 2
Training does not proceed because the layer names are different.
- reorg layer name is changed from reorg to reorg_layer

[Application] bugfix for YOLO version 2

---

Applications/Android/ResnetJNI/app/src/main/jni/dataloader.cpp
Applications/SimpleShot/README.md
Applications/SimpleShot/task_runner.cpp
Applications/TransferLearning/Draw_Classification/jni/main.cpp
Applications/meson.build

Fix Coverity issue & Fix some typo
- Auto_causes_copy issue
- leaked_storage issue
- returned_null issue
_Build test: [x]Passed [ ]Failed [ ]Skipped

[Coverity] Fix Coverity issue

---

nntrainer/layers/layer_context.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h

**Fix tizen svace issue** 
Fix Svace issues on tensor.h, blas_neon.cpp, layer_context.h

[Svace] Fix tizen svace issue

---

Applications/Android/ResnetJNI/app/src/main/jni/dataloader.cpp
Applications/SimpleShot/README.md
Applications/SimpleShot/task_runner.cpp
Applications/TransferLearning/Draw_Classification/jni/main.cpp
Applications/YOLO/jni/main.cpp
nntrainer/compiler/flatbuffer_opnode.cpp

Fix Coverity issue & Fix some typo
- Auto_causes_copy issue
- leaked_storage issue
- returned_null issue
This PR is same contents with #2290 but it fix lts 0.5 branch's issue
_Build test: [x]Passed [ ]Failed [ ]Skipped

[Coverity] Fix Coverity issue on lts 0.5 branch

---

nntrainer/tensor/tensor.cpp

- While inspecting potential bugs from Tensor, found some redundant code block
- Erase repeatedly called code block

[Tensor/trivial] Erase redundant code

---

test/unittest/compiler/unittest_interpreter.cpp

**Update get output tensor from tflite**
There some logical error on get output tensor
So, Fix get output tensor part

[tflite_export] Update get output tensor from tflite

---

nntrainer/tensor/blas_neon.cpp

- We can reduce the number of function calls by re-using the register variable both row-wise, col-wise.
- However, using both requires more-than-thirty-two (which is prohibited) register variables, which might cause register spilling. Thus, I only implemented row-wise optimization.
- This optimization is valid especially for large scale Tensor.

[Wait for #2327] [neon] Optmizie sgemm transB row-wise

---

nntrainer/tensor/blas_neon.cpp

Used NEON SIMD to calculate prefixes.
Added vectorization to process 16 rows together.

[neon] SGEMM optimized noTrans scenario

---

Applications/YOLOv3/PyTorch/main.py
Applications/YOLOv3/PyTorch/yolo.py
Applications/YOLOv3/PyTorch/yolo_loss.py
Applications/YOLOv3/jni/Android.mk
Applications/YOLOv3/jni/Application.mk
Applications/YOLOv3/jni/det_dataloader.cpp
Applications/YOLOv3/jni/det_dataloader.h
Applications/YOLOv3/jni/main.cpp
Applications/YOLOv3/jni/meson.build
Applications/YOLOv3/jni/upsample_layer.cpp
Applications/YOLOv3/jni/upsample_layer.h
Applications/YOLOv3/jni/yolo_v3_loss.cpp
Applications/YOLOv3/jni/yolo_v3_loss.h
Applications/meson.build

Add Loss layer for YOLO v3.
I added loss layer for yolo v3,
so it can be trained using this layer.
But there is still some issues for this application.
- If add validation dataset,
it raise an error (segmentation fault).
- and, at the end of the main.cpp script,
it raise an error (segmentation fault, too).

[Application] LOSS for YOLO v3 in nntrainer @open sesame 09/14 14:02

---

Applications/LLaMA/PyTorch/weights_converter.py
Applications/LLaMA/jni/Android.mk
Applications/LLaMA/jni/Application.mk
Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/meson.build
Applications/LLaMA/jni/rms_norm.cpp
Applications/LLaMA/jni/rms_norm.h
Applications/LLaMA/jni/rotary_embedding.cpp
Applications/LLaMA/jni/rotary_embedding.h
Applications/LLaMA/jni/swiglu.cpp
Applications/LLaMA/jni/swiglu.h
Applications/LLaMA/jni/transpose_layer.cpp
Applications/LLaMA/jni/transpose_layer.h
Applications/meson.build
nntrainer/layers/embedding.cpp

Added LLaMA v2 application.
This implementations is based on llama of meta.
ref url: "https://github.com/facebookresearch/llama/"
It contains...
- implementations of swiglu, rmsprop, rotary embedding
- load weights from pytorch implementation(HuggingFace)

[Application] LLaMA v2

---

Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/rms_norm.cpp
Applications/LLaMA/jni/swiglu.cpp
nntrainer/layers/activation_layer.cpp
nntrainer/layers/activation_layer.h
nntrainer/layers/embedding.cpp
nntrainer/layers/embedding.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h

This PR enables the cache sliding if it exceeds the max length of cache.
also, fix the 32bit computing issue in RMS NORM layer

[ Multi Head ] enable cache shifting

---

Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/meson.build
Applications/LLaMA/jni/rms_norm.cpp
Applications/LLaMA/jni/rms_norm.h
Applications/LLaMA/jni/swiglu.cpp
Applications/LLaMA/jni/swiglu.h
Applications/PicoGPT/jni/main.cpp
Applications/meson.build
api/ccapi/include/model.h
meson.build
nntrainer/layers/addition_layer.cpp
nntrainer/layers/addition_layer.h
nntrainer/layers/embedding.cpp
nntrainer/layers/embedding.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/fc_layer.h
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h
nntrainer/layers/multiout_layer.cpp
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
packaging/nntrainer.spec

This PR uses GEMM to compute initial sequences.
also, make toknizer as defalut.

Use GEMM computation for initial sequence

---

api/ccapi/include/model.h
debian/nntrainer-dev.install
nntrainer/layers/fc_layer.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor.cpp
packaging/nntrainer.spec

This PR fixes the output of incremental inference.
Resolves:

[ Model ] Fix incremental output in FP32

---

test/unittest/layers/layers_golden_tests.cpp

- Float16 models tend to show unavoidable higher accuracy loss in: 1. huge Tensors 2. Tensors with huge values
- Reassess value-by-value logic with relative error when large error

[gtest] Fix gtest error assessing logic

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/meson.build
Applications/ReinforcementLearning/DeepQ/res/DeepQ.ini
nntrainer/models/neuralnet.cpp

- Make res directory and move DeepQ.ini file to res dir
- If the input batch size does not match with batch size property of model graph, set model graph batch size property as input batch size in forwarding function
- Allocate weight/tensor memory as train mode of mainNet, targetNet network
- Comment "return 1" statement so as to make it as train from scratch

[Application] fix deepq to make it run

---

Applications/LLaMA/PyTorch/weights_converter.py

Actually, I already added weights converter for mha model in pr #2338 2287.
There were 2 types of converter for supporting legacy and mha model.
But now, converter for legacy model is useless. So I deleted it.

[Application] LLaMA weights converter for mha model

---

Applications/Multi_input/jni/Android.mk
Applications/Multi_input/jni/Application.mk
Applications/Multi_input/jni/main.cpp
Applications/Multi_input/jni/meson.build
Applications/Multi_input/jni/multi_loader.cpp
Applications/Multi_input/jni/multi_loader.h
Applications/meson.build

Added multi-input dataloader example application.

[Application] Add multi_input dataloader example @open sesame 09/15 16:08

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

- Change namespace name to Subplugin
- Change NNTrainerTrain class name to Trainer
- Rename object name of Trainer class
- Change InputTensorsInfo class name to TensorsQueue
- Add push method to TensorsQueue
- Change member variables of Trainer and TensorsQueue to private and rename some variables and methods

[Sub-plugin] Refactoring sub-plugin class

---

debian/nntrainer-dev.install
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/meson.build
packaging/nntrainer.spec

This PR includes creating the HalfTensor class which separates 16-bit floating point calculation from nntrainer::Tensor.
- Create a HalfTensor class that only handles 16-bit floating point calculation.
- Remove operations for Quantized Tensor.

[Tensor] HalfTensor class for 16-bit floating point

---

Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/rms_norm.h
Applications/LLaMA/jni/rotary_embedding.h
Applications/Multi_input/jni/main.cpp
Applications/Multi_input/jni/multi_loader.cpp
Applications/PicoGPT/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/YOLOv3/jni/det_dataloader.cpp
Applications/YOLOv3/jni/main.cpp
Applications/YOLOv3/jni/yolo_v3_loss.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/tensor.cpp

- Fix uninitialized class members in the constructor
- Fix potential uninitialized data
- Add try-block to catch exceptions

[Ahub] Fix AnalysisHub defects

---

debian/nntrainer-dev.install
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/meson.build
nntrainer/tensor/src_shared_tensor.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h
packaging/nntrainer.spec
test/unittest/meson.build
test/unittest/unittest_nntrainer_tensor_v2.cpp
test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp

In this PR, the initial working version of Tensor V2 is included.
- Create a TensorV2 class that follows a type erasure design pattern.
- Create a new SrcSharedTensorV2, which is a class template.

[Tensor] Initial Draft of Tensor Version 2

---

nntrainer/tensor/meson.build
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR extends the current Tensor member functions.
- Add member functions to get tensor information.
- Implement skeleton code from #2378.

[Tensor] Add Tensor member functions

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp

In this PR, FloatTensor and HalfTensor's override methods are implemented.

[Tensor] Add Float/HalfTensor Implementation

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/neon_mathfunc.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

[ BLAS ] Add trigonometric transformation functions
- In order to accelerate trigonometric calculations, add such transformation functions in BLAS module with NEON SIMD
- Add zlib license file
[ Tensor ] Add trigonometric transformation functions in Tensor
- Add sin / cos transform function in Tensor : both for BLAS/raw
- Add unittest accordingly

[ BLAS ] Add trigonometric transformation functions

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h

[ BLAS ] add inv squared root transormation inplace function for fp16
- add inv squared root transormation inplace function for fp16
- expect to accelerate rms normalization

[ BLAS ] add inv squared root transformation inplace function for fp16

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request implements a new function called apply(), which applies a given function element-by-element to a tensor.
The resulting tensor has the same shape as the input tensor, but each element has been transformed by the given function.

[TensorV2] apply() function to apply a given function

---

test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

- There was a request to add unittest for inv_sqrt_i in #2396 
- Conducted by comparing values between fp16 and fp32 Tensor with eps = 1e-3

[ unittest ] Add unittest for inv_sqrt_i with fp16

---

nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds a basic implementation of tensor multiplication operations to our codebase. 
The new functionality allows users to perform the multiplication of tensors by simply calling a function.

[TensorV2] Multiplication operation skeleton

---

nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR adds support for broadcasting to enable broadcasting in operation in the future.

[Tensor] Add broadcast support for operations

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h

This PR enables functionality to apply the given operator, such as multiply and divide, with broadcasting to the tensor.

[TensorV2] Add support for applying operators with broadcasting 

---

test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp

This PR includes the implementation of test util functions to create a tensor filled with values to utilize in unit testing.

[Test] Generate TensorV2 in unit test

---

.github/CODEOWNERS
CONTRIBUTING.md
README.md

Add new member & update CODEOWNERS
modified:   .github/CODEOWNERS
modified:   CONTRIBUTING.md
modified:   README.md

[Trivial] Add new member & update CODEOWNERS

---

.github/workflows/pylint.yml
Applications/VGG/Tensorflow/dataset.py

Add pylint yml file for python lint
- we move to gitaction from TAOS CI
- pylint.yml

[CI] Add Pylint gitaction for gitaction CI

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nntrainer/compiler/recurrent_realizer.cpp
nntrainer/compiler/slice_realizer.cpp

- Specify the lambda return type to avoid object copy

[bug] fix coverity issues

---

nntrainer/utils/node_exporter.cpp
nntrainer/utils/profiler.cpp

It fixes coverity issues.
- Use reference to avoid object copy.
Issue:
1740106
1742375
1747001

[FIX] Fix coverity issues

---

nntrainer/dataset/dir_data_producers.cpp

To resolve AUTO_CAUSES_COPY, auto was changed to const auto&.

[Ahub] Fix coverage issue

---

nntrainer/graph/network_graph.cpp

[ahub] fix converity issues

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request introduces a basic structure of tensor addition operations.
Function implementation will be added in a later PR.

[TensorV2] Add addition operation structure

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request introduces a basic structure of tensor division operations.
Function implementation will be added in a later PR.

[TensorV2] Add division operation structure  @open sesame 02/06 11:43

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request introduces a basic structure of tensor subtraction operations.
Function implementation will be added in a later PR.
** Self-evaluation**

[TensorV2] Add subtraction operation structure

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

<details><summary> [TensorV2] Add tensor power function  </summary><br />
This commit adds a power function, which takes the power of each element in the input tensor with a given exponent and returns a tensor with the result.
Signed-off-by: Donghyeon Jeong <dhyeon.jeong@samsung.com>
</details>
<details><summary> [TensorV2] Add tensor gauss error function </summary><br />
This commit adds an error function, which computes the Gauss error function of the input tensor.
Signed-off-by: Donghyeon Jeong <dhyeon.jeong@samsung.com>
</details>

[TensorV2] Add power function and Gauss error function

---

test/unittest/unittest_nntrainer_tensor_v2.cpp
test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp

This PR includes unit tests for verifying divide operation in the TensorV2 class.
Note that all unit tests are the same as tests in unittest_nntrainer_tensor.cpp file.

[Test] TensorV2 division unit test

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR adds the implementation of add operation that supports different strided inputs and output.

[TensorV2] Add strided inputs and output

---

nntrainer/tensor/blas_neon.cpp

1. Rather than using N - 8 and adding more chunk of code, using N8 can make the code shorter
2. In previous neon patch, I deliberately removed 16x8 kernel-loop for hgemv_transpose, since I could not find difference in terms of latency. However, it turns out to be efficient when multiple times of MV ops are used.

[ neon ] Hgemv transpose biggerkernel

---

api/capi/include/nntrainer_internal.h
nntrainer/utils/node_exporter.cpp

This PR resolves the coverity issues of missing lock and use of auto that cause a copy.

[Coverity] Fix the coverity issue

---

nntrainer/tensor/task_executor.cpp
nntrainer/utils/node_exporter.cpp

This PR fixes coverity issues of `auto_causes_copy`
- 1739360
- 1740106

[coverity] fix coverity issues

---

test/unittest/layers/layers_golden_tests.cpp
test/unittest/models/unittest_models_multiout.cpp
test/unittest/unittest_nntrainer_graph.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

- Fix coverity issue 1774230, 1774235, 1774238, 1774239, 1774243
Resolves:
```
Use of auto that causes a copy (AUTO_CAUSES_COPY)
auto_causes_copy: This lambda has an unspecified return type
copy: This return statement creates a copy.
```

[ coverity ] Fix coverity issue

---

test/unittest/models/unittest_models_recurrent.cpp

Fix coverity issue on
- /test/unittest/layers/layers_golden_recurrent.cpp
The other issues assigned have already been fixed.

[coverity] fix coverity issue @open sesame 03/25 15:19

---

test/tizen_capi/unittest_tizen_capi_dataset.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp
test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
test/unittest/compiler/unittest_compiler.cpp
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_nntrainer_appcontext.cpp
test/unittest/unittest_nntrainer_exe_order.cpp
test/unittest/unittest_nntrainer_graph.cpp
test/unittest/unittest_nntrainer_internal.cpp
test/unittest/unittest_nntrainer_lazy_tensor.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

Fix some typo in testcase. `duing` -> `during`, `TSETS` -> `TESTS`
Signed-off-by: heka1024 [heka1024@gmail.com](mailto:heka1024@gmail.com)

Fix typo in test

---

nntrainer/layers/addition_layer.cpp

- Enable multi batch incremental forwarding by looping batchwise

[layer] multi batch incremental forwarding

---

Applications/LLaMA/jni/main.cpp

- fix "temperature" operation
- add "top-k, top-p" option
- support batch mode

[application] update llm generate function

---

nntrainer/models/neuralnet.cpp

- The output was not considered multi batch input in incremental inference. Now it will return multi batch output.

[neuralnet] enable multi batch incremental inference

---

Applications/LLaMA/jni/main.cpp

add some options to 'generate' function of llm
- add naive repetition_penalty option
- add bad_words option

[Wait for #2532][application] add repetition_penalty to generate func @open sesame 04/06 10:40

---

api/ccapi/include/layer.h
nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/unittest_nntrainer_activations.cpp

- Now, user can use ELU activation function like torch or tensor flow.
Co-authored-by: Hanbyeol Kim kimhan0515@snu.ac.kr
Co-authored-by: Boseong Seo suzy13549@snu.ac.kr

Add ELU activation function @open sesame 04/15 20:15

---

Applications/YOLOv3/readme.md

[Docs] add yolov3 readme file

---

nntrainer/models/neuralnet.cpp

- This commit will handle when the model activation datatype is fp32

[neuralnet] bugfix multi batch incremental inference

---

api/ccapi/include/layer.h
nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/unittest_nntrainer_activations.cpp

- Now, user can use Mish activation function like torch or tensorflow.
**Self evaluation**:

Add Mish activation function

---

nntrainer/layers/acti_func.h

This PR resolves build issues that occur in `acti_func.h` when fp16 is enabled.

[bugfix] Fix build issues when fp16 is enabled

---

Applications/YOLOv2/PyTorch/dataset.py
Applications/YOLOv2/PyTorch/main.py

In order to train a large dataset, instead of loading the dataset into memory in advance, it was changed to a real-time loading method during training, and visualization code was added to check whether the training proceeded well.

[Application] update yolo v2 python for building pre-training model

---

.gitignore

add ".idea/" in gitignore file
- For ignore jetbrain's IDE

[Trivial] Update gitignore file

---

test/input_gen/gen_layer_tests.py

Added code stub to generate Swiglu layer's golden test data: `swiglu.nnlayergolden`

[goldendata] Added script to generate Swiglu data

---

Applications/YOLOv2/jni/main.cpp

register a custom layer that had been omitted on yolo v2.

[Application] yolo v2 bug fix

---

Applications/YOLOv2/jni/det_dataloader.cpp
Applications/utils/datagen/cifar/cifar_dataloader.cpp
api/capi/src/nntrainer.cpp
nntrainer/tensor/task_executor.cpp

This is imported from review.tizen.org
Change-Id: I80e2332711ae405488b39eaf060384e7490a7c45

Fixed the build error for gcc-14

---

README.md

Sync supported function with `README.md`

[Doc] Update activation function in `README.md`

---

.github/actions/check-rebuild/action.yml
.github/actions/check-rebuild/check_if_rebuild_requires.sh
.github/workflows/pdebuild.yml

Run pdebuild to test if it is not breaking PPA builds.

action: add Ubuntu pdebuild

---

.github/actions/check-rebuild/action.yml
.github/actions/check-rebuild/check_if_rebuild_requires.sh
.github/workflows/yocto.yml

Test if a pull request breaks Yocto build or not.

action: Yocto devtool test

---

.github/actions/check-rebuild/action.yml
.github/actions/check-rebuild/check_if_rebuild_requires.sh
.github/workflows/gbs_build.yml
.github/workflows/tizen.gbs.conf

Run gbs build for x64/x86/aarch64/armv7l Tizen.
This is imported from nnstreamer.git.

actions: gbs build test

---

nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/flatten_layer.cpp
nntrainer/layers/flatten_layer.h
test/unittest/layers/unittest_layers_flatten.cpp

- For now flatten layer flatten all dimension except batch. This commit will be able to flatten only the sub dimensions
Signed-off-by: hyeonseok <hs89.lee@samsung.com>

[layer] added start/end dimension in flatten layer

---

README.md

To prepare LF AI & Data project proposal, openssf best practice should be registered.

README: add openssf best practice badge.

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp

- This PR updates the DQN example.
- In the previous code, there was a bug: `copy mainNet to Target Net` was not written as intended.

[Application] Bug fix in RL example @open seasame 07/25 13:55

---

tools/README.md

This PR adds a guide for executing unit tests on the Android device.

[Doc] NNTrainer Tool Utilization Guide

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/meson.build
nntrainer/layers/weight_layer.cpp
nntrainer/layers/weight_layer.h
nntrainer/utils/base_properties.h
test/ccapi/unittest_ccapi.cpp
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_weight.cpp

- This layer contains only weights for building tensor-level graph

[Layer] add Weight Layer

---

nntrainer/layers/concat_layer.cpp

This PR renovates reshape/concatenation algorithms to facilitate efficient concatenation and split in ConcatLayer.
Previously, dimension 2 (height) was set as a standard axis to operate concatenation.
However, this causes an overhead by copying a tensor size of 1 when the concat dimension is 3 (width).
The new algorithm consolidates all dimensions to the first and last axes based on the concat dimension, sets the standard axis to be 3, and performs concat and split.
- Revise creating helper dimension logic in `finalize()`.
- Update `forwarding()` and `calcDeriv()` workflow to be efficient.
- Add descriptions for the new concat algorithm.
|key|avg|min|max|sum|
|------|---|---|---|---|
|calcDeriv(concat)|1.004153s|0.997947s|1.010360s|2.008307s| …

[Layer] enhance ConcatLayer algorithms for efficient concatenation and split

---

nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp

Accuracy issue observed while running SRLLM on GPU due to wrong gamma values being used.
Fixed the same

[GPU/OPENCL] RMSNorm Accuracy Fix

---

api/capi/doc/nntrainer_doc.h

Add MODULE in submodule name in doc file.

[ CAPI ] fix the Native API Ref Doc

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/fc_layer_cl.cpp
nntrainer/layers/cl_layers/meson.build

Removed `cl_context` dependencies.

[Wait for 2736 & 2744 ][update/gpu] Update FC layer on GPU with latest pipeline changes

---

nntrainer/models/neuralnet.cpp

Change Android Log type from ml_loge -> ml_logi
This log is not an error but simply indicates an iteration. 
However, it is being recorded as an error, so we will make changes accordingly.

[Trivial] Change Android Log type

---

Applications/MixedPrecision/jni/Android.mk
Applications/MixedPrecision/jni/Application.mk
Applications/MixedPrecision/jni/main.cpp
Applications/MixedPrecision/jni/meson.build
Applications/meson.build

Add Mixed Precision example on Application 
- this example can guide developer to handle fp16 example
- we can test & eval our model end-to-end 
- we can optimize base on this model

[Application] Add Mixed precision Application @open sesame 11/27 09:33

---

README.md
api/ccapi/include/optimizer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/optimizers/adamw.cpp
nntrainer/optimizers/adamw.h
nntrainer/optimizers/meson.build
test/ccapi/unittest_ccapi.cpp

This commit implements the AdamW algorithm in the form of an `Optimizer`.
Some (potential) further tasks include:
- Merging the implementations of Adam and AdamW, so that `AdamW` inherits from `Adam`
- Adding more unit tests

Add AdamW `Optimizer` @open sesame 12/04 16:19

---

Applications/LLaMA/jni/main.cpp
Applications/MixedPrecision/jni/main.cpp
Applications/Multi_input/jni/main.cpp
Applications/PicoGPT/jni/main.cpp
Applications/Resnet/jni/main.cpp
Applications/SimpleFC/jni/main.cpp
Applications/YOLOv2/jni/main.cpp
Applications/YOLOv3/jni/main.cpp
nntrainer/models/neuralnet.cpp

This PR aims to resolve #2830.
- This PR adds an error log when setOptimizer is called after initialization.
- This PR updates some undesirable codes of example application to check its setOptimizer status.

[ Log ] Adding an error log when setOptimizer is called after initialization

---

README.md

- Add reviewers and welcome dkjung, haehun
- Related PR: #2871

[ trivial ] Add reviewers

---

test/unittest/unittest_blas_kernels_cl.cpp

- `Unittest_blas_kernels_cl.cpp` updated with fp16 unittests.
- Several unittests added for `SGEMM`, `SGEMV` and `Addition` for fp16.

[GPU] Added multiple fp16 unittests for blas kernel operations.

---

Applications/Android/NNDetector/app/src/main/jni/dataloader.cpp
Applications/Android/NNDetector/app/src/main/jni/dataloader.h
Applications/Android/NNDetector/app/src/main/jni/simpleshot.cpp
Applications/Android/PicoGPTJNI/app/src/main/jni/picogpt.cpp
Applications/Android/ResnetJNI/app/src/main/jni/dataloader.cpp
Applications/Android/ResnetJNI/app/src/main/jni/dataloader.h
Applications/PicoGPT/jni/main.cpp
Applications/ProductRatings/jni/main.cpp
Applications/SimpleFC/jni/main.cpp
Applications/YOLOv2/jni/det_dataloader.cpp
Applications/YOLOv3/jni/det_dataloader.cpp
api/capi/include/nntrainer_internal.h
api/ccapi/include/tensor_dim.h
nntrainer/dataset/dir_data_producers.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/embedding.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/preprocess_l2norm_layer.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_dim.cpp
test/unittest/integration_tests/integration_test_fsu.cpp

We're currently using uint type which is not C++ fundamental type (see https://en.cppreference.com/w/cpp/language/types) but GNU define. This PR replace all occurrences of uint with unsigned int - which is compatible across multiple operating systems
Signed-off-by: Grzegorz Kisala <gkisala@gmail.com>

[Windows] Replace uint with unsigned int @open sesame 01/22 16:36

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/uint_tensor.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

I tried all the possible kernels that I could think of like below:
```C++
void copy_s16(const unsigned int N, const int16_t *X, int16_t *Y) {
unsigned int i = 0;
unsigned int vec_elements = 8;
size_t len = N;
asm volatile("1: \n"
"ld1 {v0.8h}, [%[X]], #16 \n"
"st1 {v0.8h}, [%[Y]], #16 \n"
"subs %[len], %[len], #8 \n"
"bgt 1b \n"
: [X] "+r"(X), [Y] "+r"(Y), [len] "+r"(len)
:
: "v0", "memory");
for (; i < N; ++i) {
Y[i] = X[i];
}
}
void copy_s16(const unsigned int N, const int16_t *X, int16_t *Y) {
unsigned int i = 0;
unsigned int vec_elements = 8;
size_t len = N;
unsigned int N8 = (N >> 3) << 3;
unsigned int N16 = (N >> 4) << 4;
unsigned int N32 = (N >> 5) << 5;
for(; i < N32; i += 32){
int16x8x4_t vec = vld1q_s16_x4(X);
vst1q_s16_x4(Y, vec);
X += 32;
Y += 32;
}
for(; i < N16; i += 16){ …
```

[ neon ] Implement copy_s16, copy_u16  function

---

docs/getting-started.md
docs/how-to-run-examples.md
packaging/nntrainer.spec

The project's meson version has already been updated to 0.55.0 or
higher, but documentation has not been updated yet. so I updated it.

[docs] update meson version document

---

nntrainer/app_context.cpp
nntrainer/models/neuralnet.cpp
nntrainer/tensor/memory_data.h

This pull request aims to resolve various Coverity issues. The following warning group IDs are addressed:
Warning Group ID
- #1832819
- #1833528
- #1834338
- #1837520
- #1839030
- #1841393
- #1837925
- #1838882
- #1839129
- #1839950
- #1840581
- #1840832

[Coverity] resolve coverity issues

---

Applications/SimpleShot/task_runner.cpp

This commit is to address coverity #1840519.

[Coverity] Wrap main() with try-catch block (#1840519)

---

Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
api/ccapi/include/layer.h
nntrainer/graph/graph_node.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/nntrainer_logger.cpp

- Resolve exception handle issue by adding try catch statement
- Remove noexcept

[coverity] resolve exception handle issue @open sesame 02/08 11:04

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This pull request modifies the unsigned int type Tensor class to include scale factors in memory.

[Tensor] Scale factors support for unsigned int type

---

docs/getting-started.md

- Along with the update of a07ed7f474ff97c4e399edab292581132bc48394, guide for getting started should be updated.
- This commit followed 4e904a689d8cc153550b3013df585a4fdad8eea1.
Build test: [ ]Passed [ ]Failed [X]Skipped
Run test: [ ]Passed [ ]Failed [X]Skipped

[ Doc ] Add install submodule step to `getting-sarted.md`

---

Applications/Multi_input/jni/multi_loader.cpp
Applications/YOLOv3/jni/det_dataloader.cpp
nntrainer/utils/util_simd.cpp

added missing header files for tizen branch

[trivial] add header files @open sesame 02/13 17:20

---

nntrainer/graph/network_graph.h
nntrainer/layers/layer_node.cpp
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/quantizer.h
nntrainer/tensor/short_tensor.h
nntrainer/tensor/uint_tensor.h

fixed some un-initialization issues

[coverity] fix un-initialization issues

---

Applications/ProductRatings/jni/main.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_node.cpp
nntrainer/nntrainer_error.h
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/quantizer.h
nntrainer/tensor/short_tensor.h
nntrainer/tensor/uint_tensor.h

I've fixed some exception issues.
However, apart from these modifications, there are still some thread_safety issues remaining in svace, and we need to discuss those issues together. I will share the relevant information at the upcoming meeting.

[svace] fix some exception issues

---

test/unittest/integration_tests/integration_test_fsu.cpp

Update Integration_test FSU case
- Label & Optimizer no longer need at inference case
- so update unit test

[UnitTest] Update Integration_test_fsu

---

nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

This pull request introduces utility functions that convert floating-point numbers to fixed-point numbers and exponents, and vice versa. Note that the fixed-point values are scaled to maximize precision in use. This enhancement allows for the integration of a third-party computation library.

[Util] Floating-point and fixed-point conversion

---

Applications/ProductRatings/jni/main.cpp
Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/quantizer.h
nntrainer/tensor/uint_tensor.h

[coverity] fix coverity & svace issues

---

Applications/ProductRatings/jni/main.cpp
nntrainer/tensor/swap_device.cpp

I tried to fix all critical issues except for false positives.

[cov] fixed coverity issues

---

Applications/LLaMA/jni/main.cpp
Applications/ProductRatings/jni/main.cpp
Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
Applications/YOLOv3/jni/main.cpp
nntrainer/dataset/dir_data_producers.cpp
nntrainer/tensor/task_executor.cpp

update exception handling for applications..

[tizen] fix svace&coverity issues in application

---

.github/workflows/android.yml
.github/workflows/codeql.yml
.github/workflows/daily_build.yml
.github/workflows/static.check.yml
.github/workflows/ubuntu_benchmarks.yml
.github/workflows/ubuntu_clean_meson_build.yml
.gitmodules
debian/control
debian/rules
debian/ruy.install
jni/Android.mk.in
jni/meson.build
meson.build
nntrainer/meson.build
packaging/nntrainer.spec
subprojects/iniparser.wrap
subprojects/ruy.wrap
test/jni/Android.mk
third_party/iniparser.wrap

This pull request enables the Ruy project to be built in NNTrainer across multiple platforms, specifically Ubuntu, Tizen, and Android, and supports both x86 and ARM processors.
For the Tizen and Ubuntu pdebuilds, we are currently using ruy.tar.gz, which contains the packaged Ruy sources, until the Ruy package becomes available.

Multi-Platform Build Support for Ruy Project in NNTrainer

---

api/ccapi/include/tensor_api.h
nntrainer/dataset/dir_data_producers.cpp

[tizen] fix coverity issues

---

nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp

This PR fix windows build (not only tests)

[Windows] Fix building tests

---

nntrainer/layers/gru.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/short_tensor.h
nntrainer/tensor/uint_tensor.h
tools/android_test.sh

This PR aims to enhance the NNTrainer Android build process by addressing compilation warnings and optimizing the android test script for improved performance.
- Warning Fixes: Resolved the compilation warnings that were hindering the build process.
- The android test script has been updated to run in parallel, significantly speeding up the testing process.

Enhance NNTrainer Android Build

---

Applications/LogisticRegression/jni/main.cpp
Applications/YOLOv2/jni/main.cpp

fix some coverity issues (exception handling issues)

[tizen] fix coverity issues in appication

---

nntrainer/layers/fc_layer.cpp

- Fix redundant code lines in `fc_layer`

[FC] Minor fix in FC layer

---

.github/workflows/android.yml
.github/workflows/daily_build.yml
.github/workflows/gbs_build.yml
.github/workflows/pdebuild.yml
.github/workflows/ubuntu_benchmarks.yml
.github/workflows/ubuntu_clean_meson_build.yml
.github/workflows/windows.yml
.github/workflows/yocto.yml

Add gitaction Runner : Ubuntu 24.04
- daily_build
- benchmakrs
- clean meson build
Resolves:
- #2943 

[CI] Add gitaction runner : Ubuntu 24.04

---

nntrainer/tensor/tensor.h

In tensor apply operation there were error in data type check. This PR fix checking output data type

[Fix] Fix tensor data type check .

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/short_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h

This pull request decisively enhances the tensor read and save functionality. It ensures that the child class can override the read and save functions with its own implementation, thereby providing greater flexibility in managing data alignment.

[Tensor] update read/save functionality

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h

- Create BCQW on every dot opertion causes serious performance degradation.

[tensor] create bcq weight on read

---

Applications/SimpleFC/jni/main.cpp
Applications/YOLOv2/jni/reorg_layer.cpp
meson.build
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/cache_elem.cpp
nntrainer/tensor/cache_elem.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/task.h
nntrainer/tensor/tensor_pool.h
test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/memory/meson.build
test/unittest/memory/unittest_cache_pool_fsu.cpp

**First of all, Sorry for Large PR.** 
I know that large PR can be difficult to review, but many parts are related and need to merge together. i tried to write detailed descriptions for each commit. so please refer them
**In This PR**
---- 
To reduce memory usage during inference by utilizing FSU, and to minimize speed degradation by performing loading during forwarding, changed to use shared memory. and ensure the existing swap in training mode is also performed normally.
**Commit 1:** [[FSU] Update FSU Forwarding (Load) Logis](https://github.com/nnstreamer/nntrainer/commit/41f926e2d097f3ae60a9227a0eaecf5664eaeddb) 
- Change FSU Forwarding Logic ( Load weight with look ahead)
**Commit 2:** [[FSU] Update swap device & cache element](https://github.com/nnstreamer/nntrainer/commit/18a64b2b21 …

[FSU] Apply FSU on CPU with Shared & memcpy-free

---

nntrainer/tensor/cpu_backend/arm/hgemm/hgemm_noTrans.cpp
nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp

- AS-IS : (alpha == 1.F)
- TO-BE : std::fpclassify(alpha- 1.f) == FP_ZERO

[ trivial ] Apply proper float comparison in arm backend

---

Applications/LLaMA/README.md
Applications/LLaMA/jni/main.cpp

In recent LLaMA implementations, unused MULTIPLE_OF parameter has been
removed and replaced with an intermediate_size parameter in the same
format as HuggingFace.
Additionally, It was modified to pass the weight, vocab, and merge paths
as parameters during app execution and update document.

[Application] Refactoring llama application

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h

- Added absolute tensor operation for fp32 and fp16
- Added tangent tensor operation for fp32 and fp16

[Tensor] Add absolute & tangent tensor operation

---

meson.build
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/integration_tests/meson.build
test/unittest/models/models_test_utils.cpp

Merge FSU Feature & Context, Context Data and Context Allocator
This PR will Merge and fix some issue : This PR is Include Below PR's commits
- #3048 
- #3021 
- #2984 
After Merge This PR, Okay to Close Other PR

[FSU][Context] Merge FSU with new Context, Support BCQW

---

Applications/LLaMA/jni/main.cpp
nntrainer/tensor/meson.build
nntrainer/utils/base_properties.h
tools/package_android.sh

This PR adds Tensor_Type property. Previously there is Tensor_Type
Property but it is more like Tensor_DataType like UINT8, UINT4. This
Tensor_Type defines Tensor usage like WEIGHT, IN_TENSOR, OUT_TENSOR,
MAX_IN_TENSOR, MAX_OUT_TENSOR. ( It also includes life span
information as well )

[ Property ] Add Tensor_Type

---

meson.build

- apply the cmake option to windows too

[meson] add CMAKE option to windows too

---

nntrainer/cl_buffer_manager.cpp
nntrainer/cl_context.cpp
nntrainer/cl_context.h
nntrainer/context.h
nntrainer/engine.h
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/layer_impl_cl.h
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/opencl/opencl_context_manager.cpp
nntrainer/opencl/opencl_program.cpp
nntrainer/tensor/cl_operations/attention_kernels.cpp
nntrainer/tensor/cl_operations/attention_kernels.h
nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/unittest/meson.build
test/unittest/unittest_attention_kernels_cl.cpp
test/unittest/unittest_blas_kernels_cl.cpp

This pull request (PR) addresses several OpenCL errors related to ClContext, OpenCL kernels, and other components. The patch consolidates the ClContexts into a single instance, which has now been integrated into the Engine object. Additionally, the GPU test cases have been refactored to enable tests when FP16 is not in use.
1. [Test] Enable OpenCL full precision only unit test
2. [ClContext] Streamlining OpenCL Context Management
3. Bug Fix: OpenCL Kernel Creation Issues in ClContext

[Wait for #3069]Consolidation and Bug Fixes for OpenCL Context Management

---

nntrainer/compiler/tflite_interpreter.cpp

This PR fix releasing of no heap allocated memory. This problem was found and fixed while attempt to move to c++20 on linux. Since decision was made to hold on with c++20 upgrade I'm adding this fix as separate PR.

Fix releasing no heap allocated memory

---

nntrainer/tensor/swap_device.cpp

In this PR
----
[FSU] Update FSU getBuffer (memcpy)
Update MMAP offset, read size calc for support various weight size
- it will use memcpy for support MMAP from not aligned size
This PR include Previous @EunjuYang change 
- #3071 

[FSU] Update FSU getBuffer (memcpy)

---

nntrainer/layers/layer_context.h

added getInputDataType function to layer_context.h

[context] add "getInputDataType" function to layer_context.h

---

nntrainer/tensor/meson.build
tools/package_android.sh

This pr enables to support additional arguments for android in build script.

[ Android ] update to support additional argument

---

debian/nntrainer-dev.install
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/utils/meson.build
nntrainer/utils/mman_windows.cpp
nntrainer/utils/mman_windows.h
packaging/nntrainer.spec
windows-native.ini

This PR add mmap support to Windows

[Windows] Add mmap support

---

nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/tensor/cl_operations/attention_kernel_strings.cpp
nntrainer/tensor/cl_operations/attention_kernels.cpp
nntrainer/tensor/cl_operations/attention_kernels.h
nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

This PR updates the creation of the OpenCL buffer to reuse pre-defined buffers in ClBufferManager.

[OpenCL] Update Buffer Creation

---

.github/workflows/ubuntu_clean_meson_build.yml
.github/workflows/yocto.yml

Update Yocto Build
- git action runner 20.04 is removed
- update yocto build scripts (get from nnstreamer)

[ci] update yotco build @open sesame 04/22

---

nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/utils/mman_windows.cpp

This PR fix error code returned by mmap on Windows and add return type checking for munmap

[Fix] Fix mmap return in case of error

---

docs/getting-started-windows.md
docs/getting-started.md

Add Getting started guide for Windows

[Windows] Add getting started guide

---

test/unittest/unittest_blas_kernels_cl.cpp

This PR refactors the OpenCL BLAS kernel unit test.

[Test] Refactor OpenCL BLAS kernel tests

---

test/unittest/unittest_nntrainer_tensor.cpp
tools/package_android.sh

This PR resolves the Android build error when compiling the tensor unit test.
This patch also changes the Android package script to enable OpenCL.

[bugfix] Android build error

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
test/unittest/unittest_nntrainer_tensor.cpp

Try to replace shared_ptr with unique_ptr if possible
1. Better control over memory ownership
2. Multi-thread performance
See good explanation of why we should use unique_ptr over shared_ptr here
https://ddanilov.me/shared-ptr-is-evil/

[Performance] Avoid using shared_ptr.

---

.gitmodules
jni/Android.mk.in
jni/meson.build
jni/prepare_ggml.sh
meson.build
meson_options.txt
nntrainer/meson.build
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
packaging/nntrainer.spec
subprojects/ggml.wrap
subprojects/packagefiles/ggml/0001-Export-some-internal-methods.patch
test/jni/Android.mk
test/unittest/meson.build
test/unittest/unittest_nntrainer_cpu_backend.cpp
tools/android_test.sh
tools/package_android.sh
windows-native.ini

[GGML] Add GEMM and GEMV for Q4_0 and Q4_K quantization using ggml - rebase

---

api/ccapi/include/tensor_dim.h
nntrainer/layers/layer_context.h
nntrainer/models/model_common_properties.h
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/q4_k_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor_dim.cpp
nntrainer/tensor/uint4_tensor.h
nntrainer/utils/base_properties.h
test/unittest/unittest_nntrainer_graph.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- This PR updates Q4_K Tensor as Weight
- Add unittest for Q4_K dot (with ggml)

[Wait for #3132, #3176] Q4_K Weight 

---

subprojects/ONNXConverter/README.md

Added a new directory for independent ONNX Converter development along
with background knowledge documentation for new contributors.
The documentation covers `graph compilation process in nntrainer`.

[onnx] add new directory and readme for onnx converter

---

nntrainer/models/neuralnet.cpp

In This PR
---- 
Fix FSU Off & fsu_look_ahead given case -> try to load weight from disk,flash bug
For accurate operation, it is necessary to ensure that the FSU option is enabled and load the data up to the Look Ahead value. However, in the current code, even if FSU is turned off, if the user has set a Look_Ahead value, it attempts to load it. Although the actual loading action is not performed because the Cache_loader is not created, code handling this logic is also required at the Neuralnet level.

[FSU] Bugfix on FSU-OFF & Look_ahead Given Case

---

nntrainer/tensor/cache_elem.cpp
test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/integration_tests/meson.build

Add FSU Unittest for various weight_act type
- Add FP32-FP32 case
- Add various feature type
- 
*Disable Profile until, new profiler enabled

[FSU][Unittest] Add FSU Unittest

---

nntrainer/models/neuralnet.cpp
nntrainer/utils/meson.build

[[Build] Fix BS_thread Util sources]
- Add bs_thread_pool_manager.cpp in util_sources
- Bug fix on Load Logic 

[Build] Fix BS_thread Util sources & Load bugfix

---

debian/nntrainer-dev.install
meson.build
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
packaging/nntrainer.spec

- Sort installation directory / file under OS / architecture

[ Tizen ] Fix tizen build error related to ggml

---

nntrainer/layers/layer_node.cpp
nntrainer/mem_allocator.cpp
nntrainer/models/model_loader.h
nntrainer/optimizers/optimizer_wrapped.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/swap_device.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/uint4_tensor.cpp
nntrainer/utils/util_func.cpp

Clang warnings found few major bugs in code. This PR fix found problems.

[Fix] Fix major warnings found by clang

---

.gitignore

After modifying the option to use ggml in nntrainer and building it, 
the cloned ggml directory was not being ignored.
Therefore, added the ggml directory to .gitignore.

[Git] Update git ignored

---

nntrainer/tensor/bcq_tensor.cpp

- This commit fixes some bugs in BCQTensor

[Bugfix] Bugs in BCQTensor are fixed

---

test/unittest/layers/unittest_layer_node.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- finalize_07_n unittest is deprecated.
- Update the finalized_07_n to make it valid for the updated version
- This PR updates time consuming unit test cases

[CI] fix crashed unit test case & update time consuming unit test

---

.github/PULL_REQUEST_TEMPLATE.md

- None
<details><summary> [Template] Update PR Template </summary><br />
Update PR Template for more detail explain
</details>
- Update PR Template for more clear explaination, give detail to Reviewers
----
<details><summary>{commit-1}</summary><br />
{commit message}
Signed-off-by: {your_name} <{your_email}>
</details>
<details><summary>{commit-2}</summary><br />
{commit message}
2. Run …

[Template] Update PR Template

---

Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.h
Applications/Custom/mae_loss.h
Applications/Custom/momentum.h
Applications/Custom/rnnt_loss.h
Applications/Multi_input/jni/multi_loader.cpp
Applications/YOLOv2/jni/yolo_v2_loss.h
Applications/YOLOv3/jni/yolo_v3_loss.h
Applications/utils/datagen/cifar/cifar_dataloader.cpp
Applications/utils/datagen/cifar/cifar_dataloader.h
linux-native-clang.ini
meson.build
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/dataset/random_data_producers.cpp
nntrainer/graph/graph_core.h
nntrainer/graph/network_graph.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/memory_pool.h
nntrainer/tensor/quantizer.h
nntrainer/utils/util_func.cpp
test/nntrainer_test_util.cpp
test/unittest/layers/layers_common_tests.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_positional_encoding.cpp
test/unittest/memory/meson.build
test/unittest/memory/unittest_memory_planner.cpp
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_nntrainer_tensor.cpp

This PR fix all warnings reported by clang compiler It will also ensure that continues integration will fail in case someone introduce any new warnings

[Quality] Fix all warnings reported by clang

---

nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
test/unittest/unittest_nntrainer_cpu_backend.cpp

- add missing dox descriptions
- DONE : throw fallback functions if NYI
- MAYBE : ggml provides raw-implemenations as well. introduce them directly on internal functions?

[ cpu_backend ] add missing dox descriptions & internal fallback functions

---

nntrainer/opencl/opencl_buffer.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp

This PR resolves an error in the HGEMM kernel for the case where matrix A is transposed.

Bugfix: OpenCL HGEMM kernel for TransA

---

Applications/LLaMA/PyTorch/weights_converter.py

- This patch updates weight conversion python script to support lora.
- This saves all of the weights in the same file.
- This will be updated after loading LoRA scheme is updated
Build test: [ ]Passed [ ]Failed [X]Skipped
Run test: [ ]Passed [ ]Failed [X]Skipped

[App] Update weight conversion script to support lora

---

nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
nntrainer/tensor/cpu_backend/x86/avx2_impl.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
test/unittest/unittest_nntrainer_cpu_backend.cpp

Add AVX implementation of methods ele_mul() and ele_add()
Speed up about 8 times.
Unit tests results:
[INFO] ele_mul: TEST CNT: 20, N: 3072, i_stride: 0, Average ref_time: 1942 ns, Average mul_time: 290 ns
[INFO] ele_mul: TEST CNT: 20, N: 3072, i_stride: 1, Average ref_time: 1900 ns, Average mul_time: 317 ns
[INFO] ele_add: TEST CNT: 20, N: 3072, i_stride: 0, Average ref_time: 1808 ns, Average add_time: 230 ns
[INFO] ele_add: TEST CNT: 20, N: 3072, i_stride: 1, Average ref_time: 2076 ns, Average add_time: 297 ns

Add AVX implementation of ele_mul() and ele_add().

---

.gitignore
.gitmodules
build_windows_resources.py
meson.build
nntrainer/opencl/opencl_loader.cpp
subprojects/benchmark.wrap
subprojects/googletest.wrap
subprojects/iniparser.wrap
windows-native-clang.ini
windows-native.ini

This PR add using of prebuild windows resources

Add windows resources.

---

CONTRIBUTING.md

Update official documented committer list to prepare LFAI proposal.
Ref: https://gist.github.com/myungjoo/80b050a0f23d4c31b31dbbaf9a5bd7c2

contributing: update the committers.

---

nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp

- Implement Q6 GEMV/GEMM without if(M==1)
- Remove unused includes
- Change number of threads to match other function
Signed-off-by: mwlasiuk <testmailsmtp12345@gmail.com>

Rework of Q6 GEMM

---

api/ccapi/include/model.h
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/addition_layer.cpp
nntrainer/layers/addition_layer.h
nntrainer/layers/input_layer.cpp
nntrainer/layers/input_layer.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/multiout_layer.cpp
nntrainer/layers/multiout_layer.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/var_grad.h

- Until now attention and input/output for autoregressive model is allocated by maximum time step. This commit will allocate memory for the input timestep.

[model] update time step

---

nntrainer/tensor/cpu_backend/README.md

None 
<details><summary>[Docs] simple update to improve readability</summary><br />
- Update Readme on cpu_backend
1. Build test: [ ]Passed [ ]Failed [x]Skipped
2. Run test: [ ]Passed [ ]Failed [x]Skipped
</details>
- Update the README file for the `cpu_backend/` directory to enhance its clarity and readability.

[Docs] simple update to improve readability

---

nntrainer/opencl/opencl_context_manager.cpp

- Select Intel GPU by device type and vendor ID
Sample output (no Intel GPU) :
``` bash
[NNTRAINER INFO  2025-07-03 13:37:49] (C:/proj/nntrainer-mw/nntrainer/opencl/opencl_context_manager.cpp:CreateDefaultGPUDevice:134) Collecting OpenCL platforms ...
[NNTRAINER INFO  2025-07-03 13:37:49] (C:/proj/nntrainer-mw/nntrainer/opencl/opencl_context_manager.cpp:CreateDefaultGPUDevice:156) Collecting OpenCL devices for platform 0 / 3 ...
[NNTRAINER INFO  2025-07-03 13:37:49] (C:/proj/nntrainer-mw/nntrainer/opencl/opencl_context_manager.cpp:CreateDefaultGPUDevice:156) Collecting OpenCL devices for platform 1 / 3 ...
[NNTRAINER INFO  2025-07-03 13:37:49] (C:/proj/nntrainer-mw/nntrainer/opencl/opencl_context_manager.cpp:CreateDefaultGPUDevice:156) Collecting OpenCL devices for platform 2 / 3 ... …
```

Add OpenCL Intel GPU selection

---

nntrainer/cl_context.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/float_tensor.cpp
test/unittest/unittest_blas_kernels_cl.cpp

This PR implements the Q6_K GEMV OpenCL kernel.
|Engine|avg time|
|------|---|
|GPU| 0.276074 ms|
|CPU| 6.41582 ms|
|Engine|avg time|
|------|---|
|GPU| 0.476897 ms|
|CPU| 14.2969 ms|
|Engine|avg time|
|------|---|
|GPU| 1.97957 ms|
|CPU| 18.3347 ms |
|Engine|avg time|
|------|---|
|GPU| 5.64532 ms |
|CPU| 18.3347 ms |

[OpenCL] Add Q6_K GEMV kernel 

---

nntrainer/opencl/opencl_program.cpp

This PR adds compiler flags to leverage compiler optimization.

[OpenCL] Add Compiler Flags for Optimization

---

test/unittest/integration_tests/integration_test_loss.cpp

- Remove unused tflite header from unittest
Signed-off-by: Hyeonseok Lee <hs89.lee@samsung.com>

[bugfix] remove unused header

---

nntrainer/tensor/cl_operations/attention_kernels.cpp
nntrainer/tensor/cl_operations/attention_kernels.h
nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
nntrainer/tensor/cl_operations/attention_kernels_templates.h

- Moved repeating code to template
As #3299 but for attention kernels
Signed-off-by: mwlasiuk <testmailsmtp12345@gmail.com>

Remove repeating code in attention kernels

---

docs/how-to-run-example-android.md

<details><summary>Updated the Android guide</summary><br />
Signed-off-by: Paweł Dębski <p.debski2@samsung.com>
</details>
- Updated the documentation for building the project for Android
Signed-off-by: Paweł Dębski <p.debski2@samsung.com>

[Docs] Updated the guide for Android

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/swiglu_cl.h
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_templates.h
test/unittest/unittest_blas_kernels_cl.cpp

This commit introduces mapping logic to the RMS Norm OpenCL kernel following kernel execution.
Additionally, this patch updates the unit tests for the OpenCL BLAS kernels.

Fix: RMS Norm OpenCL Kernel with Mapping Logic and Unit Test Updates

---

nntrainer/app_context.cpp
nntrainer/layers/meson.build
nntrainer/optimizers/adamw.cpp
test/ccapi/unittest_ccapi.cpp
test/unittest/layers/meson.build
test/unittest/models/unittest_models.cpp

- Restore mol attention layer and its unittest
Signed-off-by: Hyeonseok Lee <hs89.lee@samsung.com>

[layer] add mol attention

---

Applications/CausalLM/causal_lm.cpp
Applications/CausalLM/causal_lm.h
Applications/CausalLM/layers/embedding_layer.cpp
Applications/CausalLM/layers/mha_core.cpp
Applications/CausalLM/layers/mha_core.h
Applications/CausalLM/layers/qwen_moe_layer.cpp
Applications/CausalLM/layers/qwen_moe_layer_cached.cpp
Applications/CausalLM/layers/qwen_moe_layer_fsu.cpp
Applications/CausalLM/layers/reshaped_rms_norm.cpp
Applications/CausalLM/layers/rms_norm.cpp
Applications/CausalLM/layers/tie_word_embedding.cpp
Applications/LLaMA/jni/swiglu.cpp
nntrainer/layers/addition_layer.cpp
nntrainer/layers/fc_layer.cpp
nntrainer/models/neuralnet.cpp

- none
<details><summary>[ CausalLM ] enable kv cache save / load</summary><br />
This PR enables the KV cache save / load for causallm.
Resolves:
</details>

[ CausalLM ] enable kv cache save / load

---

Applications/CausalLM/build_android.sh
Applications/CausalLM/install_android.sh

<details><summary>[CausalLM] Update script (sync with ggml remove)</summary><br />
- This patch updates build & install script
- This patch patch removes ggml-related .so and debugging option
</details>
- This patch updates build & install script
- This patch patch removes ggml-related .so and debugging option

[CausalLM] Update script (sync with ggml remove)

---

nntrainer/tensor/cl_operations/blas_kernels.cpp

Signed-off-by: Piotr Pokorski <p.pokorski@samsung.com>

Fix build after merge due to not renamed kernel name

---

nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp

None
<details><summary>Fix: Tail Handling Bug in SwiGLU AVX2 Kernel</summary><br />
This pull request addresses a bug related to tail handling in the SwiGLU AVX2 kernel. The following issues in the implementation have been identified:
- Block conditions incorrectly use < instead of <=, causing exact multiples of 16 or 8 to be skipped.
- The final remainder check is written as i > N, but it should be i < N.
Signed-off-by:  Donghyeon Jeong <dhyeon.jeong@samsung.com>
</details>
- Fix: Tail Handling Bug in SwiGLU AVX2 Kernel
Signed-off-by:  Donghyeon Jeong <dhyeon.jeong@samsung.com>

Fix: Tail Handling Bug in SwiGLU AVX2 Kernel

---

Applications/CausalLM/layers/gpt_oss_moe_layer_cached.cpp

<details><summary>[CausalLM] updeate gpt-moe-cached to support MM</summary><br />
- This patch updates gpt_oss_moe_layer_cached.cpp to support MM operation for prefill.
- This patch accelerates the prefill speed in gpt-oss-20b
</details>
- This patch updates gpt-moe-cached to use MM instead of MV in prefill time.
- This patch copy input tensors to be processed with the same expert into one contiguous matrix to be processed with MM operation.
- Performance improvement
- log
```
X86 AS-IS)
=================[ LLM with NNTrainer ]===================
prefill: 78 tokens, 4753 ms, 16.4107 TPS
generation: 1024 tokens, 158610 ms, 6.45609 TPS …
```

[CausalLM] updeate gpt-moe-cached to support MM

---

.gitignore
Applications/CausalLM/causal_lm.cpp
Applications/CausalLM/causal_lm.h
Applications/CausalLM/layers/gpt_oss_moe_layer.cpp
Applications/CausalLM/layers/gpt_oss_moe_layer_cached.cpp
Applications/CausalLM/layers/mha_core.cpp
Applications/CausalLM/main.cpp
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h

- #3487 
- #3490 
- #3493 
<details><summary> [LLM] Implement Multiturn - CausalLM </summary><br />
Implement on CausalLM
- adjust from-to to handle Multiturn(KV Cache)
</details>
- Enable Multiturn in CausalLM Application
- Add #ifdef NPU condition at allocate rpc_mem ( use only NPU_ENABLE )

[CausalLM][Android App] Enable Multiturn
