nnstreamer/nntrainer

Applications/Classification/jni/main.cpp
Applications/Classification/res/Classification.ini
Applications/LogisticRegression/jni/main.cpp
Applications/Training/jni/main.cpp
include/tensor.h
src/layers.cpp
src/tensor.cpp

Currently only element by element calculation is available with
applyFunction. However, there are cases to deal with whole data of
tensor like softmax. Due to this reason, applyFunction is modifed.

Modify applyFunction for Tensor data type @open sesame 03/25 15:28

---

Applications/KNN/README.md
Applications/ReinforcementLearning/DeepQ/README.md
Applications/Training/README.md

fix image url

---

Applications/ReinforcementLearning/DeepQ/jni/gym_binding.cpp
Applications/ReinforcementLearning/DeepQ/jni/include/gym/gym.h
Applications/ReinforcementLearning/DeepQ/jni/main.cpp

Fix the compile warnning messages. Depending on compile options, it
could be errors.

Fix compile warnning messages

---

.github/CODEOWNERS

Modify CODEOWNERS

---

debian/rules
packaging/nntrainer.spec
packaging/run_unittests.sh

[TEST] Add testing during packaging @open sesame 04/03 17:27

---

api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
test/tizen_capi/unittest_tizen_capi.cpp

- Add Construction of Nerual Network Model with Configuration File.
. ml_nnmodel_construct_with_conf()
. Add one positive and one negative tests

[API] Add Neural Network Model Construction with Configuration File

---

Applications/Classification/jni/Android.mk
Applications/KNN/jni/Android.mk
Applications/LogisticRegression/jni/Android.mk
Applications/ReinforcementLearning/DeepQ/jni/Android.mk
Applications/Training/jni/Android.mk
api/capi/src/nntrainer.cpp
jni/Android.mk
meson.build
meson_options.txt
nntrainer/meson.build
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/tensor.cpp
packaging/nntrainer.spec
test/tizen_capi/unittest_tizen_capi.cpp

Modify codes and buld for Logging

Enable Logging

---

packaging/nntrainer.spec
packaging/run_unittests.sh
test/tizen_capi/test_conf.ini
test/tizen_capi/unittest_tizen_capi.cpp

- Add test configuration file in test directory
- modify code to read the path correctly

[Test] Fix test bug

---

jni/Android.mk
nntrainer/include/layers.h
nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/include/util_func.h
nntrainer/meson.build
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/util_func.cpp
packaging/nntrainer.spec

- Add Optimizer Class and remove duplicated codes.
. Hyperparameters related with Optimizer class placed Optimizer
Class.
. OptParam, WeightDecayParam, OptType, WeightDecayType
- Seperate math functions in util_func.h/cpp

Add Optimizer Class & separate math functions

---

nntrainer/src/layers.cpp

Remove Duplicated Code @WeightInitialization Fuc.

Remove Duplicated Code @WeightInitialization

---

jni/Android.mk
nntrainer/src/databuffer.cpp
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/nntrainer_logger.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/tensor.cpp
nntrainer/src/util_func.cpp

Remove Duplicated Codes @UpdataData

Remove Duplicated Codes @UpdateData

---

nntrainer/include/neuralnet.h
nntrainer/include/nntrainer_error.h
nntrainer/src/neuralnet.cpp
packaging/run_unittests.sh
test/meson.build
test/unittest/meson.build
test/unittest/unittest_nntrainer_internal.cpp

Add Unit Test to evaluate NNTrainer interals

Add Unit Tests for the NNTrainer internal

---

Applications/Classification/jni/main.cpp
Applications/LogisticRegression/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/Training/jni/main.cpp
api/capi/src/nntrainer.cpp
nntrainer/include/databuffer.h
nntrainer/include/layers.h
nntrainer/include/neuralnet.h
nntrainer/include/nntrainer_logger.h
nntrainer/include/optimizer.h
nntrainer/include/tensor.h
nntrainer/include/util_func.h
nntrainer/src/databuffer.cpp
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/nntrainer_logger.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/tensor.cpp
nntrainer/src/util_func.cpp
test/unittest/unittest_nntrainer_internal.cpp

- Naming Rules
. namespace : lower-case (nntrianer)
. type names ( struct, class .. etc. ) : Pascal (TypeNames)
. variable names : snakes ( variable_names )
. enum : Upper Case with underbar
- using namespace nntrainer
. remove other namespace
- add #ifdef __cplusplus
Resolves:

Naming Rules & change namespace

---

README.md

This is a trivial patch that corrects typos and grammar.
Signed-off-by: Wook Song <wook16.song@samsung.com>

README: Correct typos and grammar

---

nntrainer/include/databuffer.h
nntrainer/include/layers.h
nntrainer/include/optimizer.h
nntrainer/src/databuffer.cpp
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
test/tizen_capi/test_conf.ini
test/unittest/unittest_nntrainer_internal.cpp

Nerual Network Initialization Unit Test including layer
initialization.

Add Unit Test Cases for Neural Network Initialization 

---

README.md

This patch updates Getting Started section to reflect the recent changes.
Signed-off-by: Wook Song <wook16.song@samsung.com>

[README] Update Getting Started

---

nntrainer/include/databuffer.h
nntrainer/src/databuffer.cpp
nntrainer/src/neuralnet.cpp
test/unittest/unittest_nntrainer_internal.cpp

Initilaize data buffer and set parameters from neural network.

Initialize data buffer when neural network initializes.

---

Applications/Classification/res/Classification.ini
nntrainer/include/databuffer.h
nntrainer/include/neuralnet.h
nntrainer/src/databuffer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
test/unittest/unittest_nntrainer_internal.cpp

Add train member function of NeuralNetwork Class.
- NeuralNetwork Class has DataBuffer instance to handle datas.
- New Keywords are introduced for specify data set
. TrainData, ValidData, TestData, LabelData
- DataBuffer instance is initialized with parameters from Neural
Network instance.
- In train function,
. Data Buffer instance is running ( collecting or generating data )
. get the data from Data Buffer instance.
. Backwarding
. Display progress ( Data Buffer member funciton )
. Validate if it is enabled.

Add train member function in NeuralNetwork Class.

---

Applications/Classification/jni/main.cpp
nntrainer/include/databuffer.h
nntrainer/src/databuffer.cpp
nntrainer/src/neuralnet.cpp

thow error exceptions from data buffer thread to main.
By this pr, program stops normally with proper error handling.

Throw error exception from thread

---

nntrainer/src/util_func.cpp

Currently it is not numerically stable.
it is more stable with this pr.

Modify softmax calculation to handle large values.

---

test/unittest/unittest_nntrainer_internal.cpp

Add unit test cases for math utilities functions

Add Unit Test Cases for math utilities function

---

README.md

* Update prerequisite
* Propose GIAG Build Environment
* Make example section

[README] Add some explanation

---

README.md

Add Reviewer

---

Applications/Classification/jni/main.cpp
Applications/Classification/jni/main_func.cpp
Applications/ReinforcementLearning/Environment/CartPole/cartpole.cpp
Applications/ReinforcementLearning/Environment/CartPole/cartpole.h
Applications/Training/jni/main.cpp
nntrainer/include/databuffer.h
nntrainer/include/layers.h
nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/nntrainer_logger.cpp
nntrainer/src/optimizer.cpp

Fix Svace results
. Critical 13, Major 10 Issues : [ 440232 ] ~ [ 440258 ]

[SVACE] Fix Svace Issues

---

nntrainer/src/neuralnet.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_nntrainer_internal.cpp

. Add more unittest
. modify replace string func to change multiple line

[UNIT TEST] Add more tizen unit test

---

nntrainer/src/neuralnet.cpp

[SVACE] Fix svace issues.

---

test/unittest/unittest_util_func.cpp

Add some unittests and fix errors for utils
- changed answer to be declaritive
- fix tolerence is calculated one way (should be wrapped with fabs)
- add prime test unit tests

Add unittest for utils_func

---

README.md

This commit is trivial. It is to fix a typo in README.md file.
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

doc: Fixed typos

---

test/unittest/meson.build
test/unittest/unittest_databuffer_file.cpp
test/unittest/unittest_nntrainer_internal.cpp

Separate databuffer_file unittest for further development (#61)

Separate databuffer_file unittest

---

test/unittest/meson.build

Fix Build Error when compile unittest
1. Build test:       [X]Passed [ ]Failed [ ]Skipped
2. Run test:         [X]Passed [ ]Failed [ ]Skipped

[UNITTEST] Fix Build Error

---

api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
test/tizen_capi/meson.build
test/tizen_capi/unittest_tizen_capi_layer.cpp

- Create / Delete Layer API
. ml_nnlayer_create(ml_nnlayer_h *nnlayer, ml_layer_type_e type);
: create InputLayer, FullyConnectedLayer instance
. ml_nnlayer_delete(ml_nnlayer_h *nnlayr)
: check validation and delete instance

[API] Create / Delete Layer API

---

test/tizen_capi/unittest_tizen_capi_layer.cpp

add set property layer unittest.

[API] add set property unittest

---

api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/layers.h
nntrainer/include/parse_util.h
nntrainer/src/layers.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp

Change setProperty ( enum , string ) --> setProperty(string, string)

[API] Change enum variable to string for better usage

---

api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/neuralnet.h
nntrainer/src/neuralnet.cpp

Implement layer addition API into model
. ml_nnmodel_add_layer( ml_nnmodel_h model, ml_nnlayer_h layer)

[API] add layer API

---

api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp
nntrainer/include/layers.h
nntrainer/include/neuralnet.h
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp

using std::shared_ptr to handle heap memory space

use std::shared_ptr instead of pointer of instance

---

test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp

add test case for ml_nnmodel_add_layer() api

[API] Add add layer API test case

---

Applications/Classification/res/Classification.ini
Applications/Classification/res/Classification_func.ini
Applications/Tizen_CAPI/Tizen_CAPI_config.ini
nntrainer/include/layers.h
nntrainer/include/optimizer.h
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp
test/unittest/unittest_nntrainer_internal.cpp

Make Weight Decay Parameter for Layer Class. From Now on Weight Decay
can be defined layer by layer.

[API] Weight Decay into Layer Class 

---

api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp
test/tizen_capi/meson.build
test/tizen_capi/unittest_tizen_capi_optimizer.cpp

create / delete optimizer
- type : sgd, adam, unknown
. ml_nnoptimizer_create(ml_nnopt_h opt, const char *type)
. ml_nnoptimizer_delete(ml_nnopt_h)

[API] create/delete neural network optimizer

---

api/capi/src/nntrainer.cpp
nntrainer/include/databuffer_file.h
nntrainer/include/databuffer_func.h
nntrainer/include/layers.h
nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/include/util_func.h
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/layers.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/nntrainer_logger.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/parse_util.cpp
nntrainer/src/tensor.cpp
nntrainer/src/util_func.cpp

Make system headears as system header

Make headers as system header

---

Applications/Classification/jni/main.cpp

remove new & delete when generate input data from image

[Fix] fix double free corruption

---

test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp

- add addLayer & optimizer unit test cases

[UNIT] add & modify unit test for optimizer and addlayer

---

Applications/Classification/jni/main.cpp
Applications/Classification/jni/main_func.cpp
Applications/Tizen_CAPI/main.c
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/bn_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/include/parse_util.h
nntrainer/include/tensor.h
nntrainer/src/bn_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/input_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp
nntrainer/src/tensor.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_nntrainer_internal.cpp

- add neural network model compile API with optimizer & hyper
parameter list
- ml_nnmodel_compile --> ml_nnmodel_compile_with_conf
- Change Weight Init Property as an Layer Property
: Delete wini paramenter in Initialize()

[ API ] neural network model compile API

---

Applications/Tizen_CAPI/main.c
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/databuffer.h
nntrainer/include/neuralnet.h
nntrainer/src/bn_layer.cpp
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/input_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/unittest_tizen_capi.cpp

Now two Options for the Train are available.
- ml_nnmodel_train_with_file(ml_nnmodel_h)
: Suppose every parameters are set from configuraiton and data
files ( Training : mandatory , Validataion : optional, Test :
optional )
- ml_nnmodel_train_with_file(ml_nnmodel_h, ...)
: Suppose using APIs for the set up the network configuration and
Network hyper parameters are given by arguments (key = value
format )

[ API ] Train API with data files

---

nntrainer/include/databuffer.h
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/neuralnet.cpp
test/tizen_capi/unittest_tizen_capi.cpp

Add check the size of buffer with maximum data and reset

[ API ] Add check the size of buffer & maximum data

---

Applications/Tizen_CAPI/c_api.c
Applications/Tizen_CAPI/meson.build

Add Classification example using C-APIs.
. Using data files to train, validate.
. Store data with the follow order in binary format.
'Features label Features label Features label ...'
. There are two layers, one for the input layer and the other is fc
layer.

[ Example ] Test Classification Example using C-APIs

---

debian/nntrainer-dev.install
jni/Android.mk
nntrainer/include/layer.h
nntrainer/include/tensor.h
nntrainer/include/tensor_dim.h
nntrainer/meson.build
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
packaging/nntrainer.spec

Split Tensor Dim Class from Tensor for better usability

Split Tensor Dim Class from Tensor @open sesame 05/22 14:54

---

nntrainer/include/databuffer.h
nntrainer/include/databuffer_file.h
nntrainer/include/tensor_dim.h
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/neuralnet.cpp
test/unittest/unittest_databuffer_file.cpp

change databuffer class to use TensorDim Class for input

Use TensorDim for databuffer

---

Applications/Classification/jni/main_func.cpp
nntrainer/include/databuffer_func.h
nntrainer/include/neuralnet.h
nntrainer/src/databuffer_func.cpp
nntrainer/src/neuralnet.cpp

It is not good to get the user data as 3D std::vector format. C does
not support it. Therefore it is much better to get the data as 1D
float array (float *). In this PR, re-define function pointer to get
data as float * format.

Using 1D array to get the data from user function

---

Applications/Classification/jni/Android.mk
Applications/KNN/jni/Android.mk
Applications/LogisticRegression/jni/Android.mk
Applications/ReinforcementLearning/DeepQ/jni/Android.mk
Applications/Training/jni/Android.mk
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
meson.build
nntrainer/include/databuffer.h
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/neuralnet.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/tizen_capi/unittest_tizen_capi.cpp

There is no API to get training, validation, test data from generator
function.
In this PR, introduces new training API with generator function.
. New Tizen API.
. Add Unit Test API with generator function.
. Add Test generator for future test.

[API] Training API with generator @open sesame 05/29 20:16

---

Applications/Tizen_CAPI/capi_file.c
Applications/Tizen_CAPI/capi_func.c
Applications/Tizen_CAPI/meson.build
nntrainer/src/databuffer_func.cpp

Demo example to train with Tizen C API Train with generator.
Add simple example to train 1 FC Layer neural network and get the
train & validation data from generator created by user.
Resolves:

[ Example ] Tizen C API Train with Generator Example

---

nntrainer/include/tensor.h
nntrainer/include/tensor_dim.h
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp

Currently Tensor class handles the dimension with it's own data
structure.
It is better to use TensorDim for this for consistency with other
classes of NNTrainer.

[ Refactor ] Tensor has TensorDim

---

nntrainer/src/databuffer.cpp

There is possible double erase vector due to the duplicate random
number generation.
In this PR, remove to use random number and erase just once.

[ Bug ] possible memory corruption by double erase

---

jni/Android.mk
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/layer.h
nntrainer/meson.build
nntrainer/src/conv2d_layer.cpp
nntrainer/src/parse_util.cpp
packaging/nntrainer.spec

This is the first draft of 2d convolution layer

[ Layer ] Draft of Conv2D Layer

---

nntrainer/include/tensor.h
nntrainer/src/tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- Add subtract_i operator
- Revise subtract operator
- Change precision in add_i / subtract_i test

[Tensor] Add `subtract_i(float)` operator @open sesame 06/09 19:12 (AFTER #131)

---

nntrainer/include/tensor.h
nntrainer/src/tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- Add `multiply_i(float)`
- Add `divide_i(float)`

[Tensor] Add multiply_i / divide_i (float) operator (AFTER #131)

---

nntrainer/include/tensor.h
nntrainer/src/tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- Add `divide_i(Tensor)`
- Add `multiply_i(Tensor)`

[Tensor] Add divide_i / multiply_i (Tensor)

---

nntrainer/src/conv2d_layer.cpp

This PR provides read & save Kenel and Bias

[ Conv2d ] save & read weight from file

---

nntrainer/src/conv2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

[ Conv2d ] save & read unittest

---

debian/control

for ubuntu, add flatbuffers-dev

[ CI ] Add Build Dependency flatbuffers-dev

---

test/input_gen/genInput.py

This PR provides layer input generator to evalute the layer
calculation.
[ To Do ]
Golden Test Result Generation should be added.

[ Test ] Input Generator @open sesame 06/11 16:53 

---

nntrainer/src/tensor.cpp

Meanwhile, current implementation (plain version) of `l2norm` is not
effcient and have potential overflow problem.
- Add blas operation to `Tensor::l2norm`
- Add fixme
- Run clang format

Add blas operation to `Tensor::l2norm`

---

nntrainer/src/fc_layer.cpp
nntrainer/src/neuralnet.cpp

Added missing weight decay loss into final loss for intermediate layers

[loss] Added missing weight decay loss

---

test/unittest/meson.build

- Add `conv2d_unittest.tar.gz` to be unzipped for ninja testing
- Add foreach loop to handle duplicated control flow

[meson] Remove duplicated bits from test/meson

---

nntrainer/include/pooling2d_layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/pooling2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

This PR provides seting property for pooling 2d layer.
which is,
. stride, padding, pooling_size, pooling type

[ Pooling2D ] Set Property for Pooling 2D Layer

---

nntrainer/include/layer.h
nntrainer/include/optimizer.h
nntrainer/src/layer.cpp

Added bugfix to object initialization

[layer] object initialization bugfix

---

nntrainer/src/util_func.cpp

Simplified sigmoid prime which IMO might also be more efficient

[util] Simplify sigmoidPrime

---

nntrainer/src/pooling2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

This PR includes initialization of pooling 2d layer.
. check input dimension
. set intput / output dimemsion
. allocate hidden layer

[ Pooling2D ] initialize pooling 2d layer

---

nntrainer/include/flatten_layer.h
nntrainer/include/layer.h
nntrainer/include/pooling2d_layer.h
nntrainer/meson.build
nntrainer/src/flatten_layer.cpp
nntrainer/src/parse_util.cpp
packaging/nntrainer.spec

This PR provides skeleton code for flatten layer.
- Header & implementation of flatten layer

[ Flatten ] Skeleton of Flatten Layer @open sesame 06/16 10:54

---

README.md

- Update readme.md prerequisites to include gcc version

[Docs] Update readme.md prerequisites @open sesame 16/16 18:39

---

nntrainer/include/databuffer.h
nntrainer/include/tensor.h
nntrainer/include/util_func.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/databuffer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/tensor.cpp
nntrainer/src/util_func.cpp
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_util_func.cpp

Adding determinism to the random number generators in the library
DataBuffer has multiple threads but single thread of train/valid/test
which run in sequence in my understanding
Note: this PR does not applies to the applications using their own random number generators
resolves #167

[init] Making random deterministic

---

nntrainer/src/flatten_layer.cpp

This PR provides the fowarding/copy function of Flatten Layer
. implement forwarding function
. implement copy function
Resolves:

[ Flatten ] forwarding / copy for Flatten Layer @open sesame 06/16 13:29

---

debian/nntrainer-dev.install
jni/Android.mk
nntrainer/include/fc_layer.h
nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/include/neuralnet.h
nntrainer/meson.build
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_layers.cpp

Added loss layer
This is added by the framework and is hidden from the user
This separates all the cost/loss related extra work from the layers
Resolves #101

[layer] Added loss layer

---

nntrainer/include/fc_layer.h
nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/include/tensor.h
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/parse_util.cpp

save and load the optimizer parameters as well for continued training
Add additive option in neural to continue training from previous training
Resolves #172

[save/load] save/load the optimizer parameters

---

nntrainer/include/neuralnet.h
nntrainer/src/neuralnet.cpp
test/tizen_capi/unittest_tizen_capi.cpp

This PR handles the case when a layer is added after a model has been compiled
Currently it has been set to give out error

[neuralnet] Handle adding layer with compiled model

---

test/tizen_capi/unittest_tizen_capi.cpp

Git merged new commits causing build errors
Need urgent merge

[urgent] [bugfix] Bug fix with git merge

---

nntrainer/src/pooling2d_layer.cpp

Android warning fix of comparing unsigned int values with signed values

[warning fix] unsigned int compare with int warning

---

test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_lazy_tensor.cpp

- Add test for activation layer

Add test for activation layer

---

nntrainer/include/pooling2d_layer.h
nntrainer/src/pooling2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

This PR provides backwarding process of Pooling 2D.
. backwarding for max pooling 2D
. backwarding for average pooling 2D
. backwarding global_max, global_averge is NYI.

[ Pooling2D ] backwarding

---

nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/include/util_func.h
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/util_func.cpp

Combined cross-entropy with sigmoid version for loss because of its higher stability
Note that this happens internally and is not exposed outside

[loss] Combined cross entropy with sigmoid @open sesame 06/22 19:54

---

nntrainer/include/activation_layer.h
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/src/activation_layer.cpp
nntrainer/src/bn_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
test/tizen_capi/meson.build
test/unittest/unittest_nntrainer_layers.cpp

- strip activation function related members in `layer`
- init activation property as `activation_layer`
2. Run test: [X]Passed [ ]Failed [ ]Skipped ~(conv::forward test need change)~
resolves #153 

Attach activation layer @open sesame 06/22 19:54

---

nntrainer/include/tensor.h
nntrainer/include/tensor_dim.h
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_lazy_tensor.cpp

Added equal comparison operation
Currently its based on fixed epsilon
Needs updation to use variable number of bits based on exponentiation as done in gtest
Related Issue: #202

[tensor/tensor_dim] Added equal comparison operation

---

nntrainer/src/fc_layer.cpp

Add the deleted statement about weight update from fc layer
Resolves #221
cc. @zhoonit

[fc_layer] Add the deleted statement

---

nntrainer/include/tensor.h
nntrainer/src/tensor.cpp

- Add stride
- Add checking is countigous flag to tensor
This patch is part of #217

Add stride and contiguous flag to tensor

---

nntrainer/src/conv2d_layer.cpp

fix calculate function parameters

[ Conv2D ] fix calculate parameter of optimizer

---

nntrainer/include/conv2d_layer.h
nntrainer/include/optimizer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/optimizer.cpp
test/unittest/unittest_nntrainer_layers.cpp

Update optimizer to handle a list of weights than weights and bias individually
as layers like RNN, LSTM will have more than just (w,b)

[optimizer] Optimizer to manage list of weights @open sesame 06/25 13:00

---

nntrainer/include/layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp

Support getWeights functionality equivalent to getGradients
Resolves #232

[layer] Support get weights

---

nntrainer/src/pooling2d_layer.cpp

This PR provides global max / global average.
. forwarding global_max / global_average
. backwarding global_max / global_average

[ Pooling2D ] global max / global average

---

test/unittest/unittest_nntrainer_layers.cpp

This PR provides unittest cased for backwarding about global_max &
global average
. global_max : forwarding / backwarding
. global_average : forwarding /backwarding

[ Pooling2D ] unittest cases for backwarding

---

api/capi/src/nntrainer.cpp

- Add a functor that returns `errno` to corresponding `exception` 
See also: #233 

Add exception boundary to capi @open sesame 07/03 11:09

---

test/input_gen/genInput.py

This PR add a python function that generates bn_layer forward/backward
pass.
Return value's order & contents are subject to change for the time
being.
Run python function

Prepare bn layer tc

---

.gitignore

ignore vscode configs and multiple vim backup files

[git] ignore vscode configs and multiple vim backup files

---

nntrainer/include/layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp

Add trainable feature for each layer which allows certain layers to just not train without affecting others

[layers] Add trainable feature

---

nntrainer/include/activation_layer.h
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/include/parse_util.h
nntrainer/include/pooling2d_layer.h
nntrainer/src/activation_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp

Added sensible defaults for the network initialization
This covers layers loss and optimizer properties
However defaults are not added for some of the core properties because they should be input by the user
Resolves #236

[network] Add sensible defaults

---

nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/include/pooling2d_layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/pooling2d_layer.cpp

This PR provides initialization of conv2d, pooling2d, flatten layer
for training configuraion file.
Also modified to update mutiple weights in the optimizer.

[ NETWORK ] initialize network for conv2d/pooling2d/flatten @open sesame 07/02 19:47

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/Tizen_CAPI/capi_file.c
Applications/Tizen_CAPI/capi_func.c
Applications/Tizen_CAPI/main.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/conv2d_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/optimizer.h
nntrainer/include/parse_util.h
nntrainer/include/tensor.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/parse_util.cpp
nntrainer/src/tensor.cpp
test/include/nntrainer_test_util.h
test/unittest/unittest_nntrainer_lazy_tensor.cpp

Now CI checks formatting. This patch formats every exisiting *.cpp *.h, *c
in the project.
~See also: #271~
Resolves #271 

Format everyfile @open sesame 07/08 13:55

---

nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- Add tensor address to the print
- Handle the case when tensor is too large
- Add test
See also: #270

Enhance Tensor print

---

nntrainer/include/activation_layer.h
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/flatten_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/include/optimizer.h
nntrainer/include/pooling2d_layer.h
nntrainer/include/util_func.h
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
test/unittest/unittest_nntrainer_internal.cpp
test/unittest/unittest_nntrainer_layers.cpp

[property] Add name property for layer

---

test/unittest/unittest_nntrainer_layers.cpp

This PR makes layer unittest more concise and fix some bugs.

Refactor layer unittest

---

Applications/Classification/jni/main.cpp
Applications/Classification/jni/main_func.cpp
Applications/LogisticRegression/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/Tizen_CAPI/capi_file.c
Applications/Tizen_CAPI/capi_func.c
Applications/Tizen_CAPI/main.c
Applications/Training/jni/main.cpp
api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/src/neuralnet.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_nntrainer_internal.cpp

Update C-API and corresponding code changes
Major Changes:
1. ml_nnmodel_compile_with_conf() replaced with ml_nnmodel_construct_with_conf().
This new function loads the model from the config file but does not initialize.
ml_nnmodel_compile() should be called after ml_nnmodel_construct_with_conf() before training.
2. ml_nnmodel_compile() does not take optimizer as an input.
Rather, use ml_nnmodel_set_optimizer() to set the optimizer for the model.
3. init() from neuralnet has been updated to loadFromConfig() and does not initialize the model anymore.
Rather call init() after loadFromConfig() to initialize.
This also allows updating the model config after loading model with loadFromConfig().
4. init(optimizer, args_list) has been replaced with init()
Rather call setOptimizer(optimizer) to …

[API] Update C-API @open sesame 06/08 13:02

---

nntrainer/src/conv2d_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/pooling2d_layer.cpp
nntrainer/src/util_func.cpp

Currently validation is not work. Because the dimension of hidden
tensor is different if we use one batch input.
This PR handle this issue.
Signed-off-by: jijoong.moon jijoong.moon@samsung.com

[wait for #288] Fix to run validation process during train 

---

Applications/Classification/res/Classification_new.ini
api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/test_conf.ini
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_nntrainer_layers.cpp

Support searching of layer by name in C-API
This is part of the more changes to support this functionality
Related issue - #260

[API] Search layer by name in C-API

---

Applications/Classification/jni/Android.mk
Applications/KNN/jni/Android.mk
Applications/LogisticRegression/jni/Android.mk
Applications/ReinforcementLearning/DeepQ/jni/Android.mk
Applications/Training/jni/Android.mk
Applications/mnist/jni/Android.mk
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/layer.h
nntrainer/include/optimizer.h
nntrainer/src/bn_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/optimizer.cpp

_~Current phase of this PR is more of a proposal. I'd like to get some reviews and **approval** before proceed since this contains major change in `Layer`~_
This PR propose an `UpdateableParam` to manage trainable param altogether so that we can get the weight related parameters  easily.
- Add `UpdatableParam`
- Change `Optimizer::apply_gradient` signature
- Attach `UpdatableParam` to manage weights in layers ~(NYI except for `fc_layer` to provide a concept)~

[Proposal] Add UpdatableParam to manage weights / gradients

---

test/unittest/unittest_nntrainer_layers.cpp

- BN layer tf fixture is merged to BNLayer fixture

Refactor bn layer test fixture

---

api/capi/src/nntrainer.cpp

ml_nnmodel_get_layer function was adding another layer in struct NeuralNetwork if layer wasnt found in layers_map
This function was supposed to only add layer in layers_map and not modify struct NeuralNetwork
This PR applies the above bug fix.
cc. @jijoongmoon

[API] Bug fix in C-API get_layer

---

api/capi/capi-nntrainer.pc.in
api/capi/meson.build
packaging/capi-nntrainer.manifest
packaging/nntrainer.spec

. rpm packaging of capi-nntrainer for tzien
related #265 
**Self evaluation:** 

[ API ] capi-nntrainer packaging

---

api/capi/include/nntrainer.h

[CAPI] Add ml_nnmodel_get_summary

---

Applications/mnist/Tensorflow/Training_Keras.py
Applications/mnist/Tensorflow/dataset.py
Applications/mnist/jni/main.cpp
Applications/mnist/res/mnist.ini

. MNIST Tensorflow Example to compare with nntrainer.

[ Application ] mnist with tensorflow

---

nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp

This PR expose activation layer by ini. As #308 handles props
automatically, there is no need to set else more.
See also #210

Enable activation layer in ini

---

nntrainer/src/databuffer_func.cpp
test/tizen_capi/meson.build
test/tizen_capi/unittest_tizen_capi_dataset.cpp

Add unittest fot the tizen c-api related to datasets

[CAPI] Added more unittests for tizen capi

---

api/capi/include/nntrainer_internal.h

Add functions to be supported later in the internal capi header.

[CAPI] Add functions to be supported later

---

api/capi/doc/nntrainer_doc.h
api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h

Finalize the first draft of C-API

[API] Finalize the first draft of C-API

---

api/capi/src/nntrainer.cpp
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/flatten_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/include/nntrainer_error.h
nntrainer/include/pooling2d_layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp

- Now friendship between layer and network is over
- Move `setProperty(propType)` to public
- Add custom exception in `_error.h`
- Change `setProperty` `std::out_of_range` ->
`exception::invalid_property`
- Add error code boundary to `nntrainer_exception_boundary`
- Change inherited docs to @copydoc
resolves #315 
Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com

Follow-up after #308

---

api/capi/include/nntrainer.h

get_summary function namespace correction
cc. @zhoonit

[c-api] Function namespace correction

---

nntrainer/src/neuralnet.cpp

exception::invalid_property for not allowed property should not be
ignored for some cases. So, parsing process is patched accordingly
cc. @kparichay 

Fix neuralnetwork property logic

---

nntrainer/include/optimizer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/optimizer.cpp

. Add initialize(std::shared_ptr<UpdatableParam> params, ...)
. Update initailize conv2d for optimizer
. Update to do addition for calcuate derivatives of filter

[ Bug ] Fix initialize buffer for adam optimizer

---

Applications/Classification/res/Classification.ini
Applications/Classification/res/Classification_func.ini
Applications/Classification/res/Classification_new.ini
Applications/LogisticRegression/res/LogisticRegression.ini
Applications/ReinforcementLearning/DeepQ/jni/DeepQ.ini
Applications/Tizen_CAPI/Tizen_CAPI_config.ini
Applications/Training/res/Training.ini
Applications/mnist/res/mnist.ini
README.md
nntrainer/include/layer.h
nntrainer/src/loss_layer.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/test_conf.ini
test/unittest/unittest_nntrainer_layers.cpp

Update the name of mean squared error from MSR to MSE

[Loss] Update MSR to MSE

---

nntrainer/include/util_func.h
nntrainer/src/util_func.cpp

This patch contains small basic changes
Update input arguments of softmax to Tensor const & from Tensor to match activation
function signature

[activation] Update input arguments of softmax

---

Applications/Classification/jni/main.cpp
Applications/Classification/jni/main_func.cpp
Applications/LogisticRegression/jni/main.cpp
Applications/Tizen_CAPI/capi_func.c
Applications/Training/jni/main.cpp
Applications/mnist/jni/main.cpp
nntrainer/include/databuffer.h
nntrainer/src/databuffer_file.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/tensor.cpp
test/nntrainer_test_util.cpp

[ Coverity ] Fix Coverity Issues

---

Applications/Classification/jni/main.cpp
Applications/Classification/jni/main_func.cpp
Applications/LogisticRegression/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/Tizen_CAPI/capi_func.c
Applications/Training/jni/main.cpp
Applications/mnist/jni/main.cpp
nntrainer/include/databuffer.h
nntrainer/src/databuffer_file.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
test/nntrainer_test_util.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp
test/unittest/unittest_nntrainer_internal.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_lazy_tensor.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_tensor.cpp

This PR includes fixes about coverity issues

[ Coverity ] Fix coverity issues 

---

Applications/Tizen_native/CustomShortcut/.gitignore
Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/inc/view.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/view.c

This PR adds drawing part of example/customShortcut

[Example] Add drawing part

---

api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp

Added thread locking safety for ml_train C-API
There is a global lock to assist with destruction of object
Each object gets its own lock which maintains safety when accessing/modifying that object
Resolves #287

[API] Make C-API thread safe

---

nntrainer/src/conv2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

Finalize Conv2D verification with tensorflow

[ Unit Test ] Add Verification of Conv2D

---

README.md

Wrong notation in KNN is changed to k-NN
Signed-off-by: brainer <jeansanghyun@gmail.com>

KNN notation change

---

Applications/Classification/jni/main_func.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/ReinforcementLearning/Environment/CartPole/cartpole.cpp
Applications/Tizen_CAPI/capi_func.c
nntrainer/src/databuffer_file.cpp
nntrainer/src/nntrainer_logger.cpp

This PR includes fixes about svace

[ SVACE ] Fix svace issues.

---

api/capi/src/nntrainer.cpp
nntrainer/include/layer.h
nntrainer/include/nntrainer_error.h
nntrainer/src/flatten_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp

Change invalid_prop -> not supported for generality
See also #374 

Change exception::invalid_prop -> not_supported

---

nntrainer/src/databuffer_file.cpp
nntrainer/src/neuralnet.cpp

When path is given and invalid for dataset, it should fail. This patch updates
accordingly.
resolves #379 
2. Run test: [X]Passed [ ]Failed []Skipped

Update setDataset / loadDataset

---

Applications/Classification/jni/main_func.cpp
Applications/Tizen_CAPI/capi_func.c
Applications/mnist/jni/main.cpp
api/capi/doc/nntrainer_doc.h
api/capi/include/nntrainer.h
api/nntrainer-api-common.h
nntrainer/src/databuffer_func.cpp
test/include/nntrainer_test_util.h
test/input_gen/genInput.py
test/nntrainer_test_util.cpp

[C-API] C-API updated with tizen ACR

---

nntrainer/include/nntrainer_log.h
nntrainer/src/neuralnet.cpp
nntrainer/src/nntrainer_logger.cpp

- Add file and line to the logger
- Delete log tag for linux distro (as it is obvious and consumes space)

Print log file and line for better debuging

---

Applications/Classification/jni/main.cpp
Applications/LogisticRegression/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Applications/Training/jni/main.cpp
nntrainer/include/activation_layer.h
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/flatten_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/include/neuralnet.h
nntrainer/include/pooling2d_layer.h
nntrainer/include/tensor.h
nntrainer/src/activation_layer.cpp
nntrainer/src/bn_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/input_layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/pooling2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

Update the forwarding and backwarding layer functions to support
multiple inputs and outputs.
This is crucial to support concat, element wise add, etc kind of layers
as well as skip connection.
Further, forward no longer returns status but rather throws.
Resolves #398

[Layer] Update forward and backward layer functions

---

nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/src/fc_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp
test/meson.build
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

- Add determinancy and check to
- Delete cost / bn_follow from layer
- Enable negative test for modelfile
- fix IniSection::setEntry is wrongly using key for an erase behavior
- Delete `VERIFY_SET_DIMENSION()`
Resolves #316
See also #374

Refactor neuralnet::init

---

Applications/Tizen_native/CustomShortcut/README.md
Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Add feature extraction using `ml-pipeline-api` (saved to training.dat)
- Handle exit canvas / proceed / reset button
- Add path parsing utils
- Add logger macro

[Example] Add feature extraction part

---

Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Attach nntrainer api for training

[Example] Attach training functionality @open sesame 08/04 20:43

---

README.md

Update README file to give proper information about NNTrainer

[ README ] Update README file

---

api/capi/include/nntrainer.h

Added note that this API is experimental and not stable to most of the functions for this to be visible in the SDK function descriptions
Update since tizen version from 6.x to 6.0
Resolves #414 

[api] Update since tizen version and apply experimental

---

debian/changelog
packaging/nntrainer.spec

[ Release ] Change version of nntrainer

---

api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/capi/meson.build
api/capi/src/nntrainer-capi-tizen-feature-check.cpp
api/capi/src/nntrainer.cpp
meson.build
meson_options.txt
packaging/nntrainer.spec
test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp
test/tizen_capi/unittest_tizen_capi_layer.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp

Added tizen feature checking for C-API
Added corresponding bypass for the tizen capi unittests
See also #419

[capi] Add tizen feature checking

---

nntrainer/include/neuralnet.h
nntrainer/include/optimizer.h
nntrainer/src/neuralnet.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

- This patch disables loadFromConfig after loading
v2:
resolves #382 

Add safeguard to prevent loadFromConf twice

---

nntrainer/include/tensor.h
nntrainer/src/activation_layer.cpp

Softmax indexing bug fix
Softmax should apply on 1 axis (last axis in this patch) than all the axis.

[softmax] Bug fix for softmax

---

api/capi/include/nntrainer.h

Add commnets for privileges which might be required in case of saving the model
to a file.

[CAPI] Add comments for tizen privileges

---

Applications/Tizen_CAPI/capi_func.c
nntrainer/src/neuralnet.cpp
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
test/nntrainer_test_util.cpp

This PR includes fixes about SVACE issues

[ SAVCE ] Fix svace issues

---

test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_util_func.cpp

- Add losslayer / util negative cases
- Change ASSERT_EXCEPTION -> EXPECT_THROW

[TCM] Add few negative cases

---

Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/inc/view.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Run training asynchronsly
- Parse train result
- Change draw / result appearance
resolves #342 

[Example] Add display result

---

nntrainer/include/activation_layer.h
nntrainer/include/bn_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/flatten_layer.h
nntrainer/include/input_layer.h
nntrainer/include/layer.h
nntrainer/include/loss_layer.h
nntrainer/include/pooling2d_layer.h
nntrainer/src/activation_layer.cpp
nntrainer/src/bn_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/input_layer.cpp
nntrainer/src/loss_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/pooling2d_layer.cpp
test/unittest/unittest_nntrainer_layers.cpp

Remove last layer property from all the layers as it is redundant
Resolves #446

[layers] Remove last layer property

---

nntrainer/src/flatten_layer.cpp
nntrainer/src/input_layer.cpp

Set input and hidden consistent for all layers.
Resolves #420

[layers] Make input and hidden consistent for layers

---

Applications/mnist/Tensorflow/Training_Keras.py
Applications/mnist/Tensorflow/dataset.py
Applications/mnist/jni/main.cpp
Applications/mnist/res/mnist_valid.ini
nntrainer/include/activation_layer.h
nntrainer/include/util_func.h
nntrainer/src/activation_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/pooling2d_layer.cpp
nntrainer/src/util_func.cpp
test/unittest/unittest_nntrainer_layers.cpp

. mnist tensorflow example to compare
. data generation for tensorflow
. input for mnist ini for small size training set
. fix no_op_prime for activation layer
. add sqrtDouble
. remove conv2d rotate_180
related issues : #133 

[ MNIST ] Comparison with Tensorflow

---

Applications/Classification/README.md
Applications/Classification/jni/main_func.cpp
Applications/Classification/res/Classification.ini
docs/configuration-ini.md
docs/getting-started.md
docs/how-to-run-examples.md
docs/how-to-use-testcases.md

. getting-started.md
. how-to-run-exampels.md
. how-to-use-testcases.md

[ Documents ] Add Documentation

---

Applications/Classification/README.md
docs/configuration-ini.md
docs/getting-started.md
docs/how-to-run-examples.md
docs/how-to-use-testcases.md

Updated docs as per github MD lint
Also added minor fixes

[docs] Updated docs to github MD lint

---

Applications/Tizen_CAPI/capi_func.c
Applications/mnist/Tensorflow/Training_Keras.py
Applications/mnist/Tensorflow/dataset.py
Applications/mnist/jni/main.cpp
nntrainer/include/activation_layer.h
nntrainer/include/conv2d_layer.h
nntrainer/include/fc_layer.h
nntrainer/include/flatten_layer.h
nntrainer/include/lazy_tensor.h
nntrainer/include/pooling2d_layer.h
nntrainer/include/tensor_dim.h
nntrainer/src/activation_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/pooling2d_layer.cpp
nntrainer/src/tensor_dim.cpp
test/input_gen/genInput.py
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_lazy_tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

[license] Fix SPDX license usage

---

Applications/LogisticRegression/jni/main.cpp
Applications/ReinforcementLearning/DeepQ/jni/main.cpp
nntrainer/src/databuffer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/tensor.cpp

This PR inclues coverity issues fixes.

[ Coverity ] Fix coverity issues.

---

README.md

- How to run unittest
- How to run sample app test

[ Docs ] Add how to run test

---

Applications/Tizen_native/CustomShortcut/res/model.ini

Add missing model file that are excluded from .gitignore by force

[Example] Add missing model file

---

Applications/Tizen_native/CustomShortcut/res/model.ini

Added minor bugfix to application ini file
cc. @zhoonit

[Example] Minor bugfix

---

Applications/mnist/Tensorflow/Training_Keras.py
nntrainer/src/layer.cpp

Update tensorflow training example for mnist application
This with same initialization as nntrainer (shown with zero initialization)
matches the final accuracy as well as loss with nntrainer
See also #133
cc. @jijoongmoon

[mnist] Update tensorflow training for mnist application

---

.ahub/tcchecker-tca/config.yaml

[tcm] Add config.yaml @open sesame 08/25 18:38

---

nntrainer/src/tensor.cpp

Out-of-place operations call in-place operations with different clones and checks everywhere
Make a common abstraction to do this and use it for cleaner and readable code.

[Tensor] out-of-place to in-place call uniformly

---

nntrainer/src/tensor.cpp

Update tensor apply to use std::transform than a simple loop

[tensor] Update tensor apply

---

nntrainer/include/neuralnet.h
nntrainer/src/neuralnet.cpp
nntrainer/src/parse_util.cpp
test/tizen_capi/unittest_tizen_capi.cpp

Update model_file to save_path in neuralnet properties
Resolves #488
cc. @zhoonit

[neuralnet] Update model_file to save_path in neuralnet properties

---

nntrainer/include/tensor.h
nntrainer/include/util_func.h
nntrainer/src/activation_layer.cpp
nntrainer/src/tensor.cpp
nntrainer/src/util_func.cpp

Update softmax implementation to use tensor operations than running manual loops
See also #483

[softmax] Update softmax implementation

---

nntrainer/include/tensor.h
nntrainer/src/loss_layer.cpp
nntrainer/src/tensor.cpp

Update tensor operations to use cblas
Further, update various operations to use stl functions than implement locally
Bug fix on sum_by_batch which calculated sum of absolute values earlier
Resolves #480

[tensor] Update tensor operations to use cblas

---

packaging/nntrainer.spec

Updated tizen packing spec file

[tizen/dist] Update tizen packaging

---

nntrainer/include/conv2d_layer.h
nntrainer/src/conv2d_layer.cpp
nntrainer/src/layer.cpp

This PR includes conv2d layer gradient calculation using cblas_gemm.
In order to do this, new functions are introduced.
. conv2d_gemm
. im2col
related issue : #477

[ Conv2D ] add cblas_sgemm to calculate conv2d

---

nntrainer/src/databuffer.cpp
nntrainer/src/model_loader.cpp
nntrainer/src/neuralnet.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

Load model and dataset in config at start so that any dependencies
which model, dataset and layer have among them can be easily solved
Resolves #389
cc. @zhoonit

[loadconfig] Load model and dataset in config at start

---

nntrainer/include/tensor.h
nntrainer/include/tensor_dim.h
nntrainer/src/fc_layer.cpp
nntrainer/src/tensor.cpp
nntrainer/src/tensor_dim.cpp
test/unittest/unittest_nntrainer_tensor.cpp

Update the implementation of tensor dot product
This update applies dot on the last dimesnion of input and second last dimension of passed tensor `m`
This allows use of dot in fc layer directly eliminating calling transpose explicitly but rather use transpose in blas

[dot] Update tensor dot implementation

---

nntrainer/src/tensor.cpp

add bug fix for the sum of tensors

[tensor] bug fix for the sum

---

nntrainer/src/tensor.cpp

Fix ahub reporting buffer overflow

---

jni/Android.mk
nntrainer/include/blas_interface.h
nntrainer/include/tensor.h
nntrainer/meson.build
nntrainer/src/activation_layer.cpp
nntrainer/src/blas_interface.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/tensor.cpp
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_layers.cpp

In order to handle blas easily, blas interface is added.
.blas_interface.cpp
.blas_interface.h

[ UTIL ] Add BLAS Interface

---

Applications/mnist/Tensorflow/Training_Keras.py
jni/Android.mk
nntrainer/include/blas_interface.h
nntrainer/include/tensor.h
nntrainer/meson.build
nntrainer/src/activation_layer.cpp
nntrainer/src/blas_interface.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/tensor.cpp
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_layers.cpp

This PR includes codes to save weight initialized data for nntrainer
input. This can be read using NN.readModel() except optimizer read in
fully connected layer.

[ MNIST ] Add save weight initialization data

---

Applications/Tizen_CAPI/capi_func.c

Fix app classification capi func test fails with negative number
- Add destroy routine
- s/model_path/save_path/
Resolves #501

Fix app test fail

---

nntrainer/include/blas_interface.h
nntrainer/src/blas_interface.cpp
nntrainer/src/tensor.cpp
test/unittest/unittest_nntrainer_layers.cpp

. add sscal, snrm2, sgemv, scopy
. modify tensor.cpp to use blas_interface

[ BLAS ] Add more blas func to support and update tensor.cpp

---

nntrainer/src/conv2d_layer.cpp

Add explanation about covn2d.
. forwarding
. Calculate DelK in backwarding
. Calculate return derivative in backwarding

[ CONV2D ] Add explanation about how to calculate conv2d.

---

Applications/Training/README.md
Applications/Training/res/Training.ini

Modify Document of Training Exmaple (Transfer Learning)
. Applications/Training/README.md

[ Doc ] Add explains about Applications

---

Applications/Classification/jni/main.cpp
Applications/Tizen_CAPI/capi_func.c
api/capi/src/nntrainer.cpp

[ SVACE ] Using rand_r instead of rand

---

Applications/Classification/README.md

- Fix typo that hasn't been changed after ini spec change

[Docs] Fix typo on classificaion

---

nntrainer/src/tensor.cpp
test/tizen_capi/unittest_tizen_capi.cpp

- Fix normalization when min == max
- Add regression test from tct

Fix normalization for specific case

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp
api/capi/src/nntrainer.cpp
nntrainer/include/model_loader.h
test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp

- Fix recursive header inclusion
- Add additional destory, overlapping validation

[ SVACE ] Fix minor issues reported by svace

---

nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp

. Add Lock to set data ready flag.
. change order to set the condition
. Fix undeterministic behavior of databuffer
. related issues : #427, #464

[ Coverity ] Fix Race Condition issue about databuffer

---

nntrainer/src/databuffer.cpp
test/tizen_capi/unittest_tizen_capi.cpp

[ DataBuffer ] Hot fix for data buffer

---

meson.build
meson_options.txt
nntrainer/include/blas_interface.h
nntrainer/src/blas_interface.cpp
nntrainer/src/tensor.cpp

Move CUBLAS gemm routine into blas_interface

[ BLAS ] Modify to use CUBLAS for gemm

---

nntrainer/include/neuralnet.h
nntrainer/src/model_loader.cpp
nntrainer/src/neuralnet.cpp

. Add Inferenece Mode
Add 'is_train' to identify mode.
: Default is training mode(true). If this is set false, then it is
inference mode. If it is inference mode, then data buffer is not
initialized.

[ Example ] Add Inference Mode & Example

---

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc

[ Bug ] Free content of g_file_get_contents

---

nntrainer/src/tensor.cpp

we only copy if tensor len == 0
related issues : #539

[ Bug ] Fix Tensor Copy

---

Applications/VGG/res/vgg.ini
nntrainer/src/tensor.cpp

This PR includes configuration file (vgg.ini) for VGG 16 with bn layer
which is:
conv3_64 - conv3_64, max_pooling, conv3_128 - conv3_128, max_pooling,
conv3_256 - conv3_256 - conv3_256, max_pooling, conv3_512 - conv3_512
- conv3_512, max_pooling, conv3_512 - conv3_512 - conv3_512,
bn_layer,  max_pooling, fc_4096, bn_layer, fc_4096, bn_layer, fc_100,
softmax

[ APP ] Add VGG 16 Test Configuration

---

nntrainer/include/optimizer.h
nntrainer/include/tensor.h
nntrainer/src/bn_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/optimizer.cpp
nntrainer/src/tensor.cpp
packaging/nntrainer.spec
test/meson.build
test/nnstreamer_filter_nntrainer/nnstreamer-test.ini
test/nnstreamer_filter_nntrainer/runTest.sh

Added support to run unittest of nnstreamer plugin on tizen build on the CI server

[nnstreamer-plugin] Support to run unittest of nnstreamer plugin @open sesame 9/15 15:59

---

packaging/nntrainer.spec

This pr includes enabling unittest for gbs

[ Test ] enable unittest

---

Applications/TransferLearning/CIFAR_Classification/README.md
Applications/TransferLearning/Draw_Classification/README.md
Applications/TransferLearning/Draw_Classification/jni/Android.mk
Applications/TransferLearning/Draw_Classification/jni/main.cpp
Applications/TransferLearning/Draw_Classification/jni/meson.build
api/capi/src/nntrainer.cpp
jni/Android.mk
packaging/nntrainer.spec

Commit - 1 :
Add building of C-API for android
Also add corresponding error fix for inclusion
Commit - 2 :
Update draw-classification application to use the C-API
Also add more polishing to the application
Update building of android application to build with C-API
Update meson to use C-API than nntrainer directly
Inference of application is still remaining
Commit - 3 :
Update the documentation for the applications
Commit - 4:
Added testing for the trained model using nnstreamer CAPI
This testing of the trained model works on tizen only

[application] Transfer learning application with C-API

---

nntrainer/src/tensor_dim.cpp

- Fix index validation to be appropriate

[TensorDim] Fix index checks

---

README.md

This patch updates example link broken from moving folders.
resolves #567
1. Build test: [ ]Passed [ ]Failed [x]Skipped
2. Run test: [ ]Passed [ ]Failed [x]Skipped

[Docs] Update example link

---

Applications/LogisticRegression/README.md

Add doc for logistic regression application.

[ Application ] Doc for Logistic Regression

---

Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Remove underscore to unify code style in custom shortcut

[CS] Remove leading underscore

---

Applications/LogisticRegression/jni/main.cpp
Applications/LogisticRegression/jni/meson.build
Applications/LogisticRegression/res/LogisticRegression.ini

Current implementation of Logistic example is not working.
This PR inclues fixes.

[ Application ] Fix Logistic Regression Example to work

---

Applications/Tizen_native/CustomShortcut/README.md
Applications/Tizen_native/CustomShortcut/res/model.ini

- Update model to use 10 data
- Update readme.md

[CustomShortcut] Update docs and model @open sesame 09/22 14:05

---

Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/inc/main.h
Applications/Tizen_native/CustomShortcut/inc/view.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

This PR migrates master to main.
Please merge this PR after most of the `migrate to main` is rebased to `master` branch.

Migrate master to main

---

.gitignore

Update gitignore for android build to ignore *.o.d and downlaoded iniparser

[gitignore] Update for android build

---

Applications/MNIST/jni/main.cpp
Applications/MNIST/jni/meson.build
Applications/TransferLearning/Draw_Classification/jni/main.cpp
Applications/TransferLearning/Draw_Classification/jni/meson.build
meson.build
packaging/nntrainer.spec
test/meson.build

Commit- 1: 
Add output verification with gtest for transfer learning application
Commit- 2: 
Add output loss verification with gtest for MNIST application for 5 epochs

[application] Add output verification with gtest

---

Applications/Tizen_native/CustomShortcut/inc/main.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Visually notify when training is done
- Add go to main menu when training is done
- Go to main menu button shows the final best accuracy
Resolves #572, Resolves #574

[CS] Add visual queue when training is done

---

api/capi/src/nntrainer.cpp
nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
test/unittest/unittest_nntrainer_layers.cpp

- Add print preset for model and layer
- Add model print flags
- move printFlagEnums and print(out, flag) to private
Cc: Parichay Kapoor <pk.kapoor@samsung.com>

Add print preset

---

Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c

- Enlarge font size, and change test to eval

[CS] Enlarge fonts and s/test/eval 

---

packaging/nntrainer.spec

NNTrainer Meta :
- nntrainer-core
- nnstreamer-nntrainer if nnstreamer_filter is on
- capi-nntrainer if with tizen

[ Packaging ] Meta Package for NNTrainer

---

Applications/Tizen_native/CustomShortcut/inc/data.h
Applications/Tizen_native/CustomShortcut/res/model.ini
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c

- Add pipeline for the inference

[CS] Add inference pipeline @open sesame 10/05 11:37

---

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc

g_assert ends the program rather than give chance for calls to handle
the error code. This patch replaces g_assert with return value
v2. Remove assertion codes and unify codes to throw
- Remove assertion codes instead throw to the top level and catch
altogether
- Merge `NNTrainer::init()` logic to constructor

[Filter] Replace g_assert

---

nntrainer/src/databuffer.cpp

There was an issue that databuffer is not emptying queue properly.
This patch fixes the issue.o
Resolves #621

[Databuffer] Fix queue is not emptied properly

---

packaging/nntrainer.spec

- Fix minor typos in spec file
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>

[typo] Fix minor typos in spec file

---

Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Add color to the result label
- Fix retun status for void functions

[CS] Add color to the label and fix status

---

Applications/Tizen_native/CustomShortcut/inc/view.h
Applications/Tizen_native/CustomShortcut/res/edje/main.edc
Applications/Tizen_native/CustomShortcut/res/model.ini
Applications/Tizen_native/CustomShortcut/src/data.c
Applications/Tizen_native/CustomShortcut/src/main.c
Applications/Tizen_native/CustomShortcut/src/view.c

- Add disable mode for the buttons
- Disable eval when 'model.bin' is not present
- Remove `model.bin` when exit
- Change colors for the buttons
- Enlarge emoji
- Fewer code retouches and fix bugs..

[CS] Improve UI Interaction

---

nntrainer/include/databuffer.h
nntrainer/include/databuffer_file.h
nntrainer/include/databuffer_func.h
nntrainer/include/databuffer_util.h
nntrainer/meson.build
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
packaging/nntrainer.spec

Cleanup databuffer headers for ccapi
See also #199

[databuffer] Cleanup databuffers for ccapi

---

nntrainer/include/layer.h
nntrainer/include/neuralnet.h
nntrainer/src/neuralnet.cpp

- Open up getter for layer::num_weights and neuralnet flatGraph
- Use getOutputDimension for some codes
- Add types for future competibility

[IntegratedTest] Add methods and types for tests

---

test/input_gen/genModelTests.py
test/input_gen/recorder.py

Add test generator and model recorder for integrated test cases.
This runs multiple epochs and save related informations.

[IntegratedTest] Add test generator

---

Applications/VGG/Tensorflow/vgg_keras.py

Added bugfix for tensorflow VGG for the evaluation part

[vgg] Tensorflow VGG bugfix

---

Applications/LogisticRegression/jni/main.cpp
Applications/MNIST/jni/main.cpp
Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
Applications/VGG/jni/main.cpp
api/capi/src/nntrainer.cpp
api/ccapi/include/dataset.h
api/ccapi/include/layer.h
api/ccapi/src/factory.cpp
nntrainer/include/databuffer.h
nntrainer/include/databuffer_file.h
nntrainer/include/databuffer_func.h
nntrainer/src/databuffer.cpp
nntrainer/src/databuffer_file.cpp
nntrainer/src/databuffer_func.cpp
nntrainer/src/model_loader.cpp
test/ccapi/meson.build
test/ccapi/unittest_ccapi.cpp
test/meson.build
test/unittest/unittest_databuffer_file.cpp

Added unittests for ccapi
Also added some fixes and funcationalities revealed with unittests
Related #199

[ccapi] Added unittests for ccapi

---

Applications/VGG/Tensorflow/vgg_keras.py
Applications/VGG/res/vgg_small.ini

Change to use learning rate decay

[ Application ] VGG using learning rate decay

---

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
nntrainer/include/layer_internal.h
nntrainer/include/neuralnet.h
nntrainer/include/tensor_dim.h
nntrainer/src/addition_layer.cpp
nntrainer/src/bn_layer.cpp
nntrainer/src/conv2d_layer.cpp
nntrainer/src/fc_layer.cpp
nntrainer/src/flatten_layer.cpp
nntrainer/src/layer.cpp
nntrainer/src/neuralnet.cpp
nntrainer/src/pooling2d_layer.cpp
nntrainer/src/tensor_dim.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_models.cpp

Current implementaion only take one input. In order to take multiple
input, input_dim / output_dim should be vector type.
This PR includes this fixes except about addition layer which requires
actual multiple input. This will be done consequtive PR.

[ Layer ] Multiple Input Dimensions @open sesame 10/28 14:06

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/include/concat_layer.h
nntrainer/meson.build
nntrainer/src/concat_layer.cpp
packaging/nntrainer.spec

This PR includes Concatenate layer.

[Wait4PR#671][ Layer ] Add Concat Layer @open sesame 10/28 14:16

---

docs/getting-started.md

Troubleshooting errors observed during installation and building of NNTrainer.

Troubleshooting installation process with observed errors and working solutions

---

README.md

Add github account on README.md file

Add github account on README.md file

---

nntrainer/include/delegate.h
nntrainer/meson.build
packaging/nntrainer.spec

Add delegate support header
This supports settings backend and device
Added some properties but they are experimental
These will made by the user if needed, else defaults will be used by the model during compile
Related #659

[Delegate] Add delegate support header

---

Applications/KNN/README.md
Applications/MNIST/README.md
Applications/TransferLearning/Draw_Classification/README.md

Add bugfix for readme where images were not being shown

[README] Bugfix for image display

---

Applications/utils/datagen/cifar/How-to-gen-data.md

Add document explain how to generate cifar 10/100 bmp images

[ Util ] Add how to generate cifar 10/100 bmp images

---

test/input_gen/recorder.py
test/input_gen/transLayer.py

- ~**#678** [Test/Util] Update ini / debug info~
- ~**#678** [IntegratedTest] Add batch normalization test~
- [Test/Py] Add translayer
```
Add `translayer` to encapsulate keras layer to use nntrainer layout
This can be used for `genInput.py` as well.
```

[Test/Py] Add translayer

---

nntrainer/layers/bn_layer.cpp

Support non-trainable mode for bn layer when the parameters
for this layer are not updated.

[bn layer] Support non-trainable mode

---

Applications/KNN/README.md
Applications/MNIST/README.md
Applications/ReinforcementLearning/DeepQ/README.md
Applications/TransferLearning/Draw_Classification/README.md
Applications/TransferLearning/How-to-gen-tflite-model.md

Modify the image url from absolute path to relative path

[README] Modify the image url

---

docs/configuration-ini.md

Added documentation for backbone in ini-configuration

[backbone] Documentation for backbone

---

Applications/TransferLearning/CIFAR_Classification/jni/Android.mk
Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
Applications/TransferLearning/CIFAR_Classification/jni/meson.build
Applications/TransferLearning/CIFAR_Classification/res/Classification_func.ini

Update cifar application using databuffer with generator to
use tflite backbone.
Closes #660 

[cifar] Update cifar application with backbone

---

nntrainer/layers/nnstreamer_layer.cpp

Update nnstreamer backbone layer to support more backbones than just tflite
Wait for this PR to merge till the bug fix on nnstreamer
https://github.com/nnstreamer/nnstreamer/pull/2850 is merged and reflected
V2:
Update HW backend from ANY to AUTO

[nnstreamer/backbone] Update to support more backbone

---

nntrainer/layers/loss_layer.h
nntrainer/models/neuralnet.cpp

Handle loss layer to be added from the user which is created with c++ API
Resolves #744

[model] Handle loss layer to be added from user

---

Applications/TransferLearning/Draw_Classification/jni/Android.mk
Applications/TransferLearning/Draw_Classification/jni/main.cpp
jni/Android.mk
nntrainer/models/model_loader.cpp
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

- ~**#728** [AppContext] Add AppContext~
- [Model] Apply appcontext
```
Apply appcontext to NeuralNetwork. From this patch `chdir()` hack is not
needed :)
```

[Model] Apply appcontext

---

jni/Android.mk
nntrainer/tensor/meson.build
nntrainer/tensor/var_grad.cpp
nntrainer/tensor/var_grad.h
nntrainer/tensor/weight.cpp
nntrainer/tensor/weight.h
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_layers.cpp

Added var_grad for input/output lists which also combines derivatives
This is the baseclass for the weights
This update will help with graph class

[var_grad] Add var_grad for input/output lists

---

Applications/Custom/LayerClient/README.md
Applications/Custom/LayerClient/jni/Android.mk
Applications/Custom/LayerClient/jni/main.cpp
Applications/Custom/LayerClient/jni/meson.build
Applications/Custom/LayerClient/jni/pow.cpp
Applications/Custom/LayerClient/jni/pow.h
Applications/Custom/LayerClient/res/custom_layer_client.ini
api/ccapi/src/factory.cpp
nntrainer/layers/bn_layer.h
nntrainer/layers/layer_internal.h
nntrainer/optimizers/optimizer_factory.cpp

- ~**#760** [Custom] Add an example scaffolding~
- ~**#776** [ModelLoader] Use vector<string> when create layer~
- [Custom] Add actual example
```
- Add an example to create the custom layer to be used with ini
- Add an example to create the custom layer to be used with api
```
- [CustomLayer] Update readme.md 
```
Add readme.md about how to run and expected output
```

[CustomLayer] Add actual example

---

test/unittest/unittest_nntrainer_layers.cpp

Enable fc layer disabled unittest

[unittest] Enable disabled unittest

---

nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/conv2d_layer.h
nntrainer/layers/pooling2d_layer.cpp
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

It is better to split conv2d_gemm and im2col

[ CONV2D ] separate conv2d_gemm and im2col @open sesame 12/07 08:36

---

Applications/Tizen_native/CustomShortcut/res/model.ini

As ini format has been changed, ini for customshortcut need change
This patch handles it.

[Chores] CustomShortcut bug

---

Applications/MNIST/PyTorch/main.py
Applications/MNIST/Tensorflow/Training_Keras.py

Added pytorch version of MNIST for benchmarking purpose
This code is only tested with CPU

[MNIST] Added pytorch version

---

jni/Android.mk
jni/prepare_openblas.sh
jni/prepare_tflite.sh
meson.build

Android ndk was not building on top of openblas
This patch fixes the problem
resolves #794

[Android] Integrate openblas into android

---

Applications/KNN/jni/meson.build
Applications/LogisticRegression/jni/meson.build
Applications/ReinforcementLearning/DeepQ/jni/meson.build
Applications/TransferLearning/CIFAR_Classification/jni/meson.build
Applications/TransferLearning/Draw_Classification/jni/meson.build
Applications/VGG/jni/meson.build
api/capi/meson.build
api/ccapi/meson.build
meson.build
nnstreamer/tensor_filter/meson.build
nntrainer/dataset/meson.build
nntrainer/graph/meson.build
nntrainer/layers/meson.build
nntrainer/meson.build
nntrainer/models/meson.build
nntrainer/optimizers/meson.build
nntrainer/tensor/meson.build
nntrainer/utils/meson.build
test/unittest/meson.build

Replace join_paths in meson.build files to /
Check issue #709 for more details
Resolves #709

[meson.build] Change join_paths to / in meson.build files

---

nntrainer/tensor/tensor.cpp

Set stride for shared tensor
Resolves #816

[tensor] Set stride for shared tensor

---

nntrainer/models/model_loader.cpp

Fix model path and dataset path to involve working directory path

[bugfix] Fix model path and dataset path in model_loader.cpp

---

nntrainer/utils/profiler.cpp

Now profiler will show the avg, min, max, sum values

Support sum value in profiler

---

Applications/TransferLearning/Draw_Classification/jni/main.cpp
Applications/TransferLearning/Draw_Classification/jni/meson.build
meson.build

Enable testing of the trained model on ubuntu

[transfer learning] Enable test on ubuntu

---

Applications/LogisticRegression/jni/main.cpp

This PR includes fixes about logistic regression application
Change forwarding function

[ Fix ] Fix Logistic Regression Example Error

---

docs/getting-started.md

Add missing dependencies required to build nntrainer with meson

[docs] Add missing dependencies

---

Applications/MNIST/jni/meson.build
meson.build

Update meson to work with ubuntu 20.04
Also add some missing checks

[meson] Update meson for ubuntu 20.04

---

Applications/MNIST/jni/meson.build
meson.build
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

Add input validation for inference of the neural network
See also #860

[#863] [inference] Add input validation for inference

---

jni/Android.mk
nntrainer/models/dynamic_training_optimization.cpp
nntrainer/models/dynamic_training_optimization.h
nntrainer/models/meson.build
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/optimizers/optimizer_internal.h
nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/var_grad.h

Commit 1 : [dyanmic training] Adding dynamic-training code …
Added dynamic-training code with both max and l2norm mode
Verified working with existing examples given the threshold
Commit 2: [dynamic-training] Add dynamic training using derivatives …
Added dynamic training using derivatives where the decision to
apply the gradient is calculated using the derivative received
without calculating the gradient itself.

[dynamic finetuning] Adding dynamic-finetuning code

---

api/ccapi/include/layer.h
jni/Android.mk
meson.build
nntrainer/layers/meson.build
nntrainer/layers/preprocess_flip_layer.cpp
nntrainer/layers/preprocess_flip_layer.h
nntrainer/layers/preprocess_translate_layer.cpp
nntrainer/layers/preprocess_translate_layer.h
nntrainer/utils/parse_util.cpp
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_layers.cpp

Added data augmentation for vgg model
Data augmentation support random flip and random translate
both applied on each image in a batch independently.

[data augmentation] Added data augmentation

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/layers/layer_factory.cpp

- Setting void *user_data
- Update layer type enum

[CAPI/acr] Update tizen capi header

---

nntrainer/app_context.cpp

As static initialization order out of a translation unit is undefined,
initializing global caused some undefined behavior.
Initializing global app context is delayed until it is first called.
See https://gcc.gnu.org/legacy-ml/gcc-patches/2017-03/msg00863.html
See also #893 (verified)

[Fix] Resolve static init order fiasco

---

nntrainer/tensor/blas_interface.cpp

Add bug fix for blas raw implementation for missing return.

[blas] Add missing return

---

docs/how-to-run-example-android.md

Add documentation to build and run in android

[ Doc ] add how to run android application

---

docs/how-to-run-example-android.md
jni/Android.mk

Change Tensorflow-Lite Version from 1.13.1 to 2.30.0

[ ANDROID ] change the tflite version

---

Applications/KNN/jni/Android.mk
Applications/TransferLearning/CIFAR_Classification/jni/Android.mk

Fix the path of tensorflow-lite lib

[ Application ] Bug fix of Android target Lib

---

Applications/ResNet/res/resnet18.ini

This PR includes ini configuration file for resnet18

[ ResNet ] Add Resnet18 Application

---

README.md

Add daily build status in readme

[ Document ] Add daily build status @open sesame 02/05 10:55

---

Applications/Custom/LayerClient/jni/main.cpp
nntrainer/layers/conv2d_layer.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h

Commit 1 : resolve 456417, 456413
Added integer overflow fix notified by svace for convolution
Commit 2 : resolve 456452
Uninitialized class member issue fixed for manager.cpp - MMapedMemory
Added class member initialization
Commit 3 : resolve 455041
Added missing try-catch reported by svace for the custom tizen application

[svace] Svace issues fix

---

debian/control
meson.build
packaging/nntrainer.spec

Now api repo is newly added, change dependency to ml-inference-api.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

[Build] change dependency to nnstreamer api @open sesame 02/17 18:27

---

RELEASE.md

Add release.md to specify release policy.

[ Document ] Add RELEASE.md

---

CONTRIBUTING.md
docs/contributing.md

This patch updates broken links in contributing guide.
Signed-off-by: Juyeong Lee <2jy22@naver.com>

[Docs] Fix broken links

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/embedding.cpp
nntrainer/layers/embedding.h
nntrainer/layers/layer_factory.cpp
nntrainer/layers/meson.build

In this PR,
Skeleton Code for Embedding Layer is included.
- header / source and some modification for layer factory.

[ Layer ] Add Skeleton for Embedding Layer

---

Applications/Custom/LayerPlugin/meson.build
Applications/SimpleShot/test/meson.build
Applications/meson.build

[Meson/Clean] remove duplicating deps

---

Applications/SimpleShot/task_runner.cpp

Added missing try-catch statement
resolve 457589

Handle NO_CATCH issue

---

docs/memory-management.md

Added documentation for memory management.
Resolves #945

[docs] Added documentation for memory management

---

packaging/nntrainer.spec

This patch is a workaround to make coverage build runnable for now.
There will be following patches to enable the commented lines.
See also #997

[SE] Make coverage build runnable

---

test/unittest/unittest_util_func.cpp

Unittest for following functions
rotate_180
readString
writeString

[Unittest] Add some cases for util_func

---

docs/memory-management.md

Minor indentation fix
Applying a minor fix suggested in #993
Report from https://github.com/nnstreamer/nntrainer/pull/993#discussion_r594884810

[docs] Minor indentation fix

---

nntrainer/layers/embedding.cpp
test/unittest/unittest_nntrainer_layers.cpp

This PR includes
- Backwarding implementation of Embedding Layer
- Add Test Cases ( More Test Cases will be added )

[ LAYER ] Add backwarding of Embedding Layer

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/layer_factory.cpp
nntrainer/layers/meson.build
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h

This PR includes,
skeleton of RNN Layer

[ RNN ] Add Skeleton Code for RNNLayer

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
test/unittest/unittest_nntrainer_layers.cpp

- [ RNN ] Add initialization of RNN
```
Add Initialization of RNN Layer
- Set dimension and Weight
- Add Unittest for initialization
```
- [ RNN ] Implementaion of forwarding
```
- Implementation of RNN forwarding.
```
- [ RNN ] support various activation function
```
In this PR, various activation functions are supported using ActiFunc
Class. …
```

[ RNN ] Implement initialization and forwarding of RNN Layer

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/rnn.h
test/unittest/unittest_nntrainer_layers.cpp

Set the tanh as a default activation function

[ Wait for #1038] [ RNN ] Set tanh as a default activation function

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
nntrainer/layers/meson.build
nntrainer/utils/parse_util.cpp

This PR includes skeleton code of lstm layer
Resolves:

[ LSTM ] Add Skeleton LSTM Layer Class @open sesame 04/01 11:08

---

nntrainer/layers/rnn.cpp
test/unittest/unittest_nntrainer_layers.cpp

This commit includes calculate gradient and derivatives of RNN Layer.
Resolves:

[ RNN ] Backwarding Implementation @open sesame 04/01 11:12

---

jni/Android.mk
nntrainer/compiler/compiler.cpp
nntrainer/compiler/compiler.h
nntrainer/compiler/interpreter.h
nntrainer/compiler/meson.build
nntrainer/graph/network_graph.h
nntrainer/meson.build
test/meson.build
test/unittest/compiler/meson.build
test/unittest/compiler/unittest_compiler.cpp
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/meson.build

This patch defines interface of the graph compiler we've talked through.
I changed the design little bit that graph rep has interpreter and compiler.
The design proposed in this PR is ready-to-wrap to the discussed design.
- [Compiler/skeleton] Set up compiler source files
```
This patch setup compiler source files
```
- [Compiler] Add concept of the compiler
```
This patch adds a concept of the compiler and class declaration.
```
- [Compiler] Declare interface
``` …
```

[Compiler] Design Draft

---

api/ccapi/include/layer.h
nntrainer/app_context.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
nntrainer/layers/meson.build
nntrainer/layers/rnn.cpp
nntrainer/layers/time_dist.cpp
nntrainer/layers/time_dist.h
nntrainer/utils/parse_util.cpp

This commit includes:
. implementation of lstm forwarding implementation
Resolves:

[ LSTM ] Layer forwarding implementation @open sesame 04/02 19:38

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/layer.cpp
nntrainer/layers/layer_factory.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/time_dist.cpp
nntrainer/layers/time_dist.h
nntrainer/models/model_loader.cpp
nntrainer/utils/parse_util.cpp

This includes
. Skeleton Code for Time Distribution Layer
Resolves:

[Wait for #1065] [ TIME DIST ] Add skeleton Code for Time Distribution Layer

---

jni/Android.mk
nntrainer/compiler/ini_interpreter.cpp
nntrainer/compiler/ini_interpreter.h
nntrainer/compiler/interpreter.h
nntrainer/compiler/meson.build

1. [Ini] Implement ini deserializer 
```This patch implements ini deserializer as well as changing the interface
signature to get filepath.
Many NYI parts will be implemented soon.
```

[Ini] Implement ini deserializer

---

nntrainer/app_context.h
nntrainer/compiler/ini_interpreter.cpp
nntrainer/compiler/ini_interpreter.h

- [IniInterpreter] Add section2layer 
```
This patch add plain `section2layer`.
```

[IniInterpreter] Add section2layer

---

nntrainer/app_context.cpp
nntrainer/compiler/ini_interpreter.cpp
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

- [IniInterpreter] Add ini backbone deserialization 
```
- Add ini backbone deserialization support
```

[Wait for #1079] [IniInterpreter] Add ini backbone deserialization

---

nntrainer/layers/lstm.h

Set default recurrent_activation_type in parameter
resolves: 1224616, 1224617

Handle Uninitialized scalar variable issue @open sesame 04/20 17:02

---

nntrainer/utils/ini_wrapper.cpp
nntrainer/utils/ini_wrapper.h

- [Ini] Propose ini wrapper 2 
```
Propose ini wrapper in nntrainer, most codes are from
`nntrainer_test_util.cpp`.
```

[Wait for #1087] [Ini] Propose ini wrapper 2 @open sesame 04/22 13:18

---

api/ccapi/include/layer.h
nntrainer/app_context.cpp
nntrainer/layers/preprocess_flip_layer.h
nntrainer/layers/preprocess_translate_layer.h
test/unittest/unittest_nntrainer_models.cpp

[Unittest] Added doxygen tag
1. Added missing doxygen tag
2. remove unused function parameter
[Preprocess] Set default trainable to false
**Changes Proposed**
- Set default trainable to `false` for preprocess layer
- Register preprocess layer to the app context
- Add validate test
resolves #1129

[Preprocess] Set default trainable to false @open sesame 04/22 12:39

---

test/ccapi/unittest_ccapi.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/unittest_nntrainer_graph.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp

- [Ini] Remove IniTestWrapper 
```
This patch removes initestwrapper in favor of nntrianer::iniwrapper
```

[Wait for #1088, #1132] [Ini] Remove IniTestWrapper @open sesame 04/22 18:26

---

nntrainer/compiler/ini_interpreter.cpp
nntrainer/graph/network_graph.cpp
nntrainer/layers/time_dist.cpp
nntrainer/layers/time_dist.h
nntrainer/models/model_loader.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

if time distributed layer has activation, we have to add time
distributed layer for activation, and if it need to realize loss
layer, we also add the time distribute layer for loss.

[ TIME DIST ] Modify graph to recognize time distribute layer @open sesame 04/26 21:11

---

nntrainer/layers/addition_layer.cpp

Before adding inputs output should be set zero

[Addition_layer] Set output to zero in forward

---

nntrainer/compiler/ini_interpreter.cpp
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp
test/unittest/unittest_nntrainer_models.cpp

Update graph node to use the updated LayerNode
Graph will be updated to GraphNode<nntrainer::Layer> in an upcoming PR.

[graph] Update graph node 

---

README.md

Since web page of TAOS-CI has been changed replace nnsuite to nnstreamer

[README] Replace nnsuite to nnstreamer @open sesame 04/24 11:31

---

api/ccapi/include/model.h
api/ccapi/include/optimizer.h
nntrainer/layers/layer_node.h
nntrainer/tensor/lazy_tensor.cpp
nntrainer/tensor/lazy_tensor.h
nntrainer/tensor/var_grad.h
test/unittest/unittest_nntrainer_lazy_tensor.cpp
test/unittest/unittest_nntrainer_models.cpp

- Fix some doxygen errors
- Fix author email typo /cc @zhoonit 
Signed-off-by: Juyeong Lee <2jy22@naver.com>

[Docs] Fix doxygen

---

nntrainer/tensor/var_grad.h

Added doxygen fix for var_grad

[doxygen] Var_Grad doxygen fix

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/loss_layer.cpp
nntrainer/layers/time_dist.cpp
nntrainer/layers/time_dist.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp

- Time Dist Layer initialization
- Some modification of network graph

[ TIME DIST ] Implement Initialization of Time Dist Layer @open sesame 04/27 19:44

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_internal.h
nntrainer/layers/time_dist.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

- Time Dist Layer initialization
- Some modification of network graph

[ TIME DIST ] Implement Initialization of Time Dist Layer

---

nntrainer/layers/fc_layer.cpp
nntrainer/layers/loss_layer.cpp
nntrainer/layers/time_dist.cpp

This commit includes
. Implementation of Forwarding Implementation of Time Dist Layer

[ TIME DIST ] Forwarding Implementation

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/loss_layer.cpp
nntrainer/layers/time_dist.cpp
nntrainer/layers/time_dist.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
test/unittest/unittest_nntrainer_models.cpp

This commit includes
- implementation of TimeDistLayer Backwarding

[Wait for #1143] [ TIME DIST ] Implement Backwarding of TimeDistLayer @open sesame 04/28 21:14

---

nntrainer/graph/network_graph.cpp

Added bugfix for duplicate output connections
Resolves #1140

[graph] Bug fix for duplicate output connections

---

nntrainer/tensor/tensor_dim.h

- [Doxygen] Add doxygen to tensordim 
```
This patch adds doxygen to tensordim.
```

[Doxygen] Add doxygen to tensordim

---

Applications/Custom/LayerClient/jni/Android.mk
Applications/Embedding/jni/Android.mk
Applications/KNN/jni/Android.mk
Applications/LogisticRegression/jni/Android.mk
Applications/MNIST/jni/Android.mk
Applications/ReinforcementLearning/DeepQ/jni/Android.mk
Applications/TransferLearning/CIFAR_Classification/jni/Android.mk
Applications/TransferLearning/Draw_Classification/jni/Android.mk
Applications/VGG/jni/Android.mk
nntrainer/utils/base_properties.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
nntrainer/utils/parse_util.cpp
nntrainer/utils/parse_util.h
test/unittest/unittest_properties.cpp

- [Props] Implement load properties 
```
This patch implement `load_properties` which helps loading properties
for a tuple of properties.
```
- v2. [NDK] Add frtti to application build
```
As real time type information is used in nntrainer, frtti flag is turned
on to fix build issue
```

[Props] Implement load properties

---

test/unittest/unittest_nntrainer_layers.cpp

Added EXPECT_NO_THROW to handle No Assert Statement Found issue

Handle GTEST.NO_ASSERTION issue

---

jni/Android.mk
nntrainer/compiler/meson.build
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_interpreter.h

- [Skeleton] Add Tflite interpreter skeleton 
```
This patch adds tflite interpreter skeleton
```

[Skeleton] Add Tflite interpreter skeleton @open sesame 05/10 12:54

---

nntrainer/layers/common_properties.h
nntrainer/utils/base_properties.h
test/unittest/unittest_properties.cpp

- [Props] Change is_valid function signature
```
- s/is_valid/isValid
- change the function to const
```

[Props] Change is_valid function signature

---

test/unittest/unittest_nntrainer_layers.cpp

This patch resolves the issue of golden data of size 0.
This happened as a tensor of size 0 was trying to load the data.
As the size was 0, no data was loaded.
Further, this size was used for comparison as well, which led to
faulty testcases being passed as well.
Resolves #769 #1172
See Also #1180

[test] Resolve golden data of size 0

---

nntrainer/compiler/tflite_interpreter.cpp

- [tflite] implement serialize 
```
This patch implements serialize with bunch of NYI functions, structures
```

[tflite] implement serialize

---

test/unittest/unittest_nntrainer_layers.cpp

- [Fix] Add compiler complaining types
```
This patch fixes compiler complaning types
```

[Fix] Add compiler complaining types

---

README.md

- [Update] update daily build badge
```
Daily build has been fixed and badge has been reset. This patch update
badge path and update the information.
```

[Update] update daily build badge

---

nntrainer/utils/base_properties.cpp
nntrainer/utils/base_properties.h
test/unittest/unittest_properties.cpp

- [Props] Add dimension property
```
This patch add dimension property
```

[Props] Add dimension property

---

nntrainer/compiler/tflite_interpreter.cpp

- [Tflite] Implement serializing opcode 
```
This patch implements implementing serialize opcode by
`buildOperatorCodes`
```

[Tflite] Implement serializing opcode

---

.gitignore
jni/Android.mk

Fix android build error for file not found
add tensorflow new version to .gitignore

[android] Fix android build @open sesame 05/18 13:25

---

nntrainer/compiler/tflite_interpreter.cpp
test/unittest/compiler/unittest_interpreter.cpp

- [tflite] Implement `buildBuffers` 
```
This patch implements buildBuffers, now our generated tflite file has
buffers attached.
```

[tflite] Implement `buildBuffers`

---

nntrainer/compiler/tflite_interpreter.cpp
test/test_models/models/simple_fc.ini
test/unittest/compiler/unittest_interpreter.cpp

- [Tflite] Implement `BuildTensors` 
```
This patch add `BuildTensors` which build tensors into *.tflite file.
```

[Tflite] Implement `BuildTensors`

---

nntrainer/layers/conv2d_layer.cpp
test/unittest/unittest_nntrainer_modelfile.cpp

- [Conv2d] Clean up conv2d relates
```
This patch handles issue left at #1042
See also: #1042, #1054
```

[Conv2d] Clean up conv2d relates

---

nntrainer/layers/addition_layer.cpp

Correct initialization of output

[Addition] fix forwarding

---

test/input_gen/genModelTests.py
test/input_gen/recorder.py
test/input_gen/transLayer.py

- [Test/models] prepare to support non-linear models
```
- Make `transLayer` from proxy to a legit layer
- Add output map so that in each layer can locate it's output from model
- Support non-linear output generation
- Add support for multi input, multi output
```

[Test/models] prepare to support non-linear models

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
test/input_gen/genModelTests.py
test/unittest/unittest_nntrainer_models.cpp

- [Test/Model] Prepare addition model
```
This patch add addition model test
```
~- **[Pending MERGE commit: #1188]** Merge branch '"'"'graph_core_moved'"'"' into as/validate/non_linears/2_base~
fixes #1213

[Wait for #1197] [Test/Model] Prepare addition model

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/layers/layer_internal.h

- [Tflite] Add model input, output
```
This patch add model to track input and output
```

[Tflite] Add model input, output

---

nntrainer/layers/lstm.cpp
nntrainer/layers/lstm.h
test/unittest/unittest_nntrainer_layers.cpp

This commit includes
. calDerivative & calGradient of LSTM Layer
. Modification of Forwarding of LSTM Layer

[ LSTM ] Backwarding Implementation

---

Applications/Embedding/jni/main.cpp

- [App] Make embedding golden data optional
```
This patch makes embedding golden data optional while changing return
status
```

[App] Make embedding golden data optional

---

nntrainer/layers/layer_internal.h
nntrainer/layers/meson.build
nntrainer/layers/split_layer.cpp
nntrainer/layers/split_layer.h
nntrainer/utils/parse_util.cpp

Added split layer scaffolding with its properties and initialization
Add forwarding and backwarding for the split layer
See Also #1208

[Split layer] Added support for split layer

---

Applications/Custom/LayerPlugin/layer_plugin_test.cpp
nntrainer/app_context.cpp
nntrainer/app_context.h
nntrainer/optimizers/adam.cpp
nntrainer/optimizers/adam.h
nntrainer/optimizers/optimizer_devel.cpp
nntrainer/optimizers/optimizer_devel.h
nntrainer/optimizers/optimizer_impl.cpp
nntrainer/optimizers/optimizer_impl.h
nntrainer/optimizers/plugged_optimizer.h
test/unittest/unittest_nntrainer_appcontext.cpp

Update optimizer setProperty interface based on the requirement
from the custom optimizer.
Enable plugged optimizer with the app_context

[optimizer] Enable plugged optimizer

---

nntrainer/compiler/tflite_interpreter.cpp

- [tflite] implement build operations in subgraph 
```
This patch implements build operation in the subgraph
```

[Wait for #1121] [tflite] implement build operations in subgraph

---

packaging/nntrainer.spec

Update spec packaging for tflite layer with tflite dependency

[pkg/spec] Update spec packaging for tflite layer

---

Applications/ProductRatings/jni/main.cpp
nntrainer/graph/graph_core.h

- Initialize member variable sorted
- Catch exception when create the tensor
resolves: 1231330, 1143556

[Fix] Initialize member variable

---

api/ccapi/src/factory.cpp
nntrainer/compiler/ini_interpreter.cpp
nntrainer/graph/network_graph.cpp
nntrainer/layers/layer.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
test/unittest/unittest_nntrainer_appcontext.cpp

Move flatten property out to layerNode
also prepare for moving other properties out to layerNode

[layer] Move flatten property to layerNode

---

test/input_gen/recorder.py

- [Recorder] Add Input map generation
```
There was a bug that layer input is directly from the previous layer.
If the model is not sequential, this assumption is not true, making
Addition test fail.
This patch build `model.recoder__input_maps` to correctly locate
the input tensor with some minor clean ups
```

[Recorder] Add Input map generation

---

Applications/LogisticRegression/res/LogisticRegression.ini

Reduce logistic regression application epochs.
This application is to check working than verify accuracy and can
run with fewer epochs.

[app] reduce Logistic regression application epochs

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp
nntrainer/compiler/tflite_opnode.h
nntrainer/utils/node_exporter.cpp

- [Exporter] Implement saving fc node
```
- This patch add saving fullyconnected layer with node_exporter
- add dedeicated buffer to `TfNode`
```

[Exporter] Implement saving fc node

---

api/ccapi/include/layer.h
jni/Android.mk
nntrainer/app_context.cpp
nntrainer/layers/meson.build
nntrainer/layers/permute_layer.cpp
nntrainer/layers/permute_layer.h
nntrainer/tensor/tensor_dim.cpp
nntrainer/utils/base_properties.h
test/unittest/unittest_base_properties.cpp

- [Layer] Add permute layer scaffolding
```
This patch adds permute layer scaffolding
**Minor Fix**
- Add error handling for transpose tensordim
```

[Layer] Add permute layer scaffolding

---

Applications/ProductRatings/jni/main.cpp
Applications/ProductRatings/jni/meson.build
Applications/ProductRatings/res/product_ratings_model.ini
nntrainer/layers/split_layer.cpp
nntrainer/layers/split_layer.h
nntrainer/tensor/tensor.cpp

~**[Pending commit: #1240]**~
- [SplitLayer] Support flexible dimension
```
This patch adds support for the flexible dimension in split layer.
Cc: Parichay Kapoor <pk.kapoor@samsung.com>
```
resolves #1238

[SplitLayer] Support flexible dimension @open sesame 06/03 12:41

---

Applications/TransferLearning/Draw_Classification/jni/meson.build
test/unittest/unittest_util_func.cpp

Update tolerance for sqrt unittest for debian arm64 packaging
increase timeout for appdraw classification app for debian armhf packaging
See also #1251

[deb/pkg] Updates for debian packaging

---

Applications/Custom/LayerClient/jni/Android.mk
Applications/KNN/jni/Android.mk
Applications/LogisticRegression/jni/Android.mk
Applications/MNIST/jni/Android.mk
Applications/ProductRatings/jni/Android.mk
Applications/ReinforcementLearning/DeepQ/jni/Android.mk
Applications/TransferLearning/CIFAR_Classification/jni/Android.mk
Applications/TransferLearning/Draw_Classification/jni/Android.mk
Applications/VGG/jni/Android.mk
Applications/utils/jni/Android.mk
api/ccapi/include/dataset.h
api/ccapi/include/layer.h
api/ccapi/include/model.h
api/ccapi/include/optimizer.h
docs/contributing.md
docs/getting-started.md
docs/how-to-run-examples.md
jni/Android.mk
meson.build

- [C++17] Bump base version to c++17
```
This patch bumps baseline version to c++17.
```

[C++17] Bump base version to c++17

---

Applications/Custom/LayerPlugin/layer_plugin_test.cpp
Applications/SimpleShot/test/simpleshot_centering_test.cpp
Applications/SimpleShot/test/simpleshot_centroid_knn.cpp
Applications/SimpleShot/test/simpleshot_l2norm_test.cpp
nntrainer/graph/network_graph.cpp
nntrainer/layers/layer.cpp
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_internal.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/plugged_layer.h
nntrainer/layers/split_layer.h
nntrainer/layers/time_dist.cpp
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/meson.build
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_nntrainer_appcontext.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp

- [API/Devel] Retouch devel header
```
- Change function sinature to exploit forward declaration
- s/export_to/exportTo
- Change header guard to be unique
```

[API/Devel] Retouch devel header

---

Applications/Custom/LayerClient/jni/Android.mk
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.h
nntrainer/tensor/manager.h
test/unittest/unittest_nntrainer_models.cpp

Added todo list for the layer context creation
Added minor new interfaces for the layer context
Disable in-place optimization and inference memory optimization

[context] Layer context creation scaffolding

---

nntrainer/layers/layer_context.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/var_grad.h
nntrainer/tensor/weight.h

Added support for request Tensors and Weights
Moved spec of Tensors and Weights to VarGrad and Weights correspondingly
Also created constructors for weights and var_grad with their specs

[manager] Support request Tensors and Weights 

---

nntrainer/models/neuralnet.cpp

Bug fix patch to use constant iterators for the graph.

[neuralnet] Bug fix for graph usage

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp

implement getInputDimension, getOutputDimension in layer_node
Run test: [ ]Passed [X]Failed [ ]Skipped

Implement get input dimension get output dimension in layernode

---

nntrainer/layers/gru.cpp
nntrainer/layers/gru.h
nntrainer/layers/rnn.cpp
nntrainer/layers/rnn.h
test/input_gen/genModelTests.py
test/unittest/unittest_nntrainer_models.cpp

- [ GRU ] implement fowarding / backwarding of GRU Layer
```
. forwarding implementation
. calGradient implementation
. calDerivative implementation
. gru_basic unittest
```
- Fix activation type
```
using hidden_state_activation_type
```

[ GRU ] implement fowarding / backwarding of GRU Layer 

---

nntrainer/layers/layer_devel.h
nntrainer/layers/layer_impl.cpp
nntrainer/layers/layer_impl.h
nntrainer/layers/meson.build
test/unittest/layers/unittest_layers_fully_connected.cpp
test/unittest/layers/unittest_layers_impl.cpp

- [Layer] Scaffold layer impl
```
**Major changes**
- Create `LayerImpl`
- Change `LayerDevel` signature
s/int initialize/void finalize
s/int setProperty/void setProperty
- Move createLayer to layerImpl
```

[Layer] Scaffold layer impl

---

Applications/Custom/LayerClient/jni/meson.build
Applications/Custom/LayerPlugin/layer_plugin_mae_loss_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
Applications/Custom/LayerPlugin/meson.build
Applications/Custom/mae_loss.cpp
Applications/Custom/mae_loss.h
Applications/Custom/meson.build
Applications/Custom/pow.cpp

- [Custom/Loss] Add scaffolding for loss example
```
This patch generates a skeleton code for mae custom loss example.
```

[Custom/Loss] Add scaffolding for loss example

---

nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/layer_node.h
nntrainer/utils/base_properties.cpp
nntrainer/utils/base_properties.h
nntrainer/utils/node_exporter.h
test/unittest/unittest_base_properties.cpp

**[Pending commit: #1292]**
- [Properties] Add float and boolean cases
```
Add float and boolean case to be used later.
```

[Properties] Add float and boolean cases

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h

Implement the function to create RunLayerContext given the
InitLayerContext and update it in the given LayerNode.

[wait for #1295] [graph] Support creating RunLayerContext 

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/loss_layer.cpp
nntrainer/layers/time_dist.h
nntrainer/models/neuralnet.cpp
test/unittest/unittest_nntrainer_models.cpp

- Implement getter for variable and grad of weight, input, output
- Implement getNumWeights

[layer-internal] refactoring weight, input, output to layer_node

---

nntrainer/layers/layer_context.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h

Added support for requesting inputs and outputs
Also update implementation to use a common function for easier
management

[manager] Add support for request Inputs/outputs

---

nntrainer/layers/common_properties.h
nntrainer/layers/layer_context.h
nntrainer/layers/layer_impl.cpp
nntrainer/layers/layer_impl.h

- [Layer] Add trainable prop
```
This patch add trainable property to layer
```

[Layer] Add trainable prop

---

Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_common_test.h
Applications/Custom/LayerPlugin/layer_plugin_mae_loss_test.cpp
Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
Applications/Custom/LayerPlugin/meson.build
Applications/Custom/mae_loss.h

**[Pending commit: #1268]**
- [Plugin/Test] Add preset plugin for general test
```
This extracts common test to be used multiple times.
```

[Plugin/Test] Add preset plugin for general test

---

nntrainer/graph/network_graph.cpp
nntrainer/tensor/manager.cpp

Support initialization and allocation of weights for LayerV2

[manager] Support initialization/allocation of weights 

---

Applications/Custom/LayerPlugin/layer_plugin_test.cpp
Applications/Custom/pow.cpp
nntrainer/app_context.cpp
nntrainer/app_context.h
nntrainer/compiler/ini_interpreter.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/layers/layer.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/plugged_layer.h
test/unittest/layers/layers_common_tests.cpp
test/unittest/layers/layers_common_tests.h
test/unittest/unittest_base_properties.cpp

**[Pending commit: #1306]**
- [LayerNode] Add layer(devel) to the node
```
- Add `Layer` to the node
- Remove `node_exporter.h` from `layer_node.h`
- Change compile time switch to runtime switch of checking layer v1 and
layer v2
```

[Wait for #1306] [LayerNode] Add layer(devel) to the node

---

nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/optimizers/adam.cpp
nntrainer/optimizers/adam.h
nntrainer/optimizers/optimizer_devel.h
nntrainer/optimizers/optimizer_impl.h
nntrainer/optimizers/plugged_optimizer.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
test/unittest/unittest_nntrainer_appcontext.cpp
test/unittest/unittest_nntrainer_layers.cpp
test/unittest/unittest_nntrainer_models.cpp

[Optimizer] Implement addOptimizerVariable
- Implement addOptimizerVariable as a parameter of tensordim
- Implement requestOptimizerVariable in manager

[Optimizer] Implement addOptimizerVariable

---

api/ccapi/include/layer.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/utils/base_properties.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

- [LayerNode] Change flatten and distribute to prop
```
- Fix bug on `loadProperties`
- Add flatten and distribute to prop
```

[LayerNode] Change flatten and distribute to prop

---

nntrainer/graph/network_graph.cpp
nntrainer/tensor/manager.cpp

Added memory allocation for non-weight tensors has been added
including inputs, outputs and tensors.
For now, this does include any optimization except the gradient
based optimization.

[manager] Memory allocation for non-weight tensors 

---

nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/var_grad.h
nntrainer/tensor/weight.h

Move loss to layer node for the registered weights.

[wait for #1313] [layernode] Move loss to layer node 

---

Applications/Custom/LayerClient/jni/Android.mk
Applications/Custom/LayerClient/jni/main.cpp
Applications/Custom/LayerClient/jni/meson.build
Applications/Custom/LayerClient/res/custom_layer_client.ini
Applications/Custom/mae_loss.cpp

- [CustomLoss] Update example
```
- Update example using LayerClient
- Add LayerClient example to AppTest
```
resolves #1256, #954

[CustomLoss] Update example

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/activation_layer.cpp
nntrainer/layers/activation_layer.h
nntrainer/layers/layer.cpp
nntrainer/layers/layer_internal.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/time_dist.cpp
nntrainer/utils/parse_util.cpp

Move activation from Layer internal to LayerNode

[layernode] Move activation to LayerNode @open sesame 06/22 18:12

---

.gitignore
Applications/Resnet/jni/main.cpp
Applications/Resnet/res/prepare_dataset.sh

- [Resnet/skeleton] Add helper functions
```
- Add `withKey()`, `resnetBlock()`, `createResnet18()`
```

[Resnet/skeleton] Add helper functions

---

jni/Android.mk
meson_options.txt
nntrainer/graph/network_graph.cpp
nntrainer/layers/fc_layer.cpp
nntrainer/layers/fc_layer.h
nntrainer/layers/layer.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_factory.cpp
nntrainer/layers/layer_factory.h
nntrainer/layers/layer_impl.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/tensor/var_grad.cpp
nntrainer/tensor/var_grad.h
nntrainer/utils/node_exporter.cpp
packaging/nntrainer.spec
test/meson.build
test/tizen_capi/meson.build
test/unittest/compiler/meson.build
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/meson.build
test/unittest/unittest_base_properties.cpp

1. Update fc layer for LayerV2
2. Update node_exporter to export weights from run_context
Add corresponding const getters and setters in layer_context
Updated some fixes in var_grad
3. Update layer factory for LayerV2 for creation of layers of signature
LayerV2.

[fclayer] Update fc layer for LayerV2

---

Applications/Resnet/jni/Android.mk
Applications/Resnet/jni/main.cpp

- [Resnet] Create resnet model
```
This patch creates code to create resnet.
```

[Resnet] Create resnet model @open sesame 06/30 16:02

---

packaging/nntrainer.spec

- [Fix/trivial] Change rpm group description
```
- Change group description to machine learning/ML Framework
```

[Fix/trivial] Change rpm group description

---

nntrainer/layers/fc_layer.h
nntrainer/layers/input_layer.cpp
nntrainer/layers/input_layer.h
nntrainer/layers/layer_factory.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h

Update input layer to upgrade to LayerV2 design

[wait for #1328] [inputlayer] Update input layer with LayerV2 design

---

Applications/Resnet/jni/Android.mk
Applications/Resnet/jni/cifar_dataloader.cpp
Applications/Resnet/jni/cifar_dataloader.h
Applications/Resnet/jni/main.cpp
Applications/Resnet/jni/meson.build
meson_options.txt

- [resnet] Implement test run to resnet
```
**Changes proposed**
- Add dataloader with interface `next()`.
- Add RandomDataLoader as an example
- Minor bug fixes to the model architecture regarding name
- Add routine to train the model
```

[resnet] Implement test run to resnet

---

Applications/Resnet/jni/cifar_dataloader.cpp
Applications/Resnet/jni/cifar_dataloader.h
Applications/Resnet/jni/main.cpp

**[Pending commit: #1339]**
- [Resnet] Connect the model with cifar100
```
- Implement cifar100dataloader
- Connect the data loader
```

[Wait for #1339] [Resnet] Connect the model with cifar100  @open sesame 06/30 20:04

---

nntrainer/tensor/weight.cpp

- [Fix] Weight initializer stddev calculation
```
The weight initializer was fitted to only fully connected layer case,
this patch extends weight initializer to properly work with other
weights as well.
```

[Fix] Weight initializer stddev calculation

---

Applications/Resnet/README.md

- [docs] Add readme for resnet
```
This patch adds readme for resnet including citations.
```

[docs] Add readme for resnet

---

Applications/Resnet/jni/cifar_dataloader.cpp
Applications/Resnet/jni/main.cpp
nntrainer/layers/output_layer.cpp
nntrainer/models/neuralnet.cpp

- [Resnet] Sync resnet app with validated model
```
This patch syncs resnet application with validated model.
Changes include:
1. s/setIteration/updateIteration
2. normalize input
3. fixed batchsize of 128 -> args received from the sysargs
4. output layer to copy
5. silent failed to read epoch idx and iteration
```

[Resnet] Sync resnet app with validated model

---

docs/configuration-ini.md
nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/conv2d_layer.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/flatten_layer.cpp
nntrainer/layers/flatten_layer.h
nntrainer/layers/layer_impl.h
nntrainer/tensor/tensor_dim.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_convolution2d.cpp
test/unittest/layers/unittest_layers_flatten.cpp
test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_models.cpp
test/unittest/unittest_nntrainer_tensor.cpp

update to Layerv2 format for convolution2d and flatten.
Open the corresponding modelfile, models and common unittests.

[conv2d/flatten] Update to Layerv2

---

api/capi/include/nntrainer.h
api/capi/meson.build
api/ccapi/include/model.h
jni/Android.mk
jni/prepare_ml-api.sh
meson.build
packaging/nntrainer.spec

- [CAPI] Add ml_train_model_get_input|output_dims
```
This commit contains capi proposal to
`ml_train_model_get_input_dimensions` and
`ml_train_model_get_output_dimensions`
```

[CAPI] Add ml_train_model_get_input|output_dims

---

test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_activation.cpp

Add semantic tests for activation layer

[test] Add semantic tests for activation layer

---

nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/conv2d_layer.h
test/unittest/unittest_common_properties.cpp
test/unittest/unittest_nntrainer_models.cpp

~**[Pending commit: #1357]**~
- [Conv2D] Apply padding props to conv2d
```
This patch applies padding property to conv2d
```

[Conv2D] Apply padding props to conv2d

---

test/unittest/layers/layers_dependent_common_tests.cpp
test/unittest/layers/layers_standalone_common_tests.cpp

Add more layer common unittests without involving runContext for the
layers.

[tests] Add more layer common unittests 

---

api/capi/include/nntrainer.h
api/ccapi/include/dataset.h
api/nntrainer-api-common.h

- [CAPI] Propose dataset api sets
```
- `ml_train_dataset_create(ml_train_dataset_h *dataset);
- `ml_train_dataset_add_generator(dataset, usage, callback, user_data)`
- `ml_train_dataset_add_file(dataset, usage, file)`
- `ml_train_dataset_set_property_for_usage(dataset, usage)`
```

[CAPI] Propose dataset api sets

---

nntrainer/layers/gru.cpp
nntrainer/layers/gru.h
nntrainer/layers/lstm.cpp
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_gru.cpp
test/unittest/unittest_nntrainer_models.cpp

Update GRU implementation using layer_v2 design.
Update and enable corresponding unittests.

[layer] Update GRU for layer_v2

---

Applications/LogisticRegression/jni/main.cpp
Applications/VGG/jni/main.cpp
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/databuffer.h
nntrainer/dataset/databuffer_factory.cpp
nntrainer/dataset/databuffer_file.cpp
nntrainer/dataset/databuffer_file.h
nntrainer/dataset/databuffer_func.cpp
nntrainer/dataset/databuffer_func.h
nntrainer/models/model_loader.cpp
nntrainer/models/neuralnet.cpp
test/tizen_capi/unittest_tizen_capi_dataset.cpp
test/unittest/unittest_databuffer_file.cpp

- [dataset/cleanup] Remove type from dataset
```
This patch removes `datasetUsageType` from dataset interface
```

[dataset/cleanup] Remove type from dataset

---

nntrainer/layers/preprocess_flip_layer.cpp
nntrainer/layers/preprocess_flip_layer.h
nntrainer/layers/preprocess_translate_layer.cpp
nntrainer/layers/preprocess_translate_layer.h
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_preprocess.cpp
test/unittest/unittest_nntrainer_models.cpp

Update preprocess layers for layerv2 design.
Enable corresponding unittests.

[layer] Update preprocess layers for layerV2 
