nnstreamer/nntrainer

nntrainer/graph/network_graph.cpp
nntrainer/tensor/manager.cpp

- As bn layer does ln layer also does not need input in backwarding.
- This commit will make lifespan of ln layer input as FORWARD_FUNC_LIFESPAN.

[ln] optimize layer normalization layer input memory

---

api/capi/include/nntrainer.h
api/capi/src/nntrainer.cpp
api/ccapi/include/layer.h
nntrainer/layers/layer_node.h
test/tizen_capi/unittest_tizen_capi.cpp

This patch add the
``` c
ml_train_model_get_weight(ml_train_model_h model, const
char *layer_name, ml_tensors_data_h *weight, ml_tensors_info_h *info)
```
Now, developers are able to get the weight data & weight information.
ml_train_layer_get_weight will be added later.
Resolves: #2045

[API] add ml_train_model_get_weight api

---

nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
test/unittest/memory/unittest_cache_pool.cpp

loadExec/unloadExec are to validate/invalidate cache elements by
execution order.
loadActives/unloadActives are for swap in/out whole active
cache data, which will be used in pause/resume behaviors.
issue:#2034

[SWAP] Add load/unload methods to cachepool @open sesame 11/11 10:50

---

README.md

Fix some minor errors in README.
- Delete pooling2D layer description because it was duplicated twice.
- Fix some typo errors.
Signed-off-by: Seungbaek Hong <sb92.hong@samsung.net>

[README] Delete duplicate layer description and Fix typo errors.

---

nntrainer/graph/network_graph.h

fix the typo error in network_graph.h
the cbegin function returns a forward const iterator. 
so, removed \'reverse\' from retval description.

[typo] Fix typo

---

Applications/utils/datagen/cifar/cifar_dataloader.cpp
Applications/utils/datagen/cifar/cifar_dataloader.h

Fix RandomDataLoader parm (iteration_for_one_epoch) --> data_size
- in RandomDataLoader it make data as much as data_size
- if developer set iteration_for_one_epoch as iterate size it doesn't work
- for example developer want to make BATCH 64 and ITER 1 it should be 64 in iteration_for_one_epoch so it doesn't make sense
- for more clearly change it's name

[DataGen] Fix RandomDataLoader parms

---

api/capi/src/nntrainer.cpp
nntrainer/tensor/task_executor.cpp

- Added variable \'cur\' used for erase.
Current position is stored in cur, and the increment operation is performed on the iterator.
If an erase is required, cur is deleted and the iterator is unaffected.
- The for loop runs only once due to a return.
To resolve this issue, we added a conditional statement to run return when it is not ML_ERROR_NONE.
- The parameters of the functions \'ml_tensors_data_destroy\' and \'ml_tensors_info_destroy\' are both of the types \'ml_tensors_data_h\'.
However, several code are using address values.
Added dereference operator to match parameter type.

[Trivial] Fix svace issue @open sesame 12/20 15:37

---

nntrainer/nntrainer_logger.cpp
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

Because windows doesn't support "localtime_r" function, the "getLocaltime" function was added to use the "localtime_s" function in windows and the "localtime_r" function in linux.
Signed-off-by: Seungbaek Hong <sb92.hong@samsung.net>

[utils] add getLocaltime function @open sesame 12/20 19:20

---

nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h

- Return value of lseek is offset of requested position. The 4byte int type cannot represent more than 3GB so any request more than 3GB offset cause overflow.

[swap_device] change lseek return type from int to off_t @open sesame 12/20 15:37

---

nntrainer/compiler/tf_schema.fbs

Update Tensorflow Lite FlatBuffer Schema Version 3a --> Version 3b
- Rename fields in SignatureDef.
- Has Compatibility with Version 3 and 3a
For update Tensorflow version

[FlatBuffers] Update Tensorflow Lite FlatBuffer Schema @open sesame 12/20 15:35

---

nntrainer/models/neuralnet.h

Change the default value of the "free_mem" parameter to false 
in the inference function.
Since the "free memory" option can be used only when the model 
is in the training mode, the desired results may not be obtained 
if the "free_mem" parameter is set to true when we run inference
without training the model.
Therefore, it is better to set "free_mem" option to true only when
this option is needed.
Signed-off-by: Seungbaek Hong <sb92.hong@samsung.net>

[model] Change the default value of parameter in inference function @open sesame 12/20 16:40

---

Applications/Resnet/tensorflow/resnet18.py

In Tensorflow 2.x tf.compat or tf.session deprecated
- update random setting
- Tested on tensorflow 2.11
Close #2073

[Tensorflow] Update resnet18 example ( TF1 to TF2 )

---

api/ccapi/include/layer.h
nntrainer/graph/network_graph.cpp

- For now identity layer is not considered for support inplace in network graph.
- This commit will enable identity layer to support inplace.

[layer] enable identity layer to support inplace

---

nntrainer/compiler/flatten_realizer.cpp

modify "flatten_realizer.cpp" script for consistent codes of "flatten_realizer.cpp" and "activation_realizer.cpp".
"flatten_realizer" and "activation realizer" contain exactly same implementation but written in slightly different ways.
It's a very trivial matter, but I thought it would be better to write the same implementation in the same code, so I modified it.

[trivial] modify flatten_realizer script for consistent codes

---

nntrainer/compiler/activation_realizer.cpp
nntrainer/compiler/flatten_realizer.cpp

The flatten_realizer.cpp and activation_realizer.cpp declare the same local variable. 
However, the actual code order was written differently. 
Minor modifications were made for code consistency.

[Trivial] Modify for code consistency

---

api/ccapi/include/model.h

the default value of the "type" parameter of the "createModel" function is set to NEURAL_NET.
the createModel function receives the model type as a parameter, but the only value that can be set is NEURAL_NET.
(KNN is also not supported by the createModel function in API)
Thus, it is inefficient to set the parameter value every time because there is no other option.

[API] set default value on createModel function

---

nntrainer/tensor/cache_elem.cpp
nntrainer/tensor/cache_elem.h
nntrainer/tensor/cache_loader.cpp
nntrainer/tensor/cache_loader.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/memory_data.h
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h
nntrainer/tensor/meson.build
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/task.h
nntrainer/tensor/task_executor.cpp
nntrainer/tensor/task_executor.h
nntrainer/utils/profiler.cpp
nntrainer/utils/profiler.h
test/unittest/memory/meson.build
test/unittest/memory/unittest_cache_loader.cpp
test/unittest/models/models_golden_test.h
test/unittest/unittest_nntrainer_task.cpp

This patch adds cache loader class.
Cache loader supports loading cache elements methods in both synchoronous and
asynchronous manners. Asynchoronous methods are using task executor, and
loods whole cache elements with execution orders in other thread.

(Wait for #2055) [SWAP] Add CacheLoader class @open sesame 11/17 16:55

---

Applications/Resnet/PyTorch/main.py

Add Resnet PyTorch Example
- It support only training if user want to use this code, user need to update code with test, validation
- This Example's Dataset : CIFAR100
- This Example's network exactly same with NNtrainer Resnet18 example
- We conduct benchmark test base on this code

[Application] Add Resnet Pytorch example @open sesame 01/31 14:00

---

nntrainer/graph/graph_core.h

- Fix undefined behavior in cend() of \'graph_core.h\'
The cend() function dereference node_list.cend(). This is undefined
behavior because it accesses memory in an area that is not actually
allowed. So changed cend() to operate normally through cbegin() + size.
However, these changes also include problems. Usually, check that
node_list is empty, and if it is, it will be treated as an exception.
if use cbegin() and cend() when node_list is empty, there might be a
problem. So, Added this caution at @note.
- Fixed a minor typo.
Related : #2086

[Graph] Fix cend function

---

nntrainer/nntrainer_logger.cpp
nntrainer/nntrainer_logger.h

This patch adds types fo log timestamp type.
NNTRAINER_LOG_TIMESTAMP_SEC: year, mon, day, hour, min, sec
NNTRAINER_LOG_TIMESTAMP_MS: milliseconds from log start

[Utils] Add log timestamp type

---

nntrainer/tensor/task.h
nntrainer/tensor/task_executor.cpp
nntrainer/tensor/task_executor.h
test/unittest/unittest_nntrainer_task.cpp

It's changed to use work queue to manage executions. There is some overhead for stop and cancel behaviors, so they are removed temporaly now, due to the performance.

[SWAP] task executor: Remove stop and clean feature

---

nntrainer/tensor/cache_pool.cpp

cache policy determines whether swap in/out operation is needed
when cache data is requested. The policies are inferred from
tensor lifespan.

(Wait for #2098) [SWAP] Implement cache policy

---

nntrainer/graph/network_graph.cpp
nntrainer/models/neuralnet.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h

This patch is for implementing tarinable property behavior.
If a layer is set as non-trainable, it doesnot need to execute calcGrad step, so we can remove it from execution order, also skip gradient calculation.

[Tensor] Remove calcGrad step for non-trainable layer

---

Applications/Layers/Tensorflow/Conv.py
Applications/Layers/Tensorflow/LSTM.py
Applications/Layers/Tensorflow/Linear.py
Applications/Layers/Tensorflow/Model_A_Conv.py
Applications/Layers/Tensorflow/Model_A_Linear.py
Applications/Layers/Tensorflow/Model_C_Conv.py
Applications/Layers/Tensorflow/Model_C_Linear.py

Add Simple Tensorflow Examples with Dummy Data
- Linear
- Conv
- LSTM
- Model_A_Linear
- Model_A_Conv
- Model_C_Linear
- Model_C_Conv
It has same Layer with NNtrainer example that has same name

[Wait for #2102][Application] Add Simple Layer Tensorflow Examples

---

nntrainer/layers/acti_func.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/attention_layer.cpp
nntrainer/layers/attention_layer.h
nntrainer/layers/mol_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/multi_head_attention_layer.h

Commit 1:     [mol attention] adjust tensor lifespan to save memory
- Modify tensor lifespan of fc_out to FORWARD_FUNC_LIFESPAN
- remove unused enum updated_state
- Change param enum name from AttentionParams to MoLAttentionParams
Commit 2:     [activation] revise softmaxPrime to overwrite incoming derivative
- Revise softmaxPrime to overwrite incoming derivative by using additional temp memory
- Remove attention_score tensor in attention/multi_head_attention layer
- Reuse temporary tensor for softmax in mol attention layer
close #1986

[activation] Overwrite derivative in softmax

---

nntrainer/tensor/manager.h
nntrainer/utils/profiler.h

- add swap_lookahead to default constuctor of Manager
- add cache_swap to default constructor of ProfileEventData

[Trivial] Fix svace and coverity issue @open sesame 02/21 14:35

---

.github/workflows/labeler.yml

- this git action yml will automatically label "Need Review" when cretae PR
- when it edit or reopen it will automatically make label
- and It also remove when approved review exceed 3
For this we need ```secrets.GITHUB_TOKEN```
For Test this branch should be upstream's branch that why I made gitaction-review branch : after merge i will remove this branch asap

[Propose][GitAction] Review Request Auto labeler @open sesame 02/21 13:48 

---

.github/workflows/Upload.yml
.github/workflows/labeler.yml

Problem
- on Review commented, Review Approved There is error on http api
- it can't call issue's number because event num only valid if it run's by pull request it self
For solve this problem
- change api ```github.event.number``` to ```github.event.pull_request.number```
- change script version and some trivial part

[GitAction] Fix Labeler on review commented

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp

This patch refines forwading operation in neural network class.
The code depth is not matched for forward and backward operations. For backwarding operation, there is backwarding_op and it pasded to the graph, which can handle the operation.
To keep same depth for forwarding, this patch adds forwarding_op function, and passed to the graph class.
Releated Issue:
\#2108

[NEURALNET] Refine forwarding operation @open sesame 03/03 16:35

---

Applications/YOLO/PyTorch/dataset.py
Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo.py
Applications/YOLO/PyTorch/yolo_loss.py

Add YOLO v2 object detection example using pytorch.
It was implemented in the same way as the YOLO v2 model, but only the backbone model was made into a simpler cnn model to make it easier to configure the initial version of YOLO to be implemented by NNTrainer.
In order to clarify the parts to be implemented by NNTrainer, it is a code that constructs only the basic structure proposed in the original yolo paper, excluding several third-part training techniques.

[Application] add object detection example using pytorch

---

Applications/Resnet/PyTorch/main.py
tools/pyutils/torchconverter.py

I modified resnet example to save model trained from pytorch as nntrainer binary model format.
"translayer_v2.py" is renamed to "torchconverter.py" and moved to tools folder so that it can be used for common modules.
- the pytorch resnet example model is modified to be the same as the nntrainer resnet example model.

[Application] Save model trained from pytorch as nntrainer model format @open sesame 03/08 07:58

---

nntrainer/compiler/meson.build
nntrainer/compiler/nntrainer_schema.fbs

- This schema for Flatbuffer export
- It contain only Fully-connected Layer Options
- It contain tensorflow lite's schema
- For compiler nntrainer_schema_generated.h
**_This will be updated for more layers and operators_**

[Wait for #2109][FlatBuffer] Add nntrainer_schema.fbs @open sesame 03/13 15:00

---

nntrainer/compiler/flatbuffer_opnode.cpp
nntrainer/compiler/flatbuffer_opnode.h

- For flatbuffer interpreter : bring opnode and make variable
- Now only support Fully Connected Layer
- Now only support NCHW format tensor
**_It will be updated_**

[Flatbuffer] Add flatbuffer_opnode @open sesame 03/13 16:13

---

Applications/TransferLearning/Draw_Classification/jni/meson.build
debian/control
debian/nnstreamer-nntrainer-trainer-dev.install
debian/nnstreamer-nntrainer-trainer.install
debian/rules
meson.build
meson_options.txt
nnstreamer/meson.build
nnstreamer/tensor_filter/meson.build
nnstreamer/tensor_trainer/meson.build
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh
packaging/nntrainer.spec
test/meson.build

Create nnstreamer tensor_trainer subplugin
Subplugin Receive GstTensorTrainerProperties from nnstreamer tensor_trainer to create dataset and model. 
it receive tensor data from tensor_traner and train the model.
Subplugin is created by using GstTensorTrainerFramework and tensor_trainer call create, destroy, start and push_data.
* tensor_trainer_nntrainer.cc is a nnstreamer sub-plugine be used by nnstreamer(tensor_trainer) for training model.
1. Models are limited to creating with configuration files.
2. sub-plugin receives only pre-processed tensor data.
3. The current feature behavior has been tested with MNIST.
gst-launch-1.0 datareposrc location=mnist_trainingSet.dat …

[nnstreamer] Create nnstreamer tensor_trainer subplugin @open sesame  03/22 09:20

---

api/ccapi/include/dataset.h
nntrainer/dataset/dir_data_producers.cpp
nntrainer/dataset/dir_data_producers.h
nntrainer/dataset/meson.build
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
tools/package_android.sh

This pr includes directory dataset producer for bmp image only.
We can extend the type of image to jpg, png with the proper decoder and add a resizer according to requirements.
C API and unit test cases will be added later PRs.

[ Dataset ] Add Directory Dataset Producer @open sesame 03/24 20:22

---

api/ccapi/include/layer.h
nntrainer/layers/acti_func.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/activation_layer.cpp
nntrainer/layers/common_properties.h
test/unittest/layers/unittest_layers_activation.cpp
test/unittest/unittest_nntrainer_activations.cpp

Added the swish activation function.
It needs input of activation and output of activation
to calculate derivative value.
So, I overload run_prime_fn function to use
input and output for calculating derivative.
- add swish activation
- add test case about swish activation function
**Issue**
Currently, this swish activation function is NOT SUPPORTED
in RNN, LSTM, GRU and Attention layers. 
I opened issue about it : #2118
I will resolve this problem later. 

[activation] add swish activation function @open sesame 02/28 16:20

---

nntrainer/tensor/blas_interface.cpp

This PR allows to have 0 for incX and incY in tensor raw compuation to enable broadcasting tensor operation.

[ Tensor ] allow to have inc 0 for broadcasting for raw computation

---

Applications/SimpleShot/task_runner.cpp
nntrainer/layers/preprocess_l2norm_layer.cpp
test/unittest/unittest_nntrainer_models.cpp

This PR enables the l2norm preprocessor layer to support batch computation.

[Layer] Support batch computation for l2norm layer

---

.github/workflows/Upload.yml

Fix Duplicate Approval
- now git action count all approval
- For example someone Approve PR --> Update PR --> Approve Again then they count 2
- For example CI Approve PR every time they success then gitaction count them all
The given Git Action code performs the following tasks
1. Uses the curl command to call the GitHub REST API and retrieve a list of reviews for the given pull request in the repository.
2. Uses the jq command to filter the reviews based on whether their state is "APPROVED".
3. Extracts the login names of the users who wrote each of the filtered reviews.
4. Uses the unique function to filter out only the unique login names, removing any duplicates.
5. Calculates the length of the resulting list of unique login names, giving the count of unique users who have approved the …

[GitAction] Fix Duplicate Approvals @open sesame 04/03 14:45

---

test/ccapi/unittest_ccapi.cpp
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/models/models_golden_test.cpp

Fix Ahub Defect
- change ```stderror``` to ```stderror_r```
- stderror makes no guaranteee of thread safety
```nntrainer/test/ccapi/unittest_ccapi.cpp```
```nntrainer/unittest/compiler/unittest_interpreter.cpp```
```nntrainer/unittest/models/models_golden_test.cpp```

[AHub] Fix AHub Defect

---

api/ccapi/include/tensor_dim.h
nntrainer/layers/fc_layer.cpp
nntrainer/tensor/tensor_dim.cpp
nntrainer/utils/node_exporter.cpp

In order to support Channel Last & Channel First at the same time, we need to define the Tensor Format in TensorDim Class.
According to the format of tensorDim, it return proper value for the APIs such as bacch(), channel(), height() and width().
The default format is Channel First as it is now.
If nothing is provided when a Tensor is constructured, then it is set NCHW.

[ TensorDim ] Add tensor format in TensorDim

---

nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_tensor.cpp

This PR includes the default Tensor format (NCHW) in Tesnor
Constructor. It also includes the unittest cases for HHWC Tensor
format. Even though it has Tensor format property, but still it needs
to implement the actual tensor operation.

[ Wait for #2164] [ Tensor ] Add default Tensor format in Tensor constructor 

---

debian/control

nntrainer-dev depends on ccapi-ml-training-dev and capi-ml-training-dev.
This PR add these dependency for nntrainer-dev

[Debian] Fix the debian package dependency @open sesame 04/07 20:08

---

Applications/YOLO/jni/Android.mk
Applications/YOLO/jni/det_dataloader.cpp
Applications/YOLO/jni/det_dataloader.h
Applications/YOLO/jni/main.cpp
Applications/YOLO/jni/meson.build

Add detection dataloader for yolo example.
- Set target directory, then this dataloader loads dataset
from "images" and "annotations" folders.
- Currently, It only supports "bmp" image format.
- For variable label data, it adds zero padding to label.

[Application] dataloader for yolo @open sesame 04/07 20:08

---

api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/capi/src/nntrainer.cpp
api/ccapi/include/optimizer.h
api/ccapi/src/factory.cpp
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/optimizers/lr_scheduler.h
nntrainer/optimizers/optimizer_wrapped.cpp
nntrainer/optimizers/optimizer_wrapped.h
test/tizen_capi/meson.build
test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
test/tizen_capi/unittest_tizen_capi_optimizer.cpp

Commit 1:     [ccapi] rename LearningRateType enum name to LearningRateSchedulerType
- rename enum name LearningRateType to LearningRateSchedulerType for more detailed info
Commit 2:     [ccapi] change setLearningRateScheduler function prototype
- Change return type from void to int.
Capi will call this function so it should be return status.
- Change learning rate scheduler pointer from unique_ptr to shared_ptr
Commit 3:     [capi] add learning rate scheduler related api
- Added learning rate scheduler create/destroy/set property api
- Added set learning rate scheduler to optimizer
- Added ml_train_lr_scheduler_type_e enum
- Fix some comments
Signed-off-by: hyeonseok lee …

[capi] add learning rate scheduler related api

---

api/capi/include/nntrainer-tizen-internal.h
api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/capi/include/nntrainer_util.h

I've checked some api issues using tizen-native-api-review-script.
So, I correct most issues but there are still remain some errors in the "nntrainer_internal.h" file.
There are three type issues remaining yet.
- enum names should end with '_e'
- struct names should end with '_s'
But I think It would be better to do not rename these enum and struct because it is already released in earlier version.
And, The last type issues seem to be "false positive". I think tizen-api-review-script don't aware the macro function, etc.

[capi] fix some api issues for tizen release @open sesame 04/18 20:05

---

api/capi/include/nntrainer.h

The notation for future version has been modified.
- "tizen 8.0" to "later version".

[capi] fix comment for tizen release

---

Applications/Resnet/jni/main.cpp

Now TFLITE Interpreter is not support loss : cross type 
So in Resnet Application we made some macro to make them mse and there was some wrong part
in ResNet Application there was another macro for ENABLE_TEST GTEST's result assume that Application use cross loss
For Correct Result Fix some #if statement
**TODO :  even if fix this situation TEST still failed regardless of tflite export releated code. it seem to be data feeding problem**
```.txt
../Applications/Resnet/jni/main.cpp:233: Failure
Expected equality of these values:
training_loss
Which is: 4.3914199
4.389328
../Applications/Resnet/jni/main.cpp:234: Failure
Expected equality of these values:
validation_loss
Which is: 11.514971
11.611803
```

[Application] Fix Resnet Application -ENABLE_TFLITE_INTERPRETER CASES

---

api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/nntrainer-api-common.h

Fixed notation "tizen 7.5" to "tizen 8.0" for tizen release.

[capi] fix notation for tizen 8.0 @open sesame 06/12 11:45

---

nntrainer/tensor/manager.cpp

There is bug when the model loads the data for the batch normalziation layer.
During the setup the requestWeights in manager, it add the max execution order for graddient for gradient clipping, but variable weight also added. This pr fixs it.

[ Bug ] Fix the bug read the weight for batch normalization layer

---

api/ccapi/include/tensor_dim.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/unittest/meson.build
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

This PR includes changes of Tensor and TensorDim to support NHWC computation for dot, add_strided, multiply_strided, cat, split, and transpose. It also includes unit tests to evaluate.

[ Tensor ] Support NHWC for dot, add/multiply_strided and other ops

---

nntrainer/graph/graph_node.h

- Explicitly provide the parameter as default parameter for stl iterator is deprecated.

[graph_node] handle deprecated stl iterator

---

nntrainer/models/neuralnet.cpp

When we print the model architecture using summarize method, nntrainer prints input dimension of each layer.
But, tensorflow and pytorch are printing output dimmension of each layer in the summary, thus it is inconvenient to compare each layer with tf and torch models.
Thus, I suggest to print output dimension of each layer instead of input dimension in the model summary.

[LOG] print output dim instead of input dim in model summary  @open sesame 06/13 14:48

---

nntrainer/compiler/multiout_realizer.cpp
test/unittest/compiler/unittest_realizer.cpp

Create multiout nodes with a given connection order in building a frequency map.
Signed-off-by: Donghyeon Jeong <dhyeon.jeong@samsung.com>

[Compiler] Preserve connection order in multiout realizer @open sesame 08/02 17:37

---

docs/getting-started.md

Tizen reference link has been changed.
So, updated getting-started.md with the lastest link.
previous : https://source.tizen.org/documentation/reference/git-build-system/usage/gbs-build
updated :  https://docs.tizen.org/platform/developing/building
Thanks to this PR, I knew. **https://github.com/nnstreamer/nnstreamer/pull/4170**
================================
================================

[Doc] Fix tizen reference link

---

nntrainer/layers/fc_layer.cpp
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/tensor/tensor.cpp
test/unittest/layers/layers_golden_tests.cpp
test/unittest/layers/unittest_layers_fully_connected.cpp

This PR contains changes from the commits in [PR#2238](https://github.com/nnstreamer/nntrainer/pull/2238) and [PR#2240](https://github.com/nnstreamer/nntrainer/pull/2240) since these are required to evaluate the end to end working by the tests
Commit b57f0b222a6027b174575c60bc05fc7f759c6362 is the one that contains the newly added changes.

[FullyConnected] Added NHWC support for FC_Layer inference part.

---

Applications/YOLOv3/PyTorch/yolo.py

Added pytorch darknet53 model for yolo v3.
It is used in yolo v3 as a backbone model.
I'll add nntrainer implementation, too.

[Application] darknet53 pytorch implementation for yolo v3  @open sesame 06/10 19:30

---

nntrainer/layers/nnstreamer_layer.cpp

- Recently nnstreamer set 0 for padded value of dimensions.
- Let dimension value 1 for nntrainer when nns give 0.
REF: https://github.com/nnstreamer/nnstreamer/pull/4111

[nnstreamer] Set dim value as 1 when nnstreamer give 0 value

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh

An existing model registered in model_load_path is used when training a new model.

[sub-plugin] Add function to load an existing model

---

nntrainer/tensor/tensor_pool.cpp

This PR enables the TensorPool view to filter call from different tensor type.

[TensorPool] Check tensor type in view

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

<details><summary>   Add NEON fp16 function for snrm2    </summary><br />
Enable neon snrm2 function for Android (ARM) fp16 computation. Add unit test for fp16 snrm2 function in Android(ARM).
</details>
<details><summary>   Add NEON fp16 function for sscal    </summary><br />
Enable neon sscal function for Android (ARM) fp16 computation. Add unit test for fp16 sscal function in Android(ARM).
Modified snrm2 function brief.
</details>
<details><summary>   Add NEON fp16 function for scopy    </summary><br />
Enable neon scopy function for Android (ARM) fp16 computation. …

[blas/neon] NEON fp16 functions for Android(ARM)

---

nntrainer/models/neuralnet.cpp

**Set model batch size 1, when exported to tflite model format**
Now, After train the model and export it to the tflite format, it will be exported with the batch size used for learning.
However, for interference, it is not necessary to have a batch size, and when converting to a tensorflow lite format in tensorflow, the batch size is set to 1.

[tflite_export] Set model batch size 1, when exported

---

Applications/YOLO/PyTorch/dataset.py
Applications/YOLO/PyTorch/main.py
Applications/YOLO/PyTorch/yolo.py
Applications/YOLO/jni/Android.mk
Applications/YOLO/jni/main.cpp
Applications/YOLO/jni/meson.build
Applications/YOLO/jni/reorg_layer.cpp
Applications/YOLO/jni/reorg_layer.h

Added Re-organization layer to yolo v2 examples
of nntrainer and pytorch.
Now model implementation is same with
architecture of yolo v2 paper.

[Application] add re-orginization layer to Yolo v2

---

api/ccapi/include/tensor_dim.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_dim.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp
test/unittest/unittest_nntrainer_tensor_pool.cpp

- Quantized Tensor is now available with Int 4 with scale.
- Two Int 4 values use one Int 8 which each use 4 bits
- Dequantization is performed by multiplying scaling factors with given index (b, c, h, w).
- Only read (getValueQint4), write (setValue), and dequantization operations are allowed.

[Tensor] Quantized Tensor (Int 4) with Scale

---

debian/changelog
meson.build
packaging/nntrainer.spec

NNTrainer v0.5.1 is released.
Resolves:

[Release] NNTrainer v0.5.1 Release @open sesame 09/18 10:37

---

Applications/SimpleShot/task_runner.cpp

- Handle when getcwd return NULL to prevent dereference null pointer

[Application] handle getcwd return null pointer @open sesame 09/15 16:46

---

api/capi/include/nntrainer.h
api/capi/include/nntrainer_internal.h
api/nntrainer-api-common.h

**[Tizen] Fix Tizen Version (7.5 -> 8.0)** 
Tizen use version 7.5 no longer use, but some api docs marked as 7.5, so Fix version to 8.0

[Tizen] Fix Tizen Version (7.5 -> 8.0) @open sesame 09/12 20:44

---

Applications/meson.build
nntrainer/compiler/multiout_realizer.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/input_layer.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/loss/loss_layer.cpp
nntrainer/nntrainer_logger.cpp
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/tensor.cpp
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h
test/unittest/compiler/compiler_test_util.cpp
test/unittest/layers/layers_golden_tests.cpp

- Fixed the part where buf is not initialized and used in nntrainer_logger.cpp. 
Array initialized with ascii 0 ('\0').
- changed 'auto' to 'auto &'
- The 'initialized' variable receives a pointer via malloc.
If malloc fails, it will be null.
However, since the exception is not handled, calling initialize[i] points to null + i.
Exception handling has been added to prevent this problem.
- Restore does not work as expected after changing ostream type.
Added because there is no code to restore the variable out.
Changed the code where the nesting depth was set incorrectly to the correct location.
- Previously, nntrainer only supported fp32. nntrainer didn't need to change the data type, but it needs to be changed to support fp16.
If the tensor type is fp16, get input_dim of InitLayerContext …

[Ahub] Fix Ahub issue @open sesame 09/20 12:27

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h

Added exception handling when malloc fails.
The value of the idx variable has been changed to be initialized when declared.
In the tensor constructor, output_axis was changed to be initialized to 3.

[Svace] Fix Ahub issues

---

Applications/YOLO/jni/yolo_v2_loss.cpp
nntrainer/optimizers/adam.cpp
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h
test/unittest/unittest_nntrainer_tensor_fp16.cpp

This patch fixes the build error in yolo_v2_loss with fp16 enabled. The following works are done.
- Template sqrtFloat and absFloat
- Remove unnecessary print in the fp16 unit test

[Bug] Fix build error in yolo with fp16 @open sesame 09/15 16:02

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
test/unittest/unittest_nntrainer_tensor_fp16.cpp

- Previously, sgemm and sgemv in neon intrinsics was depdendent on two conditions
1. should have 8-divisible column or row
2. fully work with fp16 variables (which might cause precision loss while being accumulated)
- In this commit, I expect sgemm and sgemv to work like:
1. support every column length with adaptive-length-compute optimization
2. use temporal fp32 array to secure cumulative data value especially in large scale Tensor
3. accelerate converting such fp32 array to fp16 Tensor and vice versa with neon to enhance time performance
4. consider the number of register to avoid register spilling
- Moreover, with this new logic, we need to get rid of unittest cases that compares full fp16 variables with neon result. From now on, we should only compare our result with fp32 Tensors. …

[Wait for #2311] [blas/neon] Use inter-fp32 value in dimension shrinking computation in neon

---

nntrainer/graph/network_graph.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_wrap_specs.h
nntrainer/tensor/weight.cpp
nntrainer/tensor/weight.h
test/unittest/layers/layers_golden_tests.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

- FC layer manually dequantizes quantized weight tensor in forwarding instead of automatically dequantizing in getWeight.
- Dequantize function takes the output axis as a parameter instead of the tensor having an axis variable.
- Add output axis in weight spec to identify the direction of scale and zero points multiplication.

[Tensor] Dequantize tensor in forwarding FC layer 

---

nntrainer/tensor/blas_neon.cpp

- Instead of declaring explicit register variable, declaring the function in inline code can save the number of register variable in use.
- This way, we can load more of variables to accelerate sgemv computation

[neon] Optmize sgemv

---

nntrainer/tensor/tensor.cpp

Added gaussian error function(erf) to Tensor
and unittest for this.
It was already added pr #2208,
but it is deleted in pr #2238 (I don't know why it is deleted).
So, I restored that function for our tensor operation.

[Tensor] Add erf operation to Tensor @open sesame 09/15 10:43

---

Applications/utils/datagen/cifar/cifar_dataloader.cpp
Applications/utils/datagen/cifar/cifar_dataloader.h

**Update Cifar100 Dataloader (Cifar100 Dataloader is not compatible with real Cifar100 dataset)**
- now our Cifar100 Dataloader can't load real Cifar100 dataset, cause of mismatch with dataset's shape
- Before : We Assume that Cifar100 dataset's shape ```<100 label><3072 pixel>``` per one image
- After : Actual Cifar100 dataset's shape ```<coarse 1 label><fine 1 label><3072 pixel>``` per one image
cause mismatch with dataset's shape Resnet real dataset example raise error.
After merge this pr we can run and test resnet with real dataset
_Build test: [x]Passed [ ]Failed [ ]Skipped

[Cifar100] Fix Cifar100 Dataloader @open sesame 08/28 20:44

---

test/jni/Android.mk
test/unittest/meson.build
test/unittest/unittest_nntrainer_tensor_pool_fp16.cpp

TensorPool tests are added to verify TensorPool requests and the following operations from both FP16 and FP32 tensors.

[TEST] Add fp16 tensor pool test

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp
nntrainer/compiler/tflite_opnode.h
test/unittest/compiler/unittest_interpreter.cpp

**Add Unit Test case For Test Fused Op in Tensorflow lite export** 
Test Model consist like below
```Input -> Conv2D -> Batch Norm -> ReLU -> Flatten```
- make this model with nntrainer and export to tensorflow lite
- set input {1,3,4,4} Dim -> in Tensorflow lite native make same input with 3,4,4 and transpose this input
**latency**
(nntrainer exported has transpose layer)
10000 forward tflite native (sec)              : **0.0069193975830078125**
10000 forward nntrainter exported (sec) : **0.0070416927337646484**
**Related PR**
#2184 #2185 #2186

[Wait for #2186][TFLite Export] Add Unit Test

---

Applications/Resnet/jni/main.cpp
nntrainer/utils/node_exporter.cpp

Now, an Error occurs when export resnet to tflite format
Previously, the prop of the layer was changed in the process of comparing the values with the Pytorch. But, Tflite only supports ```same``` and ```valid``` padding, but the current application use value as 1,1.
To correct this, a macro was added, and a more detailed error message was added to the tflite exporter.

[tflite_export] add Error Message, Fix Application @open sesame 10/05 15:54

---

Applications/YOLOv3/jni/yolo_v3_loss.cpp

You cannot use a template function for std::function without specifying the template type name.
The usage should be updated from
```
similarity.apply_i<float>(nntrainer::absFloat)
```
to
```
similarity.apply_i<float>(nntrainer::absFloat<float>)
```
CC: @baek2sm This is caused by #2229. I'm not sure how it passed the CI system.
This fixes:
```
[  462s] [358/446] Compiling C++ object Applications/YOLOv3/jni/nntrainer_yolov3.p/yolo_v3_loss.cpp.o
[  462s] FAILED: Applications/YOLOv3/jni/nntrainer_yolov3.p/yolo_v3_loss.cpp.o
[  462s] c++ -IApplications/YOLOv3/jni/nntrainer_yolov3.p -IApplications/YOLOv3/jni -I../Applications/YOLOv3/jni -I../Applications/utils/jni/includes -Inntrainer -I../nntrainer -Iapi -I../api -I../api/ccapi/include -Inntrainer/compiler -I../nntrainer/compiler …
```

App/Yolo5: compiler error fix!

---

nntrainer/tensor/blas_neon.cpp

- Optimize sgemv transpose with partial summation
* 50% faster sgemv_transpose in case of large scale Tensors
* Support every column length (bugFix)
- Optimize sgemv noTrans with more variables
* 20% faster sgemv in case of large scale Tensors

[neon] Optimize sgemv 2.0

---

nntrainer/tensor/blas_neon.cpp

- Since we are relying on float16, using large batch for float16 computation might hinder accuracy when it comes to small-sized Tensors.
- Through unittest, I discovered there is a huge round-off error when performing non-4-divisible column-ed Tensor sgemv with batch size of 16, while batch size 8 is almost identical to batch size 1. Thus, I temporally blocked batch size 16 computation when column is not divisible with 4.
- Arbitrary classification implemented grounded on unittest, but optimal row length classification is needed.

[neon/bugFix] Classify which sgemv optimizatized code block to use by col length

---

Applications/LLaMA/jni/main.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/conv2d_layer.cpp
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/tensor/tensor_wrap_specs.h

In This PR includes,
. enable packed (bool) property for layer node. It is only for the
weight. If it is false, it follows the global activation datatype; if it is true, 
it will follow the global weight datatype.
. add output axis in Weight Spec and set the private variable in weight.
it is to find the right direction for multiplying scales and zero-point

[Wait for #2342] [ Weight ] Add packed property and output axis in weight spec 

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This patch adds functionality to read quantized tensors from a binary file. Details are as follows.
- Read the tensor in the following order (axis, scale factors, zero points, and values).
- `Tensor::read` takes an extra argument of datatype to identify the datatype of scale factors and read exact bytes.
- Fix QINT4 tensor print segfault issue.

[Tensor] Read quantized tensor from a binary file

---

nntrainer/layers/fc_layer.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

- Perform dequantization by utilizing tensor operations instead of manual calculation.
- Tensor now contains two types of scale factors (FP32, FP16).
- Add flate function that copies tensor values of different data types. This function is temporal and should be later replaced by scopy to fasten up.
- Convert unsigned QINT to signed QINT to minimize computation (i.e., remove subtract)
- Current scopy for the quantized tensor only supports QINT4 to FP16. It needs to support QINT8-FP16, QINT4-FP32, QINT8-FP32

[#Wait for #2312][Tensor] Optimize dequantize operation    

---

nntrainer/tensor/tensor.cpp

- std::erf function does not support _Float16
- Fix by casting temporally
Resolves:
error: call of overloaded ‘erf(_Float16&)’ is ambiguous
3394 |     auto f = [](_FP16 in) { return std::erf(in); };
|                                    ~~~~~~~~^~~~

[bugfix] Fix applying erf function

---

test/unittest/memory/unittest_cache_pool.cpp

- create & destroy test case for cache pool does not do anything so removed it.

[unittest] remove empty test case

---

nntrainer/compiler/tflite_interpreter.cpp
nntrainer/compiler/tflite_opnode.cpp

**For Now, We have problem that NNTrainer <-> Exported TFLite has difference Output and Inference Result
this PR Will solve that issues**
<details><summary>[TFLite] Revisit tflite_opnode.cpp</summary><br/>
For Fix TF Lite export method
- remove unnecessary transpose due to tflite_interpreter logic change
- change transpose direction according to equation change
- Change tflite_opnode.cpp
Resolves:
- TFLite Export ( BatchNormalization Fusing, Activation Fusing)
</details>
<details><summary>[TFLite] Revisit TF Lite Fusing Operation</summary><br/>
TF Lite export feature has issue that …

[TFLite] Fix TFLite export Batchnorm & Activation Fusing Op

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/tensor.cpp

- scopy_int4_to_fp32
- scopy_int8_to_fp32
- scopy_int8_to_fp16
- scopy_int8_or_int4 : Since we use uint8_t for int4 Tensors, codes can be shared here
- vcvt_fp32_u32_bitwise : Faster optimization can be done with bitwise operation rather than elementwise operation

[neon] Support scopy for multiple dataTypes in neon

---

nntrainer/tensor/tensor.cpp

- Previously, wrong getData function was called when saving fp16 Tensor
- Apply proper template parameter: _FP16
Resolves:
```
...
23/41 unittest_nntrainer_tensor_fp16          FAIL     2.26 s (exit status 1)
...
[  FAILED  ] nntrainer_Tensor.save_read_01_p
...
```

[bugfix] Fix Tensor save function when float16

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor_fp16.cpp

This PR resolves ndk-build issue in the tensor fp16 unit test.
- Move implementation to header file to avoid linker error
- Change ambiguous variable and function names
This fixes:
```
[arm64-v8a] Executable     : unittest_nntrainer_tensor_fp16
ld: error: undefined symbol: nntrainer::Tensor::setScaleFactors16(std::__ndk1::vector<_Float16, std::__ndk1::allocator<_Float16>)
>>> referenced by unittest_nntrainer_tensor_fp16.cpp:5805 (../unittest/unittest_nntrainer_tensor_fp16.cpp:5805)
```

[bugfix] Android ndk-build error fix

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h

- There was a missing implementation of user interface of fp32<->fp16 copy neon function.
- Add blas interface to use such neon funcions

[blas/neon] Add copy function for fp32 and fp16

---

test/tizen_capi/unittest_tizen_capi.cpp

This PR resolves the failing getWeight_01 test case in the unittest_tizen_capi.
In the [ML API](https://github.com/nnstreamer/api/blob/main/c/include/ml-api-common.h#L100) common data structure, the maximum rank in Tizen APIs has changed from 4 to 16 since Tizen 8.0.
However, the NNTrainer getWeight test uses a dimension with a MAXDIM of 4.
This causes an issue of `ml_tensors_info_get_tensor_dimension` overwriting irrelevant memory since it expects an array length of 16 while passing an array length of 4.
- Switch the order of defining variables to avoid memory overwrites.
This fixes:
```
[ RUN      ] nntrainer_capi_nnmodel.getWeight_01
../test/tizen_capi/unittest_tizen_capi.cpp:960: Failure
Expected equality of these values:
dim[idx][i]
Which is: 1 …
```

[bugfix] memory overwrite error fix in `unittest_tizen_capi`

---

api/ccapi/include/tensor_dim.h
nntrainer/tensor/tensor_dim.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

- Previously, there were lack of default constructors for 1-batch, 1-channel, 1-height, 1-width with currently added TensorType option (regardless of format).
- Since there are a lot of codes using such case in FP32 implementation, I had no choice but have to explicitly feed the tensor_type (which contains the fp16 info) to the previously defined tensor.
- For clean code, I would like to propose a new default constructor for better construction of TensorDim instance.

[TensorDim] Fix TensorDim constructor

---

README.md
docs/how-to-create-model.md

I have added a tutorial document on how users can build their own models using NNTrainer.
The current tutorial is just the most basic draft, and it needs updating.
It seems that the API needs to be updated to use easily,
as setting up the data by the user is very inconvenient for now.
(So in this example, it uses random data generator.
so.. user couldn't learn how to train using a real data.)
I also added this tutorial link to the README on the first page,
and since the list of maintainers and contributors currently occupies too much space,
I moved this part to the bottom of the README.

[docs] add "how-to-create-model" tutorial document

---

debian/nntrainer-dev.install
nntrainer/utils/fp16.h
nntrainer/utils/meson.build
packaging/nntrainer.spec

This PR includes utility functions for conversion to/from 16-bit floating point number, in bit representation, from/to 32-bit floating point number in IEEE format.

[Utils] Conversion to/from half-precision floating point

---

test/unittest/layers/unittest_layers_multi_head_attention.cpp

- We were using `inference_only_option` for multi_head_attention fp16 unittest since we do not have loss scaling implementation yet.
- However, I discovered that there was a missing declaration of such option which might make malfunction when build, and added accordingly.

[trivial/bugfix] Add `inference_only_option` in multi_head_attention

---

debian/nntrainer-dev.install
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/meson.build
packaging/nntrainer.spec

This PR includes creating the FloatTensor class which separates 32-bit floating point calculation from `nntrainer::Tensor`.
- Create a FloatTensor class that only handles 32-bit floating point calculation.
- Remove operations for Quantized Tensor.
Note that FloatTensor class is one of the steps in tensor refactoring, and the implementation of internal operation functions can vary depending on the situation. In addition, all operations have been verified with modification of `unittest_nntrainer_tensor`.

[Tensor] FloatTensor class for 32-bit floating point

---

nntrainer/tensor/blas_neon.cpp

- There was a wrong implementation of `ewva` function. It should be added, not multiplied.
- I was implementing more options for SIMD BLAS operations, but it is being postponed for merging due to current Tensor refactorization. However as far as I am concerned, for this particular bug, it might be fatal in imbalanced-Tensor or exceptional cases, so made an immediate PR before a whole new PR for refactorization of BLAS library in NNTrainer.

[neon/bugfix] Fix ewva function

---

nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

Update node_exporter.cpp and node_exporter.h
The issue was that new properties were added to the layer node, causing existing TFLite export code to fail recognizing the layer_node.
This problem was resolved by adding these properties to the node_exporter.
added props
-  props::Packed
-  props::Print
- modified:   nntrainer/utils/node_exporter.cpp
- modified:   nntrainer/utils/node_exporter.h
Resolves:
- tflite export error 
- #2371 

[Exporter] Update node_exporter

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h
test/include/nntrainer_test_util.h
test/nntrainer_test_util.cpp
test/unittest/unittest_nntrainer_tensor_v2.cpp
test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp

This PR enables additional functionality for TensorV2, such as setting/getting various data, operator overloading, etc.
- Extends current TensorV2 member functions.
- Implement TensorV2 class operator overloading.
- Add unit test for newly added features.

[Tensor] Add non-operation member functions of TensorV2

---

debian/nntrainer-dev.install
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h
packaging/nntrainer.spec

In this PR, the TensorV2 structure is refactored instead of following a Type erasure pattern.
- TensorV2 is a target, expected for a user to use, that contains a TensorBase pointer.
- TensorBase is an abstract class that provides default infrastructure code.
- FloatTensor class inherits the TensorBase class and overrides the pure virtual methods with 32-bit floating point calculation.
- HalfTensor class inherits the TensorBase class and overrides the pure virtual methods with 16-bit floating point calculation.
**Note**
This is a skeleton to build the structure with no implementation.

[Tensor] Refactored TensorV2 class

---

test/unittest/compiler/meson.build
test/unittest/compiler/unittest_interpreter.cpp

**Fix unittest_interpreter**
The unit test interpreter had been previously disabled due to build errors.
However, the TensorFlow Lite (TFLite) related unit tests were separated and dependencies were removed, reflecting changes made in the neural network trainer.
- modified:   ../test/unittest/compiler/meson.build
- modified:   ../test/unittest/compiler/unittest_interpreter.cpp
**Resolves:** 
- #2375 

[Wait for #2375][Unit Test] Fix unittest_interpreter

---

nntrainer/utils/fp16.cpp
nntrainer/utils/fp16.h
nntrainer/utils/meson.build

This PR fixes multiple definition errors when using FP32/16 conversion functions in `fp16.h`.
- Function definition is moved to fp16.cpp.

[Util] Fix error in using `fp16.h` functions

---

api/ccapi/include/tensor_api.h
api/ccapi/meson.build
api/ccapi/src/tensor_api.cpp
debian/ccapi-ml-training-dev.install
packaging/nntrainer.spec
test/ccapi/meson.build
test/ccapi/unittest_ccapi_tensor.cpp

In this PR,
. Add skeleton Tensor Class in cpp api which inherite the
nntrainer::var_grad.
. include setter and getter of source layer which create this
tensor.
. Add unittest case
Resolves:

[ API ] Add Tensor CPP API for Auto Grad

---

nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR fixes the issue of SrcSharedTensorV2 containing TensorV2 which creates cyclic dependency.
(SrcSharedTensorV2 -> TensorV2 -> TensorBase -> SrcSharedTensorV2)
- SrcSharedTensorV2 owns TensorBase instead of TensorV2.
- Rename SrcSharedTensorV2 as SrcSharedTensorBase accordingly.
- Add functions to create and get shared data tensor.

[Tensor] Resolve SrcSharedTensorV2 cyclic dependency

---

nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

- Fixes : TensorV2 may not initialize itensor
- Fixes : After dynamic memory allocation of itensor, there is no destructor

[ Ahub ] Fix svace issue

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp

In this PR, the float/half tensor can be allocated based on the source tensor.

[Tensor] Support source tensor allocation

---

debian/nntrainer-dev.install
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h
packaging/nntrainer.spec

In this PR, multiple constructors are supported in the original Tensor class.
- TensorV2 constructors decide which Tensor to create.
- TensorBase constructors handle initialization that is shared.
- Float/HalfTensor constructors manage their own unique initialization.

[Tensor] Enable additional constructors

---

api/ccapi/include/tensor_dim.h
nntrainer/tensor/tensor_dim.cpp

This PR defines the Tensor storage order in the TensorDim class to support Row-major and Column-major order.
- Add enum class StorageOrder to define storage order

[TensorDim] Add column-major storage order

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR includes the implementation of comparison operators for TensorV2-related classes.
- TensorBase comparison operator compares Tensor information such as TensorDim.
- Float/HalfTensor comparison operator checks Tensor data.
- Destructor implementation is removed and set to default due to the rule of five.

[Tensor] Comparison operator overloading

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h

This PR enables a summation of tensor elements by axis in column-major order.
- Use sgemv in sum() with CblasColMajor when the tensor is column-major.

[Tensor] Sum by axis in column-major order

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR enables additional weight initializers with a probability distribution.
- Functions to set tensor with random distribution are implemented.
- Tensor now supports various initializers besides zero and one.

[Tensor] Support additional weight initialization @open sesame 1/5 11:58

---

nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor.cpp

A tensor containing a NaN value cannot be equal to any other tensors since NaNs are never equal. Therefore, comparison operator logic changed in handling NaN values.
- Comparison operator returns false if tensor has a NaN value.

[Tensor] Fix comparison operator

---

debian/nntrainer-dev.install
nntrainer/layers/multi_head_attention_layer.h
nntrainer/utils/meson.build
nntrainer/utils/util_simd.cpp
nntrainer/utils/util_simd.h
nntrainer/utils/util_simd_neon.cpp
nntrainer/utils/util_simd_neon.h
packaging/nntrainer.spec

[ util ] Add util_simd file
- Here I would like to introduce util_simd. I had no choice but to differentiate this file with blas for following reasons:
1. This is actually not 'Basic Linear Algebra Subprogram' indeed
2. This code is only used in very specific occasion.
[ layer ] Apply neon simd acceleration in rotary embedding computation
- Previous rotary embedding computation code was naively implemented with for-loop
- Using simd code, I expect this code to behave efficiently in time cost perspective, without precision loss
- Current implementation only supports Neon simd (ARMv8)

[ layer ] SIMD function for Rotary embedding incremental forwarding

---

nntrainer/layers/multi_head_attention_layer.cpp

1. Fix re-definitions of macros
2. Determine mask num in runtime, not in compile-time. You do not know whether users want fp16 or not at compile-time.
Fixes #2407
CC: @lhs8928

fix: multi-head-attention incorrect macro usage. @open sesame 1/16 17:11

---

nntrainer/utils/util_simd.h

_FP16 is the macro to unify different fp16 typenames across different architectures or libraries.
Note that util_simd.cpp has the correct name (_FP16) while the header has the incorrect naming (__fp16).
Although this does not break the build or execution, this is not good for readability and dependency clean-ups.
CC: @skykongkong8

util_simd: make typename consistent (__fp16 --> _FP16)

---

test/unittest/meson.build
test/unittest/unittest_nntrainer_tensor_v2.cpp
test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp

This PR enables unit testing for the TensorV2 class by adding a suite of tests that cover public methods.
More tests will be added in a future PR to further validate the TensorV2 class.
- Edit meson build file to include tensor v2 unit tests
- Fix public methods usage due to changed function use.

[Test] Enabled unit testing for TensorV2 class

---

meson.build

The previous meson logic force enabled ml-api if it is not disabled and common headers are found.
The new logic disables ml-api even if common headers are found if ml-inference is not found.
This allows to build nntrainer in a system only common ml headers are available without any meson options.

meson: do not force enable ml-api when it's not force enabled.

---

docs/how-to-create-model.md

[DOCS] add instructions to create `meson.build` in `how-to-create-model.md`
* This PR adds a missing part in `docs/how-to-create-model.md`.
* It includes some explanations to write `meson.build` file of a new application (under `Applications/MyApp/jni/` so as to build it.

[DOCS] add instructions to create meson.build in how-to-create-model.md

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR enables deep copy functionalities of a contiguous tensor with the following functions. `copy()`, `copyData()`, and `copy_with_strides()`.
The copy function completely copies the target tensor values regardless of the dimension of the input tensor. All elements and properties of the original tensor are copied to the new tensor. Therefore, if the copy function is used, a new tensor with the same size and shape as the original tensor is created.
On the other hand, the copyData function must match the size of the input and target tensors. This function only copies the data of the original tenor, so if the size or shape of the tensor is different, the copy may not be done properly.
Note that `copy` and `copyData` functions support copy data from multiple tensor data types while the …

[TensorV2] Enable copying data from Tensor

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp

This PR fixes a bug where a segmentation fault occurs when the output tensor is empty.
The fix initializes the output tensor when empty to avoid this error.

[bugfix] Resolve segfault in tensor apply

---

.github/workflows/ubuntu_clean_meson_build.yml

Add Clean meson build .yml file for ci
- This file was taken from nnstreamer's git action and modified to fit nntrainer.
- ref : https://github.com/nnstreamer/nntrainer/blob/main/docs/getting-started.md
- .github/workflows/ubuntu_clean_meson_build.yml
Resolves:
- Add gitaction ci

[CI] Add Clean meson build for gitaction ci

---

.github/workflows/cpp_linter.yml

This patch adds a Github Action workflow to check cpp file format
- this file imported from deviceMLOps.MLAgent
- this file use cpp_linter marketplace actions

[CI] Add cpp file format checker

---

nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request introduces a basic structure of tensor multiplication operations that support different strided inputs and outputs.

[TensorV2] `multiply_strided()` skeleton

---

nntrainer/tensor/tensor_v2.cpp

This PR fixes the Coverity issue, indicating no effect code
- Remove negative check (unsigned int is always non-negative).

[coverity] Remove no effect code

---

nntrainer/tensor/blas_neon.cpp

With stricter compilers, fp16 codes are not compilable.
To enable testing in non-android, fix type mismatches.
@s-debadri Note that there have been critical errors that Android compilers have ignored:
```C
for (; idx < (size - idx) >= 8; idx += 8) {
```
``` a < b >= c``` is not interpreted by C/C++ compilers as intended.
It is going to be interpreted as: ```( a < b ) ? ( 1 >= c ) : ( 0 >= c )```, not ``` (a < b) && (b >= c) ``` 
The compiler must have complained about this error/warning. Please DO NOT ignore or suppress them. Correct the code if there are warnings, please.
And ```float Y32[rows];``` (rows is a variable) is not in C/C++ syntax.

blas_neon: fix compiler errors in aarch64/Linux

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_v2.cpp

This PR adds support for performing the multiplication operation on two tensors.
- TensorV2 includes member functions to perform tensor multiplication.
- FloatTensor and HalfTensor take TensorV2 as input/output to perform multiplication.

[TensorV2] Multiplication support

---

.github/workflows/check_count.yml
.github/workflows/labeler.yml

In order to improve the convenience and robustness of GitAction, make the following modifications:
1. In accordance with the guidelines to upgrade from Node 16 to Node 20, change gitaction-script version to v7
- ref : https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
2. If the check_count fails, alter it so that no additional actions are executed and the process terminates immediately.
3. adopt more descriptive and clear names for better understanding.
renamed:    .github/workflows/Upload.yml -> .github/workflows/check_count.yml
modified:   .github/workflows/labeler.yml

[CI] Rename laber & upgrade node version & add workflow fail process

---

nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/models/neuralnet.cpp

This PR resolves the coverity issues that were identified.
- Specify the return type of the lambda function
- Use reference to not copy the object.
This fixes:
- Use of auto that causes a copy (AUTO_CAUSES_COPY)

[coverity] Fix coverity issues

---

nntrainer/tensor/manager.cpp
nntrainer/tensor/optimized_v2_planner.cpp
nntrainer/tensor/task_executor.cpp

- Fix non-const variables to const variables since their value is never changed in actual practice
- Use reference to avoid object copy
- Delete redundant variable
Resolves:
```
non-const type variable, but its value is never changed.
auto_causes_copy
```

[ Bug ] Fix coverity issues

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/utils/util_simd_neon.cpp
test/unittest/unittest_nntrainer_tensor.cpp

[ Trivial ] Refactor trigonometric functions
- In case of non-contiguous Tensor, it is impossible to apply SIMD instructions. Add expection accordingly.
- Rename the function name for intuitiveness :
-  sin_transform-> sin
- cos_transform -> cos
[ Trivial ] Add exception in inv_sqrt_i function
- In case of non-contiguous Tensor, it is impossible to apply SIMD instructions. Add expection accordingly.
[ Tensor ] Support non-contiguous case in sin, cos, inv_sqrt_i
- If it is not for BLAS, we can also support sin, cos, inv_sqrt_i functions for non-contiguous case as well.
- Fix related functions and add unittest accordingly.
Resolves: non-contiguous Tensor case of function usage raised from #2402 and #2410 
2. Run test: …

[ Trivial ] Refactor trigonometric functions & inv_sqrt_i

---

packaging/nntrainer.spec

NNTrainer FP16 implementation relies on NEON, which requires armv8.2-a ISA.
Tizen aarch64 is on armv8.0-a; thus it cannot support fp16-neon. Thus, disable fp16 in armv7l and aarch64.
Tizen x86/x64 does not support fp16, too.
This re-enabled Tizen build of nntrainer.
Please do not break the build in main branch!

dist/Tizen: disable fp16 in Tizen

---

meson.build
nntrainer/tensor/blas_neon.cpp
nntrainer/utils/meson.build

1. unsigned / signed int type mismatch in blas_neon.cpp
2. build condition cleanup (meson.build)
3. explicitly disable fp16 in armv7l/Tizen. (not because of HW support, but because of the library usage of nntrainer)

Clean up fp16 related build scripts and conditions

---

nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR proposes refactoring the TensorV2 class to use a shared_ptr instead of a raw pointer for managing its TensorBase object. By adopting this change, we can improve the safety and reliability of our code and reduce the likelihood of memory leaks and other issues related to manual memory management.
- Replace the TensorBase pointer in the Tensor class with a shared_ptr.
- Update any relevant code to use the shared_ptr instead of the raw pointer.

[TensorV2] Refactoring TensorBase pointer to shared_ptr

---

.github/workflows/cpp_linter.yml

update cpp-linter action's option
- extensions : cc only -> defualt option
below is cpp-linter's defualt Option & Description
```
extensions
Description: The file extensions to run the action against. This is a comma-separated string.
Default: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
```

[CI] Update cpp-linter's option - extensions

---

api/ccapi/include/common.h
api/ccapi/src/factory.cpp
jni/Android.mk.in
jni/meson.build
meson.build

An API has been added to check the version of nntrainer through the project version of meson build.
Available via ml::train::getVersion.
issue : #2435

[API] Add getVersion function

---

nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp

This PR resolves a bug that occurred after #2428 in the TensorV2 class when getting a shared data tensor, which shares memory.
** Self-evaluation**

[bugfix] Fix the creation of SharedDataTensor

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

<details><summary>  [TensorV2] Multiply strided inputs and output </summary><br />
This patch adds the implementation of multiplication operation that supports different strided inputs and output.
Signed-off-by:Donghyeon Jeong <dhyeon.jeong@samsung.com>
</details>
<details><summary>  [TensorV2] Additional functionality to access tensor elements </summary><br />
This commit adds functionality to retrieving and modifying tensor elements in specific locations.
This will provide convenience in implementing the math operation of tensor.
Signed-off-by: Donghyeon Jeong …

[TensorV2] Multiply strided inputs and output

---

nntrainer/tensor/tensor.cpp

- std::sqrt does not support fp16, so need to be casted
- Have to re-cast to fp16 when using apply function with _Float16 ( not __fp16 )

[ bug ] Use fp16 when applying sqrt_i

---

nntrainer/tensor/blas_interface.cpp

This pull request aims to optimize the performance of `GEMV` and `GEMM` operations when the data type is float16. 
This is achieved by converting the half-precision data to single-precision and utilizing the cblas functions instead of manually computing them using for loops. 
This change should improve the overall efficiency of these operations without requiring ARM NEON support. 
| TensorDim | Time | CPU | Iterations |
| --- | --- | --- | --- |
| (1, 1, 1, 512) $\times$ (1, 1, 512, 512) | 1.32ms | 1.32 ms | 452 |
| (1, 1, 1, 1024) $\times$ (1, 1, 1024, 1024) | 5.37ms | 5.37ms | 130|
| (1, 1, 1, 2048) $\times$ (1, 1, 2048, 2048) | 22.4ms | 22.4ms | 31|
| (1, 1, 1, 768) $\times$ (1, 1, 768, 96000) |  407ms | 407ms | 2 |
| TensorDim | Time | CPU | Iterations |
| --- | --- | --- | --- |
| …

[blas] Optimize gemv and gemm for float16 data type

---

.github/workflows/cpp_linter.yml
nntrainer/dataset/func_data_producer.h

For now we use cpp-linter as option 'file-annotations' but there is too many annotations and that make hard to read code
So make false file-annotations & replace that to **step-summary**
- fix typo for check cpp-linter exec
ref : https://github.com/marketplace/actions/c-c-linter
- modified:   .github/workflows/cpp_linter.yml
- modified:   nntrainer/dataset/func_data_producer.h
Resolves:
- #2463

[CI] Update cpp-linter ci (false file-annotations)

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor_v2.cpp

This PR adds support for performing the addition operation on two tensors.
- TensorV2 includes member functions to perform tensor addition.
- FloatTensor and HalfTensor take TensorV2 as input/output to perform addition.

[TensorV2] Addition support 

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/utils/util_simd.cpp
nntrainer/utils/util_simd_neon.cpp
nntrainer/utils/util_simd_neon.h

- Every neon function resides in nntrainer::neon namespace, no need to be differentiated
- 's' in BLAS functions indicates the function works with single-precision (fp32). Incase of half-precision functions we should use 'h' instead of 's'
- In case of previous functions like : 'scopy_fp32_to_fp16', the function name itself shows the dataType it gets, so no need to add neither 's' nor 'h'
- There are more rooms for this, but still WIP ( e.g. `blas_interface.h` )

[ rename/neon ] Fix neon-related functions name

---

test/unittest/unittest_nntrainer_tensor_v2.cpp
test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp

This PR includes unit tests for verifying `multiply_strided()` in the TensorV2 class.
Note that all unit tests are the same as tests in unittest_nntrainer_tensor.cpp file.

[Test] strided tensor multiplication unit test

---

meson.build
meson_options.txt
nntrainer/tensor/meson.build
nntrainer/utils/meson.build
tools/package_android.sh

- Use unsigend int iterator to avoid compiler warnings
- Keeping in mind that NEON is properly supported on later version than ARMv8.2, modify sources to include.

[ fp16 ] Fix to avoid build error / compiler warnings

---

.github/workflows/labeler.yml

Currently, we have a git action that automatically labels as "Need Review" when the number of reviews is insufficient, and removes it when necessary. This automation allows developers to know which pull requests need review.
In addition, we want to automate the process of labeling pull requests that require merging, to make it more convenient for developers.
Resolves:
- #2463 

[CI] Update labeler : Add READY2MERGE label

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR adds the ability to compute the dot product between two tensors.
- Added a new method `dot()` to the `TensorV2` class that computes the dot product between two tensors.

[TensorV2] Add dot product support

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor_v2.cpp

This PR adds support for performing the subtraction operation on two tensors.
**Changes proposed**
- TensorV2 includes member functions to perform tensor subtraction.
- FloatTensor and HalfTensor take TensorV2 as input/output to perform subtraction.

[TensorV2] Subtraction support @open sesame 02/20 11:30

---

meson.build
meson_options.txt
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/blas_neon_setting.h
test/include/nntrainer_test_util.h
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp
tools/package_android.sh

- In special occasion, we can enjoy computational profit with multithreading
- Settings in multithreading might differ.

[ neon ] Apply openMP in HGEMM, HGEMV in neon for multithreading

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor.cpp

Implemented elementwise vector operations
* ele_add (previously `ewva`)
* ele_sub
* ele_mul (previously `ewvm`)
* ele_div
with fp32 / fp16 precisions
for current BLAS, implement with raw version
for NEON SIMD, implement with SIMD version

[ BLAS ] Implement elementwise operations

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds the ability to transpose tensors, which allows users to flip or rotate their data along its axes.
- Added a new method called transpose() to the TensorV2 class, which takes direction argument: the axes to be swapped.

[TensorV2] Add Transpose Support for Tensor

---

nntrainer/tensor/meson.build
nntrainer/utils/meson.build
packaging/nntrainer.spec

It supports enable_neon only when aarch64 architecture.
And, neon option can be selectable for aarch64.

[SPEC] support neon enable option

---

meson.build
meson_options.txt
nntrainer/tensor/blas_avx.cpp
nntrainer/tensor/blas_avx.h
nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/meson.build

This pull request adds VCVT (between floating-point and integer) AVX support for the x86 architecture. 
This feature allows efficient conversion between single-precision floating-point and half-precision floating-point data types using the AVX instruction set.
- Added new VCVT instructions to the blas_interface
- Fix incorrect meson.build logic in checking gcc version and AVX support
- Add enable-avx option to enable AVX hardware acceleration

[AVX] Added VCVT (between floating-point and integer) AVX support for x86 architecture

---

jni/Android.mk.in
jni/meson.build

It fixes Android conf for CXX flags.
It uses the same flags as c initially.

[Android] Fix for cxxflags

---

test/unittest/unittest_nntrainer_tensor_v2.cpp

This PR resolves the coverity issue of resource leak.
- Switch the order of assert to check if the output is a nullptr to ensure releasing acquired resources (e.g., outdata_beta)
**This fixes:**
- leaked_storage: Variables going out of scope leak the storage it points to

[Coverity] Fix the coverity issue

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This PR adds new functionalities for getting masks of the following techniques: dropout, filter, and zoneout. These functions enable working with masks, making it easier to perform such techniques in regularization.
- Added `dropout_mask()`, which calculates the dropout mask by multiplying tensor elements by 1.0 / (1.0 - dropout rate), in place.
- Added `filter_mask()`, which takes an input tensor and applies a filter mask based on the given mask length and invert option.
- Added `zoneout_mask()`, which generates two zoneout masks, one for in-place operation and another for opposite operation, based on the specified zoneout rate.

[TensorV2] Create a mask of dropout, filter, and zoneout @open sesame 02/26 12:23

---

Applications/utils/meson.build
Applications/utils/npy_reader/meson.build
Applications/utils/npy_reader/npy_reader.cpp
Applications/utils/npy_reader/npy_reader.h

In deep learning data feeding, there are often tasks that involve reading and processing numpy (.npy) files.
Therefore, it would be much more convenient to develop by entering the file name and returning the data in a vector instead of manually writing code to read it every time.
Function Signature
```
void read_npy_file(const char *file_path, std::vector<int> &dims,
std::vector<float> &values);
```

[util] Add numpy file reader

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request introduces a new feature that enables the summation of tensor elements by axes.
This feature allows users to sum up tensor values along specified axes, making it easier to perform complex mathematical operations involving tensors.
- Added new function sum() that takes a tensor and an axis as input and returns the sum of all elements along that axis.
- Added mergeAxis feature which merges the two axes for tensor into one.

[TensorV2] Tensor element summation by axes feature

---

nntrainer/utils/util_simd.cpp
nntrainer/utils/util_simd.h
nntrainer/utils/util_simd_neon.cpp
nntrainer/utils/util_simd_neon.h

- Current activation functions are implemented as a function template, and fully computes with the function template parameter's precision unless using NEON intrinsics with inter-fp32-values explicitly.
- According to current papers, for safe convergence of mixed precision training, it is quite critical to calculate softmax with fp32 precision.
- This PR proposes a SIMD version of softmax calculation, and uses temporally higher precision when using half-precision
- For mathematical stability, applied linear translation (using minus values for the input of exponential function) to avoid precision overflow

[ util ] Implement softmax calculation function in util

---

nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds new functions to the TensorV2 that allow users to average tensor elements along specified axes. 
The functions take in an axis or list of axes as input and return a new tensor with elements replaced by their corresponding means. If no axis is provided, it returns a tensor value by averaging the elements by all axes.

[TensorV2] Average Tensor element by axes @open sesame 03/07 10:42

---

.github/workflows/cpp_linter.yml

sync cpp-linter version with clang-format
- change cpp-linter version to 14

[Trivial/CI] sync cpp-linter version with clang-format

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds two new methods to the Tensor class: split() and cat().
The `split()` method allows users to divide a tensor into multiple smaller tensors along the specified axis.
The `cat()` method enables them to combine multiple tensors into a single larger tensor along a given axis.

[TensorV2] Add functions to split and concatenate tensors @open sesame 03/07 10:42

---

tools/package_android.sh

Added `enable-opencl` flag to `/tools/package_android.sh`.
This will compile OpenCL related changes for `libnntrainer.so`.

[build] Updated Android build script for OpenCl inclusion

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds several new utility member functions to the TensorV2 class, enabling users to perform various tasks with their tensors more easily and efficiently.
These include saving and loading tensors, updating batches, getting argmax and max absolute values, and more.
The implementation is based on the current Tensor class and aims to improve the overall usability and flexibility of the TensorV2 class.
- Added `save()` and `read()` methods to allow saving and loading of saved tensor data.
- Added `Map()` method to create a new Tensor object from a buffer.
- Added `argmax()` and `max_abs()` methods to retrieve the indices of max value by batch and the value of the maximum absolute element in a tensor.
- Added `updateBatch()` to update tensor …

[TensorV2] Add utility member functions to TensorV2 class @open sesame 03/07 10:42

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_v2.cpp
nntrainer/tensor/tensor_v2.h

This pull request adds two new feature scaling functions - standardization and normalization - to the Tensor class.
These functions help users preprocess input data before feeding it into models, improving model performance and accuracy. 
* Added `normalization()` function to rescale values to a range between 0 and 1
* Added `standardization()` function to center data around the mean and scales to a standard deviation of 1

[TensorV2] Feature Scaling Functions @open sesame 03/14 11:49

---

nntrainer/layers/layer_normalization_layer.cpp
nntrainer/layers/loss/cross_entropy_softmax_loss_layer.cpp
nntrainer/layers/lstm.cpp
nntrainer/layers/lstmcell.cpp
nntrainer/layers/lstmcell_core.cpp
nntrainer/layers/multi_head_attention_layer.cpp

In several layers, there are attempts to change the data type of a Tensor object after initializing it.
This is currently possible but can cause issues down the line (e.g., treat FloatTensor object as HalfTensor).
As such, the setDataType() method will be removed and considered not to be used in future updates.
Instead, users will need to provide the desired data type when creating a new tensor. 

[Layer] Remove Tensor setDataType() usage

---

.github/workflows/ubuntu_clean_meson_build.yml

Node 16 has reached end of life. So, github recommend transition to actions which use node 20+. [Ref](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

Bump actions/checkout in Ubuntu Meson build & test

---

test/unittest/unittest_common_properties.cpp

To make code more readable, use parameterized test according to existing TODO comment.

Use parameterized test in `NamePropertyTest`

---

.github/workflows/pylint.yml
.github/workflows/ubuntu_clean_meson_build.yml

- `actions/setup-python@v1` is deprecated. So, bump version to v5.
- Step name says it uses python3.9, but it actually installs 3.10. Match name and what it actually doing.

Fix minor error in github action

---

test/unittest/layers/layers_golden_tests.cpp

Fix Coverity issue on
- /test/unittest/layers/layers_golden_tests.cpp
- /test/unittest/models/unittest_models_recurrent.cpp
- /test/unittest/unittest_nntrainer_models.cpp
Resolves:
```
Use of auto that causes a copy (AUTO_CAUSES_COPY)
auto_causes_copy: This lambda has an unspecified return type
copy: This return statement creates a copy.
```

[ coverity ] Fix Coverity issue

---

.github/workflows/cpp_linter.yml

We currently perform a Clang format check during our static checks.
The CPP-Linter we are using is from the Action Market and occasionally produces different results even when the same version is specified. This reduces efficiency for developers, so only the static check with more detailed logs will be left and the CPP-Linter function will be disabled.
However, the existing Linter function will remain.

[Trivial] Disable cpp-linter action's clang-format

---

nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_common.h
nntrainer/tensor/hgemm/hgemm_kernel_4x4.h
nntrainer/tensor/hgemm/hgemm_kernel_8x8.h
nntrainer/tensor/hgemm/hgemm_kernel_pack.h
nntrainer/tensor/hgemm/hgemm_util.h
nntrainer/tensor/meson.build

- Previously, hgemm was implemented without taking packing / kernel into consideration.
- Here I would like to introduce kernel-based hgemm. 
It consists of:
1. packing A / B matrix for 4 / 8 divisible case
2. 4x4, 8x8 hgemm kernel for full-fp16 case.
- Note that this is just a draft PR to get review w.r.t. file structure from other reviewers

[ HGEMM ] Draft of kernel-based hgemm

---

nntrainer/layers/depthwise_conv2d_layer.h

This pull request defines a header file for depthwise convolution.
It is a draft for a new layer and welcome any feedback or assistance you may have.
This layer is necessary to support various applications such as SV.
- Depthwise convolution is a type of convolution in which each input channel is convolved with a different kernel (called a depthwise kernel).
- Unlike a regular 2D convolution, depthwise convolution does not mix information across different input channels.
- Add Depthwise Convolution 2D Layer
Resolves:
- #2520

[Layer] Create Depthwise 2D Convolution

---

nntrainer/layers/common_properties.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/fc_layer.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

(Update)
This PR contains commits to
* Add a new feature [LoRA](https://arxiv.org/abs/2106.09685) to `fc_layer`.
* Add a new property : LoraRank (PositiveIntegerProperty)
* Update forward func.
* Update calcGradient func.
* Update calcDerivative func.
* Update `node_exporter` of fully connected layer (to pass tflite test)
2024/03/06
* revise `forwarding` function
* (W + A@B)x  ➡️  Wx + (A@B)x
* `forwarding_lora` is deleted
* Test with an application: two fc-layer w/ LoRA

[LoRA] feat/ add LoRA to fc_layer @open sesame 03/07 10:42

---

test/unittest/unittest_nntrainer_appcontext.cpp

To make code more readable, use parameterized test according to existing TODO comment.
Signed-off-by: Boseong Seo <suzy13549@snu.ac.kr>

Use parameterized test in `AppContextTest`

---

nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_kernel_4x8.h
nntrainer/tensor/hgemm/hgemm_kernel_8x16.h
nntrainer/tensor/hgemm/hgemm_kernel_8x8.h
nntrainer/tensor/hgemm/hgemm_kernel_pack.h
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

This commit proposes a 8x16 kernel for Half-precision GEMM
Note that this is not an '100%' optimized version of HGEMM, but still better than before.
Following is unittest output with f16-f32 partial accumulated HGEMM.
Fine accuracy with better latency.
> **mean latency ( TC = 20 )**
| GEMM dimension | fp32 (cblas) | prev | 8x8 | 8x16 |
| --- | --- | --- | --- | --- |
| 4096 square | 2087 ms  | 7172 ms | ... | **1964 ms** |
| 2048 square | 260 ms  | 413 ms | ... | **250 ms** |
| 1024 square | 34 ms  | 52 ms | ... | **30 ms** |
| 768 square | 13 ms | 18 ms | ... | **11 ms** |
| 256X1440X256 | 2869 mcrs | 3807 mcrs | ... | **2544 mcrs** |
| 256X256X1440 | 2929 mcrs | 3950 mcrs | ... | **2467 mcrs** |
| 8X1440X8 | 5 mcrs | **5 mcrs** | ... | 10 mcrs |
| 8X8X1440 | 5 mcrs | **4 mcrs** | ... | …

[ hgemm ] hgemm noTrans with kernel 8x16

---

Applications/Custom/README.md
Applications/Custom/mae_loss.h
Applications/README.md
Applications/YOLO/jni/reorg_layer.cpp
Applications/YOLO/jni/reorg_layer.h

Remove LSTM example in Applications/README.md
- existing link to LSTM example does not work
- user can find LSTM example in Layers dir
+ LSTM dir merged to Layers dir (in #2107)
- delete LSTM example in order to reduce confusion
1. Build test:  [X]Passed [ ]Failed [ ]Skipped
2. Run test:    [X]Passed [ ]Failed [ ]Skipped
Signed-off-by: Boseong Seo <suzy13549@snu.ac.kr>

[Docs] Fix readme in Applications dir

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h

Handling existing kernels:
- Modified `clCreateKernel` to read pre-compiled kernel binaries.
- Handling already initialized kernels using global bitmask.
- Added enumerator for kernel names and a method to resolve as string.

[GPU/OpenCL] Handling pre-compiled and existing kernels

---

nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/unittest_nntrainer_activations.cpp

- Now, user can use Softplus activation function like torch or tensor flow.
- Furthermore, we can use this function to build Mish or other activation functions

Add Softplus activation function @open sesame 04/15 10:41

---

api/ccapi/include/functions.h

I added tensor & function(operation) API structure for supporting autograd.
Users can make a model graph using this api.
The operators will be supported one-to-one with ONNX.

[API] Add tensor&operations API structure for supporting autograd @open sesame 04/01 10:42

---

.github/workflows/cpp_linter.yml

It gives an error of "iostream" not found.
Install libstdc++-dev for possible compilers.

ci / remove cpp-linter's false positive reports.

---

nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_common.h
nntrainer/tensor/hgemm/hgemm_kernel_1x8.h
nntrainer/tensor/hgemm/hgemm_kernel_pack.h

Added 1x8 hgemm kernel, packing_A1, packing_B1 functions. Incorporated hgemm_noTrans_1x8.

[hgemm] hgemm noTrans with kernel 1x8

---

nntrainer/layers/common_properties.h
nntrainer/layers/fc_layer.cpp
nntrainer/layers/fc_layer.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

This PR is reopened. It is updated from [#2539](https://github.com/nnstreamer/nntrainer/pull/2539), in the way of taking `lora_alpha` as a hyper-parameter instead of getting `lora_scaling` parameter directly.
- This commit adds `lora_alpha` parameter to LoRA (fc layer)
- In the original paper,they adopted `lora_alpha (uint)` as a parameter to derive the scaling factor internally, i.e., scaling = alpha / rank
- This commit takes `lora_alpha` as a hyper-parameter and apply the scaling factor to the LoRA layer.
- This commit's updates are summarized as follows:
- `common_properties.h` : add LoraAlpha as a parameter.
- `fc_layer.cpp`: update forwarding / calcGradient / calcDerivative func to apply scaling factor in LoRA computation
- `fc_layer.h`: update to take LoraAlpha as fc_props, add …

[LoRA] add alpha parameter to LoRA (fc_layer) @open sesame 04/23 09:33

---

nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_kernel_1x4.h
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

Changes related to `hgemm` 1x4 kernel:
- Added hgemm_kernel_1x4
- Added hgemm_noTrans_1x4 calls
- Added unittest dot_gemm_50_768_516

[hgemm] hgemm noTrans with 1x4 kernel

---

Applications/LLaMA/jni/main.cpp

- This commit fixes a bug in `applyTKP` function.
- It seems applying Top-K and Top-P to `logits` didn't work as intended

[Application] Bugfix in LLaMA Application

---

debian/control
packaging/nntrainer.spec

Code clean, fix cyclic dependency between nntrainer and ml-api.
Build dependency to ml-api on nntrainer is unnecessary.

[Build] dependency to api

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

Along with #2555 I inspected through every custom-made half-precision calculation function, and `hnrm2` is the only one left that needs f16-f32 precision supplement.
**Proposed Changes**
- Previous hnrm2 was using full-fp16.
- Since this is also one of dimension-shrinking computation, should use inter-fp32 values to enhance precision.
- This has not been detected due to small dimension Tensor usage in unittest. Add higher dimension test case accordingly.
- Note that this function is responsible for `Tensor::l2norm()`, frequently used for mse loss computation.
| dim | f16 (prev) | f16f32 (now) |
| 768 | 282.233 | 0.232574 |
> mean value ( TC = 100)
> Since this is nanosec-unit result, almost trivial
| dim | f16 | f16f32 | fp32-cblas | 
| --- | --- | --- | --- |
| 768 | …

[ hnrm2 ] Use precision-enhanced hnrm2

---

api/ccapi/include/layer.h
nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h
test/unittest/unittest_nntrainer_activations.cpp

- Now, user can use SELU activation function like torch or tensor flow.
Signed-off-by: kimhan0515 <kimhan0515@gmail.com>

Add SELU activation function

---

Applications/LLaMA/jni/main.cpp

Added generate_multiple_tokens function for first generation on llm.
This function takes one logits and generates multiple output tokens.
To meet the purpose of the target application,
even if input are multiple logits,
only the first logits is used to generate multiple output tokens.

[Wait for #2536][application] add generate_multiple_tokens for llm @open sesame 04/05 16:14

---

meson.build

According to GCC document,
https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Half-Precision.html even if -mfp16-format=ieee is not given, aarch64 supports ieee fp16. Thus, for aarch64, even if the option is not available, try to built it with __fp16 type.
Then, add condition for arm: the final "else" is written for x64/x86 machines.
Need #2430 and test before merging.

meson: fix fp16 support conditions for arm/aarch64

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/tensor_wrap_specs.h
nntrainer/tensor/var_grad.cpp
nntrainer/tensor/var_grad.h
nntrainer/tensor/weight.cpp
nntrainer/tensor/weight.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h

This PR enables separate definition of variable and gradient of Weight. It's because we have to support different type considering Mixed Precision Training or Quantization.  
For example, Variable should be FP16 and Gradient should be FP16 for FP16-FP16 Mixed Precision. 
Or Variable should support BCQ3 and Gradient FP16 for BCQ3-FP16 QAT.
Therefore, we need to set update the Variable weight as it is requested.. and for Gradient, we have to set same type of Activation. 
This PR enables to set different type between Variable and Gradient.
<details><summary>[Property] Add loss scale property </summary><br />
It add loss scale property as model common property.
</details>
<details><summary>[ Weight ] Add Loss Scale factor in Weight</summary><br …

[ Loss Scale ]  Enable to define different type of Variable and Gradient for Loss Scale

---

Applications/LLaMA/PyTorch/weights_converter.py

the num_layer parameter is set to be automatically through auto config when converting weights from pytorch format to nntrainer format.

[Application] Update weights_converter

---

Applications/LLaMA/jni/main.cpp

in case of running without encoder, a problem has been fixed where invalid values are set during operation due to incorrect assignment of input data, and this causes word index related errors.

[Application] fix input data error on example of LLaMa

---

nntrainer/tensor/blas_neon.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

**hdot : vec(1 x K ) x vec(K X 1 ) -> 1 (scalar)**
- Previous hdot was using full-fp16.
- Since this is also one of dimension-shrinking computations, should use inter-fp32 values to enhance precision.
- This has not been detected due to small dimension Tensor usage in unittest. Add bigger-sized test case accordingly.
| dim | hdot-f16 (previous) | hdot-f16f32 (now) |
| 1024 | 0.250061 | 3.72529e-09 |
| 2048 | 2.07308 | 0.00362171 |
| 4096 | 11.8475 | 0.195379 |
> Since this is nanosec-unit result, almost trivial
| dim | hdot-f16 | hdot-f16f32 | cblas-f32 |
| --- | --- | --- | --- |
| 1024 | 261 ns | 280 ns | 347 ns |
| 2048 | 328 ns | 359 ns | 1473 ns |
| 4096 | 508 ns | 562 ns | 909 ns |
Conclusion : Better accuracy with almost no latency deterioration
**Self …

[ hdot ] Use precision-enhanced hdot

---

nntrainer/tensor/hgemm/hgemm.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

Changes added in this PR:
- `K%8 == 0` condition added before calling 1x4 and 1x8 kernels to enhance accuracy.
- Added `hgemm_noTrans_4x4` before `hgemm_noTrans_1x8`.
- Added test cases for `hgemm_noTrans_1x8`.
- Used bitmasks for dimension checks to reduce latency.

[hgemm/bugfix] Added conditions for 1x8 and 1x4 kernel calls to enhance accuracy @open sesame 05/09 09:04

---

Applications/YOLOv2/PyTorch/dataset.py
Applications/YOLOv2/PyTorch/main.py
Applications/YOLOv2/PyTorch/yolo_loss.py

- add cuda option to train yolo v2 model backbone (for converting to nntrainer model)
- preprocessing for input dataset
* unmatched paired dataset
* no annotation value

[Application] cuda support for example of pytorch yolo v2 @open sesame 05/10 19:54

---

nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc

- Add save_path to setProperty to save the model for each epoch.
- Remove model->save() call to avoid saving the current epoch result to the model when current epoch is interrupted

[Nnstreamer-subplugin] Add save_path to setProperty

---

nntrainer/layers/fc_layer.h

This PR resolves an issue related to the incorrect array size for `lora_idx` in the fully connected layer.
Specifically, the fix has made the array size four elements long, corresponding to `loraA`, `loraB`, `loraTmp`, and `loraOut`.

[bugfix] Fix LoRA indices array size in the FC layer

---

nntrainer/layers/fc_layer.cpp

This PR resolves the coverity issue of the constructor may not initialize class members.
- initialize lora_idx and lora_scaling in class constructor.

[coverity] fix coverity issue

---

Applications/Resnet/README.md

Edited build instructions for Resnet18 test
**Fixing the meson build option**
Resolves: Error on building the test example where it says  `-c is an un-recognized option` and in the meson documentation -C is used, so it seems to be a typo. 
1. Build test:     []Passed [ ]Failed [ X]Skipped
2. Run test:     []Passed [ ]Failed [ X]Skipped

Edited build instructions for Resnet18 test

---

nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_kernel_4x4.h
nntrainer/tensor/hgemm/hgemm_kernel_4x8.h
nntrainer/tensor/hgemm/hgemm_kernel_8x16.h
nntrainer/tensor/hgemm/hgemm_kernel_8x8.h

> Unittest output using Galaxy S23 with local commit
> mean latency with TC = 100
| dim | KERNEL_8x16_ACC16 | KERNEL_8x16_ACC8 | cblas fp32 |
| --- | --- | --- | --- |
| 1024 | **23 ms** | 30 ms | 32 ms |
| 768 | **9 ms** | 12.8 ms | 13.6 ms |
| 256x1440x256 | **2054 mcrs** | 2664 mcrs  | 2701 mcrs |
| 256x256x1440 | **2359 mcrs** | 2965 mcrs  | 3104 mcrs |
| dim | KERNEL_8x16_ACC16 | KERNEL_8x16_ACC8 |
| 1024 |  0.00608169 | 0.00226737 |
| 768 | 0.00310214 | 0.0017091 |
| 256x1440x256  | 0.0149112 | 0.00518965 |
| 256x256x1440 | 0.00119428 | 0.000306849 |
- Overall, this shows **150% boost-up** with f16-f32 w.r.t. cblas fp32
- Considering enlarged vector length from f32 to f16, and partial-accumulation, result above sounds reasonable.
- However, this code takes a …

[ hgemm ] Partial sum up to 2048 digits for more acceleration & trivial refactor @open sesame 05/10 10:47

---

api/ccapi/include/layer.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/blas_kernels.cpp
nntrainer/layers/cl_layers/blas_kernels.h
nntrainer/layers/cl_layers/fc_layer_cl.cpp
nntrainer/layers/cl_layers/fc_layer_cl.h
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/meson.build
test/jni/Android.mk
test/unittest/layers/layers_common_tests.h
test/unittest/layers/layers_golden_tests.cpp
test/unittest/layers/unittest_layers_fully_connected_cl.cpp

Added initial version of FC Layer for GPU. This is a basic implementation using naive kernels.
Changes added with this PR:
- `fc_layer_cl.cpp` added containing the new `FullyConnectedLayerCl` class for OpenCL implementation.
- Modified `registerFactory` in `cl_context` to add `FullyConnectedLayerCl`.
- Re-used `FullyConnected` API in `layer.h` for CPU/GPU execution depending on compute engine option.
- Created common BLAS OpenCL kernels for usage inside `blas_kernels` to enhance re-usability.
- Updated `LayerKernel` enum inside `layer_context.h`.
- Added `unittest_layers_fully_connected_cl.cpp` to test FC Layer on GPU.
- Added unit test for incremental forwarding in `layers_golden_tests.cpp`
> **To do**: Modify data transfer by adding `cl_buffer` with `var_grad`, optimize kernels.
**Self …

[GPU/OpenCL] Initial version of FC Layer with OpenCL ops

---

Applications/YOLOv2/PyTorch/dataset.py
Applications/YOLOv2/PyTorch/main.py
Applications/YOLOv2/PyTorch/yolo.py
Applications/YOLOv2/jni/main.cpp

update yolo v2 modeling part of yolo v2.
(update some hyper param values)
- update yolo v2 pytorch(python) script, and apply pep8 style guide
- update yolo v2 nntrainer(c++) script
**issue:**
- activation function(in this case, leaky relu) of nntrainer needs to support setting negative slope via
parameter...

[Wait for #2588][Application] update yolo v2 hyper params

---

nntrainer/opencl/opencl_context_manager.cpp
nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h

Added check for OpenCL fp16 `half` support on device.
Will show proper message if not found.
To use fp16 enable `cl_khr_fp16` as following with the kernels.
```cpp
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
__kernel void kernel_name(...) { } 
```

[GPU/OpenCL] Check fp16(half) support

---

nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
test/unittest/layers/layers_common_tests.h
test/unittest/layers/layers_dependent_common_tests.cpp
test/unittest/layers/layers_standalone_common_tests.cpp

Added unit test for layer semantics on GPU:
- `LayerSemanticsGpu` test suite added.
- Modified `layers_[standalone|dependent]_common_test.cpp` to incorporate the test cases.
Resolved a bug:
- Removed `run_context->setComputeEngine(...)` call from LayerNode since `run_context` doesn't get initialized in the beginning.
- Used `LayerNode` to store compute engine info which can be propagated as required.
> Key for new implemented layers on GPU will be different which can not be fetched from `app_context`. Hence these changes were made to fetch the keys from `cl_context` as required.

[unittest/gpu] Added LayerSemanticsGpu test suite

---

nntrainer/layers/cl_layers/blas_kernels.h
nntrainer/layers/cl_layers/blas_kernels_fp16.cpp
nntrainer/layers/cl_layers/fc_layer_cl.cpp
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
test/unittest/layers/unittest_layers_fully_connected_cl.cpp

FC Layer GPU kernels added for `fp16` operation:
- Added `blas_kernels_fp16.cpp` for BLAS `fp16` OpenCL kernels.
- Used `lda` for SGEMV computation for generalization.
- Unit tests added for FC Layer `fp16` support on GPU.

[GPU/OpenCL] Added fp16 support for FC layer on GPU

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/matrix_transpose_neon/mask_neon.h
nntrainer/tensor/matrix_transpose_neon/matrix_transpose_kernels_neon.h
nntrainer/tensor/matrix_transpose_neon/matrix_transpose_neon.cpp
nntrainer/tensor/matrix_transpose_neon/matrix_transpose_neon.h
nntrainer/tensor/matrix_transpose_neon/meson.build
nntrainer/tensor/matrix_transpose_neon/transpose_utils_neon.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor.cpp

PR for issue raised in #2582 
Matrix Transpose function in the latest NNTrainer (14.05.24) is implemented using for-loops.
Although current implementation is useful for general use in **(b,c,h,w)-Tensor** transpose, it would be a little bit naive implementation for the **(h,w)-matrix** transpose.
> TC = 20, tested on Galaxy S23, with frequently used ones
| dim | prev | neon |
| 768x768 | 400 mcrs | 121 mcrs |
| 1440x1440 | 2 ms | 0.44 ms |
| 1920x1560 | 4.3 ~ 1.6 ms | 1.8 ~ 0.8 ms |
| 1560x2048 | 4.18 ms | 0.618 ms |
| 512x2048 | 1.31 ms  | 0.18 ms  |
- Overall, **200%~ 500%** acceleration. ( Note that this method is effective for sufficiently big matrices )
- Merging this PR will instantly impact BiQGEMM calculation (`transpose("0:2:1")`)

[ tensor ] Apply SIMD in matrix transpose

---

nntrainer/tensor/blas_neon.cpp
test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp

Fixes #2593 :
- Used `uint32_t` operations to process indices larger than `65535`.
- Added unittest of shape(1,1,768,768) for `max_abs()` which calls `isamax()`.

[blas/neon] isamax improvement for larger input length

---

nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h

- Implemented quick gelu function. Please note that quickGeluPrime which is calculate derivate of quickGelu function is not yet implemented.
Signed-off-by: hyeonseok <hs89.lee@samsung.com>

[acti_func] implement quick gelu

---

nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h

- This commit allows hgemm to get beta condition as well.
- Note that beta for here is as follows:
```math
C = alpha * A * B + beta * C
```
- In many cases, beta is 0.F. However, we can fuse calculation process if we have to do something like:
```C++
Tensor A, B, C;
Tensor tmp;
bool transA = false;
bool transB = false;
float scalar = 1.1F // anything you want
// redundant case 1
tmp = A.dot(B);
C.multiply_i(scalar);
C = tmp.add(C);
// use beta
C = A.dot(B, C, transA , transB, scalar);
// redundant case 2
C = A.dot(B);
C.add_i(scalar);
// use beta
C = C.ones();
C = A.dot(B, C, transA , transB, scalar);
```
- In addition add zero-init code for beta = 0.F case. According to recent model profiling result, even for initialization, minimizing instruction is quite helpful for overall model …

[ hgemm ] Support beta case @open sesame 06/04 13:13

---

test/unittest/layers/unittest_layers_fully_connected_cl.cpp

Using newly added LayerSemanticsGpu for FC Layer GPU unit tests. Renaming fp16 unit test variable to avoid duplicate declaration when all tests are run.

[bugfix/unittest] Using LayerSemanticsGpu for FC Layer test

---

Applications/LLaMA/jni/Android.mk
Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
Applications/LLaMA/jni/custom_multi_head_attention_layer.h
Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/meson.build
nntrainer/layers/multi_head_attention_layer.h
test/unittest/layers/meson.build

- Current mha layer at nntrainer/layer is not for general use, but implemented solely for LLaMA support.
- In order to run unittest for mha layer:
1. rollback current mha layer to previous one
2. move current implemenation to Application/LLaMA
3. enable unittest

[ layer ] Enable mha gtest and match version @open sesame 06/04 13:01

---

README.md

[trivial] fix typo error

---

.github/actions/check-rebuild/action.yml
.github/actions/check-rebuild/check_if_rebuild_requires.sh
.github/workflows/android.yml

Android is the major release target of nntrainer.
Build and run test cases for Android.

action: add Android build test

---

jni/Android.mk.in
jni/meson.build
meson.build

ML_API_COMMON macro has been inconsistent for Android build, where it is force-defined 1 in Android.mk while it may become 0 or 1 depending on build system in meson.
Because android build uses meson and Android.mk simultaneously, this must become consistent.

android: consistant ML_API_COMMON macro

---

nntrainer/layers/lstmcell_core.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h

Through this PR, 2 things:
1. Cleaner code : reduce if/def code block to tensor level
2. Acceleration : Use SIMD haxpy in fp16 case. Previously it was only using naive loop

[ layer ] Lower the computational code of lstmcell_core to BLAS level

---

.github/workflows/ubuntu_clean_meson_build.yml

Closes #2560. You can now see the build results from Fp16 in a Github action.

[CI] Add fp-16 build in github action

---

Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/meson.build
Applications/PicoGPT/jni/main.cpp
Applications/PicoGPT/jni/meson.build
meson.build

Now, PICO GPT and LLAMA are adding extra_defines meson option in the application side.
However, even if this code is executed during build, this definition is not reflected when actually running the app.
Because the application area is built after the process of reflecting extra_defines to add_project_arguments has already been completed, so adding extra_defines during application build is meaningless.
In addition, it is impossible to call add_project_arguments after build, so the structure to add extra_defines during build process is wrong.
The reason why PICO GPT and LLAMA add extra_defines is that the JSON-related script created now does not run on tizen, so json-related option was added to the root meson and the options on the application side were removed.
1. …

[Application] Bug fix about meson setting @open sesame 06/10 13:02 

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h

- This commit fixes unusual memory access on cross-compiled unittest executable on Android
Resolves:
> SIGSEGV : signal segmentation violation
- lldb | signal SIGSEGV: invalid address
- SIGILL : illegal instruction

[ layer ] Bugfix for enabling unittest_models on Android

---

.github/workflows/ubuntu_clean_meson_build.yml

To de-dup scripts handling fp16-enabled and fp16-disabled cases for meson-clean build, add another matrix entry.
Reference: https://github.com/nnstreamer/nntrainer/pull/2641/files#r1646986341
CC: @heka1024

action/ubuntu: fp16 on/off handled by matrix

---

README.md

This PR contains commits to
- add recent NNTrainer paper and its citation to `README.md`
- fix trivial typo in `README.md`

[DOCS] update README.md @open sesame 06/18 13:33

---

api/ccapi/include/layer.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/addition_layer_cl.cpp
nntrainer/layers/cl_layers/addition_layer_cl.h
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/input_gen/gen_layer_tests.py
test/jni/Android.mk
test/unittest/layers/unittest_layers_addition_cl.cpp

Added initial version of Addition Layer for GPU. This is a basic implementation using naive kernel.
Changes added with this PR:
- `addition_layer_cl.cpp` added containing the new `AdditionLayerCL` class for OpenCL implementation.
- Updated `LayerKernel` enum inside `layer_context.h.`
- Added `unittest_layers_addition_cl.cpp` to test Addition Layer on GPU.
Signed-off-by: Yash Singh [yash.singh@samsung.com](mailto:s.debadri@samsung.com)

[GPU/OpenCL] Initial version of Addition Layer with OpenCL ops

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
test/input_gen/gen_layer_tests.py
test/jni/Android.mk
test/unittest/layers/unittest_layers_swiglu_cl.cpp

Added initial version of SwiGLU Layer for GPU. This is a basic implementation using naive kernel.
- `swiglu_layer_cl.cpp` added containing the new `SwigluLayerCL` class for OpenCL implementation.
- Added `unittest_layers_swiglu_cl.cpp` to test Swiglu Layer on GPU.
Signed-off-by: Niket Agarwal [niket.a@samsung.com](mailto:s.debadri@samsung.com)

[GPU/OpenCL] Initial version of SwiGLU Layer with OpenCL ops

---

test/unittest/layers/unittest_layers_addition_cl.cpp

- Found duplicated TC name while creating GPU unittest cases, and this makes unittest build to fail
CC : @yashSingh0723 
Resolves:
```
[arm64-v8a] Executable     : unittest_layers
ld: error: duplicate symbol: addition_w16a16
...
defined at unittest_layers_addition.cpp:33 (../unittest/layers/unittest_layers_addition.cpp:33)
...
defined at unittest_layers_addition_cl.cpp:47 (../unittest/layers/unittest_layers_addition_cl.cpp:47)
...
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

[ trivial ] Fix typo

---

nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_common.h
nntrainer/tensor/hgemm/hgemm_kernel_1x8.h
nntrainer/tensor/hgemm/hgemm_kernel_4x4.h
nntrainer/tensor/hgemm/hgemm_kernel_4x8.h
nntrainer/tensor/hgemm/hgemm_kernel_8x16.h
nntrainer/tensor/hgemm/hgemm_kernel_8x8.h

- For temporary solution apply zero padding in non-8-K divisible case.

[ hgemm ] Use zero-padding in non-8 divisible case GEMM case

---

nntrainer/layers/cl_layers/swiglu_cl.h

Currently, the SwiGLU layer using OpenCL operations does not support training/backpropagation.
Consequently, we are updating the logic to reflect that it is false.

[Layer] Fix logic: SwiGLU Layer Training Incompatibility

---

nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h

- Current implementation is rooted on general cases, thus optimize only w.r.t. K accumulation.
- However, when it comes to M,1 x 1,N computation, all optimizations like packing, transposing is no use.
- Implementing a explicit kernel function for such case resolved the latency issue.
| dim = (576, 1) x (1, 1024) | fp16 | fp32 |
| noTrans | **190834 ns** |  380525 ns |
| transA |  **173896 ns** | 387860 ns |
| transB | **180369 ns** | 382123 ns |
| transAB | **179263 ns** | 379238 ns |
Since this is K=1 case, we do not need to partial-accumulate w.r.t. K-direction with fp32, thereby accelerated approximately 200%

[ hgemm ] Consider K=1 changes

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/jni/Android.mk
test/unittest/unittest_blas_kernels_cl.cpp

- `sscal` equivalent kernel added for multiply.
- Added standalone unit test `unittest_blas_kernels_cl.cpp` for easily testing OpenCL kernels.
- Added an overload of `dotCl`.

[ blas/OpenCL ] Added multiply OpenCL kernel and unit test

---

.github/workflows/cpp_linter.yml

This PR enables the GitHub actions bot to suggest changes based on the clang-format directly.
- Add format-review options to enable Pull Request reviews from clang-format.
- Upgrade the cpp-linter version to 2.9.0 to meet minimum version requirements.

[CI] Add PR review from clang-format

---

nntrainer/tensor/tensor.cpp

Fixed-sized integer formats do not have a way of explicitly indicating invalid data.
Every possible value of an int is a number. Therefore, removing NaN check for int values.

[Tensor] Remove NaN check for integer

---

nntrainer/tensor/tensor.cpp

There are unnecessary copy of tensor, in case of fp16
It seems that when developing previously, the tensor structure was not accurately established, so it attempted to save by forcibly converting to FP16.
Now, when performing getData<_FP16>(), it is automatically converted, so the process of putting every tensor one by one in the temp array is unnecessary and only slows down the speed.

[FP16][Tensor] Remove unnecessary copy on save

---

api/ccapi/include/layer.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
test/input_gen/gen_layer_tests.py
test/jni/Android.mk
test/unittest/layers/unittest_layers_reshape_cl.cpp

Added initial version of Reshape Layer for GPU. This is a basic implementation using naive kernel.
- `reshape_cl.cpp` added containing the new `ReshapeLayerCL` class for OpenCL implementation.
- Added `unittest_layers_reshape_cl.cpp` to test Reshape Layer on GPU.

[GPU/OpenCL] Initial version of Reshape Layer with OpenCL ops

---

nntrainer/layers/cl_layers/addition_layer_cl.cpp
nntrainer/layers/cl_layers/addition_layer_cl.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.h
test/unittest/layers/unittest_layers_addition_cl.cpp

Moved `addition_cl` kernel to Tensor directory and refactored it for generalization.
Naming convention changed for `fp16` in `addition_layer` unittests.

[GPU/OpenCL] Moving Addition kernel to Tensor Directory @open sesame 07/04 09:01

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/unittest/unittest_blas_kernels_cl.cpp

Added SGEMM OpenCL kernels for the following:
- `noTrans`
- `transA`
- `transB`
- `transAB`

[ blas/OpenCL ] SGEMM OpenCL kernels added

---

.github/workflows/android.yml

This pr fixs the duplicated build in android build action.

[ CI ] modify android build test in action

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
test/input_gen/gen_layer_tests.py
test/jni/Android.mk
test/unittest/layers/unittest_layers_rmsnorm_cl.cpp

- Added naive version of OpenCL implementation for RMSNorm Layer.
-  Incorporated kernel for ops used.
- Added unit test for rmsnorm_layer_cl.

[GPU/OpenCL] Initial version of RMSNorm Layer

---

nntrainer/opencl/meson.build

Changes in this PR:
- Added opencl/third_party folder to include directory.
- Will prevent file not found errors if GPU related APIs used inside Applications.

[build] Added third party to include directories

---

nntrainer/layers/acti_func.h
nntrainer/layers/common_properties.h

- add tanh-based approximate gelu(tanh gelu) for vision transformer.
- rename quick gelu to sigmoid gelu(it's a sigmoid-based approximate gelu)

[Layer] add tanh-based approximate gelu activation function

---

api/capi/meson.build
api/ccapi/meson.build
meson.build
nntrainer/meson.build

When a dependency library is installed with hardcoded scripts, declare dependency with as much information as possible from the installed package to detect dependency errors at build-time.
Don't add a dummy dependency for actual library dependencies.
Fixes #2673

Remove dangerous dummy meson dep

---

Applications/LLaMA/jni/main.cpp
meson.build
meson_options.txt

- fix 'ENABLE_ENCODER' option typo errors in llama application
- add 'enable_encoder' to meson option
After reflecting this modifications, i've checked that the llama is running well. (If you build the enable_encoder option as true, it works.)

[meson] fix typo error and add encoder option

---

nntrainer/layers/layer_node.h
nntrainer/layers/lstm.h
nntrainer/models/neuralnet.h
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.h
test/unittest/unittest_nntrainer_appcontext.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

This PR resolves warnings that occur during the Android build. The list is as follows.
- Resolves explicitly defaulted function is implicitly deleted.
- Fix function that overrides virtual functions but is not marked override.
- Resolves clang warning on expression side effects.

[bugfix] Resolves Android build warnings

---

nntrainer/utils/util_simd.cpp
nntrainer/utils/util_simd.h
nntrainer/utils/util_simd_neon.cpp
nntrainer/utils/util_simd_neon.h

- There was a typo in swiglu function. With Z element multiplication, this function is a swiglu, not a swish

[ trivial/util ] Change name swish -> swiglu

---

nntrainer/layers/common_properties.h

Some activation types were missing from EnumList.
Added missing types to EnumList.
Changed the order of ActivationType and EnumList to be the same.

[Layer] Add missing activation type

---

test/unittest/models/models_test_utils.cpp

This PR removes the print statement that was previously added for debugging purposes.

[trivial] remove unnecessary code

---

tools/android_test.sh

This patch adds a script to run unit tests on Android devices.

[Android] Add android test script

---

Applications/PicoGPT/jni/main.cpp

When -DENABLE_ENCODER is given, you do
#ifdef ENABLE_ENCODER
not
#ifdef DENABLE_ENCODER
CC: @baek2sm

fix: incorrect C/C++ preprocessor macro

---

api/ccapi/include/layer.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
test/jni/Android.mk
test/unittest/layers/unittest_layers_concat_cl.cpp

Added initial version of Concat Layer for GPU. This is a basic implementation using naive kernel.
- `concat_cl.cpp` added containing the new `ConcatLayerCL`class for OpenCL implementation.
- Added `unittest_layers_concat_cl.cpp` to test Concat Layer on GPU.
@todo concat layer incremental forwarding

[GPU/OpenCL] Initial version of Concat Layer with OpenCL ops

---

nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h

This PR adds summary content to help users quickly understand the role and scope of the Tensor API.
2. Run test:   [ ]Passed [ ]Failed [X]Skipped

[doc] Extend code documentation

---

tools/android_test.sh

This patch checks if Android NDK is installed and configured before building using NDK in the Android test script.

[Android] Verify Android NDK Installation and Configuration

---

test/unittest/layers/unittest_layers_concat_cl.cpp

Modified the concat gpu testcases name in unittest_layers_concat_cl for differentiation with concat cpu testcases name.

BUG FIX : Concat GPU Layer and CPU layer unittest cases name overlapping.

---

nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h

This PR updates the TensorBase class to make mathematical operations that are not required to create a new tensor class.
This change allows developers to easily create new classes without implementing math operations.
Note that these functions should be implemented to utilize tensor operations fully.
- Change math operation function from pure virtual function to virtual function
- Add a private function to get the data type as a string

[Tensor] Update tensorbase for efficient creation of new tensor class.

---

meson.build
meson_options.txt
nntrainer/tensor/hgemm/hgemm.cpp
nntrainer/tensor/hgemm/hgemm.h
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel.h
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_1x4.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_1x8.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_4x4.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_4x8.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_8x16.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_8x16_experimental.cpp
nntrainer/tensor/hgemm/hgemm_kernel/hgemm_kernel_8x8.cpp
nntrainer/tensor/hgemm/hgemm_kernel/meson.build
nntrainer/tensor/hgemm/hgemm_noTrans.h
nntrainer/tensor/hgemm/hgemm_util.cpp
nntrainer/tensor/hgemm/hgemm_util.h
nntrainer/tensor/hgemm/meson.build
tools/package_android.sh

- According to current paper, accumulating up to 64 ~ 128 w.r.t. K-direction is fine.
- Since conventional error metric, and newly introduced metric (max component relative error) is fine as well, introduce experiemntal kernel that is faster, but less accurate.
- using build option `-Dhgemm-experimental-kernel=true` can enable such kernel when *android build*.
- Performance of this kernel is shown at  #2655 
- Include experimental kernel and exclude the previous one when experimental kernel build -> no newly added `#ifdef`s in file

[ hgemm ] Add experimental kernel

---

nntrainer/tensor/matrix_transpose_neon/matrix_transpose_kernels_neon.h

- Previous transpose kernel occasionally load/save unallocated memory, and then masked it.
- Now, it does not read them at the first place, but load with for-loop
- This would deteriorate speed of fp16 matrix transpose, but won't be dominant in total model latency
| dim | before | after |
|  87,2049 | 884 ns | 16114 ns  |
| 2048, 86 | 34019 ns | 82258 ns  |

[ matrix_transpose/bugfix ] Prevent reading/saving data from/to unallocated memory

---

nntrainer/layers/concat_layer.cpp

This pull request aims to optimize the performance of `forwarding()` in `ConcatLayer`.
This is accomplished by improving the current concatenation logic by utilizing the tensor operation `concat()` instead of `Map()`.
Note that this optimization is only for `forwarding()` and `calcDeriv()` would be improved in later PR.
|key|avg|min|max|sum|
|------|---|---|---|---|
|calcDeriv(concat)|1.004153s|0.997947s|1.010360s|2.008307s|
|forward(concat)|1.083193s|1.042626s|1.010360s|2.166386s|
|concat|1.129055s|0.997965s|1.252510s|9.032440s|
|key|avg|min|max|sum|
|------|---|---|---|---|
|calcDeriv(concat)|1.134034s|1.131812s|1.136257s|2.268069s|
|forward(concat)|0.017167s|0.012304s|0.022031s|0.034335s|
|concat|0.627868s|0.012310s|1.346551s|5.022949s|
input 0: 1:1:196:256 [ FP16 : NCHW ]
input 1: …

[Layer] Improve forwarding logic of ConcatLayer @open sesame 08/08 18:22

---

jni/meson.build
test/jni/Android.mk
test/jni/meson.build
test/unittest/jni/Android.mk

This PR enables NNTrainer to use Android NDK r27 to support compiling 16 KB-aligned shared libraries.
While -fpu is ignored and -mfloat-abi option is not valid with AArch64 targets, removing these options has no effect on using current NEON instructions for armv8.2.

[Android] Support Android NDK r27 and higher

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp

- Remove cblas params from tensor related files since nntrainer is not fully-dependent on cblas anymore.
- Letting tensors to be aware of Cblas related parameters is a nonsense at the first place.
- CBLAS params will be declared only when functions from cblas is called.
- fyi) `TStorageOrder` : Tensor Storage Order

[ Tensor ] Remove CBLAS params from Tensor related files.

---

nntrainer/tensor/blas_interface.cpp

This PR resolves the build error after #2704 when enable_fp16 is true.
This fixes:
blas_interface.cpp:141:9: error: ‘order’ was not declared in this scope
141 |   sgemv(order, TransA, M, N, alpha, A_, lda, X_, incX, beta, Y_, incY);
|         ^~~~~
2. Run test:   [ ]Passed [X]Failed [ ]Skipped

[bugfix] Resolve fp16 enabled build error

---

nntrainer/tensor/blas_interface.cpp

- Since current function implementations are not using CBLAS params, should directly call function from cblas.h

[ blas/bugfix ] Fix irrelevant function call

---

nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h

Enhanced `LayerKernel` enum and mask to use 64-bit values (`ull`).
This was done to include more kernels with the same enum type.
> This entire management of kernels from `LayerContext` might be changed in upcoming design changes related to GPU pipeline.

[enhance] Using 64 bit for LayerKernel enum

---

jni/Android.mk.in

Android encourage to use 16KB package for the shared library. This PR add the 16KB package option and also recommand to use ndk which is higher or equal version of r27.
Resolves:

[ BUILD ] Add 16K shared lib package option for Android

---

api/ccapi/include/layer.h
debian/nntrainer-dev.install
meson.build
nnstreamer/meson.build
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.h
nntrainer/layers/meson.build
nntrainer/tensor/hgemm/hgemm_pack.cpp
packaging/nntrainer.spec

This pull request includes the following commits to backport NNTrainer for Tizen 7.0:
- Commit related to fp16 enablement is included: 9328d1f898953d08d5e2f48c3c9f500b1ad3fdee
- Commit for layer initialization is included : 4d7a8c4b9bfc998a71df94aec2b2a856aba71478
- Commit to disable nnstreamer nntrainer is included : 450000572e8a7e993d36f06e0413c2ae4abc2e5a
- Commit to support Tizen7.0 is included : 96bb3df9726e3975710817a82c2889f1c26b4484
This PR is tested with AuXFT example on QRB4210 board (w/ Tizen 7.0).
----

[Tizen7.0] PR to support Tizen7.0

---

nntrainer/tensor/short_tensor.cpp

This PR resolves coverity issues in the ShortTensor class. Replace max_abs() implementation with maxValue() since the maximum absolute value of unsigned int equals to the maximum value.

[bugfix] fix coverity issues

---

debian/nntrainer-dev.install
nntrainer/models/meson.build
packaging/nntrainer.spec

- Update the code to include `neuralnet.h` in -dev header.
- Some applications, e.g., ReinforcementLearning uses `forwarding` and `backwarding` directly. To support it, this commit adds the header into dev package.

[ Tizen7.0 ] Include `neuralnet.h` in -dev header

---

.github/workflows/ubuntu_clean_meson_build.yml
packaging/nntrainer.spec

Fix build bug
- Currently, there is a bug in the matrix used in CI where the first Meson build runs successfully but subsequent builds fail due to the presence of a 'build' folder. I would like to fix this issue.
- Before running the Meson build, ensure that any existing folders named 'build' are deleted.
Resolves:
- https://github.com/nnstreamer/nntrainer/issues/2715
Co-authored-by: hyeonseok <hs89.lee@samsung.com>
Co-authored-by: Donghyeon Jeong <dhyeon.jeong@samsung.com>

[Wait for #2720][CI] Fix meson ubuntu ci build

---

debian/nntrainer-dev.install
nntrainer/compiler/meson.build
nntrainer/graph/meson.build
nntrainer/layers/meson.build
nntrainer/models/meson.build
nntrainer/optimizers/meson.build
nntrainer/tensor/meson.build
packaging/nntrainer.spec

- In the previous PR (77e56f1), `neuralnet.h` was included in dev package.
- However, some headers were missing used in `nueralnet.h`
- This PR adds headers which have dependencies with `neuralnet.h`
- This version is tested; It supports ReinforcementLearning example app on Tizen7.0
Here is the list of headers, included in `neuralnet.h`
- compiler_fwd.h
- dynamic_training_optimization.h
- layer_node.h
- graph_node.h
- model_common_properties.h
- network_graph.h
- graph_core.h
- graph_node.h
- manager.h
- basic_planner.h
- memory_planner.h
- tensor_pool.h
- cache_loader.h
- task_executor.h
- cache_pool.h
- cache_elem.h
- memory_pool.h
- swap_device.h
- optimizer_wrapped.h

[ Tizen7.0 ] Include some headers in -dev header for neuralnet.h

---

nntrainer/layers/fc_layer.cpp
nntrainer/layers/fc_layer.h

This pull request (PR) consists of two commits:
1) Update 'incremental_forwarding' for 'FullyConnectedLayer'.
- Code updated to support multiple batches .
- Code modified to work with incremental forwarding using LoRA.
2) Fix bugs in 'fc_layer.cpp/h' handling of batch size with LoRA.
- In the previous version, tensor dimensions used in LoRA computations did not account for batch size.
- 'setBatch' function has been overrided to correctly update the batch size of tensors.

[ LORA ] Update FC Layer to support LoRA's incremental forwarding & batch_size option.

---

test/unittest/memory/unittest_cache_loader.cpp

This pull request fixes the issue of failing Continuous Integration.
The new patch checks for nullptr after a flush operation on the cache pool.
This adjustment is expected to rectify the previous failures encountered during the CI process.

[bugfix] Fix memcheck in CacheLoader unit tests @open sesame 10/02 10:47

---

Applications/Multi_input/Readme.md
Applications/Multi_input/jni/main.cpp
Applications/Multi_input/jni/multi_loader.cpp
nntrainer/models/neuralnet.cpp

- This PR contains two commits:
- c37a14e5283eb6e542809f7ff482fa3b4c25f6e2: Updating the multi-input example
- In the previous version, the example builds a graph having multiple inputs with the **same** shape, which couldn't detect the bug (#2660). 
- To provide proper example to handle multiple inputs, it is desired to create a model taking multiple inputs with different shapes. To this end, the main application is updated.
- If we just update the example to have different inputs, one can face the error by the issue; this commit shows how to handle the issue by updating input feeding in reverse way.
- It is not desirable way to handle the bug; it is required to be updated later.
- 805b4a60c530f7a06c05fc69e3c5b9117a78ec69: Updating the model summary print of the multi-input layer
- …

[ App ] Update Multi_Input example

---

nntrainer/tensor/cl_operations/blas_kernel_interface.cpp

Fixed `sgemv_cl` function call. Was failing unittest after recent changes.

[bugfix] Fix sgemv_cl function call from blas_kernel_interface @open sesame 14/10 10:42

---

nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

Fixed always failing condition in `sgemm_cl`. Updated function argument for `DispatchCommand` call.

[bugfix/blas] Fixed sgemm_cl pointer check @open sesame 10/04 17:23

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h

Updated the **SwiGLU**, **Reshape**, and **Concat** layer with the new shared_ptr flow.
Replaced `clCreateKernel` with `registerClKernel` for all these layers.

[GPU/OpenCL] Updated the SwiGLU, Reshape and Concat Layers with latest GPU pipeline changes

---

nnstreamer/tensor_filter/tensor_filter_nntrainer.cc

Use util function to get nth tensor-info ptr.
Also, remove unnecessary header include in filter subplugin.

[Filter] util to get nth info

---

nntrainer/tensor/blas_neon.cpp

This PR resolves the issue by checking what the malloc function returned

[coverity] fix coverity issue @open sesame 10/02 11:44

---

packaging/nntrainer.spec

In order to generate test coverage rerport with gcov, option needs to be fixed.
- remove meson exclude option
Resolves:

Fix for compiling with testcoverage

---

nntrainer/cl_context.cpp
nntrainer/cl_context.h

- In the previous code, `registerClKernel` function returned reference of `SharedPtrClKernel`, causing the possible two problems: 
- returning by reference cannot return nullptr, leading an error in line 170 of `cl_context.cpp`
- returning by reference of `shared_ptr` may not increase the reference counter, leading to early free problem.

[ GPU ] fix return by reference to return by value

---

Applications/Multi_input/jni/multi_loader.cpp
Applications/YOLOv3/jni/det_dataloader.cpp
nntrainer/utils/util_simd.cpp

[header] add missing headers @open sesame 10/02 11:44

---

test/tizen_capi/unittest_tizen_capi_layer.cpp
test/unittest/compiler/unittest_realizer.cpp
test/unittest/datasets/unittest_iteration_queue.cpp
test/unittest/layers/layers_dependent_common_tests.cpp
test/unittest/layers/layers_golden_tests.cpp
test/unittest/memory/unittest_cache_pool.cpp
test/unittest/models/models_golden_test.cpp
test/unittest/unittest_base_properties.cpp
test/unittest/unittest_common_properties.cpp
test/unittest/unittest_nntrainer_internal.cpp
test/unittest/unittest_nntrainer_lr_scheduler.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp
test/unittest/unittest_nntrainer_tensor_nhwc.cpp

- added negative unittest cases
- deleted unittest cases that cause GTEST.MEANINGLESS_ASSERTION defect

[unittest] add negative cases & delete meaningless cases

---

nntrainer/tensor/tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

This PR adds unit tests for the recently implemented tensor data types.
The purpose is to ensure their functionality and correctness by performing various test cases.
- Added unit tests to test functions for CharTensor and ShortTensor
- Check if both tensor data are contiguous before `copy()`

[Test] Add unit tests for newly added tensor type @open sesame 10/17 17:36

---

api/ccapi/include/optimizer.h
api/nntrainer-api-common.h
test/unittest/unittest_nntrainer_graph.cpp
test/unittest/unittest_nntrainer_lr_scheduler.cpp

1. [[Unittest] Add network_graph unit test](https://github.com/nnstreamer/nntrainer/pull/2762/commits/72ecd76f69911a4b7dcb64900188f15069031edb)
- add reinitialize / catch exceptions
- These tests are not limited to specific layers but rather serve as test cases for checking activities performed on actual network graphs.
2. [[Unittest] Add lr_scheduler_cosine unit test](https://github.com/nnstreamer/nntrainer/pull/2762/commits/5423dabe7d9d9cb50b8532f6e262c0d0257adb37)
- property setting test / finalize test / getLearningRate test
- add to api and make helper function 

[Unittest] Add network_graph & lr_cosine unit test case

---

test/ccapi/unittest_ccapi.cpp
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_reduce_mean.cpp
test/unittest/models/meson.build
test/unittest/models/unittest_models.cpp

I have reactivated the deactivated unittest except for the test cases that cause errors.
- enable mol_attention_layer unittest
- enable reduce_mean_layer unittest
- enable unittest_models except for test cases that cause errors

[Unittest] re-activate the deactivated unittest

---

test/unittest/unittest_nntrainer_modelfile.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- unittest_nntrainer_modelfile have not been even "initialized" properly, and fixing this issue shown multiple failing TCs.
- Temporally remove TCs, and upcoming commit will fix them again.
- Still, this commit makes 127 TCs to run additionally.
- Added todo comments for each commented-out TCs.

[ unittest ] Remove improperly formulated TCs @open sesame 10/23 13:26

---

test/unittest/unittest_nntrainer_modelfile.cpp
tools/android_test.sh

- In modelfile unittest, some .ini files are formulated temporally at res directory on the fly.
- Previous code did not make res directory, thus fail to write those files.
Resolves:
`nntrainerIniTest.backbone_from_different_directory_n`

[ unittest/modelfile ] Add res directory when compiled for android unittest

---

test/unittest/layers/unittest_layers_loss.cpp

Currently, there is a layersemantics in the NNTrainer Unittest that verifies the behavior of the losslayer but it does not include the case for the constant DerivativeLossLayer.
By simply filling in the parameters and passing them over, we can perform unit tests on basic operations so I added this feature.
commit : [[Unittest] Add constant DerivativeLossLayer unittest](https://github.com/nnstreamer/nntrainer/commit/5044f9885bde1fe75f424ea94cfa8c51ea0a68ef)

[Unittest] Add constant DerivativeLossLayer unittest

---

test/unittest/unittest_nntrainer_modelfile.cpp

- The original purpose of this TC is to make sure the model is not compiled when input layer is not clarified.
- As far as I am concerned, without any information about input layer, the model should fail to compile, and since it is not compiled, should not support initialization.
- Related commit hashes:
original purpose : 68e7dab5ed2f99e8b380ec8a5f599d76952b7fc3
wrong fix : e1c5915fba7d64db66062d8b62a722d6c1b653ad

[ unittest/modelfile ] Fix backbone_n_15 @open sesame 10/17 17:36

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/flatten_layer.cpp

This PR fixes the bug about the inplace layers when the channel last is enabled.
Previously, the input var_grad tensor's format is not changed in inplace layers.

[ Layers ] Bug Fix for NHWC Support

---

test/unittest/unittest_nntrainer_modelfile.cpp

- Previous network was using hard-coded same-named layers, thus connecting convolution layer with invalid input layer.
This caused :
`"Failed to initialize: in size + padding is smaller than effective kernel" thrown in the test body.`
- Differentiate input layer names, and fix corresponding network size, which is 10:
`mse0, fclayer/act_realized, fclayer, flat, inputlayer2d, mse1, inputlayer/act_realized, conv2d/activation_realized, conv2d, inputlayer`

[ unittest/modelfile ] Fix backbone_20 @open sesame 10/25 10:21

---

test/unittest/unittest_nntrainer_modelfile.cpp

Fix nntrainer IniTest cases on basic valid senarios
- fix old parm to valid ```momentum = 0.99```
- uncommnet tcs
Fix below TEST_P
- nntrainerInitTest - init 
- nntrainerInitTest - initTwice

[ Wait for #2771 ][unittest/modelfile] Fix nntrainerIniTest @open sesame 10/28 13:48

---

nntrainer/cl_context.cpp
nntrainer/layers/layer_node.cpp
test/unittest/unittest_blas_kernels_cl.cpp

- With the current version code, a user should be care about the timing to call `initBlasClKernels()`. However, it is not desirable, causing some unexpected mistakes.
- Instead of that, this draft moves the `initBlasClKernels()` into registerer, which is called once in Global().`
- This PR is related to #2723 

[ GPU ] move `initBlaseClKernels()` to registerer

---

nntrainer/opencl/opencl_buffer.cpp
nntrainer/opencl/opencl_buffer.h
nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/opencl/opencl_command_queue_manager.h
nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h

Changes in this PR:
- Modified `opencl::Buffer` constructor to use `CL_MEM_USE_HOST_PTR` to use host memory from GPU.
- Loaded APIs for `clEnqueueMapBuffer` and `clEnqueueUnmapMemObject` OpenCL functions to map/unmap `opencl::Buffer` to host address space.
- Added required functions in `opencl::Buffer` and `opencl::CommandQueueManager` classes to manage mapping and unmapping from host address.
> Purpose of these changes is to make use of host memory to reduce the copying of data to and from GPU.

[GPU/OpenCL] Adding map/unmap feature for buffer @open sesame 10/29 21:51 

---

nntrainer/layers/cl_layers/addition_layer_cl.h

This PR removes a macro with the same name and functionality defined in multiple locations.
This ensures only one source has the definition of the macro, preventing compilation errors or unexpected behavior.

[GPU/OpenCL] Remove duplicate macro definition.

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This PR updates a parameterized constructor accepting a shared pointer of the TensorBase class.
Users now have greater flexibility when creating Tensors, enabling them to adapt new types of user-defined tensors by initializing the itensor object.
Please note that TensorBase remains an abstract class and cannot be instantiated directly.
Remember to utilize a shared_ptr with a derived class when employing this constructor.

[Tensor] Parameterized constructor with TensorBase 

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h

This pull request aims to enhance the functionality of the Tensor class by enabling it to handle scale factors specifically designed for quantized data types. This patch ensures tensor class accurately represents and processes quantized data while maintaining original features. This update will provide developers with more flexibility when working with quantized models

[Tensor] Update with scale factor support for quantized data types

---

test/unittest/unittest_nntrainer_modelfile.cpp

- With new fixes, more modelfile TC can be used.
- backbone_relative_to_ini_p
- backbone_based_on_working_directory_p

[ unittest ] Enable more modelfile TCs

---

test/unittest/unittest_nntrainer_modelfile.cpp

- `backbone_relative_to_ini_p` : fix invalid bn layer param
- `backbone_08_n` : insufficient init parameters should fail, thus wrong test status
- `backbone_09_n` : current loadFromConfig does not return `ML_ERROR_NOT_SUPPORTED`. Think this is deprecated. Instead, `ML_INVALID_PARAM` is thrown in current version
- `buffer_size_smaller_than_batch_size_p`, `buffer_size_smaller_than_batch_size_2p` : missing res directory
- `basic_dataset_p`, `basic_dataset2_p`, `basic_dataset3_p`: missing res directory

[ unittest ] Fix modelfile TCs @open sesame 11/07 16:09

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/layers/meson.build
nntrainer/layers/subtract_layer.cpp
nntrainer/layers/subtract_layer.h
test/ccapi/unittest_ccapi.cpp
test/input_gen/genModelTests_v2.py
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_subtract.cpp
test/unittest/models/unittest_models.cpp

[Wait for #2710][Layer] add "subtract layer" @open sesame 11/06 18:29

---

Applications/Custom/mae_loss.cpp
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/acti_func.h
nntrainer/layers/activation_layer.cpp
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/identity_layer.cpp
nntrainer/layers/input_layer.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/multiout_layer.cpp
nntrainer/layers/reshape_layer.cpp
nntrainer/layers/time_dist.cpp

currently, same term 'InPlace' is used with different meanings by script.
it could refer to a boolean type value indicating whether in-place operation is supported, or it could refer an enum type value representing the in-place type(type: None, Restriction, Non-Restriction).
To clarify this distinction, variables and functions related to the in-place type have been renamed from 'InPlace' to 'InPlaceType'.
Similarly, both functions for getting/setting whether it supports inplace (boolean) and those for getting/setting the type of inplace (enum) use the same name, "executeInPlace".
To clarify this, I've changed the names as follows..
- set the in-place flag (boolean) : 'executeInPlace' -> 'setInPlace'.
- get the in-place flag (boolean) : 'executeInPlace' -> 'getInplace'.
- set the type of …

[Graph] rename variable & function names for clarity @open sesame 11/07 21:30

---

nntrainer/tensor/blas_avx.cpp
nntrainer/tensor/blas_avx.h
nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h

- Using traditional cblas_scopy is causing some segfault in some cases.
- Implement custom scopy function to avoid this issue.
> TC = 20, unit : microseconds 
| dim | intrinsic | cblas | asm | loop |
| --- | --- | --- | --- | --- |
| 3x1x768x768 | 567.384 | 238.796 | 346.572 | 1438.179 |
> TC = 20, unit : microseconds
| dim | intrinsic | cblas | asm | loop |
| --- | --- | --- | --- | --- |
| 3x1x768x768 | 224.382 | 210.520 | 213.494 | 655.476 |
This is my first time coding in inline asm style, so there might be a little bit of awkwardness. Please review carefully.

[ blas ] Custom-defined scopy functions : aarch64, armv7, x86, incremental indices

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/layers/meson.build
nntrainer/layers/multiply_layer.cpp
nntrainer/layers/multiply_layer.h
test/ccapi/unittest_ccapi.cpp
test/input_gen/genModelTests_v2.py
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_multiply.cpp
test/unittest/models/unittest_models.cpp

- added "multiply layer" for multiplication

[Wait for #2724][Layer] add "multiply layer" @open sesame 11/12 10:52

---

api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/app_context.cpp
nntrainer/layers/divide_layer.cpp
nntrainer/layers/divide_layer.h
nntrainer/layers/meson.build
test/input_gen/genModelTests_v2.py
test/unittest/layers/meson.build
test/unittest/layers/unittest_layers_divide.cpp
test/unittest/models/unittest_models.cpp

- added "divide layer" for division.

[Wait for #2725][Layer] add "divide layer"

---

Applications/LLaMA/jni/transpose_layer.h
api/ccapi/include/layer.h
api/nntrainer-api-common.h
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/meson.build
nntrainer/layers/cl_layers/transpose_cl.cpp
nntrainer/layers/cl_layers/transpose_cl.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.h
nntrainer/tensor/cl_operations/blas_kernel_strings.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/input_gen/gen_layer_tests.py
test/jni/Android.mk
test/unittest/layers/unittest_layers_transpose_cl.cpp

**(New PR. Closed last one due to merge conflicts.)**
Added initial version of Transpose function for GPU. This is a basic implementation using naive kernel.
Changes added with this PR:
Incorporated kernels for GPU to transpose about different axes.
Added unittest_layers_transpose_cl.cpp to test Transpose function on GPU.
Updated with the recent GPU pipeline changes.

[GPU/OpenCL] Initial version of Transpose (all axes) with OpenCL ops. 

---

nntrainer/cl_context.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/unittest/unittest_blas_kernels_cl.cpp

Changes in this PR:
- Added `sgemv_noTrans` kernel.
- `trans` information was added to the required functions.
- Added all possible unit tests for `sgemv` and `sgemv_noTrans`.

[gpu/blas] sgemv_noTrans kernel and unit tests @open sesame 10/29 21:54

---

api/ccapi/include/layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.h

remove initialize functions of layer, layer_node and layer_devel.
because it have been replaced to finalize functions (renamed)

[trivial] remove unused function (initialize func of layer)

---

nntrainer/app_context.cpp
nntrainer/optimizers/lr_scheduler.h
nntrainer/optimizers/lr_scheduler_linear.cpp
nntrainer/optimizers/lr_scheduler_linear.h
nntrainer/optimizers/meson.build
test/unittest/unittest_nntrainer_lr_scheduler.cpp

This PR adds the [LinearLearningRateScheduler](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.LinearLR.html) class, which adjusts the learning rate using a Linear formula.
The implementation includes setting the max/min learning rates, decay steps, and proper error handling for missing properties.
And add unittest cases(property setting test, finalize test, getLearningRate test).

[lr] Add Linear Learning Rate Scheduler

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor_base.h

This PR enhances the existing functionality by supporting reading and saving operations on quantized type tensors.
This change can ensure that quantized tensors can accurately retrieve and store their data from binary files.

[Tensor] Support Read/Save Functionalities for Quantized Type

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/addition_layer_cl.cpp
nntrainer/layers/cl_layers/addition_layer_cl.h
nntrainer/layers/cl_layers/meson.build
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.h
nntrainer/tensor/cl_operations/blas_kernel_strings.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
test/include/nntrainer_test_util.h
test/jni/Android.mk
test/unittest/unittest_blas_kernels_cl.cpp

Performing addition where dimensions of InputA and InputB vary.
Added broadcasting support only where number of batches vary and other dimensions are same for both inputs.
Number of batch of InputB must be 1.
Output of add_i_cl(A,B) is stored in A inplace.

[GPU/OpenCL] Broadcasting support added for GPU Addition kernel.

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/flatten_layer.h
nntrainer/layers/identity_layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/multiout_layer.h
nntrainer/layers/reshape_layer.h

The method of setting the inplace-type has been redefined.
The reason why inplace processing becomes complicated is that since a `multi-out layer` shares output variables, so it needs to be considered whether or not inplace can be performed.
Actually, the layers that can perform inplace even after the `multi-out layer` are only `no-operation layers(no-op layers)`. These `no-op layers` include `identity`, `reshape`, and `flatten layers`.
For other layers, even if they support inplace, they cannot perform inplace when there is a `multi-out layer` in front of them.
Note that because `no-op layers` connected with `multi-out layer` share memory with the `multi-out layer`, so they have the same properties as the `multi-out layer`. This property is expressed as `RESTRICTING` in our script.
Based …

[Graph] change of inplace-type setting method

---

nntrainer/layers/acti_func.h
nntrainer/layers/input_layer.cpp
nntrainer/layers/input_layer.h
nntrainer/layers/layer_context.cpp
nntrainer/layers/layer_context.h
nntrainer/layers/loss/loss_layer.cpp
nntrainer/layers/loss/loss_layer.h

- The variables with the same meaning are written as `in_place` or `is_inplace` by the script, so I unified it to use the term "is_inplace".
- Some layer's finalize function includes code that determines whether or not to support in-place depending on the tensor type. However, this code does not work. The reason it seems like this code is working is because there is a same purpose of code at the top of the `canExecuteInPlace` function within the `network_graph.cpp` and that code works.
It is meaningless to determine whether or not to support in-place within the `finalize` function because the `canExecuteInPlace` function, which decides how InPlace will behave, is called before the `finalize` function.
The canExecuteInPlace function is called during `compile` while the finalize function is …

[Graph] rename variable and remove non-working codes @open sesame 11/14 19:02

---

nntrainer/layers/input_layer.cpp
nntrainer/layers/input_layer.h
nntrainer/layers/loss/loss_layer.cpp
nntrainer/layers/loss/loss_layer.h

Currently, when using mixed precision mode with in-place set to true, the ninja test fails.
I think this failure is due to setting the in-place default value as true for all cases where it shouldn't have been.
Since loss layers and input layers haven't yet implemented non-FP32 operations, I've modified them so that they now specify in-place computations as false.

[Bugfix] Revert mixed precision case inplace set false

---

test/input_gen/genModelTests_v2.py
test/input_gen/recorder_v2.py

Currently, errors occur in creating golden data for most of `genModelTests_v2.py` unittests except for mixed-precision unittests. Therefore, I've restored the previous function as a 'default' type for non-mixed-precision unittests, while newly added mixed-precision unittests are classified as 'mixed' type.
Additionally, python formatter has been applied and some bugs(cpu<->cuda mismatch, etc.) have been fixed.

[trivial] bug fix on recorder_v2.py script

---

.github/workflows/gbs_build.yml

according to Tizen official supported arch list, drop i586 no longer need to test
below list is official supported arch
- armv7l
- armv7hl
- aarch64
- x86_64
- riscv64

[CI] Drop i586 GBS build test

---

meson_options.txt
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/models/model_common_properties.cpp
nntrainer/models/model_common_properties.h
test/unittest/integration_tests/integration_test_mixed_precision.cpp
test/unittest/integration_tests/meson.build
test/unittest/models/meson.build

I would like to add missing verification code related to mixed precision operation and also include associated unittest 
- test each layers compile, initialize, train 
- add some property's validation check code

[Property][Unittest] Mixed Precision Unittest & Adding verification code @open sesame 12/02 09:00

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h
nntrainer/layers/cl_layers/fc_layer_cl.cpp
nntrainer/layers/cl_layers/fc_layer_cl.h
nntrainer/layers/cl_layers/layer_impl_cl.h
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
test/jni/Android.mk

- This draft is a suggestion for #2723
- This draft splits kernel registration from forwarding function.
- This draft make kernelPtr as static member of layer to avoid redundant kernel registration.
- This draft contains example update for `concat_cl` , `reshape_cl`, and `fc_layer_cl` only.

[ GPU/OpenCL ] Split kernel registration from forwarding method @open sesame 12/02 09:39

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h

[Mixed Precision] Fix gradient clipping logic
update mixed precision - gradient clipping logic
- when gradient clipping, gradient should unscale before calc l2norm
Resolves:
- #2746 

[Wait for #2803][Mixed Precision] Fix gradient clipping logic @open sesame 12/02 09:37

---

nntrainer/utils/nntr_threads.cpp

This PR fix the nntr prarallel run. Previously it is not set properly according to NNTR-NUM-THREADS options in meson_options.txt

[UTIL] fix the bug in nntr parallel run @open sesame 12/02 17:11

---

api/ccapi/include/model.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h

- Added return last output option in incremental inference. To support backward compatibility, default value would be set as false.

[ccapi] add return last output option in incremental inference @open sesame 12/04 16:19

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/SECURITY.md
.github/workflows/codeql.yml

This is a pull request to add and modify necessary actions as we completely disable TAOS CI in NNTrainer.
- Add CodeQL to nntrainer (This .yml file, simply copy from nnstreamer's ci file )
- i will add more action for variout test
3. Run test:	 [X]Passed [ ]Failed [ ]Skipped

[CI] Replace TAOS -> gitaction & Add more CI

---

api/ccapi/include/tensor_dim.h
meson.build
meson_options.txt
nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/meson.build
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor_dim.cpp

This PR adds a Tensor class that supports the Binary-code-based quantization type.
Binary-code-based quantization ([BCQ](https://sites.google.com/view/insoochung/sub-3bit-quantization)) allows extremely low bit quantization and BCQTensor aims to store and manage such quantized data.
Note that the BiQGEMM is utilized for quantized inference and the BiQGEMM library is needed to use BCQTensor fully.
[Binary-code-based quantizer](https://github.com/insoochung/transformer_bcq) demonstrates how to perform binary-code-based quantazation.

[Tensor] Binary-code-based quantized tensor

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/tensor.cpp

This PR resolves an issue that quantized tensors incorrectly read and save their data.
Note that scale factors are assumed to be in full-precision, and half-precision support will be later introduced.

[Bugfix] Read & save quantized tensor data.

---

api/ccapi/include/tensor_dim.h
nntrainer/models/model_common_properties.h
nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/utils/base_properties.h

[ BCQ ] Support BCQ type as model Weight
- Previous PR enabled BCQTensor.
- This PR enables BCQTensor as a weight.
- This PR add BCQ-FP32 as a weight-activation type.

[Wait for #2819] [BCQ] Add a feature to enable BCQ tensor as a weight type

---

nntrainer/tensor/meson.build

- This commit add BiQGEMM path to nntrainer_inc_abs to support Android build with enable-biqgemm option.
- The path for BiQGEMM corresponds to the one in the top `meson.build`

[ Meson ] BCQTensor dependency is added for Android build

---

api/nntrainer-api-common.h

---
It's about fixing typo to example code `ml_train_datagen_cb` of  `nntrainer-api-common.h`

docs: fix typo

---

nntrainer/cl_context.cpp
nntrainer/layers/bn_layer.cpp
nntrainer/layers/bn_layer.h
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
nntrainer/layers/common_properties.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/layer_normalization_layer.cpp
nntrainer/layers/layer_normalization_layer.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
test/jni/Android.mk

- This PR is continuation of #2785 .
- This PR applies the splitting kernel registration in forward function to RMSNorm layer.
- Please refer to #2723
- 0be5f29aedc3c8861f5cb735f85b7c1a0756e0b0 : new feature included in this PR
-----------------------------------
**2024-12-02** New commit is added :
78907d7b59f887f2751ad6419a00094cf72b15ce
- This commit updates some bn layer's properties to make them follow
naming convention
- BNPARAMS_GAMMA_INIT -> GammaInitializer
- BNPARAMS_MU_INIT -> MuInitializer
- BNPARAMS_VAR_INIT -> VarInitializer
- BNPARAMS_BETA_INIT -> BetaInitializer
- This commit replaces parts of using RMS_NORM_GAMMA_INIT to GammaInitializer
---------------------------------

[ GPU ] split kernel registration from forwarding function in `rmsnorm_layer_cl`

---

nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/transpose_cl.cpp

- As far as I know, `PLUGGABLE` flag is valid only for custom layers.
- However, there are pluggable-related codes in  `transpose_cl` and `swiglu_cl` layers.
- This commit removes the code blocks.

[ GPU ] Removing PLUGGABLE flag and its action from official cl layers.

---

nntrainer/layers/layer_context.h

- This patch adds a missing part of #2820.
- In order to use BCQ as a weight, this patch should be included.

[ BCQ ] Add a feature to enable BCQ tensor as a weight type (cont.)

---

nntrainer/models/model_common_properties.cpp

- This commit fixes a minor error to print error log.
- This commit adds a condition to print the error log.
Relevant issue: #2826 

[ minor ] bugfix in printing error log (model_commo_properties / LossScale)

---

nntrainer/cl_buffer_manager.cpp
nntrainer/cl_buffer_manager.h
nntrainer/cl_context.h
nntrainer/meson.build
nntrainer/opencl/opencl_buffer.cpp
nntrainer/opencl/opencl_buffer.h
nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/opencl/opencl_command_queue_manager.h
nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h

Optimized GPU pipeline by managing `Buffer` creations globally:
- Added singleton class `ClBufferManager` for global `Buffer` objects.
- Created 5 buffers of 256 mebibytes globally which can be used by all the kernels multiple times.
- Added wrappers for OpenCL APIs `clEnqueueReadBufferRect` and `clEnqueueWriteBufferRect`.
- Implemented `WriteDataRegion` and `ReadDataRegion` members of `Buffer` class to read and write to a particular region of device  buffer.
- Lazy initialization of buffers at `cl_context`.
- Tested with BLAS kernels.
These changes optimizes the current GPU pipeline by managing device buffers optimally.
> Note: Device buffer preset size can be modified later if required.
2. Run test:	 [X]Passed [ ]Failed …

[GPU] Global Buffer manager and optimization

---

nntrainer/models/neuralnet.cpp

Currently, only the forwarding code is distinguished when Train and Swap are enabled. 
I also added a case where Swap is turned off and only Inference is turned on.

[hotfix] Fix if-else condition for FSU

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/quantizer.h

- intY -> incY (incremental index of Y)
- __scopy_kernel() only works for interested SIMD register width

[ trivial ] Fix typo & misspelled function param

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp

This pull request aims at adding the functionality to copy the int8 data type into other types such as int8, fp16, and fp32.
Please note that this implementation follows the intrinsic used for copying uint8 values.
By including this feature, we can expect more flexibility in handling different data types which will contribute to overall system performance improvement.

[Blas] copy functionality for signed int8 data type

---

test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/integration_tests/meson.build

Add Unittest for FSU
- Use Simple FC Model that consist with 6-FC layer
- FP16-FP16 / Lookahead 1
i will add more case of FSU Model at Benchmark

[Unittest] FSU Unittest with Simple FC Model

---

meson.build
meson_options.txt
nntrainer/tensor/meson.build

- This PR reflects the previous comment by @myungjoo [[link](https://github.com/nnstreamer/nntrainer/pull/2823#issuecomment-2533883640)]
- removing hard code external path in meson script
- Since BiQGEMM is header-only lib, I skipped the step to search from pkgconfig 
- In the previous version, meson.build contains hard coded path for the BiQGEMM enablement, which is undesirable.
- This commit updates the meson build script including the top meson and tensor meson by adding meson_option and the step to search the default path.

[ meson ] remove hard code path in meson script @open sesame 12/23 15:55

---

api/ccapi/include/common.h
api/ccapi/include/layer.h
api/ccapi/src/factory.cpp
nntrainer/layers/common_properties.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
test/unittest/layers/layers_dependent_common_tests.cpp

This PR add ComputeEngine Enum Property.
Enum elements are "cpu", "gpu", "qnn" for now.
The property format is "engine=qnn".

Add ComputeEngine Property for choosing Engine

---

nntrainer/tensor/manager.cpp

at case of inference there are some bug
- when set lifespan to tensor swap & non-swap value is exchanged
- set swap case - forward_func_lifespan
- set non-swap case - forward_infer_lifespan

[FSU][Bugfix] Bugfix on FSU Inference

---

nntrainer/graph/network_graph.cpp
nntrainer/layers/add_layer.h
nntrainer/layers/common_properties.h
nntrainer/layers/divide_layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/layers/multiply_layer.h
nntrainer/layers/subtract_layer.h
nntrainer/utils/node_exporter.h

added inplace direction setting for binary tensor operation layer.

[Wait for #2796][Graph] add inplace direction setting through layer property

---

nntrainer/tensor/quantizer.cpp
nntrainer/tensor/quantizer.h
test/unittest/meson.build
test/unittest/unittest_nntrainer_quantizer.cpp

This PR adds initial PerTensorAffineQuantizer operation implementations.
This change allows users to quantize and dequantize tensors.
Note that the current implementation is naive and has limited features.
The optimized version will be introduced in the later PR. 

[Quantizer] PerTensorAffineQuantizer operations

---

nntrainer/models/neuralnet.cpp
test/ccapi/unittest_ccapi.cpp
test/tizen_capi/unittest_tizen_capi.cpp
test/unittest/compiler/unittest_tflite_export.cpp
test/unittest/unittest_nntrainer_exe_order.cpp
test/unittest/unittest_nntrainer_graph.cpp

**Abstract**
Currently, our code requires an optimizer setup even when developers intend to execute the network using INFERENCE mode. To address this issue, the PR've updated the `initialize` method to validate the presence of an appropriate optimizer based on the specified execution mode.
https://github.com/nnstreamer/nntrainer/blob/24a868de5bb59004dae69aea97d6386ed7ec9596/nntrainer/models/neuralnet.cpp#L266-L267
Additionally, earlier unit tests did not account for varying execution modes, leading to gaps in checking optimizer configurations. Consequently, this PR includes modifications to ensure comprehensive coverage through updated unit test cases.

[ Init ] Verify optimizer during initialization according to execution mode.

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/quantizer.cpp
nntrainer/tensor/quantizer.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h
test/unittest/unittest_nntrainer_quantizer.cpp
test/unittest/unittest_nntrainer_tensor.cpp

This pull request aims to modify the existing codebase such that the memory data of CharTensor can now store scale factors based on different quantization schemes.
Additionally, this change allows the Tensor class to specify the desired quantization scheme while creating a new CharTensor instance.
The scale factors are determined either during the quantization process using a specific quantizer or they can be manually initialized if both the quantized data and the corresponding scale factors are provided as inputs.

 [CharTensor] Enable memory data to store scale factors based on quantization schemes

---

api/ccapi/include/model.h
nntrainer/graph/network_graph.cpp
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/unittest_nntrainer_graph.cpp

- Inference model does not require label and loss layer.
- Therefore, we can just simply ignore addLossLayer during the inference mode.
- Add unittest to verify such.
FYI) Following is the output of : 
```C++
TEST(nntrainerGraphUnitTest, NoLossLayerWhenInferenceMode) {
...
model->summarize(std::cout, ML_TRAIN_SUMMARY_MODEL);
...
}
```
```bash
================================================================================
Layer name          Layer type    Output dimension         Input layer
================================================================================
input0               input           1:1:1:256 …
```

[ graph ] Divide addLossLayer process when compiling inference model graph @open sesame 01/15 14:27

---

.github/CODEOWNERS

- Remove ineligible users
- @nnstreamer/nnstreamer 
- @helloahn
- @kparichay
- @dongju-chae
- @zhoonit
- Add a new user
- @dkjung
1. Build test: [X]Passed [ ]Failed [*]Skipped
2. Run test: [X]Passed [ ]Failed [*]Skipped
1. NA

[trivial] Update CODEOWNERS

---

jni/prepare_ml-api.sh

This PR updates the URL of the NNStreamer's latest android build result.
The previous URL is deprecated and is no longer be updated.

Update: New URL for NNStreamer Latest Android Build

---

.github/workflows/daily_build.yml

Add Dailt Ubuntu build for our projects build test
- for now we use AWS S3 for daily build from now we use gitaction
- use matrix on ubuntu 20.04, ubuntu 22.04
- use matrix on fp16 enable / disable
- use matrix on swap enable / disable

[CI] Add daily Ubuntu build

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_interface.h
nntrainer/tensor/blas_neon.cpp
nntrainer/tensor/blas_neon.h
nntrainer/tensor/float_tensor.cpp

This pull request aims to add the functionality of copying the int16 data type into fp32.
Please note that this implementation does not utilize SIMD at this time.

[Blas] copy functionality for signed int16 data type

---

.github/workflows/cpp_linter.yml
.github/workflows/static.check.yml

This pull request updates the workflow script to run on Ubuntu 22.04 instead of the latest version, allowing the static checker to use clang-format version 14.
2. Run test:   [ ]Passed [ ]Failed [X]Skipped

[CI] update static checker script to downgrade clang-format version.

---

jni/prepare_ml-api.sh

**Update nnstreamer-lite-native url to const name from date base name**
1. if the cron job of NNStreamer runs and builds at a certain time while the day has changed, the file may not exist due to the interval between those times.
2. For whatever reason, if NNStreamer fails to perform daily build, the file may not exist.
**change --cut-dirs : 6 -> 3**
- "nH" option will remove "https://nnstreamer-release.s3-ap-northeast-2.amazonaws.com"
- then dir would be /nnstreamer/latest/android/
- cut 3 dir will make "main" dir on builddir/ml-api-inference directly
@djeong20 Thank you for working on the URL-related task. 
Although it works normally now, using the ZIP file named updated by @gichan-jang  would increase stability to prevent failures as much as possible.
1. Build …

Update: NNstreamer-lite-Native URL with const name

---

nntrainer/tensor/quantizer.cpp
nntrainer/tensor/quantizer.h
test/unittest/unittest_nntrainer_quantizer.cpp

This PR enhances the quantizer by leveraging the output tensor along with scale factors for more accurate quantization.
Furthermore, it introduces support for the QINT16 data type, expanding our capabilities and improving performance.

Enhanced Quantizer with QINT16 Support

---

Applications/utils/datagen/cifar/cifar_dataloader.cpp
benchmarks/fake_data_gen/fake_data_gen.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/models/model_loader.cpp
nntrainer/tensor/swap_device.cpp
nntrainer/utils/ini_wrapper.cpp
nntrainer/utils/util_func.h
test/ccapi/unittest_ccapi.cpp
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/compiler/unittest_tflite_export.cpp
test/unittest/models/models_golden_test.cpp

This PR is part of porting nntrainer to windows.
This PR replace using GNU specific function strerror_r with portable version std::strerror
Replace this:
https://linux.die.net/man/3/strerror_r 
With:
https://en.cppreference.com/w/cpp/string/byte/strerror

[Windows] Use portable version of strerror

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h

[ GPU/OpenCL ] change swiglu_cl to inherit LayerImplCl
- This commit updates swiglu_cl.cpp/h to inherit LayerImplCl.
- This commit implements registerClKernels() of swiglu_cl layer.
- This commit update cl_context.cpp (applying swiglu_cl's update)
- This PR is continuation of #2785

[ GPU ] split kernel register from forwarding function in `swiglu_cl` @open sesame 12/02 10:40

---

nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/addition_layer_cl.h
nntrainer/layers/cl_layers/transpose_cl.h

[ GPU/OpenCL ] change  `addition_layer_cl` and `transpose_cl` to inherit LayerImplCl
- This commit updates  `addition_layer_cl` and `transpose_cl`.cpp/h to inherit LayerImplCl.
- This commit implements registerClKernels() of  `addition_layer_cl` and `transpose_cl` layer.
- This commit update cl_context.cpp (applying  `addition_layer_cl` and `transpose_cl`'s update)
- This PR is continuation of https://github.com/nnstreamer/nntrainer/pull/2785
- This PR can close #2723 

[ GPU ] split kernel registration from forwarding function in `addition_layer_cl` and `transpose_cl`

---

Applications/Custom/LayerPlugin/layer_plugin_test.cpp
debian/nntrainer-dev.install
nntrainer/app_context.cpp
nntrainer/opencl/opencl_loader.cpp
nntrainer/utils/dynamic_library_loader.h
nntrainer/utils/meson.build
packaging/nntrainer.spec

Create class which make possible to use the same interface for loading dynamic libraries and symbols for multiple operating systems

[Windows] Add multi os wrapper for loading dynamic libraries

---

debian/changelog
meson.build
packaging/nntrainer.spec

It has been too long since the last version update, and we had too huge changes since 0.5.0 release.
Besides, PPA Launchpad has issue of having 0.5.1 release, which blocks updating latest 0.5.0 updates.
PPA status:
```
[Built] by recipe [nntrainer-daily] for [nnstreamer]
Published on 2023-09-18
Changelog
nntrainer (0.5.1-0~202309180717~ubuntu22.04.1) jammy; urgency=low
* Auto build.
-- Launchpad Package Builder <[noreply@launchpad.net]>  Mon, 18 Sep 2023 12:47:09 +0000
```

Release of 0.6.0

---

nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp

This pull request addresses the issue of improper vector initialization that leads to an error in the `Tensor::split` function. Previously, the vector was reserved but accessed directly without inserting any elements. Reserving memory only allocates space internally, leaving the vector uninitialized.
- Initialize the vector using the constructor that takes "count copies of elements."
- Properly initialize tensors when they are added to a vector of tensors.

[Tensor] Fix improper vector initialization in Tensor::split function

---

nntrainer/app_context.cpp

This PR start series of changes which should make possible compilation of nntrainer on windows platform.
Header dirent.h is not available on windows so to make code more portable I've replaced this functionality with std::filesystem

[Windows] Avoid using dirent.h

---

packaging/nntrainer.spec

Path macro has been incorrectly used.
%{_libdir} == /usr/lib, /usr/lib64, or ...
%{_bindir} == /usr/bin
Meson accepts postfixes for libdir and bindir.
Do not give meson absolute pathes for libdir/bindir. The relative library path working as postfix is %{_lib}.
Standard rpm macros are at:
https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/

tizen spec: fix path macros

---

nntrainer/opencl/opencl_context_manager.cpp

If you have a local variable having the same with the member property, you need ```this``` to address the member property.
Fixes #2763
CC: @DonghakPark

Fix opencl/context member property init.

---

meson.build
nntrainer/tensor/meson.build

enable-avx=true is the default option, which breaks the build in other archs in general.
1. Ignore AVX if arch is not x64/x86.
2. Reading get_option should be done only once. Fixed for enable-avx.
2. Corrected the buggy AVX condition.
This fix is required by RISC-V: #2638

meson: avx condition fix.

---

nntrainer/tensor/blas_interface.cpp

Do not use #include <header> if the header is a local header file. Use #include "local_path".
This incurs compiler errors in some environment (include path):
```
[70/572] Compiling C++ object nntrainer/libnntrainer.so.p/_home_runner_work_nntrainer_nntrainer_nntrainer_tensor_blas_interface.cpp.o
FAILED: nntrainer/libnntrainer.so.p/_home_runner_work_nntrainer_nntrainer_nntrainer_tensor_blas_interface.cpp.o
c++ -Inntrainer/libnntrainer.so.p -Inntrainer -I../nntrainer -Iapi -I../api -I../api/ccapi/include -Inntrainer/compiler -I../nntrainer/compiler -Inntrainer/dataset -I../nntrainer/dataset -Inntrainer/layers/loss -I../nntrainer/layers/loss -Inntrainer/layers -I../nntrainer/layers -Inntrainer/models -I../nntrainer/models -Inntrainer/optimizers -I../nntrainer/optimizers -Inntrainer/tensor …
```

blas_interface.cpp: header syntax fix

---

nntrainer/tensor/tensor_pool.cpp
test/unittest/unittest_nntrainer_tensor_pool.cpp

This PR enables the tensor pool to allocate memory for scale factors associated with quantized tensors. Currently, only single-precision scale factors are supported.

[TensorPool] Memory allocation for quantized tensor scale factors

---

nntrainer/dataset/iteration_queue.cpp

- This PR resolves coverity issue (number : 1831328) in recent report. I verified this PR resolves the coverity issue.
- The `unique_lock` was manually unlocked before going out of scope, causing a double unlock issue.
- This has been fixed by removing the explicit `unlock()` call.
- Additionally, `notify_emptied_cv.notify_all()` is now called without holding the lock to avoid unnecessary cntention.
FYI) I initially thought it would be fine to simply remove the unlock code line (no issue with notify_all) , but I decided to update it to a scoped lock just in case.

[Coverity] Fix double_unlock issue in markFilled()

---

nntrainer/models/neuralnet.cpp

Uncaught exception (UNCAUGHT_EXCEPT)
exn_spec_violation: An exception of type std::length_error is thrown but the exception specification /*implicit*/noexcept doesn't allow it to be thrown. This will result in a call to terminate().
- in general, throw exception at destrctor is not allowed
- so, add exception at deallocate Tensor
Resolves:

[Coverity] Fix Coverity issue at neuralnet destructor

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/uint_tensor.cpp

This PR addresses memory leak issues in the NNTrainer.
- Release the MemoryData pointer in the Tensor constructor using the vector.

Memory Leak Fixes in NNTrainer

---

meson.build
meson_options.txt
nntrainer/app_context.cpp
nntrainer/compiler/remap_realizer.h
nntrainer/dataset/databuffer.cpp
nntrainer/dataset/dir_data_producers.cpp
nntrainer/layers/acti_func.h
nntrainer/layers/dropout.h
nntrainer/layers/rnn.cpp
nntrainer/layers/rnncell.cpp
nntrainer/models/dynamic_training_optimization.cpp
nntrainer/nntrainer_log.h
nntrainer/nntrainer_logger.cpp
nntrainer/optimizers/lr_scheduler_cosine.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/task_executor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/weight.h

[Windows] Compile nntrainer on windows
After this PR all nntrainer library files are possible to compile with MSVC compiler on Windows and most of MSVC warnigs are fixed.
It can be tested by using meson.build from #2868 
Following options should be disabled during build:
[project options]
enable-blas=false 
enable-tflite-backbone=false 
enable-memory-swap=false 
enable-nnstreamer-backbone=false 
enable-tflite-interpreter=false 
enable-app=false 
ml-api-support='disabled'
enable-test=false
install-app=false
enable-avx=false
enable-mmap=false
[built-in options]
werror=false
As a next step I'll modify build system in order to make both windows / linux / android / tizen build possible using the same meson scripts
Run test: [X]Passed …

Compile nntrainer on windows

---

nntrainer/app_context.cpp

- Fixes: leaked_storage: Variable handle going out of scope leaks the storage it points to.
- Apply: Use std::move(factory_func) instead of factory_func.

[ coverity ] Fix coverity issue : leaked_storage

---

nntrainer/layers/preprocess_l2norm_layer.cpp
nntrainer/layers/preprocess_l2norm_layer.h

- This commit resolves coverity issue of DIVIDE_BY_ZERO.
- This commit updatees preprocess_l2norm_layer.cpp/.h
- In order to fix the DIVIDE_BY_ZERO issue, epsilon property is added to l2norm_layer; the value is used when the norm is divided.

[Coverity] Fix DIVIDE_BY_ZERO issue

---

nntrainer/compiler/ini_interpreter.cpp

For Resolve below issue
- Return value of a function 'iniparser_getstring' is dereferenced at ini_interpreter.cpp:350 without checking for null, but it is usually checked for this function
add NNTR_THROW_IF() to check backbone_path is null when backbone_path is nullptr then it will print error msg

[Coverity] Fix Coverity issue on ini_interpreter (path nullptr excetion)

---

Applications/KNN/jni/main.cpp

Uncaught exception (UNCAUGHT_EXCEPT)
- root_function: In function main(int, char **) an exception of type std::bad_cast is thrown and never caught
- to fix issue, add try catch statement at writefile

[Coverity] Fix Coverity issue at KNN Application

---

nntrainer/tensor/blas_interface.cpp
nntrainer/tensor/blas_neon.cpp

- load for s16, widen to s32, convert to f32, and store.
- Add fallback function with the same function param for easier later refactor.

[ neon ] Implement neon kernel for copy_s16_f32 

---

test/jni/Android.mk
test/unittest/jni/Android.mk

This pull request addresses unsupported option errors during the Android build process.
**Proposed changes in this pull request:**
- Removed the options '-mfpu=' and '-mfloat-abi='.

[bugfix] Unsupported option errors in Android build

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp

To address coverity issue #1839950, the main function is wrapped with try-catch block.

[Coverity] Wrap main() with try-catch block (#1839950)

---

Applications/ReinforcementLearning/DeepQ/jni/main.cpp

This commit is to address Coverity issue #1840581.

[Coverity] Wrap main() with try-catch block (#1840581)

---

nntrainer/tensor/memory_pool.cpp

this patch fix a memory leakage issue in inference mode.
The problem occurred because even though deallocation was performed,
vectors inside the memory pool were still remained.

[Bug] fix memory leakage issue in inference mode @open sesame 02/10 19:43

---

nntrainer/tensor/task_executor.cpp

Resolves:
- double_unlock: ~unique_lock unlocks lk while it is unlocked.   
By applying:
- Removing unnecessary `unlock()`, since it will be unlocked through loop anyway.
- In this case, #2913 (using std::lock_guard) is not valid since wait() function from std::condition_variable is being called.

[ coverity ] Fix coverity issue : Double unlocking @open sesame 02/08 11:00

---

Applications/SimpleFC/jni/main.cpp
nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/cache_loader.cpp
nntrainer/tensor/cache_loader.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/swap_device.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h

Modiy Simple FC Application for FSU-CPU Side TEST 
commit summary
commit 1 [[Application] Update FSU SimpleFC Application](https://github.com/nnstreamer/nntrainer/commit/c0569b52f0ceb4f54de85329fec028e279f1f4e2) : update SimpleFC Application for more easy test & actual environment
commit 2 [[FSU] update layer weight load logic at fsu](https://github.com/nnstreamer/nntrainer/commit/950c5d50efdb2a038d5bc228b11effb3e660d3c3) : update layernode not to load weight at load()
commit 3 [[FSU] Modify Application for CPU side Test](https://github.com/nnstreamer/nntrainer/pull/2906/commits/ec4e82c9cac230dda47ef6503a786de36f61e5c6) : update Application
Signed-off-by: Donghak PARK …

[Wait For #2854][FSU] Modify SimpleFC Application for FSU-CPU Test @open sesame 02/10 14:56

---

nntrainer/nntrainer_logger.cpp
nntrainer/nntrainer_logger.h

Now, the nntrainer log file have timestamps as their names are saved directly under the execution folder every time. Since Unnecessary files keep pilling up with multiple executions. I changed it this stored under "logs" folder

[Log] Change the log files to be saved under the logs folder

---

docs/getting-started.md
docs/how-to-run-examples.md

- In order to build nntrainer with -Denable-fp16=true option on Ubuntu, it is required to use gcc/g++ >= 13.
- This commit adds the comment to the related `.md` files.
Build test: [ ]Passed [ ]Failed [X]Skipped
Run test: [ ]Passed [ ]Failed [X]Skipped

[ Doc ] add a note about the gcc/g++ version (enable_fp16)

---

Applications/utils/datagen/cifar/cifar_dataloader.cpp
benchmarks/fake_data_gen/fake_data_gen.cpp
nntrainer/compiler/tflite_interpreter.cpp
nntrainer/models/model_loader.cpp
nntrainer/nntrainer_error.h
nntrainer/tensor/swap_device.cpp
nntrainer/utils/ini_wrapper.cpp
nntrainer/utils/util_func.h
test/ccapi/unittest_ccapi.cpp
test/unittest/compiler/unittest_interpreter.cpp
test/unittest/compiler/unittest_tflite_export.cpp
test/unittest/models/models_golden_test.cpp

In #2870, the thread-safe function strerror_r was replaced with the non-thread-safe function strerror.
However, due to issues related to thread_safe, it was re-modified to use the thread-safe function.
For Windows support, a macro was defined to replace strerror_r with strerror_s only when the operating system is Windows.

[windows] replace strerror with thread_safe func

---

.github/workflows/daily_build.yml
.github/workflows/pdebuild.yml
.github/workflows/ubuntu_benchmarks.yml
.github/workflows/ubuntu_clean_meson_build.yml

1. Remove Ubuntu 20.04 : Github will soon end support
- For now 24.04 stability is low, so it has been excluded. --> will add later

[CI] update Github-hosted runner & remove Ubuntu 20.04 @open sesame 02/12 13:01

---

meson.build
nntrainer/cl_context.cpp
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/meson.build
nntrainer/opencl/opencl_program.cpp
windows-native.ini

After this change nntrainer can be build on windows using meson.
This change depends on #2904
Requirements on Windows:
1. Install MSVC compiler
2. Install CMake
3. Install meson (using pip)
How to run:
meson setup --native-file windows-native.ini builddir
meson compile -C builddir
This PR also fix build with opencl enabled on windows
5. Run test:   [X]Passed [ ]Failed [ ]Skipped

[Windows] Modify meson build to support windows

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This pull request updates the unsigned int type Tensor class to include zero points in its memory management.
It's important to note that the size of the scale factors matches the size of the zero points.
At present, the zero point uses a scale factor size, which will be modified soon.

[Tensor] Zero point support for unsigned int type 

---

nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/layer_impl_cl.h
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

- Updated the GPU pipeline for both fp32 and fp16 for blas kernels operations.
- `SGEMM`, `SGEMV`, `DotCL`, `SSACL`, `Transpose `, `SwiGLU`, `RMSNorm`, `Concat `ops updated.

[GPU] Optimized operations in the blas kernels with the latest buffer changes.

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This pull request aims to enable the QINT8 element-wise multiplication feature in CharTensor.
This takes two tensors of the same dimensions and returns a matrix of the multiplied corresponding elements.
Please note that automatically determining the new scale factor will be added in a future update.

[CharTensor] Enable QINT8 multiplication feature

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

This pull request addresses activating the QINT8 element-wise addition feature in CharTensor.
It allows the addition of two tensors of the same dimensions, returning a matrix that contains the sums of the corresponding elements.
Please note that the functionality for automatically determining the new scale factor will be implemented in a future update.

[CharTensor] QINT8 addition feature

---

jni/meson.build
meson.build
test/jni/meson.build

Both grep and nproc are part of coreutils.
One can obtain number of cores/threads directly using this command.
Not applicable, it is sufficient it builds.

[meson] Use nproc for number of cores

---

.clang-format

Update .clang-format file : update field & value with clang-foramt version 14
- AllowShortBlocksOnASingleLine: Never
- BreakTemplateDeclarations: Yes
- SortIncludes:    CaseSensitive
- Standard:        c++17

[Foramt] Update .clang-format file with valid parm & value

---

.clang-format

AlwaysBreakTemplateDeclarations (deprecated) will renamed as BreakTemplateDeclarations.
But BreakTemplateDeclarations from clang-format version 19 ( we use clang-format version 14 )
Sorry for confuse !

[Format] Remove AlwaysBreakTemplateDeclarations (deprecated) options

---

test/tizen_capi/unittest_tizen_capi.cpp

Resolve UNINIT.LOCAL_VAR Alarm
Coverity issue : Uninitialized data is read from local variable 'model' at unittest_tizen_capi.cpp:183.
Fix : Add Null Check

[Coverity] Fix Coverity issue on test/tizen_capi

---

Applications/LLaMA/jni/main.cpp
Applications/MixedPrecision/jni/main.cpp
Applications/Multi_input/jni/main.cpp
Applications/Resnet/jni/main.cpp
Applications/SimpleFC/jni/main.cpp
Applications/YOLOv2/jni/main.cpp
Applications/YOLOv3/jni/main.cpp
benchmarks/benchmark_application/benchmark_resnet.cpp
nntrainer/utils/util_func.h
test/unittest/compiler/unittest_tflite_export.cpp
test/unittest/integration_tests/integration_test_fsu.cpp
test/unittest/integration_tests/integration_test_loss.cpp
test/unittest/unittest_nntrainer_graph.cpp

The `withKey` function is frequently used to pass keys and values when
using nntrainer. however, this function is re-defined in every
application example and unit test, resulting in significant code
duplication within the project(moreover, it is inconvenient because
users of nntrainer have to define this function every time)
So I removed the duplicated `withKey` functions from each script and
added `withKey` function to utility functions.

[refactoring] add withKey function to utility functions @open sesame 02/21 08:59

---

.github/workflows/windows.yml
meson.build

This PR add running continues integration build of nntrainer on Windows
Tests are turn off for now since two test cases failed on Windows

[Windows] Add Windows CI

---

nntrainer/graph/graph_node.h

While it is not technically used by normal build its presence is verified during debug standard library build.
More info about debug mode of standard library: https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode.html

Add GraphNodeIterator::operator<= required by std::reverse_iterator

---

test/unittest/unittest_blas_kernels_cl.cpp

---
As there is no test for `dotCl` function in the case with `N=1, M=1`,
I added two unit-tests for that condition.
1. Run `./tools/android_test.sh` with an Android device attached to your machine
2. ```bash
adb shell /data/local/tmp/nntr_android_test/unittest_blas_kernels_cl --gtest_filter=blas_kernels.dotCL_sgemv_N_1_M_1_*
```

Add unit-tests for dotCL function, N=1, M=1 case

---

meson.build

Quick fix for Ubuntu when OpenBLAS is build as subproject
Resolves: #2996
1. Build test: [*]Passed [ ]Failed []Skipped
Not applicable

Fix Ubuntu build with OpenBLAS as subproject

---

api/ccapi/include/layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.h

This initialize function is used for running the llm model. It is removed accidently.
Resolves:

[ Bug ] restore the initailize function in layer

---

nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
nntrainer/tensor/cpu_backend/arm/neon_impl.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/quantizer.cpp
nntrainer/tensor/quantizer.h
test/unittest/unittest_nntrainer_quantizer.cpp

This pull request enhances the quantizer class by allowing it to perform quantization on tensors with an unsigned integer data type. It includes consideration of the zero-point during the quantization process.
- The quantizer can now quantize and dequantize unsigned integer data types.
- Test cases have been added to verify quantization on unsigned integers.
- Functions for copying unsigned integer data to floating-point format have also been included.

[Quantizer] Unsigned Integer Tensor Support

---

nntrainer/layers/gru.cpp
nntrainer/layers/grucell.cpp
nntrainer/layers/lstmcell_core.cpp
nntrainer/layers/multi_head_attention_layer.cpp
nntrainer/layers/preprocess_translate_layer.cpp
nntrainer/models/dynamic_training_optimization.cpp
nntrainer/models/dynamic_training_optimization.h

This PR fix some of compilation warnings related with initialization of float variable with double value on Windows build

[Windows] Fix nntrainer double to float init warnings

---

meson.build
test/unittest/compiler/meson.build
test/unittest/meson.build

Misc fixes for some of the options disabled by configuration options.
This is step in direction of fixing builds with various configuration options configurations.
1. Describe how to evaluate in order to be reproduced by reviewer(s).
meson setup <builddir> --native-file=disables.ini
`disables.ini` with contents:
```
[project options]
enable-blas=false 
enable-tflite-backbone=false 
enable-memory-swap=false 
enable-nnstreamer-backbone=false 
enable-tflite-interpreter=false 
enable-app=false 
ml-api-support='disabled'
enable-test=true
werror=false
```

Meson option build fixes

---

meson.build

googletest provided as CMake subproject requires both gtest_dep and gtest_main_dep Also it should be built with PIC (Position Independent Code) when built as static library
1. Build test: [*]Passed [ ]Failed []Skipped
Not applicable (if possible remove system googletest and build)

[gtest] Enable gtest built as subproject on linux

---

Applications/AlexNet/jni/meson.build
Applications/Custom/LayerClient/jni/meson.build
Applications/Layers/jni/meson.build
Applications/LogisticRegression/jni/meson.build
Applications/MNIST/jni/meson.build
Applications/ProductRatings/jni/meson.build
Applications/meson.build
meson.build
test/meson.build
test/unittest/meson.build

On windows mkdir command does not have flag allowing to skip making dir if it already exists This PR add check if directory exist on windows before calling mkdir
It should fix build on #2964

[Windows] Check if directory exist prior running mkdir

---

nntrainer/tensor/cpu_backend/arm/arm_compute_backend_fp16.cpp
nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp

- Previous is_valid() for half-precision inspected with f32 inf values.
- Fix this to check with f16 inf and -inf values (reinterpreted from u16)
- Fix missing return bug

[ bugfix ] Fix is_valid algorithm

---

test/unittest/integration_tests/meson.build

the test/unittest/integration_tests/integration_tests.cpp already contains main, causing linking to fail on some Ubuntu 22.04
The suspicion is that are those with multilib installed, due to libc difference.
The root cause of this issue exposing on some systems is not confirmed.
But both gtest and this compilation unit contain symbol 'main' thus change of dependency is correct fix.
1. Build test: [*]Passed [ ]Failed []Skipped

[gtest] Remove duplicated main() in integration unit test

---

nntrainer/tensor/cpu_backend/arm/hgemm/hgemm_util.cpp

This patch removes the assert statement in the function get_prev_mltpl_of_2p_n, which previously required that the input value N be a multiple of two. After review, I have identified several instances where N is not necessarily a multiple of two.
For instance, 
https://github.com/nnstreamer/nntrainer/blob/9c0c43e9f47ef7a0a94a316d570245ae44b0d79c/nntrainer/tensor/cpu_backend/arm/hgemm/hgemm_util.cpp#L46
Therefore, I've decided to remove this assert statement.

[hgemm] Removal of assert in get_prev_mltpl_of_2p_n

---

test/tizen_capi/unittest_tizen_capi.cpp
test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp

Resolve Tizen 10.0 issue
UNINIT.LOCAL_VAR : Uninitialized data is read from local variable 'model'

[Tizen][Covierty] Fix Coverity Issue on Tizen 10.0

---

jni/prepare_encoder.sh

The url to download an encoder for Application/Llama was outdated. 
This is going to update the url.

Fix the url to download the encoder from

---

nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h

This PR fixes build using GCC version 13.3 on Ubuntu 22.04 when OpenCL backend is enabled.
``` bash
/home/michal/code/nntrainer/nntrainer/layers/cl_layers/concat_cl.cpp:381:5: error: variable ‘input2_batch_size’ set but not used [-Werror=unused-but-set-variable]
381 |     input2_batch_size, input2_height, input2_width, input2_channels;
|     ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```
Unused __input2_batch_size__ could be removed but I would imagine it might be nice to inspect it using debugger.
Checkout on this PR branch on Ubuntu 22.04 machine and try building project using gcc version 13.3 …

Fix GCC 13.3 build on Ubuntu 22.04 when OpenCL bakecnd is enabled .

---

api/ccapi/include/model.h
api/nntrainer-api-common.h
meson.build
nntrainer/compiler/meson.build
nntrainer/compiler/onnx_interpreter.cpp
nntrainer/compiler/onnx_interpreter.h
nntrainer/models/model_loader.cpp
nntrainer/models/model_loader.h
nntrainer/models/neuralnet.cpp

A simplest basic structure of onnx_interpreter has been added.
In this implementation, only input layer, weight layer, add layer are supported.
Basically, it is implemented by reading and parsing the onnx file using protobuf, and then creating an NNTrainer graph by sequentially checking the nodes. Users can simply specify the path to the ONNX model file through the "loadONNX" NNTrainer API function.
The types of tensors handled during the process of creating a graph can be classified into input tensor, constant tensor, weight tensor.
Among these, the current implementation only supports input tensor and weight tensor.
In ONNX, weight tensors have initializers unlike other tensors, so it can be distinguished as weight tensors through initializers. In the current implementation, initializer …

[ONNX] add basic onnx interpreter @open sesame 02/17 20:00

---

test/ccapi/meson.build
test/nnstreamer/meson.build
test/tizen_capi/meson.build
test/unittest/compiler/meson.build
test/unittest/datasets/meson.build
test/unittest/integration_tests/meson.build
test/unittest/layers/meson.build
test/unittest/memory/meson.build
test/unittest/meson.build
test/unittest/models/meson.build

This PR seperates unit tests as seperate testsuite
This lets runnig it separatly and it will allow to specify meson test_setup for them.
`meson test -C <builddir> --suite unittests # runs unittests`
`meson test -C <builddir> --no-suite unittests # runs app tests`

[Wait for #2962] Meson unittests suite

---

Applications/ONNX/jni/Android.mk
Applications/ONNX/jni/Application.mk
Applications/ONNX/jni/add_example.onnx
Applications/ONNX/jni/main.cpp
Applications/ONNX/jni/meson.build
Applications/meson.build
nntrainer/compiler/onnx_interpreter.h

added basic onnx application example.
It loads `add_example.onnx` file and create nntrainer network graph.
(network structure is "input + bias = output")
Output of this example is as below:
```
================================================================================
Layer name          Layer type    Output dimension         Input layer
================================================================================
input               input             1:1:1:2
--------------------------------------------------------------------------------
bias              weight             1:1:1:2
--------------------------------------------------------------------------------
add                 add             1:1:1:2               input
bias …
```

[Wait for #2951][application] add onnx example

---

Applications/AlexNet/jni/meson.build
Applications/Android/PicoGPTJNI/app/src/main/jni/meson.build
Applications/Custom/LayerClient/jni/meson.build
Applications/KNN/jni/meson.build
Applications/LLaMA/jni/meson.build
Applications/Layers/jni/meson.build
Applications/LogisticRegression/jni/meson.build
Applications/MNIST/jni/meson.build
Applications/MixedPrecision/jni/meson.build
Applications/PicoGPT/jni/meson.build
Applications/ProductRatings/jni/meson.build
Applications/ReinforcementLearning/DeepQ/jni/meson.build
Applications/TransferLearning/CIFAR_Classification/jni/meson.build
Applications/TransferLearning/Draw_Classification/jni/meson.build
Applications/meson.build
jni/meson.build
meson.build
test/jni/meson.build
test/meson.build
test/unittest/meson.build

This cleans up meson warning:
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in meson 2.0.
See also: https://github.com/mesonbuild/meson/issues/9300
N/A

[Wait for #2963] Meson run command check

---

Applications/MixedPrecision/jni/meson.build

This change removes copy run_command that was always failing without us noticing. This was part of change 931c586ac23
"[Application] Add Mixed Precision Application"
Path Application/MixedPrecision/res has never existed.
This change partly addresses build failure in #2964 on Ubuntu

[meson] Remove bogus resource copy command

---

Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
Applications/LLaMA/jni/custom_multi_head_attention_layer.h

Previously, the `multi_head_attention_layer` is seperated into a custom layer called `custom_multi_head_attention_layer` for refactoring purposes. At that time, the namespace of custom layer should be changed, but they were copied over as-is, causing duplication. I've renamed namespace.
This issue was discovered and reported by @gkisalapl . I always appreciate your efforts. thanks a lot!
Even after resolving this problem, the llama application still does not work properly now.
I'll try to resolve this issue as soon as possible.
2. Run test:     [ ]Passed [ ]Failed [X]Skipped

[application] namespace duplication in llama application @open sesame 03/07 15:57

---

Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
Applications/LLaMA/jni/custom_multi_head_attention_layer.h
Applications/LLaMA/jni/main.cpp

In PR #2617 , the `internal multi_head_attention` and `custom_multi_head_attention for llama application` were seperated, but
there was duplication in the key values of `multi_head_attention` and `custom_multi_head_attention`, causing unintended issues.
So, the llama application has been modified to always use the `custom_multi_head_attention` layer.
It seems that the errors occuring in the llama application have now been revoled, but I'll carry out the refactoring the example to improve usability and add unit tests for this application.

[Wait for #2989][bug fix] key duplication in llama application

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/half_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/short_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h

- Added SQRT tensor operation for fp32 and fp16.
- Added arg_min tensor operation for fp32, fp16, int8, int4 and unsigned int.
2. Run test:     [ ]Passed [ ]Failed [X]Skipped

[Tensor] Add SQRT & arg_min tensor operation

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/quantizer.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/short_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.h
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h

This PR includes two commits that enhance the functionality of the tensor class:
1. Update QScheme data type to 16-bit unsigned integer
This commit changes the QScheme data type to a 16-bit unsigned integer. This modification ensures consistency with the BCQTensor in reading and saving quantization information, which simplifies calculating the offset.
2. [Tensor] Total Memory Size Retrieval
This commit introduces a new method, getMemoryBytes(), to the tensor class, which retrieves the total size of the allocated memory in bytes. The key difference between the existing bytes() function and the new method is that bytes() only returns the storage size for quantized data in quantized tensors, without accounting for the memory used for scaling factors and zero points. However, for float-type …

Update QScheme data type and add total memory size retrieval

---

nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h

- Implement argmin() function for BCQTensor, which should be implemented
to cover the virtual function (Based on @djeong20 's opinion, this patch changed argmin and argmax as non-pure virtual instead of implementing the op for BCQTensor in this PR)
- matrixDotMatrix takes reference (not pointer)

[BCQTensor] add argmin & bugfix in BCQTensor @open sesame 13:23

---

nntrainer/layers/bn_layer.cpp
nntrainer/layers/bn_layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp

- This patch move action of save from layer_node to every layer
- Instead of branchiing the action of save in the common layer_node wrapper, it is more desirable to define every save action in layer
- This update refers to #2984, which enabled similar features in `read()`
Build test: [*]Passed [ ]Failed [ ]Skipped
Run test: [*]Passed [ ]Failed [ ]Skipped

[Save] Update save action (from layer_node -> to layer-wise)

---

Applications/LLaMA/jni/main.cpp
Applications/LLaMA/jni/meson.build
Applications/meson.build
jni/prepare_encoder.ps1
meson_options.txt
windows-native.ini

0. `Applications/LLaMA` requires the encoder's download. The following Powershell scirpt
- jni/prepare_encoder.ps1
is meant to be doing the same as jni/prepare_encoder.sh.
1. The following file
- /Applications/LLaMA/jni/meson.build
is edited to invoke the script for Windows build.
2. `strcasecmp` => `_stricmp` for Windows
- `strcasecmp` is a Posix function, not available for Windows
3. Applications/LLaMA/meson.build
- Use `static_library` instead of `shared_library`
- `shared_library` doesn't generate `.lib` file
- Windows build fails to link shared libraries for executable
- To avoid the error, `static_library` for sub-libraries

[Windows] Fix Application/LLaMA for Windows @open sesame (03/19 21:00)

---

nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h
nntrainer/opencl/opencl_context_manager.cpp
nntrainer/tensor/cl_operations/attention_kernels.h
nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

Fixed OpenCL with FP16 build - changed used FP16 type in files that used __fp16 instead of _FP16 which is defined based on platform capabilities. Fixed allocation of static array with dynamic size - used std::vector
Comparison of build outputs on main and this branch. Both done (after removing build directory) with:
```bash
meson setup build -Denable-opencl=true -Denable-fp16=true && meson compile -C build
```
On **main** branch:
[opencl_fp16_main.txt](https://github.com/user-attachments/files/19102305/opencl_fp16_main.txt)
On **fix-fp16-opencl-build** branch:
[oepncl_fp16_this_branch.txt](https://github.com/user-attachments/files/19102306/oepncl_fp16_this_branch.txt)
Note that this PR only changes files used on desktop build.
1. Build test: [ ]Passed [ ]Failed …

Fix fp16 opencl build.

---

nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp
nntrainer/tensor/swap_device.h

- Followed by discussion made from #3001, naive reinterpret cast is an undefined behavior. (Thanks @piotrrak !)
- Instead, using std::memcpy will do.
- Meanwhile, SIMD instruction for reinterpret cast will work as the way it is expected.

[ bugfix ] Fix fp16 is_valid algorithm bug

---

nntrainer/tensor/cache_pool.cpp

- This message is used only for debugging.
- This patch remove the code line

[code clean] remove std::cout in cache_pool

---

nntrainer/tensor/tensor_pool.cpp

- This message is used only for debugging.
- This patch remove the code line

[code clean] remove std::cout in tensor_pool

---

Applications/AlexNet/jni/meson.build
Applications/Custom/LayerClient/jni/meson.build
Applications/Layers/jni/meson.build
Applications/LogisticRegression/jni/meson.build
Applications/MNIST/jni/meson.build
Applications/ProductRatings/jni/meson.build
Applications/meson.build
meson.build
nntrainer/meson.build
test/meson.build
test/unittest/memory/meson.build
test/unittest/meson.build

Those are meson fixes to enable cross-compilation to windows on linux using MSVC
Those are not sufficient to get proper build, due to OpenBLAS cross-compilation problems, but are sufficient to check for compilation errors and warnings.
Using MSVC installed under wine it is possible to start cross-compilation (won't build properly functioning binary yet).
Configuring the tree:
```meson setup --wipe --cross-file=x64-msvc-wine-path.ini --cross-file=x64-msvc-wine-toolchain.ini --cross-file=windows-native.ini build=wine-msvc --buildtype=release```
Where:
`x64-msvc-wine-path.ini`:
```ini
[constants]
x64_msvc_wine_path = '<REPLACE_WITH_PATH_WHERE_INSTALLED>/MSVC/bin/x64/'
```
`x64-msvc-wine-toolchain.ini`:
```ini
[binaries]
c = [x64_msvc_wine_path+'/'+'cl']
cpp = [x64_msvc_wine_path+'/'+'cl']
ar …
```

 Experimental win32 cross fixes

---

nntrainer/tensor/cpu_backend/arm/armv7_neon.h
nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
nntrainer/tensor/cpu_backend/arm/neon_impl.h

- Add missing int8 qmul neon implementation (missed due to current refact #2930)
- Refer to #2857 for details.

[ neon ] Add qmul8 implementation

---

nntrainer/tensor/tensor_base.h
test/jni/Android.mk

This PR enables using Ruy as a prebuilt static library in Android tests.
When the proper Ruy interface is introduced, the Ruy header will be included in the cpu_backend directory.

[Android] Ruy as a prebuilt static library

---

test/unittest/layers/meson.build
test/unittest/memory/meson.build

This PR fix following warnings during Windows compilation: cl : Command line warning D9024 : unrecognized source file type '', object file assumed

[Windows] Fix D9024 warnings

---

nntrainer/models/neuralnet.cpp

This line was doing nothing, so removed.
This possibly has no effect because the compiler is doing nothing with this line.

Remove unnecessary line

---

nntrainer/cl_context.h
nntrainer/engine.cpp
nntrainer/engine.h
test/unittest/layers/layers_dependent_common_tests.cpp
test/unittest/unittest_attention_kernels_cl.cpp
test/unittest/unittest_blas_kernels_cl.cpp

This pull request addresses a bug in the Engine class related to the registration of the OpenCL context. The newly introduced Engine class lacked the functionality to register the OpenCL context, which prevented NNTrainer from utilizing the GPU engine. Additionally, I corrected a typo that caused the registerContext function to fail in checking the GPU context, preventing it from registering properly with the engine. I have also updated the functions for context registration.

Bug Fix: OpenCL Context Registration in Engine Class for NNTrainer GPU Support

---

meson.build

This PR adds the minimum CMake policy version since compatibility with CMake < 3.5 has been removed.

[Meson] Add minimum cmake policy version

---

nntrainer/cl_context.cpp
nntrainer/cl_context.h
nntrainer/context.h
nntrainer/engine.h

This pull request addresses issues related to the GPU context when creating the global instance and the GPU layer object.
- Modify ClContext::Global to return the newly created object rather than a static instance.
- Override the Context::createLayerObject function to correctly create a GPU layer object.

GPU Context Initialization and Layer Object Creation

---

Applications/AlexNet/jni/meson.build
Applications/Custom/LayerClient/jni/meson.build
Applications/Layers/jni/meson.build
Applications/LogisticRegression/jni/meson.build
Applications/MNIST/jni/meson.build
Applications/ProductRatings/jni/meson.build

While meson-setting is being run on Windows, `xcopy` fails when it overwrites
with the build dir already containing resource files (mostly by previous build). 
This commit fixes it by adding `/Y` option.

Fix meson.build for Applications on Windows

---

nntrainer/layers/input_layer.cpp
nntrainer/models/model_common_properties.h
test/unittest/integration_tests/integration_test_mixed_precision.cpp

- This patch supports UINT4-UINT8 / UINT4-UINT16 / UINT8-UINT8 / UINT8-UINT16
- Please note that the input_layer is updated to `copyData` 
- Quantizer is removed in this layer. 
- Input layer should be updated in the way to take `quantize` parameter making a branch of its action.

[UINT] Support UINT4-UINT8 / UINT4-UINT16 / UINT8-UINT8 / UINT8-UINT16 (@open sesame 2025-03-31)

---

nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h

To reviewers, this PR might be helpful for those who want to add a new function interface on `cpu_backend.h`.
Those who want to involve in adding more features here can come back to this PR, and implement from the beginning.
Proposes:
- Add a skeleton implementation for q4_K quantized GEMM.
- Internal representation will be proposed later on.
- Function parameters introduced here might change.

[ cpu_backend ] Add skeleton for gemm_q4_K

---

nntrainer/cl_context.cpp
nntrainer/engine.h
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/tensor/cl_operations/attention_kernel_strings.cpp
nntrainer/tensor/cl_operations/attention_kernel_strings.h
nntrainer/tensor/cl_operations/attention_kernels.cpp
nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.h
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
nntrainer/tensor/cl_operations/meson.build

This commit fixes an error that occurred during the registration of OpenCL kernels. The issue was caused by the static initialization order, with `std::call_once` in the Engine class being invoked before the kernel strings had been initialized. This patch introduces functions to lazily initialize the kernel strings, ensuring that they are fully initialized before they are used.

Bug Fix: OpenCL Kernel Registration Error through Lazy Initialization

---

nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/uint_tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

- This commit implements template function copy_fp32 in x86_backend / fallback / arm_backend with __fallback
- This commit updates tensors' copyData() in uint/short/char tensor
- The reason I used template for `copy_fp32` is to use same signature function (overriden) in UIntTensor, which is implemented with template. In order to avoid the case where the type is not yet implemented, I implemented copy_fp32 as template as well.
- Please leave comment if you have better and simpler way to update
- This patch updates unittest for tensor: 1) update two negative cases as positive 2) add two more negative cases
- see also https://github.com/nnstreamer/nntrainer/issues/3065

[Tensor] copy_fp32 implementation and its application in tensor copyData() @open sesame

---

meson.build
windows-native.ini

This PR make number of threads for Open BLAS configurable (when we build Open BLAS from source) Based on benchmarks on windows with LLM's it seems that 6 threads are optimal for Windows.

[Performance] Configure Open BLAS threads.

---

test/meson.build

This fix the error when you can see running
`build compile -C xxx`
on Windows.

Fix meson error for Windows

---

nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
nntrainer/tensor/cpu_backend/x86/avx2_impl.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp

Added AVX implementation for transpose matrix operation.
It is the first implementation - not the best, but much faster than the current implementation.
In the future (if needed) we will further optimize this method.
**Latency measurement**
| dim        | prev    | AVX    | speedups |
|------------|---------|--------|------- |
| 768x768    | 3.1 ms  | 0.5 ms | x6.1   |
| 1440x1440  | 4.7 ms  | 1.7 ms | x2.7   |
| 1920x1560  | 10.9 ms |2.8 ms  | x3.9   |
| 1560x2048  | 15.8 ms | 3.9 ms | x4.0   |
| 512x2048   | 7.3 ms  | 1.4 ms | x5.2   |
Measurement was made on 12th Gen Intel(R) Core(TM) i7-12700
using the modified unit test `transpose_5122048`
We modified dimensions and we run 1000 iterations of transpose in both directions, the part of code:
```
for (int i = 0; i < 1000; i++) {
A_T = …
```

[CPU] Add AVX implementation of __fallback_transpose_matrix

---

nntrainer/cl_context.cpp
nntrainer/cl_context.h
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/concat_cl.h
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp

This patch introduces a Memory Allocator for the OpenCL context, which was previously lacking, and ensures that the Context data captures information about GPU layers created by ClContext.
It fixes an error related to the initialization order of a static member variable, which affected the use of registered kernels in OpenCL Layers.
Additionally, the patch addresses issues in OpenCL kernel strings by modifying the concatenation logic and providing a temporary fix for SwiGLU and RMSNorm half-precision operations, ensuring the correct registration of half-precision kernels when FP16 is enabled.

Enhance OpenCL Context: Memory Allocator and Kernel Registration Improvements

---

nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h

This PR adds loading clFinish to block until all previous queued OpenCL commands have been completed.

[OpenCL] Load clFinish to make synchronization point

---

nntrainer/cl_buffer_manager.cpp
nntrainer/layers/cl_layers/concat_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/opencl/opencl_context_manager.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

This PR combines two commits that address improvements in our OpenCL implementation:
1. Removal of Half-Precision Floating Point Support Check: The first commit removes the requirement to check for half-precision floating point support on devices. In CUDA, enabling the cl_khr_fp16 pragma/feature macro allows for basic operations using half data types, including addition, subtraction, multiplication, and division, with the newer compiler. 
2. Adjust Kernel Execution Global and Local Work Sizes: The second commit updates the global and local work sizes used when dispatching OpenCL kernels. Previously set to a fixed value of 32, this could lead to errors when the input size was less than 32. The work sizes have now been adjusted to align with the specific requirements of each kernel, …

Remove Half-Precision Floating Point Support Check and Adjust Kernel Execution Work Sizes

---

Applications/SimpleFC/jni/main.cpp

SimpleFC application try to allocate big array on stack which results in stack overflow on Windows platform. This PR changge stack allocated array to std::vector

[Fix] Fix stack overflow in SimpleFC

---

nntrainer/layers/input_layer.cpp

- Based on 9f86c, we can simplify input layer
- Simply call .copyData()
- The currently supported activation types are all supported.

[Input] Simplify Input Layer

---

nntrainer/layers/bn_layer.cpp
nntrainer/layers/bn_layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/memory_data.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h

In This PR
----
The current method of reading FSU weights is as follows (Simple Description):
1. In read, if FSU, it does not read during the initial load process.
2. During inference, depending on the execution order and look-ahead, the weight file is read through the FSU function at the moment it is needed and loaded.
There is a problem with this method. For logic like BCQ that reads information during loading and uses it to create tensors, the information needs to be known before memory allocation, so there is need to pass only that information. so I created a new readFSU function for cases in the future where settings for FSU are needed for various tensors.
Add readFSU function & Change BCQ Create Signature
- prepare Tensor that has other information (except Weight)
- Change bcq …

[FSU] Add readFSU to createFSU Tensor (BCQ)

---

nntrainer/graph/network_graph.cpp
nntrainer/graph/network_graph.h
nntrainer/models/neuralnet.cpp
nntrainer/models/neuralnet.h
nntrainer/tensor/cache_elem.h
nntrainer/tensor/cache_loader.cpp
nntrainer/tensor/cache_loader.h
nntrainer/tensor/cache_pool.cpp
nntrainer/tensor/cache_pool.h
nntrainer/tensor/manager.cpp
nntrainer/tensor/manager.h
nntrainer/tensor/swap_device.cpp
nntrainer/tensor/tensor_pool.cpp
nntrainer/tensor/tensor_pool.h

[FSU] update offset calc & Window page_size
- Update offset calc with getmemoryBytes()
- Update Window page_size to  sysInfo.dwAllocationGranularity;
ref : https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile
[in] dwFileOffsetLow
A low-order DWORD of the file offset where the view is to begin. The combination of the high and low offsets must specify an offset within the file mapping. They must also match the virtual memory allocation granularity of the system. That is, the offset must be a multiple of the VirtualAlloc allocation granularity. To obtain the VirtualAlloc memory allocation granularity of the system, use the [GetSystemInfo](https://learn.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getsysteminfo) function, which fills in …

[FSU] update offset calc & Window page_size

---

nntrainer/tensor/cpu_backend/cpu_backend.h

This PR fix selection of proper CPU backend on Windows
__x86_64__ macro is not recognized by MSVC which cause that instead of selecting 
<x86_compute_backend.h> we chose <fallback.h> in backend selection

[Fix] Fix x86 backend on Windows

---

nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
test/unittest/unittest_nntrainer_tensor.cpp

[tensor] Enhance dotBatch to enable GQA(Grouped Query Attention)
- In GQA(Grouped Query Attention) given two tensors have a different batch sizes.
So we need to figured out which samples are corresponding to each other.
LCM(least common multiple) is used as a key point to figure this out.
Each sample performs a dot operation one by one with corresponding group samples.
In case of the batch size of the given tensor does not equal, the bigger on should be a multiple of the smaller one.
[test] Add dot batch unittest
- Added dot batch unittest for following cases
(1) If the batch sizes of the given two tensors does not have common multiple.
(2) If the batch sizes of the bigger one is not a multiple of the smaller one.
(3) If the batch sizes of the bigger one is a multiple of the smaller one.

[tensor] modify dotBatch for gqa

---

.github/workflows/windows.yml
Applications/LogisticRegression/jni/meson.build
Applications/MNIST/jni/meson.build
test/ccapi/meson.build
test/unittest/meson.build

This PR
---
Currently, in CI, we are only proceeding with Window Compile and not running unit tests. Although a few tests fail, we cannot delay testing any further, so this pr will exclude some failing tests specifically for Windows and proceed with Unit Tests. Additionally, we will add a new Runner.
- Enable Window Unittest
- Add runner window-2025
- Disable some unittest ( will be enable ASAP )

[CI][Window] Enable Window Unittest & Add Window 2025

---

test/unittest/unittest_nntrainer_tensor.cpp

In unit tests we're copying unitialized output to initialized input and we were lucky enough to pass those tests. This PR fix copying direction in unit tests

[Fix] Fix copy data unit tests

---

nntrainer/tensor/cl_operations/blas_kernel_strings.cpp

This patch fixes half-precision OpenCL kernels to accumulate values in single-precision format. It also corrects the output for the BLAS kernel unit test.

[OpenCL] Fix Half-Precision Kernels

---

.github/workflows/ubuntu_clean_meson_build_clang.yml
linux-native-clang.ini
nntrainer/engine.h
test/tizen_capi/unittest_tizen_capi.cpp

We're now supporting 3 major compilers: gcc, clang, msvc
This PR add running clang build to continues integration in order to not lose clang compilation ability.
It will also give us chance to monitor and fix multiple compiler warnigs

[CI] Add clang build to continues integration

---

meson.build
nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
nntrainer/tensor/cpu_backend/x86/avx2_impl.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp

This uses custom expf() approximation with maximal error <= 5e-6. Speedup of 9x-12x. Differs by compiler 8x wrt. scalar should be expected.

[x86_64] AVX approximation of swiglu

---

meson.build

This pull request addresses an error that occurred during the GGML build in NNTrainer.
The error reported unsupported instructions from AVX512, which happens exclusively on Ubuntu 20.04 with assembler version 2.34.
This change restricts the use of any AVX-512 instructions, allowing only up to AVX2 level instructions.

Bugfix: GGML Build Error in NNTrainer on Ubuntu 20.04

---

nntrainer/utils/bs_thread_pool.h
nntrainer/utils/bs_thread_pool_manager.cpp
nntrainer/utils/bs_thread_pool_manager.hpp
nntrainer/utils/meson.build
packaging/nntrainer.spec

- introduce bs threadpool to manage multithreading throughout the nntrainer
- Use through bs_thread_pool_manager to not only instantiate
threadpool only once, but also use from distinctive nntrainer structure
levels without tangled dependency.

[ Wait for #3176 ] [ util ] Add bs threadpool

---

nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp

This pull request adds a highly optimized single-precision General Matrix Multiplication (GEMM) kernel developed for OpenCL. The enhancements in this kernel aim to improve computational efficiency and performance for matrix operations, reducing execution time and enhancing throughput.
|engine|avg|
|------|---|
|CPU|108.05ms|
|GPU (prev)|3848.6 ms|
|GPU|68.5 ms|
|engine|avg|
|------|---|
|CPU|293.75ms|
|GPU (prev)|19600.8 ms|
|GPU|534.1 ms|
This is a profiling result with the following matrix size.
- M: 1024
- K: 3072
- N: 3072

[OpenCL] Optimized Single-Precision GEMM Kernel

---

nntrainer/layers/bn_layer.cpp
nntrainer/layers/bn_layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/models/neuralnet.cpp
nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/bcq_tensor.h
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/char_tensor.h
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/int4_tensor.h
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/short_tensor.h
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor.h
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/tensor_base.h
nntrainer/tensor/uint4_tensor.cpp
nntrainer/tensor/uint4_tensor.h
nntrainer/tensor/uint_tensor.cpp
nntrainer/tensor/uint_tensor.h
nntrainer/utils/util_func.cpp
nntrainer/utils/util_func.h

In This PR 
----
This PR improves the loading logic so that model weight files are read asynchronously and in parallel.
By calculating each weight’s file offset, multiple threads can simultaneously read weights, and to enable this, a start_offset parameter was added to read function interfaces, ensuring that file reading uses the right offset.
Loading performance improved (for 16GB, about 4500ms → 1600ms).
``` 
Linux
CPU info : 11th i7-11700
memory Performance 28693.32 MB/s
Disk Random 16.0 Read 240.06 MB/s 8.0
Disk Sequential 64.0 Read 835.56 MB/s 8.3
Disk Sequential 64.0 Write 287.56 MB/s 7.7
load : 16GB bin file, 4543 ms --> 1446 ms,
```
The implementation uses futures and async so that multiple layers or weights are loaded at the same time, and read function signatures across tensor …

[Load]Optimize load with Async

---

meson.build
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.h
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_cpu_backend.cpp

- Add openMP-optimized q4K GEMM and GEMV multithreaded functions
- Add openMP-optimized q40 GEMM and GEMV multithreaded functions  
- Remove redundant codes and print statements
- BS threadpool-optimized functions will be introduced later on
- non-256-divisible-M computation of q4K GEMM will be introduced later on

[ q4K ] Add optimized q4K/q40 GEMM and GEMV functions

---

meson.build
nntrainer/utils/util_func.h

The meson.build has been modified to build nntrainer on Windows. 
Additionally, exp_util with _Float16 type has been added for Windows.
The current modifications have only been tested with msvc. 
Testing and additional support for Clang builds will be implemented later.

[Windows] Modify meson.build for windows build(msvc)

---

nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
test/unittest/unittest_nntrainer_cpu_backend.cpp

- DONE : Compute all q4K GEMM rows with q4K GEMV to avoid divisibility
- TODO : Compute with q4K GEMM kernel first, and compute remaining rows with q4K GEMV + apply multithreading on the total sequence
- Add unittest for that (M = 457, 458, 459) accordingly
- With recent upstream main, leftover rows for 4 after GEMM kernel, left zero-filled rows

[ q4K ] Enable non-4-divisible-M q4K GEMM case

---

nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp

This pull request adds a highly optimized half-precision General Matrix Multiplication (GEMM) kernel developed for OpenCL. 
|engine|avg|
|------|---|
|CPU|116ms|
|GPU (prev)|3845 ms|
|GPU|63.05 ms|
|engine|avg|
|------|---|
|CPU|214.2ms|
|GPU (prev)|26572.3ms|
|GPU|503.35 ms|
This is a profiling result with the following matrix size.
- M: 1024
- K: 3072
- N: 3072

[OpenCL] Optimized Half-Precision GEMM Kernel @open sesame 05/22 09:09

---

nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.h
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
test/unittest/meson.build
test/unittest/unittest_nntrainer_cpu_backend.cpp

Implement q6_K gemm with simple logic:
- fill all the output scalar from q6_K dot kernel for all output matrix
- Need to apply multithreading for optimal performance.
- With this simple openMP parallelization,
```bash
for TC : GEMV_1x3072x105900
BEFORE:
[INFO] gemm_q6_K: 251178704 ns
AFTER:
[INFO] gemm_q6_K: 28968825 ns
while, 
[INFO] sgemm :   50981615 ns 
```

[ q6K ] Vanilla implementation of q6K GEMM

---

jni/prepare_ggml.sh
meson.build
subprojects/ggml.wrap
subprojects/packagefiles/ggml/0001-nntrainer-ggml-patch.patch

CMake is not able to find OpenMP package when compiling with clang on windows platform. It cause that ggml is running on single thread. This PR apply patch in ggml to workaround this problem
With this change clang build is ~20% faster than msvc build on LLM inference

[Windows] Fix OpenMP linking problem of ggml on windows clang build

---

nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/utils/base_properties.h
nntrainer/utils/node_exporter.cpp
nntrainer/utils/node_exporter.h
test/unittest/layers/unittest_layer_node.cpp

- This commit adds weight_dtype property
- This commit applies this weight_dtype property to layer_node
- This commit adds a simple unittest

[Props] add WeightDType property

---

nntrainer/engine.cpp
nntrainer/models/neuralnet.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/float_tensor.h
nntrainer/utils/base_properties.h
test/unittest/unittest_nntrainer_tensor.cpp

- This patch adds Q6K weight type
- This ptach implements dot operation of Q6K with FP32 tensor
- This patch adds init_backend to support cpu_backend initialization
- This patch adds Q6_K as the type to be read without givine an offset
for qparam when loading the tensor
- This patch adds Q6_K tensor unittests: dot with FP32, quant/dequant

[Q6K] Add Q6K as weight & dot operation & related unittest

---

nntrainer/tensor/q6_k_tensor.h

- This patch update missing override keyword in Q6K

[Q6K] clarify `override` for parent's pure virtual

---

nntrainer/layers/fc_layer.cpp

(None)
<details><summary>[LoRA] bugfix in LoRA</summary><br />
- Fix the data type of tensor allocated when the LoRA is enabled.
- loratmp and loraout tensors should be `activation_type`
</details>
- Fix the data type of tensor allocated when the LoRA is enabled.
- loratmp and loraout tensors should be `activation_type`

[LoRA] bugfix in LoRA

---

nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp

- During Q6 GEMM there is no need to split quantization and dot operations to 2 separate OMP parallel blocks
Signed-off-by: mwlasiuk <testmailsmtp_12345@gmail.com>

Do not split qantization and dot steps

---

nntrainer/models/neuralnet.cpp
nntrainer/tensor/bcq_tensor.cpp
nntrainer/tensor/char_tensor.cpp
nntrainer/tensor/int4_tensor.cpp
nntrainer/tensor/short_tensor.cpp
nntrainer/tensor/tensor_base.cpp
nntrainer/tensor/uint4_tensor.cpp
nntrainer/tensor/uint_tensor.cpp

- None
<details><summary>[Tensor][Read] Change Tensor read from file_offset</summary><br />
[Tensor][Read] Change Tensor read from file_offset
Previously, the tensor would receive parameters and, if the flag to read from the file offset was true, it would read from the passed start_offset.
Now, since the tensor holds its own fileOffset, if the value is size_t::max, it will default to reading from the stored fileOffset.
</details>
<details><summary>[Load] Refactoring Model Load Async</summary><br />
[Load] Refactoring Model Load Async
The existing method, which passed the offset through the execution order for each layer …

[Tensor][Read] Change Tensor read from file_offset

---

api/ccapi/include/layer.h
nntrainer/layers/layer_devel.h
nntrainer/layers/layer_impl.cpp
nntrainer/layers/layer_impl.h
nntrainer/layers/layer_node.cpp
nntrainer/layers/layer_node.h
nntrainer/utils/util_func.h

Implemented a getProperty function that allows checking the value using the key of a set property.
The actual implementation must be added in the layer. 
If not implemented, it returns an empty string ("").
To use getProperty, inherit from layer_impl and insert the property tuple existing in the layer into LayerImpl::for_each function.
If the key exists in the tuple, it returns the value. If the property is not set and there is no default value, it returns "empty".

Add getProperty function

---

jni/Android.mk.in
jni/meson.build
jni/prepare_opencl.sh
meson.build
nntrainer/layers/cl_layers/reshape_cl.cpp
nntrainer/layers/cl_layers/reshape_cl.h
nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
nntrainer/tensor/cl_operations/blas_kernel_interface.h
nntrainer/tensor/cl_operations/clblast_interface.cpp
nntrainer/tensor/cl_operations/clblast_interface.h
nntrainer/tensor/cl_operations/meson.build
test/jni/Android.mk
test/unittest/unittest_blas_kernels_cl.cpp

This PR introduces the implementation of basic BLAS functions in CLBlast, including scal, copy, axpy, dot, nrm2, asum, amax, and amin, while noting that GEMV, GEMM, and im2col will be included in a future pull request. Additionally, it enhances the NNTrainer BLAS kernel with newly added CLBlast kernels by incorporating new kernel interfaces and replacing existing ones, although half-precision support is not yet implemented and will be addressed later. Furthermore, unit tests were added for the new OpenCL BLAS kernels to verify their adaptation to NNTrainer and to compare the results with those generated by the CPU.

Integration of Basic BLAS Functions in CLBlast with Enhancements for NNTrainer

---

nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp

- Removed dot(q6, float) copy that was never used because there is second function doing same job that is acctually called
Signed-off-by: mwlasiuk <testmailsmtp12345@gmail.com>

Remove leftover unused function

---

nntrainer/tensor/cpu_backend/x86/avx2_impl_fp16.cpp

If remaining data size is less than 8 avoid using vector instructions

[Fix] Fix memory access violation in fp16

---

test/unittest/unittest_nntrainer_tensor.cpp

Fix ggm assertion in unit test caused by row value not divided by 256

[Fix] Fix ggml assertion in q6K quantization test

---

meson.build
nntrainer/opencl/CL/cl.h
nntrainer/opencl/CL/cl_platform.h
nntrainer/opencl/CL/cl_version.h
nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h
nntrainer/tensor/cl_operations/blas_kernels.cpp

This PR includes two key updates to enhance OpenCL support:
<details><summary>Update OpenCL headers to support newer versions</summary><br />
This commit updates the OpenCL headers to support versions beyond OpenCL 1.2.
The previous headers were limited to OpenCL 1.2, but this patch introduces support for newer versions, ensuring compatibility with modern hardware and features.
This change will enable developers to leverage the latest advancements in OpenCL for their applications.
</details>
<details><summary>Update OpenCL loader to support SVM</summary><br />
This commit updates the OpenCL loader to add support for OpenCL 2.0 features. The following changes are included:
- Added …

Update OpenCL Headers and Loader to Support SVM

---

nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/opencl/opencl_command_queue_manager.h
nntrainer/opencl/opencl_context_manager.cpp
nntrainer/opencl/opencl_context_manager.h
nntrainer/opencl/opencl_kernel.cpp
nntrainer/opencl/opencl_kernel.h
nntrainer/tensor/memory_pool.cpp
nntrainer/tensor/memory_pool.h

<details><summary> Update OpenCL Kernel Wrappers</summary><br />
This commit updates the OpenCL kernel wrappers to utilize clSetKernelArgSVMPointer.
This enables the use of Shared Virtual Memory (SVM) to manage memory more efficiently.
</details>
<details><summary>Update Memory Pool to Allocate SVM Buffer</summary><br />
This commit updates the memory pool to allocate a shared virtual memory buffer when it is available.

[OpenCL] Enable Support for Shared Virtual Memory (SVM)

---

test/tizen_capi/unittest_tizen_capi_optimizer.cpp

Fix the following Valgrind error:
==1356345==
==1356345== 285 (80 direct, 205 indirect) bytes in 1 blocks are definitely lost in loss record 395 of 404
==1356345==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1356345==    by 0x155042: ml_train_optimizer_create (in /source/github/nnstreamer/nntrainer/build/test/tizen_capi/unittest_tizen_capi_optimizer)
==1356345==    by 0x12C7B7: nntrainer_capi_nnopt_setProperty_05_n_Test::TestBody() (in /source/github/nnstreamer/nntrainer/build/test/tizen_capi/unittest_tizen_capi_optimizer)
==1356345==    by 0x19704E: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in …

memory leak fix (valgrind error): unit test tizen capi optimizer

---

nntrainer/tensor/int4_tensor.cpp

This fixes the following Valgrind error (didn't delete an object)
CC: @djeong20 (this leak comes from 5120f50af653ebe94e0adcfda18d53fb2351a8b8 )
```
==1519278==
==1519278== HEAP SUMMARY:
==1519278==     in use at exit: 440 bytes in 5 blocks
==1519278==   total heap usage: 123,581 allocs, 123,576 frees, 82,037,108 bytes allocated
==1519278==
==1519278== 88 bytes in 1 blocks are definitely lost in loss record 1 of 5
==1519278==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1519278==    by 0x4C6D824: nntrainer::Int4QTensor::Int4QTensor(std::vector<std::vector<std::vector<std::vector<signed char, std::allocator<signed char> >, std::allocator<std::vector<signed char, std::allocator<signed char> > > >, …
```

memory leak fix (valgrind error): int4_tensor leak

---

nntrainer/engine.cpp
nntrainer/engine.h

Fix the following valgrind error:
==1332058== 10,413 (392 direct, 10,021 indirect) bytes in 1 blocks are definitely lost in loss record 394 of 395
==1332058==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1332058==    by 0x4CE3C43: nntrainer::Engine::add_default_object(nntrainer::Engine&) (in /source/github/nnstreamer/nntrainer/build/nntrainer/libnntrainer.so)
==1332058==    by 0x4CE3F1E: nntrainer::Engine::registerer(nntrainer::Engine&) (in /source/github/nnstreamer/nntrainer/build/nntrainer/libnntrainer.so)
==1332058==    by 0x5787ED2: __pthread_once_slow (pthread_once.c:116)
==1332058==    by 0x4CE2C6F: nntrainer::Engine::Global() (in /source/github/nnstreamer/nntrainer/build/nntrainer/libnntrainer.so)
==1332058==    by …

memory leak fix (valgrind error): engine and context

---

test/unittest/layers/unittest_layer_node.cpp

Although this is merely a unit test code,
we need to clean up all Valgrind errors before we turn the Valgrind-test github workflow on.
After that, we can reject all commits causing
any Valgrind errors.
This fixes:
```
==1541951==
==1541951== 4 bytes in 1 blocks are definitely lost in loss record 1 of 167
==1541951==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1541951==    by 0x1AE611: nntrainer_LayerNode_setWeights_01_n_Test::TestBody() (unittest_layer_node.cpp:299)
==1541951==    by 0x243ADE: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /source/github/nnstreamer/nntrainer/build/test/unittest/layers/unittest_layers)
==1541951== …
```

memory leak fix (valgrind error): layer unittest

---

README.md

Ubuntu Launchpad PPA build is now working for 22.04 and 24.04 only.

readme: update supported ubuntu version.

---

nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal_fp16.cpp
nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
nntrainer/tensor/float_tensor.cpp
nntrainer/tensor/half_tensor.cpp
nntrainer/tensor/tensor.cpp
nntrainer/tensor/tensor_base.h
test/unittest/models/models_test_utils.cpp

This PR address following issues:
1. Workaround for problem with nan when calculating beta * nan
In many functions we're calculating:
Z[i] = X[i] - alpha * Y[i] + beta * Z[i];
if beta is zero we're expecting to have 0 as results of beta * Z[i] but it's not always true because when Z is not initialized it can be nan. This PR add workaround for this and fix problem when beta is 0
2. Fix problem of not initialized tensors in tests (model_test_utils.cpp) - we were running tests with uninitialized memory in tensors and expect zeros (which was not always true). This PR initialize tensors memory

[Fix] Fix nan values problem while beta calculation.

---

Applications/KNN/jni/main.cpp

Before turning on github-action valgrind testing,
I'm clearing all known Valgrind errors in meson test.
This fixes:
```
==1574890==
==1574890== 540,000 bytes in 2 blocks are possibly lost in loss record 12 of 14
==1574890==    at 0x48485C3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1574890==    by 0x111F73: tflite::label_image::read_bmp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, int*, int*) (bitmap_helpers.cpp:109)
==1574890==    by 0x10DA64: main (main.cpp:181)
==1574890==
==1574890== 2,160,000 bytes in 8 blocks are definitely lost in loss record 13 of 14
==1574890==    at 0x48485C3: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1574890== …
```

memory leak fix (valgrind error): Application/KNN

---

nntrainer/tensor/float_tensor.cpp

This PR removes the SVM allocation from the FloatTensor class.

[Tensor] Remove SVM Allocation

---

test/unittest/layers/unittest_layer_node.cpp
test/unittest/unittest_nntrainer_tensor.cpp
test/unittest/unittest_nntrainer_tensor_fp16.cpp

- added 81 number of negative unittests
- expanded function call coverage
before:
- Positive TCs: 503
- Negative TCs: 475
after:
- Positive TCs: 503
- Negative TCs: 556

[unittest] add negative unittests

---

nntrainer/opencl/opencl_kernel.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
nntrainer/tensor/cl_operations/blas_kernels_templates.h

Replace repeating FP16/FP32 code with template
- These kernels have exactly the same structure with only thing that differs is used kernel (its registered name) and type dependent sizeof()-s
Signed-off-by: {your_name} <{your_email}>

Replace repeating FP16/FP32 code with template

---

meson_options.txt
nnstreamer/tensor_filter/meson.build
nnstreamer/tensor_trainer/meson.build
packaging/nntrainer.spec

The default option should follow the prefix.
Don't make a hardcoded absolute path as the default.
This often make problems in Github workflow action script testing.

build/install: install path of nnstreamer subplugins

---

nntrainer/tensor/float_tensor.cpp
test/unittest/unittest_nntrainer_tensor.cpp

<details><summary>[Q6_K] Update Q6_K dot opration</summary><br />
- This patch updatese Q6_K's dot operation to support transpose.
- In pricinple, Q6_K doesn't support transpose, but here, we aim to support trans option for dimension change in tensor for dot operation.
</details>
- This PR updates FP32.dot(Q6_K).
- In the previous implementation, it assumes 'transposed' in dimension by default.
- This PR fixes the operation, while supporting in_transpose.
- Please note that this in_transpose support does not transpose of the matrix data but only change the dimension of height and weight.
Signed-off-by: Eunju Yang …

[Q6_K] Update Q6_K dot opration.

---

nntrainer/nntrainer_error.h

- Added macros disabling warning (throwing exception in class destructor) to silence compiler warnings (as this throw is intended here)
Not proper way to fix it but if original code is written that way by intention lets at least suppress this warning
Signed-off-by: {your_name} <{your_email}>

Wrap nntrainer::ErrorNotification with warning suppressor

---

nntrainer/opencl/opencl_loader.cpp
nntrainer/opencl/opencl_loader.h

None
fe45afe1
<details><summary>[OpenCL] Load clWaitForEvents</summary><br />
- Enable clWaitForEvents
- Remove macros defined in cl.h (CL_API_ENTRY, CL_API_CALL, CL_CALLBACK)
Signed-off-by: Daekyoung Jung <dk11.jung@samsung.com>
</details>
</details>
- [OpenCL] Load clWaitForEvents
Signed-off-by: Daekyoung Jung <dk11.jung@samsung.com>

[OpenCL] Load clWaitForEvents

---

nntrainer/models/neuralnet.cpp

<details><summary>[Bugfix] neuralnet load is fixed.</summary><br />
- read with filedescriptor should be used
- variant doesn't work in ubuntu.
- In current, mmap is set 0. This mmap read option should be fixed later.
</details>
- Bug fix in neuralnet.cpp
- read(ReadSource ...) doesn't work in Linux. Thus, this patch fixes the read from read(ReadSource) to read(std::ifstream)

[Bugfix] neuralnet load is fixed.

---

.github/workflows/android.yml
jni/Android.mk.in
jni/meson.build
jni/prepare_ggml.sh
meson.build
test/jni/Android.mk
test/jni/meson.build
tools/package_android.sh

<details><summary>[Build] fix android build to support opencl disablement</summary><br />
- Fix #3416
- This patch updates build script for Android (ggml-related script)
- This patch updates meson build and Android mk files to support enable-opencl=false option
</details>
- Fix #3416
- This patch updates build script for Android (ggml-related script)
- This patch updates meson build and Android mk files to support enable-opencl=false option
- One can do the android build with `./tools/package_android.sh -Denable-opencl=true / false`

[Build] support opencl disablement in Android

---

nntrainer/layers/cl_layers/swiglu_cl.cpp
nntrainer/layers/cl_layers/swiglu_cl.h
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
test/unittest/unittest_blas_kernels_cl.cpp

- swiglu layer was setting cl_mem object instead pointer to cl_mem object as input / outpt arg causing error '-38'
- this PR fixes failing SwiGLU layer tests
``` bash
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = *Swiglu*
[==========] Running 12 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 10 tests from SwigluGPU/LayerSemanticsGpu
[ RUN      ] SwigluGPU/LayerSemanticsGpu.createFromClContext_pn/0
[       OK ] SwigluGPU/LayerSemanticsGpu.createFromClContext_pn/0 (472 ms)
[ RUN      ] SwigluGPU/LayerSemanticsGpu.setPropertiesInvalid_n/0
[       OK ] SwigluGPU/LayerSemanticsGpu.setPropertiesInvalid_n/0 (0 ms)
[ RUN      ] SwigluGPU/LayerSemanticsGpu.finalizeValidateLayerNode_p/0
[       OK ] …
```

Fix SwiGLU layer + utilize local group.

---

nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/cl_operations/blas_kernels_templates.h
test/unittest/unittest_blas_kernels_cl.cpp

This commit fixes and optimizes RMSNorm implementation of OpenCL kernel. Details:
1. `rmsnorm_cl` function is added to `blas_kernels.h`
2. RMSNormLayerCL now only calls `rmsnorm_cl` instead of setting up the kernel
3. `rmsnorm_cl` optionally uses SVM
4. The implementation is change inspired by GGML implementation - there's one subgroup per workgroup and each workgroup cooperatively calculates sum of elements in each row and then normalizes the row. Performance was tested for `3072x3072` tensor.
5. Currently there's an additional, commented implementation of kernel which uses 64 size workgroup (2 subgroups). On my machine (Intel UHD Graphics) there's no difference in performance between them, but on something other there can be.
| CPU      | GPU Before | GPU After         | …

Fix and optimize rmsnorm OpenCL implementation, inspired by GGML opecl kernel.

---

nntrainer/cl_buffer_manager.cpp
nntrainer/cl_buffer_manager.h
nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/tensor/cl_operations/blas_kernels.cpp
nntrainer/tensor/cl_operations/blas_kernels.h
nntrainer/tensor/float_tensor.cpp
test/unittest/unittest_blas_kernels_cl.cpp

This pull request introduces support for asynchronous execution of the Q4_0 GEMM kernel.
The main change involves configuring the OpenCL command queue to operate in an out-of-order mode.
Additionally, the CL buffer manager class has been updated to include a vector for scales and quantization parameters, which are reserved for asynchronous kernel launches.

[OpenCL] Asynchronous Execution and Out-of-Order Queue Support

---

debian/nntrainer-dev.install
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
nntrainer/tensor/cpu_backend/cpu_backend.h
nntrainer/tensor/cpu_backend/fallback/fallback.cpp
nntrainer/tensor/cpu_backend/fallback/fallback.h
nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
nntrainer/tensor/cpu_backend/fallback/fallback_kleidiai.cpp
nntrainer/tensor/cpu_backend/fallback/fallback_kleidiai.h
nntrainer/tensor/cpu_backend/fallback/meson.build
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
packaging/nntrainer.spec
test/unittest/unittest_nntrainer_cpu_backend.cpp

- None
1. 0efcd42573b2393a4aafccefcfdb663df425ab3a
- Introduce reference functions from kleidiai (Apache 2.0) from ARM. I went through internal discussions with internal Open Source License Team, but let me know if there is anything illegal or harm the project LICENSE.
- Adapt with nntrainer's format, and verify with unittest.
2. b1746376d7fe71aa834319e43963d4e6eec3e30a
- Expand 1 to other backend's candidate.
- `qai8dxp` : quantized asymmetric integer 8bit per-dimenstion packed
- `qsi4cxp` : quantized symmetric integer 4bit per-channel packed
- `qs4cx_f32` : `qs4cx` quantization from `f32` 
- This commit introduces a function that do GEMM of `qai8dxp` activation and `qsi4cxp` weight, for BOTH rhs weight transposed and non-transposed.
- activation will be runtime-quantized on the fly, and …

[ cpu_backend ] Enable channelwise 4bit quantized GEMM ( A : F32 -> U8 * W : S4 = O : F32)

---

.gitignore

<details><summary>[git] update ignore file to exclude res/*</summary><br />
- This patch aims to exclude files under Applications/**/res/*
- This may protect your unexpected resource addition
</details>
- [git] update ignore file to exclude `Applications/**/res/*`

[git] update ignore file to exclude res/*

---

Applications/CausalLM/layers/embedding_layer.cpp

- wait for #3452 
- see also #3466 
<details><summary>[CausalLM] enable Q4_0 in Embedding Layer</summary><br />
- This patch enables Q4_0 embedding layer
- This patch reduces embedding layer size by supporting Q4_0 type
</details>
- Enable Q4_0 type for embedding layer.
- This can reduces memory size by supporting Q4_0
- Performance comparison gpt-oss-20b with FP32 embedding layer vs. Q4_0 embedding layer
- x86 / FP32 embedding layer
```
=================[ LLM with NNTrainer ]===================
prefill: 78 tokens, 5141 ms, 15.1721 TPS
generation: 1024 tokens, 156711 ms, 6.53432 TPS …
```

[CausalLM] enable Q4_0 in Embedding Layer

---

nntrainer/cl_context.cpp
nntrainer/opencl/opencl_program.cpp
nntrainer/opencl/opencl_program.h

Closes #3427 
None
- When building a kernel, a hash will be taken of the kernel code and build options. Hash will be the binary's filename
- Upon context initialization, the program will look for a binary. If it is found, binary will be used to create program.
- This change should be immune to changes in code and command line options. Not to driver and device version for now.
A quick tests I did showed the time to complete `nntrainer:unittests / unittest_blas_kernels_cl` reduced from 6.5 seconds without cache to 0.17 seconds with cache (for me this test fails after first test case but context initializes correctly).
Signed-off-by: Piotr Pokorski p.pokorski@samsung.com

Cache built kernel binaries and load them on subsequent runs

---

nntrainer/cl_context.cpp
nntrainer/cl_context.h
nntrainer/opencl/opencl_buffer.cpp
nntrainer/opencl/opencl_command_queue_manager.cpp
nntrainer/opencl/opencl_context_manager.cpp
nntrainer/opencl/opencl_loader.cpp

This PR addresses issues where the OpenCL context only considered scenarios in which OpenCL was available.
As a result, there was no proper handling of cases where OpenCL was not available.
This patch now restricts the use of the OpenCL context accordingly.
Please note that additional work may still be required.

Restricting OpenCL Context Usage When Unavailable

---

meson.build
meson_options.txt
packaging/nntrainer.spec

#3410 
<details><summary>[Tizen] fix tizen-build related to ruy and ggml </summary><br />
- This patch fixes some issues in tizen-7.0 build
- This patch updates ruy and ggml use as an option in tizen build
- tizen build error by warning is fixed (removing unused param)
</details>
<details><summary>[Tizen-7.0] edit build options for submodules</summary><br />
- This patch aims to resolve tizen-7.0 gbs build error.
- This patch resolves ruy-related issue
```
[   93s] c++ -Isubprojects/ruy/libruy_system_aligned_alloc.a.p -Isubprojects/ruy -I../subprojects/ruy -Isubprojects/ruy/__CMake_build -I../subprojects/ruy/__CMake_build …
```

[Tizen] fix tizen-build related to ruy and ggml

---

debian/control
debian/rules
debian/ruy.install
jni/Android.mk.in
jni/meson.build
meson_options.txt
packaging/nntrainer.spec
test/jni/Android.mk

See also : #3512
- nntrainer never have been using ruy in any feature or module. Never used at all, even once.
- it is highly-unlikely to use ruy in the near, or even long-term future.
- Remove ruy from android build, and let all the default options for ruy to false.

[ ruy ] Set ruy usage to false by default
